### ISSUE TITLE
Unable to use the extension

### ISSUE THREAD

**Issue by debajiteziodutta** [micheleg/dash-to-dock#1445] opened 2021-05-12 16:34 UTC
After installing as prescribed in the Readme file, I am getting the following error from the gnome "_Extensions_" app (screenshot attached)

![image](https://user-images.githubusercontent.com/51490675/118011887-20067280-b36e-11eb-80a4-dc6810b18a21.png)

![image](https://user-images.githubusercontent.com/51490675/118011031-3233e100-b36d-11eb-8b5c-bc84d2418673.png)

The following is the output form "_Technical Details_" section:-

`Gtk.BuilderError: /home/debajitdutta/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/Settings.ui:13:35 Invalid property: GtkBox.margin_left

Stack trace:
  DashToDock_Settings@/home/debajitdutta/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:92:23
  buildPrefsWidget@/home/debajitdutta/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:869:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  `

**Comment by Tuxman2** [comment] 2021-05-13 10:10
@debajiteziodutta:  Have you got installed the sassc package before making the compilation ?

That's why I did and  I didn't encounter problem. So, install sassc package + dependencies, make, make install.

Note: I took the Dash to dock extension from here: https://github.com/ewlsh/dash-to-dock/tree/ewlsh/gnome-40
That version works with Gnome 40. Of course, it is not perfect yet (some bugs) but it does the job.

@Sidpatchy: Dash to Dock extension works with Gnome 40 but you must take the version from Ewlsh and not from Micheleg.

**Comment by debajiteziodutta** [comment] 2021-05-14 11:35
@Tuxman2 I have uninstalled the extension and deleted the micheleg cloned version and cloned ewlsh repo in my home directory. I installed the sass package and executed the "make" and "make install" command.


> dependencies

I am not sure what other dependencies are required and from where to get them.

**Comment by Tuxman2** [comment] 2021-05-16 11:51
@debajiteziodutta: Does it work now with ewlsh version ?

**Comment by debajiteziodutta** [comment] 2021-05-16 11:54
@Tuxman2  no it didn't worked, facing same issue here as well.

Maybe some dependencies are not there. 

Not sure how can I check it.

**Comment by lozanotux** [comment] 2021-05-20 19:29
@debajiteziodutta in my case, I'm using Fedora 34... at beginning, after install the extension using the version of ewlsh (gnome-40 branch) I had to restart gnome-shell by pressing Alt+F2 and writing r in the input. I hope this tip help you. Regards!

**Comment by linoshkm** [comment] 2021-05-29 06:05
> @Tuxman2 no it didn't worked, facing same issue here as well.
> 
> Maybe some dependencies are not there.
> 
> Not sure how can I check it.

If you try to git clone the Ewlsh/Dash-to-dock repository, it will clone the master branch, not the gnome 40 branch
So you'll have to download as Zip from https://github.com/ewlsh/dash-to-dock/tree/ewlsh/gnome-40
To build the extension you need sassc installed.
Once installed log out and log in  or Alt+F2 r (On X.Org) to restart the session and it should work.

**Comment by ewlsh** [comment] 2021-10-05 05:22
Duplicate of #1358

**Closed by ewlsh** 2021-10-05 05:22 UTC
