### ISSUE TITLE
glitches in fullscreen auto hide feature in full screen 

### ISSUE THREAD

**Issue by SarikAnwar01** [micheleg/dash-to-dock#1760] opened 2022-05-28 11:26 UTC
whenever i am using any full-screen app the intelligent autohide glitches when move my cursor to dock or to top bar it even prevents me from changing tabs or switching to other app , i have to use my super key to switch apps plz help its very  disturbing and annoying

**Comment by vanvugt** [comment] 2022-06-08 09:39
This sounds like a duplicate of #1755 which will be fixed in the next release.

**Comment by vanvugt** [comment] 2022-06-17 06:02
Duplicate of #1755

**Closed by vanvugt** 2022-06-17 06:02 UTC
