### ISSUE TITLE
apt-get install doesn't work

### ISSUE THREAD

**Issue by pH142857** [micheleg/dash-to-dock#2126] opened 2023-11-21 23:33 UTC
On Debian 12 - GNOME 43.6, successfully running `apt-get install gnome-shell-extension-dashtodock`, the dash behavior didn't change, it doesn't show while I don't click on Activities. I am, however, able to access the settings by running `gnome-shell-extension-prefs dash-to-dock@micxgx.gmail.com` but they seem to have no effects.

Everything works as expected if I install it through https://extensions.gnome.org/extension/307/dash-to-dock. It would be great to fix what seems to be a bug to me, because I find it a pity to resort to a browser extension to install desktop environment features. However I am aware the apt-get method isn't listed amongst download methods in https://micheleg.github.io/dash-to-dock/download.html so at least it's consistent.

**Comment by vanvugt** [comment] 2023-11-22 05:28
As mentioned above, whatever the problem is here is Debian-specific and already resolved upstream. This is the upstream. So we should close this bug and please report Debian bugs at https://bugs.debian.org/gnome-shell-extension-dashtodock

**Closed by vanvugt** 2023-11-22 05:28 UTC
