### ISSUE TITLE
Sometimes icon background is broken

### ISSUE THREAD

**Issue by ibahnasy** [micheleg/dash-to-dock#2092] opened 2023-09-13 10:08 UTC
Sometimes the icons background looks broken as shown in the screenshot and when hovering it's changing.
This is gnome-shell 43.6 on Debian 12 with Wayland.

![Screenshot from 2023-09-13 13-06-29](https://github.com/micheleg/dash-to-dock/assets/19417705/85c19620-ee9a-4765-ad7a-9fa44dce6fdb)

**Comment by vanvugt** [comment] 2023-09-14 07:01
Duplicate of #1817

**Closed by vanvugt** 2023-09-14 07:01 UTC
