### ISSUE TITLE
Gtk.BuilderError: /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/Settings.ui:13:35 Invalid property: GtkBox.margin_left

### ISSUE THREAD

**Issue by fahmidbinfarooqui** [micheleg/dash-to-dock#1490] opened 2021-07-25 15:06 UTC
After updating my OS, I am facing problems accessing **Dash to Dock** settings. It's showing a message like this: `We're very sorry, but there's been a problem: the settings for this extension can't be displayed. We recommend that you report the issue to the extension authors`

The technical details are as below: 
``` 
Gtk.BuilderError: /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/Settings.ui:13:35 Invalid property: GtkBox.margin_left

Stack trace:
  DashToDock_Settings@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:92:23
  buildPrefsWidget@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:878:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
About my Operating System:
```
██████████████████  ████████   fahmid@manjaro 
██████████████████  ████████   -------------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: 80SX Lenovo V310-14ISK 
████████            ████████   Kernel: 5.10.52-1-MANJARO 
████████  ████████  ████████   Uptime: 8 hours, 58 mins 
████████  ████████  ████████   Packages: 1184 (pacman), 5 (flatpak), 5 (snap) 
████████  ████████  ████████   Shell: zsh 5.8 
████████  ████████  ████████   Resolution: 1366x768 
████████  ████████  ████████   DE: GNOME 40.3 
████████  ████████  ████████   WM: Mutter 
████████  ████████  ████████   WM Theme: Orchis-dark 
████████  ████████  ████████   Theme: Orchis-compact [GTK2/3] 
████████  ████████  ████████   Icons: Tela-circle [GTK2/3] 
                               Terminal: gnome-terminal 
                               CPU: Intel i5-6200U (4) @ 2.800GHz 
                               GPU: Intel Skylake GT2 [HD Graphics 520] 
                               GPU: AMD ATI Radeon HD 8670A/8670M/8690M / R5 M330 / M430 / Radeon 520 Mobile 
                               Memory: 2090MiB / 7313MiB                                               
```

**Comment by mouncy** [comment] 2021-07-27 07:58
Same issue on Ubuntu 21.04 after updating GNOME from 38 to 40.
About my OS:
```
            .-/+oossssoo+/-.               filippo@ubuntu
        `:+ssssssssssssssssss+:`           ------------------------------------ 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 21.04 x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: KVM/QEMU (Standard PC (i440FX  
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.11.0-25-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 1 hours, 24 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1530 (dpkg), 6 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.1.4 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1365x851 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 40.3 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru-dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel Xeon (Cooperlake) (2) @ 1 
    .ossssssssssssssssssdMMMNysssso.       GPU: 00:02.0 Red Hat, Inc. QXL parav 
      -+sssssssssssssssssyyyssss+-         Memory: 673MiB / 3927MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
```

**Comment by emvidi** [comment] 2021-08-31 19:57
same here arch linux
```
Linux ar 5.13.13-arch1-1 #1 SMP PREEMPT Thu, 26 Aug 2021 19:14:36 +0000 x86_64 GNU/Linux
```
```
Gtk.BuilderError: /home/e/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/Settings.ui:13:35 Invalid property: GtkBox.margin_left

Stack trace:
  DashToDock_Settings@/home/e/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:92:23
  buildPrefsWidget@/home/e/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:878:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17```

**Comment by xDestac** [comment] 2021-09-29 00:09
To fix the bug, at least in Arch Linux, what i have done has been from pacman download from the AUR repositories the package called: gnome-shell-extension-dash-to-dock-git 69.r14.g302c693-1

**Comment by ewlsh** [comment] 2021-10-05 05:28
Duplicate of #1358

**Closed by ewlsh** 2021-10-05 05:28 UTC
