### ISSUE TITLE
BETA 3.36 - Dock is "centered" to the left of screen

### ISSUE THREAD

**Issue by TheRoarkster** [micheleg/dash-to-dock#1119] opened 2020-03-10 15:42 UTC
As you develop for 3.36, please note that the current tmp/gnome-3.36 branch (as of 03.10.2020) results in a working dock on GNOME 3.36, but with it "centered" on the left side of the screen.  Settings do not get it back to the middle.  Thanks for the indispensable extension.

**Comment by dvorapa** [comment] 2020-03-10 16:00
> As you develop for 3.36, please note that the current tmp/gnome-3.36 branch (as of 03.10.2020) results in a working dock on GNOME 3.36, but with it "centered" on the left side of the screen. Settings do not get it back to the middle. Thanks for the indispensable extension.

This issue is a duplicate of #1113.

**Closed** 2020-03-10 16:15 UTC
