### ISSUE TITLE
Minimize problem!

### ISSUE THREAD

**Issue by chamfay** [micheleg/dash-to-dock#182] opened 2015-06-11 06:46 UTC
Hello,

when I choose "Minimize" on click action and when i click on program icon with multiple opened windows (ex: 2 nautilus windows), i can't switch between them.
can you please add an option (ex: switching using mouse wheel).

Another thing, if I minimize all windows (using CTRL+D), after that i can't restore (unminimize) minimized window.

Thanks.

**Comment by micheleg** [comment] 2015-06-12 17:37
For the first part, I have a limited number of actions (clicks, scroll, plus modifiers) which I can use. The scroll in particular is used to scroll the dock itself.  This is basically a duplicate of  #183. Regarding the second issue, what action is triggered by CTRL+D in your system? I haven't understood the problem.

**Comment by chamfay** [comment] 2015-06-13 06:53
Sorry sorry my mistake ;)
i mean Super+D (show desktop and minimize all windows).

**Comment by micheleg** [comment] 2015-06-14 13:24
Ok. I've spot the problem. It's is somehow the default shell behaviour which is not activating the hidden windows. With the cycle windows option I'm overwriting it and things works as expected. I'll look for a quick workaround, but I'll have to reconsider the mouse actions to provide a more consistent and functional behaviour overall. Related: #148, #144 This is actually a duplicate of #134, so I'm closing this issue.

**Closed** 2015-06-14 13:24 UTC
Labels: duplicate
