### ISSUE TITLE
weird glith while using application launcher in pop os?

### ISSUE THREAD

**Issue by phantom2152** [micheleg/dash-to-dock#1427] opened 2021-04-24 19:09 UTC
Hey I am experiencing an glitch when using the application launcher button in pop os . The animation is not smooth and for a second the desktop entries appear and then the animation will occur can anyone help me with this?

https://user-images.githubusercontent.com/70034285/115970164-62524600-a55e-11eb-9626-51a0d6505c35.mp4

**Comment by MathiasVjt** [comment] 2021-05-07 21:09
Happens in Ubuntu 21.04 too

**Comment by noahball** [comment] 2021-05-08 07:46
Happens to me on the latest version of Pop! OS too.

**Comment by CristianH033** [comment] 2021-05-09 17:49
It's happening to me too in ubuntu 21.04

**Comment by phantom2152** [comment] 2021-05-10 12:48
Hey @micheleg please look into this issue

**Comment by yahya-mohammed07** [comment] 2021-07-16 08:36
same issue on 20.04 LTS

**Comment by vanvugt** [comment] 2023-01-17 09:11
Duplicate of #1359.

**Closed by vanvugt** 2023-01-17 09:11 UTC
