### ISSUE TITLE
Error on disabling extension in DesktopIcons Integration

### ISSUE THREAD

**Issue by smedir** [micheleg/dash-to-dock#2073] opened 2023-08-17 10:27 UTC
https://github.com/micheleg/dash-to-dock/blob/71189a9fcc62a73f50add8a99baaeb6256ac9b68/desktopIconsIntegration.js#L161

Aug 17 06:20:23 archlinux gnome-shell[4514]: JS ERROR: TypeError: DockManager.getDefault() is null
                                             get extension@file:///home/x/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1719:28
                                             _sendMarginsToExtension@file:///home/x/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/desktopIconsIntegration.js:161:1
                                             _sendMarginsToAll/<@file:///home/x/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/desktopIconsIntegration.js:149:18
                                             _sendMarginsToAll@file:///home/x/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/desktopIconsIntegration.js:148:43
                                             _changedMargins/this._timedMarginsID<@file:///home/x/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/desktopIconsIntegration.js:141:18
                                             @resource:///org/gnome/shell/ui/init.js:21:20

**Comment by vanvugt** [comment] 2023-08-18 02:16
Duplicate of #1444

**Closed by vanvugt** 2023-08-18 02:16 UTC

**Comment by smedir** [comment] 2023-08-18 14:16
Not just duplicate, need to use https://gitlab.com/smedius/desktop-icons-ng/-/blob/main/desktopIconsIntegration.js?ref_type=heads, updated file.

Initiate DestopIocnsIntegraton with DesktopIconsIntegration.DesktopIconsUsableAreaClass(DockManager.getDefault) instead... OR the directly the uuid of the extension.
