### ISSUE TITLE
The default dot indicator is broken

### ISSUE THREAD

**Issue by a1ex-ak** [micheleg/dash-to-dock#2232] opened 2024-06-11 13:59 UTC
By default, in version 92, together in the Blur my Shell, and this is how the point is displayed. If you select the 'Dot' indicator, everything is fine.
![Снимок экрана от 2024-06-11 16-54-24](https://github.com/micheleg/dash-to-dock/assets/121604147/eacb535c-8a40-402c-bb49-d12310d54e15)

**Comment by vanvugt** [comment] 2024-06-12 03:41
Duplicate of #2222

**Closed by vanvugt** 2024-06-12 03:41 UTC
