### ISSUE TITLE
scroll action: switch workspace not work.

### ISSUE THREAD

**Issue by gapplef** [micheleg/dash-to-dock#935] opened 2019-04-26 09:10 UTC
Ubuntu 18.04.2
Dash to Dock V65

Set the `Scroll action` to `Switch workspace`, and scrolling on the icon of application, nothing happened. The switch workspace action only take effect when scrolling on the `Show Applications` icon.

**Comment by micheleg** [comment] 2019-04-26 11:08
Duplicate of #710, have a look at the discussion there and add any other considerations.

**Closed** 2019-04-26 11:10 UTC
Labels: duplicate
