### ISSUE TITLE
starts getting 2 docks  after few time you put sleep and wake up

### ISSUE THREAD

**Issue by mohammad-zadeed** [micheleg/dash-to-dock#2001] opened 2023-04-26 23:39 UTC
i am using ubuntu 23.04
DE: GNOME 44.0
WM: Mutter 
WM Theme: Colloid-Dark 
Theme: Colloid-Dark [GTK2/3] 
Icons: WhiteSur [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 5 5600G with Radeon G 
GPU: AMD ATI Radeon Vega Series 

when i pt my pc to sleep then wake up
sometimes  , isee 2 docks in when i am in overview or sometimes i can't do or change anything i just only see a blurry screen with only menu button
i have to restart it to fix it
![Screenshot from 2023-04-26 21-56-11](https://user-images.githubusercontent.com/120179019/234724934-01cbbf8f-8770-4d2c-b70d-6397b6091f98.png)

i am using blur my shell also

**Comment by vanvugt** [comment] 2023-05-15 08:07
Duplicate of #1992

**Closed by vanvugt** 2023-05-15 08:07 UTC
