### ISSUE TITLE
Hide dock in overview

### ISSUE THREAD

**Issue by Hombremaledicto** [micheleg/dash-to-dock#681] opened 2018-01-30 22:07 UTC
Ok, i'm asking this for two reasons:

- Aestethics: to fetch the need of OCD customizer out there
- Compatibility: there are extensions that already do this, but unfortunately, they are incompatible with dash-to-dock

This is totally a non-priority request: i do no expect it to be implemented, or to be implemented anywhere soon.

Eventually, an ideal behaviour would be to allow users to set dock visibility for the primary Activities view and for the app grid view.

**Comment by micheleg** [comment] 2018-03-04 01:41
Some changes partially in this direction was experimented here: https://github.com/micheleg/dash-to-dock/tree/experimental_autohide_in_overview.

**Comment by dvorapa** [comment] 2018-03-05 07:49
Maybe a duplicate of #25?

**Comment by micheleg** [comment] 2018-03-31 20:37
Closing as duplicate of #25 (Thanks @dvorapa!)

**Closed by micheleg** 2018-03-31 20:37 UTC
Labels: Feauture request
