### ISSUE TITLE
[Feature Request] Dragging files into an application by hovering over the  dock icon

### ISSUE THREAD

**Issue by daniesmar0** [micheleg/dash-to-dock#2213] opened 2024-05-02 18:57 UTC
I don't know if it's possible to achieve this on Walyand, but here it is:
It's very annoying that you can't drag a file from nautilus or desktop into a different application if it is full screened.

**How it works now:** Open the app, resize it so you can see both nautilus and the target application, and drag and drop.

**How it could work:** While dragging a file and _hovering over a Dock icon, the app "pops up"_ so you can drop the file into it.

I believe Windows does this or something very similar. It would make a huge difference.

**Comment by vanvugt** [comment] 2024-05-27 08:45
Duplicate of #49

**Closed by vanvugt** 2024-05-27 08:45 UTC
