### ISSUE TITLE
doubled icons for certain apps

### ISSUE THREAD

**Issue by ItamarShDev** [micheleg/dash-to-dock#239] opened 2015-10-15 13:16 UTC
When opening some  apps  from the dock (Popcorn time for example) 
the apps dock icon appears while a new app (original) icon added to the dock, creating a situation that the dock has two app icons
![Uploading Screenshot from 2015-10-15 16-11-11.png…](as seen here)

**Comment by algamer31** [comment] 2015-10-16 08:55
Possible duplicate of #215

**Comment by micheleg** [comment] 2015-10-18 00:58
Closing as duplicate.

**Closed by micheleg** 2015-10-18 00:58 UTC
Labels: duplicate
