### ISSUE TITLE
Dash to Dock causes Gnome core dump, when locking screen in overview mode (incl. debug symbols)

### ISSUE THREAD

**Issue by VeldoraTheDragon** [micheleg/dash-to-dock#2228] opened 2024-06-05 12:38 UTC
**OS**: Arch Linux
**Gnome-Shell Version**: `46.2-1`
**GDM Version**: `46.2-1`
**Dash to Dock Version**: `92-1`
**Kernel Version**: `>= 6.9.2.arch1-1` (also tested w. `6.9.3.arch1-1`)

**How many devices are affected?**
60+

**Other Active Extensions besides DtD**:
None

**Description**:
When running Dash to Dock v92 on Gnome-Shell v46, it causes a core-dump in Gnome-Shell, when the screen is being locked, while in overview mode. This causes the gnome-shell session to exit, losing all data of all open programs. Sometimes, it happens, that after re-login, all extensions are disabled.

**How to reproduce**
1) Make sure the specs from above match your system
2) Go into overview mode, by pressing `<Super>`/`<Win>`-Key
3) Press `<Super>`/`<Win>` + `<L>` to lock the screen
4) Observe how gnome-shell exists and falls back to gdm

If you want, you can follow the procedure, by ssh'ing onto the machine and by typing `journalctl -f`

<details>
<summary>Core Dump</summary>
<pre>
Jun 05 14:21:52 systemd-coredump[86696]: [🡕] Process 86047 (gnome-shell) of user 1518 dumped core.
                                                                                
                                                                                Stack trace of thread 86047:
                                                                                #0  0x000070ea093fd4f0 st_theme_node_lookup_shadow (libst-14.so + 0x494f0)
                                                                                #1  0x000070ea093fdf7d st_theme_node_get_box_shadow (libst-14.so + 0x49f7d)
                                                                                #2  0x000070ea094014d6 st_theme_node_get_paint_box (libst-14.so + 0x4d4d6)
                                                                                #3  0x000070ea0940f31f n/a (libst-14.so + 0x5b31f)
                                                                                #4  0x000070ea0949e1ed n/a (libmutter-clutter-14.so.0 + 0x3d1ed)
                                                                                #5  0x000070ea0949e636 clutter_actor_get_transformed_paint_volume (libmutter-clutter-14.so.0 + 0x3d636)
                                                                                #6  0x000070ea0940f4b3 n/a (libst-14.so + 0x5b4b3)
                                                                                #7  0x000070ea0949e1ed n/a (libmutter-clutter-14.so.0 + 0x3d1ed)
                                                                                #8  0x000070ea0949e636 clutter_actor_get_transformed_paint_volume (libmutter-clutter-14.so.0 + 0x3d636)
                                                                                #9  0x000070ea0940f4b3 n/a (libst-14.so + 0x5b4b3)
                                                                                #10 0x000070ea0949e1ed n/a (libmutter-clutter-14.so.0 + 0x3d1ed)
                                                                                #11 0x000070ea0949e636 clutter_actor_get_transformed_paint_volume (libmutter-clutter-14.so.0 + 0x3d636)
                                                                                #12 0x000070ea0940f4b3 n/a (libst-14.so + 0x5b4b3)
                                                                                #13 0x000070ea0940eb06 n/a (libst-14.so + 0x5ab06)
                                                                                #14 0x000070ea0949e1ed n/a (libmutter-clutter-14.so.0 + 0x3d1ed)
                                                                                #15 0x000070ea0949e636 clutter_actor_get_transformed_paint_volume (libmutter-clutter-14.so.0 + 0x3d636)
                                                                                #16 0x000070ea0940f4b3 n/a (libst-14.so + 0x5b4b3)
                                                                                #17 0x000070ea0949e1ed n/a (libmutter-clutter-14.so.0 + 0x3d1ed)
                                                                                #18 0x000070ea094a4ec0 n/a (libmutter-clutter-14.so.0 + 0x43ec0)
                                                                                #19 0x000070ea094a4e9e n/a (libmutter-clutter-14.so.0 + 0x43e9e)
                                                                                #20 0x000070ea094a4e9e n/a (libmutter-clutter-14.so.0 + 0x43e9e)
                                                                                #21 0x000070ea094a4e9e n/a (libmutter-clutter-14.so.0 + 0x43e9e)
                                                                                #22 0x000070ea094a4e9e n/a (libmutter-clutter-14.so.0 + 0x43e9e)
                                                                                #23 0x000070ea094a4e9e n/a (libmutter-clutter-14.so.0 + 0x43e9e)
                                                                                #24 0x000070ea095012ed n/a (libmutter-clutter-14.so.0 + 0xa02ed)
                                                                                #25 0x000070ea09502f11 n/a (libmutter-clutter-14.so.0 + 0xa1f11)
                                                                                #26 0x000070ea094c2b04 n/a (libmutter-clutter-14.so.0 + 0x61b04)
                                                                                #27 0x000070ea09741a89 n/a (libglib-2.0.so.0 + 0x5ca89)
                                                                                #28 0x000070ea097a39b7 n/a (libglib-2.0.so.0 + 0xbe9b7)
                                                                                #29 0x000070ea09742787 g_main_loop_run (libglib-2.0.so.0 + 0x5d787)
                                                                                #30 0x000070ea090ce3dc meta_context_run_main_loop (libmutter-14.so.0 + 0xce3dc)
                                                                                #31 0x000070ea0929b596 n/a (libffi.so.8 + 0x7596)
                                                                                #32 0x000070ea0929800e n/a (libffi.so.8 + 0x400e)
                                                                                #33 0x000070ea0929abd3 ffi_call (libffi.so.8 + 0x6bd3)
                                                                                #34 0x000070ea095c8fe1 n/a (libgjs.so.0 + 0x4bfe1)
                                                                                #35 0x000070ea095c9688 n/a (libgjs.so.0 + 0x4c688)
                                                                                #36 0x000070ea07b6280a n/a (libmozjs-115.so + 0x156280a)
                                                                                #37 0x000070ea077d9161 n/a (libmozjs-115.so + 0x11d9161)
                                                                                #38 0x000070ea077d4525 n/a (libmozjs-115.so + 0x11d4525)
                                                                                #39 0x000070ea07cbaa41 _ZN2JS4CallEP9JSContextNS_6HandleINS_5ValueEEES4_RKNS_16HandleValueArrayENS_13MutableHandleIS3_EE (libmozjs-115.so + 0x16baa41)
                                                                                #40 0x000070ea095fff02 n/a (libgjs.so.0 + 0x82f02)
                                                                                #41 0x000070ea0960817f gjs_context_eval_module (libgjs.so.0 + 0x8b17f)
                                                                                #42 0x000070ea09608481 gjs_context_eval_module_file (libgjs.so.0 + 0x8b481)
                                                                                #43 0x0000596b0d71658c n/a (gnome-shell + 0x258c)
                                                                                #44 0x000070ea08e39c88 n/a (libc.so.6 + 0x25c88)
                                                                                #45 0x000070ea08e39d4c __libc_start_main (libc.so.6 + 0x25d4c)
                                                                                #46 0x0000596b0d716a05 n/a (gnome-shell + 0x2a05)
                                                                                
                                                                                Stack trace of thread 86097:
                                                                                #0  0x000070ea08ea34e9 n/a (libc.so.6 + 0x8f4e9)
                                                                                #1  0x000070ea08ea5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                                                #2  0x000070e9edc9d44e n/a (iris_dri.so + 0x9d44e)
                                                                                #3  0x000070e9edc7b1fc n/a (iris_dri.so + 0x7b1fc)
                                                                                #4  0x000070e9edc9d37d n/a (iris_dri.so + 0x9d37d)
                                                                                #5  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #6  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86144:
                                                                                #0  0x000070ea08f27e9d syscall (libc.so.6 + 0x113e9d)
                                                                                #1  0x000070ea0979c9e0 g_cond_wait (libglib-2.0.so.0 + 0xb79e0)
                                                                                #2  0x000070ea0970a8dc n/a (libglib-2.0.so.0 + 0x258dc)
                                                                                #3  0x000070ea0970a94d g_async_queue_pop (libglib-2.0.so.0 + 0x2594d)
                                                                                #4  0x000070ea08495c48 n/a (libpangoft2-1.0.so.0 + 0x9c48)
                                                                                #5  0x000070ea09771236 n/a (libglib-2.0.so.0 + 0x8c236)
                                                                                #6  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #7  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86073:
                                                                                #0  0x000070ea08ea34e9 n/a (libc.so.6 + 0x8f4e9)
                                                                                #1  0x000070ea08ea5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                                                #2  0x000070ea07abfca1 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-115.so + 0x14bfca1)
                                                                                #3  0x000070ea07abfb53 n/a (libmozjs-115.so + 0x14bfb53)
                                                                                #4  0x000070ea07d1ef8e n/a (libmozjs-115.so + 0x171ef8e)
                                                                                #5  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #6  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86069:
                                                                                #0  0x000070ea08ea34e9 n/a (libc.so.6 + 0x8f4e9)
                                                                                #1  0x000070ea08ea5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                                                #2  0x000070ea07abfca1 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-115.so + 0x14bfca1)
                                                                                #3  0x000070ea07abfb53 n/a (libmozjs-115.so + 0x14bfb53)
                                                                                #4  0x000070ea07d1ef8e n/a (libmozjs-115.so + 0x171ef8e)
                                                                                #5  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #6  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86055:
                                                                                #0  0x000070ea08f27e9d syscall (libc.so.6 + 0x113e9d)
                                                                                #1  0x000070ea0979c9e0 g_cond_wait (libglib-2.0.so.0 + 0xb79e0)
                                                                                #2  0x000070ea0970a8dc n/a (libglib-2.0.so.0 + 0x258dc)
                                                                                #3  0x000070ea09776687 n/a (libglib-2.0.so.0 + 0x91687)
                                                                                #4  0x000070ea09771236 n/a (libglib-2.0.so.0 + 0x8c236)
                                                                                #5  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #6  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86056:
                                                                                #0  0x000070ea08f1c39d __poll (libc.so.6 + 0x10839d)
                                                                                #1  0x000070ea097a38fd n/a (libglib-2.0.so.0 + 0xbe8fd)
                                                                                #2  0x000070ea09740f95 g_main_context_iteration (libglib-2.0.so.0 + 0x5bf95)
                                                                                #3  0x000070ea09740fea n/a (libglib-2.0.so.0 + 0x5bfea)
                                                                                #4  0x000070ea09771236 n/a (libglib-2.0.so.0 + 0x8c236)
                                                                                #5  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #6  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86058:
                                                                                #0  0x000070ea08f1c39d __poll (libc.so.6 + 0x10839d)
                                                                                #1  0x000070ea097a38fd n/a (libglib-2.0.so.0 + 0xbe8fd)
                                                                                #2  0x000070ea09742787 g_main_loop_run (libglib-2.0.so.0 + 0x5d787)
                                                                                #3  0x000070ea099454b4 n/a (libgio-2.0.so.0 + 0x1124b4)
                                                                                #4  0x000070ea09771236 n/a (libglib-2.0.so.0 + 0x8c236)
                                                                                #5  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #6  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86688:
                                                                                #0  0x000070ea08f27e9d syscall (libc.so.6 + 0x113e9d)
                                                                                #1  0x000070ea0979d337 g_cond_wait_until (libglib-2.0.so.0 + 0xb8337)
                                                                                #2  0x000070ea0970a8a5 n/a (libglib-2.0.so.0 + 0x258a5)
                                                                                #3  0x000070ea0977724b n/a (libglib-2.0.so.0 + 0x9224b)
                                                                                #4  0x000070ea09771236 n/a (libglib-2.0.so.0 + 0x8c236)
                                                                                #5  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #6  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86374:
                                                                                #0  0x000070ea08f2a4e2 epoll_wait (libc.so.6 + 0x1164e2)
                                                                                #1  0x000070e9f94b5197 n/a (libspa-support.so + 0x15197)
                                                                                #2  0x000070e9f94a6a21 n/a (libspa-support.so + 0x6a21)
                                                                                #3  0x000070ea08947103 n/a (libpipewire-0.3.so.0 + 0x1c103)
                                                                                #4  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #5  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86066:
                                                                                #0  0x000070ea08f1c39d __poll (libc.so.6 + 0x10839d)
                                                                                #1  0x000070ea097a38fd n/a (libglib-2.0.so.0 + 0xbe8fd)
                                                                                #2  0x000070ea09740f95 g_main_context_iteration (libglib-2.0.so.0 + 0x5bf95)
                                                                                #3  0x000070ea09ddcfde n/a (libdconfsettings.so + 0x5fde)
                                                                                #4  0x000070ea09771236 n/a (libglib-2.0.so.0 + 0x8c236)
                                                                                #5  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #6  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86101:
                                                                                #0  0x000070ea08ea34e9 n/a (libc.so.6 + 0x8f4e9)
                                                                                #1  0x000070ea08ea5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                                                #2  0x000070e9edc9d44e n/a (iris_dri.so + 0x9d44e)
                                                                                #3  0x000070e9edc7b1fc n/a (iris_dri.so + 0x7b1fc)
                                                                                #4  0x000070e9edc9d37d n/a (iris_dri.so + 0x9d37d)
                                                                                #5  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #6  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86102:
                                                                                #0  0x000070ea08ea34e9 n/a (libc.so.6 + 0x8f4e9)
                                                                                #1  0x000070ea08ea5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                                                #2  0x000070e9edc9d44e n/a (iris_dri.so + 0x9d44e)
                                                                                #3  0x000070e9edc7b1fc n/a (iris_dri.so + 0x7b1fc)
                                                                                #4  0x000070e9edc9d37d n/a (iris_dri.so + 0x9d37d)
                                                                                #5  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #6  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86091:
                                                                                #0  0x000070ea08ea34e9 n/a (libc.so.6 + 0x8f4e9)
                                                                                #1  0x000070ea08ea5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                                                #2  0x000070e9edc9d44e n/a (iris_dri.so + 0x9d44e)
                                                                                #3  0x000070e9edc7b1fc n/a (iris_dri.so + 0x7b1fc)
                                                                                #4  0x000070e9edc9d37d n/a (iris_dri.so + 0x9d37d)
                                                                                #5  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #6  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86074:
                                                                                #0  0x000070ea08ea34e9 n/a (libc.so.6 + 0x8f4e9)
                                                                                #1  0x000070ea08ea5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                                                #2  0x000070ea07abfca1 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-115.so + 0x14bfca1)
                                                                                #3  0x000070ea07abfb53 n/a (libmozjs-115.so + 0x14bfb53)
                                                                                #4  0x000070ea07d1ef8e n/a (libmozjs-115.so + 0x171ef8e)
                                                                                #5  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #6  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86092:
                                                                                #0  0x000070ea08ea34e9 n/a (libc.so.6 + 0x8f4e9)
                                                                                #1  0x000070ea08ea5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                                                #2  0x000070e9edc9d44e n/a (iris_dri.so + 0x9d44e)
                                                                                #3  0x000070e9edc7b1fc n/a (iris_dri.so + 0x7b1fc)
                                                                                #4  0x000070e9edc9d37d n/a (iris_dri.so + 0x9d37d)
                                                                                #5  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #6  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86068:
                                                                                #0  0x000070ea08ea34e9 n/a (libc.so.6 + 0x8f4e9)
                                                                                #1  0x000070ea08ea5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                                                #2  0x000070ea07abfca1 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-115.so + 0x14bfca1)
                                                                                #3  0x000070ea07abfb53 n/a (libmozjs-115.so + 0x14bfb53)
                                                                                #4  0x000070ea07d1ef8e n/a (libmozjs-115.so + 0x171ef8e)
                                                                                #5  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #6  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86103:
                                                                                #0  0x000070ea08f1c39d __poll (libc.so.6 + 0x10839d)
                                                                                #1  0x000070ea097a38fd n/a (libglib-2.0.so.0 + 0xbe8fd)
                                                                                #2  0x000070ea09742787 g_main_loop_run (libglib-2.0.so.0 + 0x5d787)
                                                                                #3  0x000070ea091cb874 n/a (libmutter-14.so.0 + 0x1cb874)
                                                                                #4  0x000070ea09771236 n/a (libglib-2.0.so.0 + 0x8c236)
                                                                                #5  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #6  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86071:
                                                                                #0  0x000070ea08ea34e9 n/a (libc.so.6 + 0x8f4e9)
                                                                                #1  0x000070ea08ea5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                                                #2  0x000070ea07abfca1 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-115.so + 0x14bfca1)
                                                                                #3  0x000070ea07abfb53 n/a (libmozjs-115.so + 0x14bfb53)
                                                                                #4  0x000070ea07d1ef8e n/a (libmozjs-115.so + 0x171ef8e)
                                                                                #5  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #6  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86694:
                                                                                #0  0x000070ea08ea34e9 n/a (libc.so.6 + 0x8f4e9)
                                                                                #1  0x000070ea08ea5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                                                #2  0x000070e9edc9d44e n/a (iris_dri.so + 0x9d44e)
                                                                                #3  0x000070e9edc7b1fc n/a (iris_dri.so + 0x7b1fc)
                                                                                #4  0x000070e9edc9d37d n/a (iris_dri.so + 0x9d37d)
                                                                                #5  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #6  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86067:
                                                                                #0  0x000070ea08ea34e9 n/a (libc.so.6 + 0x8f4e9)
                                                                                #1  0x000070ea08ea5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                                                #2  0x000070ea07abfca1 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-115.so + 0x14bfca1)
                                                                                #3  0x000070ea07abfb53 n/a (libmozjs-115.so + 0x14bfb53)
                                                                                #4  0x000070ea07d1ef8e n/a (libmozjs-115.so + 0x171ef8e)
                                                                                #5  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #6  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86072:
                                                                                #0  0x000070ea08ea34e9 n/a (libc.so.6 + 0x8f4e9)
                                                                                #1  0x000070ea08ea5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                                                #2  0x000070ea07abfca1 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-115.so + 0x14bfca1)
                                                                                #3  0x000070ea07abfb53 n/a (libmozjs-115.so + 0x14bfb53)
                                                                                #4  0x000070ea07d1ef8e n/a (libmozjs-115.so + 0x171ef8e)
                                                                                #5  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #6  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86085:
                                                                                #0  0x000070ea08f1c39d __poll (libc.so.6 + 0x10839d)
                                                                                #1  0x000070ea097a38fd n/a (libglib-2.0.so.0 + 0xbe8fd)
                                                                                #2  0x000070ea09742787 g_main_loop_run (libglib-2.0.so.0 + 0x5d787)
                                                                                #3  0x000070ea091d23f9 n/a (libmutter-14.so.0 + 0x1d23f9)
                                                                                #4  0x000070ea09771236 n/a (libglib-2.0.so.0 + 0x8c236)
                                                                                #5  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #6  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86098:
                                                                                #0  0x000070ea08ea34e9 n/a (libc.so.6 + 0x8f4e9)
                                                                                #1  0x000070ea08ea5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                                                #2  0x000070e9edc9d44e n/a (iris_dri.so + 0x9d44e)
                                                                                #3  0x000070e9edc7b1fc n/a (iris_dri.so + 0x7b1fc)
                                                                                #4  0x000070e9edc9d37d n/a (iris_dri.so + 0x9d37d)
                                                                                #5  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #6  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                
                                                                                Stack trace of thread 86070:
                                                                                #0  0x000070ea08ea34e9 n/a (libc.so.6 + 0x8f4e9)
                                                                                #1  0x000070ea08ea5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                                                #2  0x000070ea07abfca1 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-115.so + 0x14bfca1)
                                                                                #3  0x000070ea07abfb53 n/a (libmozjs-115.so + 0x14bfb53)
                                                                                #4  0x000070ea07d1ef8e n/a (libmozjs-115.so + 0x171ef8e)
                                                                                #5  0x000070ea08ea6ded n/a (libc.so.6 + 0x92ded)
                                                                                #6  0x000070ea08f2a0dc n/a (libc.so.6 + 0x1160dc)
                                                                                ELF object binary architecture: AMD x86-64
</pre>
</details>

**output  of `coredumpctl gdb 86047` w. debug-symbols enabled**
```
Core was generated by `/usr/bin/gnome-shell'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000070ea093fd4f0 in st_theme_node_lookup_shadow (node=<optimized out>, property_name=0x70ea0943d0d6 "box-shadow", inherit=0, 
    shadow=<optimized out>) at ../gnome-shell/src/st/st-theme-node.c:3548
Downloading source file /usr/src/debug/gnome-shell/build/../gnome-shell/src/st/st-theme-node.c
3548          if (strcmp (decl->property->stryng->str, property_name) == 0)
```

**Comment by vanvugt** [comment] 2024-06-06 01:05
Duplicate of #2179.

The fix is in progress upstream: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3252

**Closed as not planned by vanvugt** 2024-06-06 01:05 UTC
