### ISSUE TITLE
The bottom of the window overview is cut off if the dock is extended.

### ISSUE THREAD

**Issue by laichiaheng** [micheleg/dash-to-dock#1114] opened 2020-03-09 05:10 UTC
It happens when there are 3 to 4 windows are opened, if I open the 5th window, it becomes normal.
3 windows:
![2020-03-09 13-08-37 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/76184530-3e6f5c00-6207-11ea-81cb-9775a9f83c62.png)
4 windows:
![2020-03-09 13-08-53 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/76184532-40391f80-6207-11ea-8e81-25b0ebb38cfc.png)
5 windows:
![2020-03-09 13-09-47 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/76184535-44653d00-6207-11ea-8ba1-b1adbb20de51.png)
And it happens again when there are 8 windows.
![2020-03-09 13-12-04 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/76184640-a160f300-6207-11ea-8cf8-6a2e38422aaf.png)

**Comment by 3v1n0** [comment] 2020-03-18 00:49
Duplicate of #1007

**Closed** 2020-03-18 00:49 UTC

**Comment by MauricioGlz** [comment] 2020-11-10 21:08
This issue is here again, disabling Dash to dock makes windows to be fully visible on the overview, enabling it makes windows to bu cut.
