### ISSUE TITLE
dock still appear when in lcok screen

### ISSUE THREAD

**Issue by qingju32** [micheleg/dash-to-dock#768] opened 2018-07-05 11:37 UTC
Ubuntu18.04,gnome-3-26-1604,dash to dock 63,donot have a multi-monitor configuration
In the starter there have two dock and a dock still exits when I lock the screnn.

**Comment by faraazahmad** [comment] 2018-07-09 16:34
Duplicate of #762

**Comment by micheleg** [comment] 2018-07-29 20:22
Closing as duplicate.

**Closed by micheleg** 2018-07-29 20:22 UTC
Labels: duplicate
