### ISSUE TITLE
Ctrl-click required to launch Firefox

### ISSUE THREAD

**Issue by arcasinky** [micheleg/dash-to-dock#1276] opened 2020-07-19 14:02 UTC
I recently began seeing the following behavior...

I have dash-to-dock configured to launch on click.  This works for everything on the dock except Firefox where I now have to ctrl-click.  I've verified that Firefox is not running.  Dash-to-Dock itself also indicates that it's not running (no blue bar beneath).

If I click from the Favorites menu/panel, FF starts so this behavior seems to be limited to the dock itself.

As an additional test, I started FF and then covered it with other windows to see what would happen if I tried to click from the dock.  Would it try to raise the existing FF window?  It did not.  It's as if the click does nothing at all.

Looking Glass doesn't show any errors and nothing gnome-related shows up in the system journal.

This is vaguely similar to issue "#734: Ctrl-Click not launching new instance of some gtk apps" except my behavior is the opposite:  a ctrl-click seems to be _required_ to launch the app.  I only have a half-dozen or so apps in my Favorites list so I can't say if other GTK apps are affected.

Configuration:
OpenSuSE Leap 15.1
Gnome Shell v3.26
Dash-to-Dock v65
Firefox v78.02
2 monitors

Dash-to-Dock settings:
```
[/]
animate-show-apps=false
show-windows-preview=false
force-straight-corner=false
intellihide-mode='ALL_WINDOWS'
click-action='launch'
intellihide=false
show-favorites=true
dock-position='TOP'
custom-theme-shrink=true
preferred-monitor=0
dash-max-icon-size=32
show-running=false

```

**Comment by cls-02** [comment] 2020-07-19 20:13
Can confirm this, running openSUSE Tumbleweed with gnome 3.36.4
Starting Firefox from the dock yields a following error message in journalctl:

```
Jul 19 22:12:05 ryzenshine gnome-shell[6026]: sh: line 0: exec: =firefox: not found
Jul 19 22:12:05 ryzenshine systemd[3535]: Started Application launched by gnome-shell.
-- Subject: A start job for unit UNIT has finished successfully
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- A start job for unit UNIT has finished successfully.
-- 
-- The job identifier is 302.
```

**Comment by emilianolangella** [comment] 2020-07-20 19:33
+1 with openSUSE running Tumbleweed with Gnome 3.36.4:

`Jul 20 21:30:28 kitt gnome-shell[3170]: sh: line 0: exec: =firefox: not found`
`Jul 20 21:30:28 kitt systemd[2112]: Started Application launched by gnome-shell.`
`Jul 20 21:30:28 kitt systemd[1]: systemd-localed.service: Succeeded.`

**Comment by arcasinky** [comment] 2020-07-20 20:10
Interesting that you see errors in the system log.  I don't see anything in my logs though I'm running Leap, not Tumbleweed.

Out of curiosity, are you able to start Firefox from the dock with a ctrl-click like I can?

**Comment by emilianolangella** [comment] 2020-07-21 05:53
> Interesting that you see errors in the system log. I don't see anything in my logs though I'm running Leap, not Tumbleweed.
> 
> Out of curiosity, are you able to start Firefox from the dock with a ctrl-click like I can?

Yes, I can start Firefox from the dock with a ctrl-click.

**Comment by franglais125** [comment] 2020-07-21 15:25
So all of you have this problem on openSUSE? I can't reproduce this on Debian testing (3.36.4).

**Comment by arcasinky** [comment] 2020-07-21 18:30
Looks OpenSuSE introduced a bug when they generated MozillaFirefox 78.02 package.

Simple fix:
```

-- /usr/share/applications/firefox.desktop.old	2020-07-21 14:28:20.468554634 -0400
+++ /usr/share/applications/firefox.desktop	2020-07-21 14:28:25.344529802 -0400
@@ -16,7 +16,7 @@
 
 [Desktop Action new-window]
 Name=New Window
-Exec==firefox --new-windows %u
+Exec=firefox --new-windows %u
 
 [Desktop Action PrivateBrowsing]
 Name=New Private Browsing Window

```

**Comment by cls-02** [comment] 2020-07-22 09:44
Fixing that line in the .desktop and reloading GNOME works, thank you for finding this!

**Comment by emilianolangella** [comment] 2020-07-22 09:47
For your information, it will be fixed on TW in the next submission:
https://bugzilla.opensuse.org/show_bug.cgi?id=1174360

**Closed** 2020-08-12 00:53 UTC
