### ISSUE TITLE
Clicking on the icons in the panel does not open the application windows

### ISSUE THREAD

**Issue by DmitrySkibitsky** [micheleg/dash-to-dock#2024] opened 2023-06-02 08:10 UTC
I can't tell you what affects it. 
But today the usual use of the panel stopped working correctly. 
I scattered applications on different desktops, as I always do, and at some point I start clicking on the panel, and it does not respond to my taps (application windows do not open, the button that opens the list of applications does not respond either).
Then I repeatedly switch to the current desktop application overview mode, then I click on the icon and the application window starts to appear.

Version: 82

**Comment by DmitrySkibitsky** [comment] 2023-06-02 08:11
I understand it's not very informative. Maybe someone knows how to reproduce this exactly and what to pass the application logs?

**Comment by alfrede** [comment] 2023-06-05 07:59
I had the same Problem. I solved it with deactivating this:
![grafik](https://github.com/micheleg/dash-to-dock/assets/1897882/e855b3c5-ce27-477c-806c-491a90423a51)

**Comment by alfrede** [comment] 2023-06-05 08:06
I had the same Problem. I solved it with deactivating this:
![grafik](https://github.com/micheleg/dash-to-dock/assets/1897882/e855b3c5-ce27-477c-806c-491a90423a51)
and
![grafik](https://github.com/micheleg/dash-to-dock/assets/1897882/4c426db3-a75b-4f4f-ba2d-453e32cc85aa)

Deactivating the gnome integration effect that the icons became clickable and open the program when the Dash to Dock Task is open:
![grafik](https://github.com/micheleg/dash-to-dock/assets/1897882/7f26fb65-6cf2-413b-aee3-4e44c59bf71c)

When i close this or reboot nothing will work again.

**Comment by valiantgenomics** [comment] 2023-06-05 11:08
Same issue here.... Please fix it as soon as it's convenient for you, since this bug makes Dash to Dock completely unusable.

**Comment by vanvugt** [comment] 2023-06-07 09:10
Ubuntu bug: https://launchpad.net/bugs/2022885

**Comment by fabd** [comment] 2023-06-08 09:15
Confirm issue with v82. Though for me I noticed it as soon as I logged in. Clicking any icons in the dash wouldn't launch the apps. I'm sorry I didn´t spend too much time investigating, like I don't know if the Cmd+0-9 shortcuts worked. I instantly knew it was the update since I tend to hold back so all I can confirm is reverting to v81 fixed the issue.

**Comment by fabd** [comment] 2023-06-08 09:30
Noobsai's fix may or may not solve this issuehttps://github.com/micheleg/dash-to-dock/issues/2029#issuecomment-1575258576

**Comment by sistosilvio** [comment] 2023-06-08 16:44
> Confirm issue with v82. Though for me I noticed it as soon as I logged in. Clicking any icons in the dash wouldn't launch the apps. I'm sorry I didn´t spend too much time investigating, like I don't know if the Cmd+0-9 shortcuts worked. I instantly knew it was the update since I tend to hold back so all I can confirm is reverting to v81 fixed the issue.

I have the same issue in v82. 
can confirm reverting to v81 solves the issue

**Comment by vanvugt** [comment] 2023-06-10 07:49
Looks like only Xorg sessions are affected?

**Comment by 3v1n0** [comment] 2023-06-13 00:40
I've released a new version but it should not fix this this, unless I'm missing something, however it would be nice if you could provide a `git bisect` to figure out what was the guilty commit.

**Comment by 3v1n0** [comment] 2023-06-13 00:45
Could be that https://github.com/micheleg/dash-to-dock/commit/c6c4092d9134b718a940a168ce06dac92710f779 is related?

**Comment by 3v1n0** [comment] 2023-06-13 11:30
Plase check https://github.com/micheleg/dash-to-dock/pull/2040

**Comment by Twonkk** [comment] 2023-06-14 00:32
still looks to be an issue on the V83, on reboot, everything works and then between goin into Show Apps and back to desktop or even just bouncing between open apps, it stops working and I have to go into Activities to use the function.

**Closed** 2023-06-15 20:41 UTC
