### ISSUE TITLE
With Auto-Hide disabled, an invisible Dock block mouse when using software in full screen mode.

### ISSUE THREAD

**Issue by nightonion** [micheleg/dash-to-dock#367] opened 2016-08-28 15:01 UTC
I disabled the auto-hide and put the dock at the bottom of screen to make it like a task bar in windows. When I was watching a video on YouTube in full screen mode using Chrome, I found that although the dock is invisible, it blocked my mouse from clicking  the progress bar of the video. Then I tested several software such as Firefox, Spyder and Gwenview in full screen mode. The dock always block my mouse from interacting with the GUI of these programs. Nothing will happen if I click a button or link occluded by the invisible dock.

**Comment by Domii894** [comment] 2016-08-28 19:55
Confirming this.
I have the same issue.

I can't play video games and watch youtube videos when this is enabled.
Seems that the dock is above all other windows, ...

**Comment by H4rtland** [comment] 2016-09-01 22:54
I came here to submit the same issue. Is a fix possible or is this an unavoidable behaviour?

**Comment by zosy** [comment] 2016-09-07 10:51
i have this issue too,
env 
1.archlinux X86_64
2.gnome-shell Version 3.20.2
repreduce
1.set  position bottom
2.intelligent autohide off
 when you watching videos in fullscreen,the control bar like progress bar and volume and fullscreen in dash area all can't click by mouse.

**Comment by franglais125** [comment] 2016-09-07 21:54
What version of the extension and gnome shell are you all using?

**Comment by nightonion** [comment] 2016-09-07 22:01
Ubuntu 16.04
GNOME Shell 3.18.5
Dash to Dock 53

**Comment by H4rtland** [comment] 2016-09-07 22:05
I've had it on fresh installs of Fedora 24 and Ubuntu GNOME 16.04.

So that's GNOME 3.20 and 3.18. Looking at the releases page I think that's v53 of the extension for both.

**Comment by franglais125** [comment] 2016-09-07 22:33
@nightonion and @H4rtland thanks for the quick replies!
For some reason I can't reproduce the bug, I'll keep trying though :)

Meanwhile, can either of you check if the bug is present in _master_ as well?

You just need to download, `make` `make install` and restart the shell.

**Comment by H4rtland** [comment] 2016-09-07 23:00
I don't see it anymore after installing from the master branch. For completeness I went back and installed the version from extensions.gnome.org and the issue reappeared.

**Comment by franglais125** [comment] 2016-09-07 23:10
@H4rtland Thanks. Perhaps it's patch [42ee3eca48663d5ec858ce114d8a0eb267caf8d7] that fixed the issue. I've seen @micheleg mention it a few times.

Whenever a new version comes out, probably this bug will be fixed. In any case, I still don't know why I can't reproduce this on 3.20, v53.

 Cheers.

**Comment by H4rtland** [comment] 2016-09-07 23:19
That certainly looks like it could be it. Is the master version stable enough to use for now or am I better off waiting for the next release?

**Comment by franglais125** [comment] 2016-09-07 23:21
I'm using master with no problems. However, your use-case might be different! If you find a bug, please do report it :)

**Comment by franglais125** [comment] 2016-09-07 23:38
Heh, silly me, I read "Autohide" and assumed that was the problem... Turned it off and could easily trigger the bug.

And again, the bug seems to be fixed in _master_.

**Comment by Domii894** [comment] 2016-09-19 09:50
@franglais125 
I now figured out, that this bug only happens, if I have at least one window minimized. Is this also fixed in master-branch?

**Comment by Domii894** [comment] 2016-09-19 15:54
@franglais125 
I am using archlinux newest version (4.7.4-1-ARCH) and the newest gnome-shell version (GNOME Shell 3.20.4)
I had version 53 and didn't notice that there is already version 54 released (sry :()
For the first few moments it seems to be fixed.
I will give a shout if I find something new.

**Comment by franglais125** [comment] 2016-09-19 15:56
@Domii894  Awesome... I'll consider that v54 fixed it for you :). Let me know if it's not the case.

To anyone else affected by this, if you are running Gnome 3.18 or newer, do check if there is an update for your extensions!

**Comment by micheleg** [comment] 2017-03-21 01:42
Closing as it was indeed fixed by  [42ee3ec].

**Closed by micheleg** 2017-03-21 01:42 UTC
