### ISSUE TITLE
All app icons are missing after computer locked for some time

### ISSUE THREAD

**Issue by renetchi** [micheleg/dash-to-dock#1852] opened 2022-10-13 04:46 UTC
Happening in Ubuntu 22.04

How to reproduce:
1. Left computer idle and locked for quite some time
2. Unlock the computer
3. Only `Show Applications` icon is shown in dash-to-dock
4. When clicked, blank black screen with no application is shown. And can't return to desktop or do any other navigations.

Log out / restart menu still works so I usually restart my computer to fix this.

**Comment by 3v1n0** [comment] 2022-10-13 19:21
Do you have anything useful in your `journalctl /usr/bin/gnome-shell '?

**Comment by vanvugt** [comment] 2022-10-14 06:41
Downstream Ubuntu bug: https://launchpad.net/bugs/1936734

**Comment by vanvugt** [comment] 2022-10-14 06:42
Do you mean the whole screen is black or just the dock?

If the whole screen is blank then please report a new bug to Ubuntu by running:
```
ubuntu-bug gnome-shell
```

**Comment by eliyaoo32** [comment] 2022-10-15 06:37
I also have this issue

**Comment by vanvugt** [comment] 2022-10-19 02:17
See also https://launchpad.net/bugs/1993284

**Comment by bartkoro** [comment] 2022-10-20 13:34
I'm also having this issue.

**Comment by eduardoc7** [comment] 2022-10-23 14:59
This solve for me:

https://github.com/micheleg/dash-to-dock/issues/1282#issuecomment-664693977

**Comment by holiq** [comment] 2023-01-30 16:02
still not fix?

**Comment by vanvugt** [comment] 2023-02-24 02:06
Duplicate of #1522

**Comment by vanvugt** [comment] 2023-02-24 02:06
Duplicate of #1522

**Closed by vanvugt** 2023-02-24 02:06 UTC

**Comment by santimoy044** [comment] 2023-04-16 19:18
Still not fixed?

**Comment by vanvugt** [comment] 2023-04-17 03:34
> Still not fixed?

Please use #1522 to track this issue.

**Comment by abdasis** [comment] 2024-05-16 01:37
Still not fixed

**Comment by gen3vra** [comment] 2024-05-24 21:21
Not fixed

**Comment by Rodmatronic** [comment] 2024-08-19 07:12
Still not fixed. Happened to me out of the blue

**Comment by vanvugt** [comment] 2024-08-19 07:20
Please use #1522 to track this issue.

**Comment by sapphicart** [comment] 2025-09-29 11:05
Just had this issue and followed the [suggestion by monocongo](https://github.com/micheleg/dash-to-dock/issues/1282#issuecomment-664693977) from Issue #1522 
so far so good, I have tried locking thrice and the problem has not re-appeared
