### ISSUE TITLE
Show Applications icon is not working when `Animate Show Application` is unchecked

### ISSUE THREAD

**Issue by BlackDex** [micheleg/dash-to-dock#2125] opened 2023-11-17 09:07 UTC
On Gnome 45 using extension v89 the `Show Apps` icon is not working if you have the `Animate Show Application` unchecked

Looking at the logs i see the following:
```
gnome-shell[4051]: JS ERROR: TypeError: "ANIMATION_TIME" is read-only
                                                _onShowAppsButtonToggled/<@file:///home/blackdex/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:2587:21
                                                @resource:///org/gnome/shell/ui/init.js:21:20
```

It looks like either this is a bug in Gnome, or that checkbox/feature needs to be removed.

**Comment by vanvugt** [comment] 2023-11-21 06:10
Duplicate of #2112

**Closed by vanvugt** 2023-11-21 06:10 UTC
