### ISSUE TITLE
Blur instead of transparency in gnome 46

### ISSUE THREAD

**Issue by LuJaFriK** [micheleg/dash-to-dock#2215] opened 2024-05-03 23:44 UTC
When I installed the extension in my gnome 46 desktops (tumbleweed and fedora 40) i noticed that transparency is not like it used to be, instead of bein literally transparency of wherever you are in, it became some sort of blur of my wallpaper
 
![Captura desde 2024-05-03 17-44-05](https://github.com/micheleg/dash-to-dock/assets/168876040/0666b5d9-0bc6-4f9e-804d-4981f7112fc6)

**Comment by padgriffin** [comment] 2024-05-07 00:07
Do you have Blur My Shell installed? It seems to be a problem caused by that extension. Disable Dash to Dock blur in that extension's settings.

**Comment by leachimus** [comment] 2024-05-10 09:21
> Do you have Blur My Shell installed? It seems to be a problem caused by that extension. Disable Dash to Dock blur in that extension's settings.

That really helped. I would never have thought of it. Thank you!

**Comment by po1o** [comment] 2024-05-10 11:15
> Do you have Blur My Shell installed? It seems to be a problem caused by that extension. Disable Dash to Dock blur in that extension's settings.

This worked for me too.

**Comment by vanvugt** [comment] 2024-05-27 08:52
Duplicate of #2195.

**Closed by vanvugt** 2024-05-27 08:52 UTC
