### ISSUE TITLE
Double dock background in Gnome 41 (Fedora)

### ISSUE THREAD

**Issue by shabby-goddess** [micheleg/dash-to-dock#1623] opened 2021-12-19 19:08 UTC
Additional rectangle rendered behind the dock after installation on Fedora.

Seems to be the same problem as #1436, although there is insufficient information there to confirm.

![double dock issue screenshot](https://i.ibb.co/L5nQbHd/Screenshot-from-2021-12-19-13-58-41.png)

[full screenshot](https://ibb.co/X2QXHgP)

System info:
> D2D Version: 71
> Gnome: 41
>Theme: Dracula
> WM: Wayland
> Distro: Fedora 35 Workstation
> Kernel: 5.15.8

**Comment by hackingguy** [comment] 2022-01-03 08:15
I am also getting similar issue!

**Comment by WeversonL** [comment] 2022-01-04 18:01
I think the problem is the theme used in Shell, when I switch to 'WhiteSur Dark', they fit perfectly. But when I use my pattern, 'Zorin Gray Dark', it gets this rectangle. I wanted to know if it's possible to put a fixed theme in Dash to Dock, and leave the WhiteSur Dark one

**Comment by hackingguy** [comment] 2022-01-05 09:33
It is not a problem with this extension, the issue is with the Blur my shell extension it breaks **dash to dock**!

**Comment by OlegKrikun** [comment] 2022-01-08 17:05
I have the issue with out "Blur my shell" and "User Themes" extensions.

```
Gnome: 41.2
WM: Wayland
Theme: Adwaita
Distro: Arch
```

**Comment by shabby-goddess** [comment] 2022-01-11 19:38
> It is not a problem with this extension, the issue is with the Blur my shell extension it breaks **dash to dock**!

Don't think this is the case. Issue remains when Blur My Shell is disabled, while the issue is resolved when User Themes extension is disabled. Thus, it seems that the problem lies with how gnome handles custom gtk themes.

If this is the case, it seems possible that Dash 2 Dock could implement a workaround. Given gnome's stance toward user theming, I don't expect it to be resolved upstream...

**Comment by shabby-goddess** [comment] 2022-01-11 20:03
Updating my gtk theme and disabling dash blur in blur-my-shell fixed the issue for me. Regardless, apparent incompatibility between D2D & BMS should be addressed.

**Comment by OlaoluwaM** [comment] 2022-01-23 02:33
Same here 

`
  Gnome: 41.3
  WM: Wayland
  Theme: Catppuccin
  Distro: Fedora
`

**Comment by OlaoluwaM** [comment] 2022-01-23 02:42
Currently, my only remedy is to force sharp corners, but that is barely a panacea

**Comment by viktarchemko** [comment] 2022-03-17 20:06
Uncheck this box

![image](https://user-images.githubusercontent.com/61193973/158886429-6ebf6596-1b37-46cf-9a6a-d43f557070a1.png)

**Comment by vanvugt** [comment] 2022-09-20 05:59
Moving to:
https://github.com/aunetx/blur-my-shell/issues/8
https://github.com/aunetx/blur-my-shell/issues/248

**Closed by vanvugt** 2022-09-20 05:59 UTC
