### ISSUE TITLE
Allow drag and drop opening of files

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [micheleg/dash-to-dock#446] opened 2017-02-07 20:45 UTC
With other docking applications it is possible to just drag a file's icon from a file manager, and sometimes even a web browser, it would be nice to have this feature with Dash to Dock.

**Comment by micheleg** [comment] 2017-02-07 21:18
Closing as a duplicate of #49. Unfortunately, there are technical limitations that prevents the implementation of this feature.

**Closed by micheleg** 2017-02-07 21:18 UTC
Labels: duplicate
