### ISSUE TITLE
Double letter in fedora search field

### ISSUE THREAD

**Issue by blackoutsystem** [micheleg/dash-to-dock#1976] opened 2023-03-27 17:36 UTC
with the latest version 79 in the fedora search field the first letter is doubled. I don't have this problem with version gnome-shell-extension-dash-to-dock-74-1.fc36.noarch

**Comment by vanvugt** [comment] 2023-03-28 02:11
Duplicate of #1855

**Closed by vanvugt** 2023-03-28 02:11 UTC
