### ISSUE TITLE
[Request] Minimize to an icon of its own

### ISSUE THREAD

**Issue by GNOME-IS-LIFE** [micheleg/dash-to-dock#501] opened 2017-05-12 11:16 UTC
suppose i have three different Google Chrome windows open. if I minimize all of them in conjunction with using this extension, I'll have to digging in the Overview or repeatedly click on the Google Chrome icon to find & unminimize my desired window. However, if you implement minimization on its own icon, then i can easily tell which window is which minimized. Thanks again

**Comment by micheleg** [comment] 2017-05-12 23:11
I think this is a duplicate of #201, as you have found out.

**Closed by micheleg** 2017-05-12 23:11 UTC
Labels: duplicate
