### ISSUE TITLE
Show "window preview" when mouse hover above icon

### ISSUE THREAD

**Issue by monte-monte** [micheleg/dash-to-dock#541] opened 2017-07-08 02:33 UTC
For now when enabled "Show open windows preview" option it shows actual preview only in context menu in another sub-menu. I don't see this feature useful as it is now. On screenshot in OMG!Ubuntu article I've seen behavior similar to windows' one, when preview of multiple windows is shown when you hover mouse pointer over program icon. 
I'm confused if it is a bug with my setup or am I getting something wrong. Either it can be a bug report, or a feature request, it depends. 

v.59,
GNOME Shell 3.24.2

**Comment by gunwald** [comment] 2017-07-12 19:58
I totally agree to the statement above. The window preview would finally make sense, if it was triggered on mouse hover.

**Comment by franglais125** [comment] 2017-07-13 21:48
I think this is a duplicate of https://github.com/micheleg/dash-to-dock/issues/273.

I'll post an small update there soon.

**Closed** 2017-07-16 16:36 UTC
Labels: duplicate
