### ISSUE TITLE
Autohide deosn't work with Hide Top Bar Extension in fullscreen

### ISSUE THREAD

**Issue by polnyjj** [micheleg/dash-to-dock#2048] opened 2023-06-21 00:30 UTC
When I 'm in fullscreen on some app with enabled Hide Top Bar, Dash to Dock's Autohide feature doesn't work properly. I move my cursor where the dock is but it doesn't come up correctly, it starts flickering and doesn't stop.

**Comment by vanvugt** [comment] 2023-06-22 05:25
Duplicate of #1381

**Closed by vanvugt** 2023-06-22 05:25 UTC
