### ISSUE TITLE
Disabling app shortcuts (Super + <number>) not working anymore

### ISSUE THREAD

**Issue by gitaarik** [micheleg/dash-to-dock#932] opened 2019-04-24 10:24 UTC
It used to work when applying this setting:

    gsettings set org.gnome.shell.extensions.dash-to-dock hot-keys false

Or in the settings window:

![image](https://user-images.githubusercontent.com/2470302/56652343-73c09900-668b-11e9-9729-eaff69fd5a78.png)

But it doesn't seem to work on Ubuntu 19 anymore. Very annoying because I use `Super + <number>` to switch workspaces. It works *sometimes* but not all of the time. Very weird.

GNOME Shell 3.32.0
Dash-to-dock version 66

Also see: https://askubuntu.com/questions/1135205/disable-default-dock-app-shortcut-supernum-functionality-on-ubuntu-19-04

Any ideas?

**Comment by Old-Knitterhemd** [comment] 2019-04-26 10:09
I have the exact same issue since forever.

Every now and then it just ignores it or overwrites my dconf settings.

**Comment by gitaarik** [comment] 2019-04-26 10:55
Oh wow, I didn't know about these settings! Thanks, I disabled them. Hope this will fix it for good! BTW, you can also set these settings on the command line, I added an answer to that SO question (the question wasn't mine actually): https://askubuntu.com/a/1138322/230971

**Comment by micheleg** [comment] 2019-04-26 11:03
Duplicate of #914. I need to think how to address this as it is a builtin functionality now, altough we anhance it with the shortcuts indicators and dock showing. Probably need a better wording in the settings to avoid confusion.

**Closed by micheleg** 2019-04-26 11:03 UTC
Labels: duplicate
