### ISSUE TITLE
 Unmounted drive shortcut is on the dock 

### ISSUE THREAD

**Issue by frenchy82** [micheleg/dash-to-dock#1031] opened 2019-10-21 04:00 UTC
Hi,

Concerning the new "show-mounts" option (very nice option and thanks for it ) :
On ubuntu 19.10,when the google account is set, there is a shortcut in nautilus.

This shortcut, even when if it's not mounted, is visible in the dock when show-mounts option is actived.
Left click on the icon does nothing

If i'm not wrong, it should be visible only when it's mounted. (show-mounts)

**Comment by xordspar0** [comment] 2019-10-28 12:39
Left clicking the icon should mount the volume. That works for me.

**Comment by xordspar0** [comment] 2019-10-28 12:46
Actually I can reproduce this. The first time I clicked the icon it worked correctly, but after unmounting the volume and closing Files it doesn't work anymore.

**Comment by frenchy82** [comment] 2019-11-05 09:37
On debian SID left click works percfectly.
But the question was in fact to know if unmounted drive should be on the dock?

**Comment by philipl** [comment] 2019-11-05 16:32
I tried to emulate the behaviour of Unity 7, which will show an icon for an unmounted device if the device has a known mount location. There's also some additional logic to only show an icon for local devices - which the google storage is not. I'm not sure why that's happening, and whether it would behave the same or differently in unity.

**Closed** 2020-01-07 15:22 UTC
