### ISSUE TITLE
The dot to mark running applications bugged

### ISSUE THREAD

**Issue by hien-ngo29** [micheleg/dash-to-dock#2264] opened 2024-08-21 02:22 UTC
Here's the image

![image](https://github.com/user-attachments/assets/bb3698df-79f8-4d88-9cb3-340357d300ab)

Distro: Fedora Workstation 40

**Comment by vanvugt** [comment] 2024-08-21 03:26
Duplicate of #2222

**Closed by vanvugt** 2024-08-21 03:26 UTC
