### ISSUE TITLE
Automaticly switch windows while DnD-ing a file

### ISSUE THREAD

**Issue by gigglylo** [micheleg/dash-to-dock#948] opened 2019-05-17 19:46 UTC
Hi, i have a feature request that hopefully makes the extension more useful.

Well it's easier explain it with a real case. So here it is. I'm currently working with gimp, and there's a image file displayed on a file manager i want to edit. The way im doing it now is to left click on the file, click open with, and i choose gimp. It would be simpler if i can just drag that file on the gimp icon on dock and gimp windows automatically open and i drop my file there to open it

**Comment by stokito** [comment] 2019-10-02 09:02
I just had a the problem and wondered why this is not implemented

**Comment by the-mentor** [comment] 2019-11-09 13:14
+1

**Comment by ghabit** [comment] 2020-03-06 15:56
Me too please.

**Comment by vanvugt** [comment] 2022-11-28 09:43
Duplicate of #49

**Closed by vanvugt** 2022-11-28 09:43 UTC
