### ISSUE TITLE
dock size limit ignored above 90%

### ISSUE THREAD

**Issue by benjamindaines** [micheleg/dash-to-dock#633] opened 2017-11-04 05:08 UTC
**Expected Behavior:**
Dock should take up maximum space defined by `dock size limit` as running applications are added to the dock.  Icons should only shrink after the dock cannot grow beyond set limit.  

**Current Behavior:**
Dock icons shrink as running applications are added, and the dock remains at around the default 90%.  The preference does seem to be honored when set below 90%

Gnome 3.26.2 with latest extensions.gnome release.

**Comment by micheleg** [comment] 2017-11-05 00:21
I think this is due to the fact that we only consider specific icons sizes. Therefore it can happen that the dock never reach 100% size. To double check this,  could you try to set the dock size to 100%, fill it with launchers, and then try to adjust the icon size in the settings to a different value to see if you can actually extend it to the screen edge?

**Comment by benjamindaines** [comment] 2017-11-05 02:28
Makes sense, with the perfect number of launches the dock will be close to 100% as you described.  I think what's really going on here is that once the dock is too full, icons are scaled down to the next "true" icon size (48 to 32).  Perhaps the icons should scale gradually down, which would give behavior closer to Mac OS's dock implementation.

**Comment by micheleg** [comment] 2017-11-05 14:36
Continuos scaling was consered in the past: #15. I honestly don't know what's the best. I believe in MacOsX a very high resolution icon (~1024x1024) is rescaled. We don't alwasy have access to such high resolution icons. The quality of the downscaling versus a proper rescaling of the icon is argualble, and I believe it depends quite a bit on the screen resolution, being less of a problem with highdpi panels.  

I'm closing this as it is somehow a duplicate of #15. Please referer to that issue for further discussions.

**Closed by micheleg** 2017-11-05 14:36 UTC
