### ISSUE TITLE
Blur effect (feature request)

### ISSUE THREAD

**Issue by scottmangiapane** [micheleg/dash-to-dock#448] opened 2017-02-23 23:11 UTC
This dock is awesome, thanks for making it! The only thing I wish it did differently is to have a 'Gaussian Blur' effect, like the dock on macOS or the Unity search menu. Is this something that could be added?

![Screenshot](https://cdn.arstechnica.net/wp-content/uploads/2014/10/dock-slices-wide@2x.png)

**Comment by zapashcanon** [comment] 2017-02-23 23:22
Looks like a duplicate of #429.

**Comment by scottmangiapane** [comment] 2017-02-23 23:29
Similar to that, yes. But ideally blurring the background image as well (notice that in the screenshots, the color is a translucent gradient not a single color throughout).

**Comment by micheleg** [comment] 2017-02-25 15:12
A blur effect could be nice and it would brighten up a bit the desktop probably. It is also a not trivial and computational consuming effect. It's not a new request. I'm closing this as a duplicate of #224.

**Closed by micheleg** 2017-02-25 15:12 UTC

**Comment by subbame** [comment] 2018-08-08 07:17
This would be an awesome feature. I have been supporting Dash to Doc for ages and without this extension, Gnome would be incomplete. I know not having this feature will not hinder anything but it would make the icons pop out and look cool with gaussian blur.
