### ISSUE TITLE
Wrong layout with Gnome 3.36

### ISSUE THREAD

**Issue by laichiaheng** [micheleg/dash-to-dock#1113] opened 2020-03-09 02:18 UTC
It only displays correctly if I extend the dock.
![2020-03-09 10-17-14 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/76177448-3c999e80-61ef-11ea-84a9-cb4bcdd139b2.png)

**Comment by JonahAragon** [comment] 2020-03-09 02:36
+1 Probably a similar issue, my dock is nearly full-width in Gnome 3.36.

![image](https://user-images.githubusercontent.com/3637842/76178193-93b65980-6184-11ea-8835-45a598d5194c.png)

**Comment by afrapiqin** [comment] 2020-03-09 04:28
there's another branch tmp/gnome-3.36 but it has position issue

**Comment by devillove084** [comment] 2020-03-09 04:58
+1

**Comment by green4ao** [comment] 2020-03-09 06:26
As for me moving "Dock size limit" slider right moves panel left..

**Comment by MaxXor** [comment] 2020-03-09 08:58
Dock width is messed up on GNOME 3.36. Using the `gnome-3-36` branch.

**Comment by GabMus** [comment] 2020-03-09 10:02
Can confirm the same happens here with my Arch Linux install and dash to dock installed from source from branch `tmp/gnome-3.36`

**Comment by jinhucheung** [comment] 2020-03-09 11:43
+1 Probably a similar issue in Arch Linux. And dash to dock installed  from branch tmp/gnome-3.36

**Comment by DarkSunOne** [comment] 2020-03-09 12:59
+1 also on Arch

**Comment by codecex** [comment] 2020-03-09 13:24
+1 anarchy linux (arch) idk why this extension is not already built-in inside Gnome meta-package. Most of users uses it.

**Comment by luckycurioso** [comment] 2020-03-09 15:21
+1 got gnome'd AGAIN. You dumbfucks have ZERO respect for your userbase

**Comment by laichiaheng** [comment] 2020-03-09 15:36
> +1 got gnome'd AGAIN. You dumbfucks have ZERO respect for your userbase

They really need to do something to improve the compatibility for extensions.

**Comment by dvorapa** [comment] 2020-03-10 15:57
> +1 anarchy linux (arch) idk why this extension is not already built-in inside Gnome meta-package. Most of users uses it.

Lack of developers I guess? (or maybe a different UI strategy)

**Comment by TheRoarkster** [comment] 2020-03-10 16:16
+1 Manjaro.  Apologies for not seeing this issue and opening a new one (now closed) #1119

**Comment by xrayn** [comment] 2020-03-10 19:04
As a sidenode, using the tmp/gnome-3.36 scrolling to cycle through workspaces is also not working atm.

**Comment by Sebdevar** [comment] 2020-03-10 20:23
+ 1, gnome 3.36 on arch linux

**Comment by cjdm** [comment] 2020-03-10 22:46
+1 in gnome 3.36 on Arch, both on wayland and X.
![image](https://user-images.githubusercontent.com/29413765/76365957-00edfa00-62ff-11ea-830c-df68fd7c7a2b.png)

**Comment by Tooniis** [comment] 2020-03-11 11:44
+1 on Arch. I don't know if those +1s are helping really.

**Comment by swilli** [comment] 2020-03-11 13:05
+1 let's find out.

**Comment by TheRoarkster** [comment] 2020-03-11 18:16
Further to this issue, the out-of-place dock remains on the screen when the screensaver is started and the dock is set to dodge apps and no dodgeable app is present.

**Comment by SB2502** [comment] 2020-03-11 20:54
I just installed the extension via the `tmp/gnome-3.36` branch. What it changed for me > at first the dock was stretched all over screen, with the regular apps on the left side of the dock, then a stretched void and then the 'show Appllications' icon. Now, all items are neatly grouped together again, but the dock is still positioned left of center. 

I am on Arch (hardened), using gnome 3.36.

**Comment by green4ao** [comment] 2020-03-11 22:00
> I just installed the extension via the `tmp/gnome-3.36` branch. What it changed for me > at first the dock was stretched all over screen, with the regular apps on the left side of the dock, then a stretched void and then the 'show Appllications' icon on the far right side of the dock. Similar to [cjdm's post](https://github.com/micheleg/dash-to-dock/issues/1113#issuecomment-597357350).
> 
> Now, after installing from `tmp/gnome-3.36` branch, all items are neatly grouped together again, but the dock is still positioned left of center.
> 
> I am on Arch (hardened), using gnome 3.36.

Try to move "Dock size limit" slider left in Dash-to-Dock settings

**Comment by prurigro** [comment] 2020-03-12 03:57
I got tmp/gnome-3.36 centering itself correctly -- I'm not submitting a PR because I changed the previous logic without understanding it fully, and I have no idea if the method I used is a bad practice for some reason.

Hopefully it can be used to help ship a working 3.36 release, but if not it should at least help people get it working locally while we wait for a proper solution.

Relates to #1097 #1120 and probably #1116 

```
diff --git a/docking.js b/docking.js
index 235f6d3..fdc6cf8 100644
--- a/docking.js
+++ b/docking.js
@@ -1052,7 +1052,7 @@ var DockedDash = GObject.registerClass({
             }
 
             this.move_anchor_point_from_gravity(anchor_point);
-            this.x = workArea.x + Math.round((1 - fraction) / 2 * workArea.width);
+            this.x = workArea.x + Math.round(workArea.width / 2 - this.dash._container.get_width() / 2);
             this.y = pos_y;
 
             if (extendHeight) {
@@ -1079,7 +1079,7 @@ var DockedDash = GObject.registerClass({
 
             this.move_anchor_point_from_gravity(anchor_point);
             this.x = pos_x;
-            this.y = workArea.y + Math.round((1 - fraction) / 2 * workArea.height);
+            this.y = workArea.y + Math.round(workArea.height / 2 - this.dash._container.get_height() / 2);
 
             if (extendHeight) {
                 this.dash._container.set_height(this.height);
```

**Comment by mrpeabody** [comment] 2020-03-12 04:44
> I got tmp/gnome-3.36 centering itself correctly -- I'm not submitting a PR because I changed the previous logic without understanding it fully and don't know if the method I used includes any bad practices.
> 
> Hopefully it can be used to help ship a working 3.36 release, but if not it should at least help people get it working locally while we wait for a proper solution.
> 
> Relates to #1097 #1120 and probably #1116
> 
> ```
> diff --git a/docking.js b/docking.js
> index 235f6d3..fdc6cf8 100644
> --- a/docking.js
> +++ b/docking.js
> @@ -1052,7 +1052,7 @@ var DockedDash = GObject.registerClass({
>              }
>  
>              this.move_anchor_point_from_gravity(anchor_point);
> -            this.x = workArea.x + Math.round((1 - fraction) / 2 * workArea.width);
> +            this.x = workArea.x + Math.round(workArea.width / 2 - this.dash._container.get_width() / 2);
>              this.y = pos_y;
>  
>              if (extendHeight) {
> @@ -1079,7 +1079,7 @@ var DockedDash = GObject.registerClass({
>  
>              this.move_anchor_point_from_gravity(anchor_point);
>              this.x = pos_x;
> -            this.y = workArea.y + Math.round((1 - fraction) / 2 * workArea.height);
> +            this.y = workArea.y + Math.round(workArea.height / 2 - this.dash._container.get_height() / 2);
>  
>              if (extendHeight) {
>                  this.dash._container.set_height(this.height);
> ```

Thanks man, it works! I'll be using your patch until the fix hits the EGO

**Comment by prurigro** [comment] 2020-03-12 04:47
Glad to hear it worked for you! After playing around a bit I realized there's a race condition that sometimes causes the alignment to be a bit off... I think I resolved it (so far so good) by shifting the lines that set the x and y coordinates after the width and height is set:

```
diff --git a/docking.js b/docking.js
index 235f6d3..234c239 100644
--- a/docking.js
+++ b/docking.js
@@ -1052,8 +1052,6 @@ var DockedDash = GObject.registerClass({
             }
 
             this.move_anchor_point_from_gravity(anchor_point);
-            this.x = workArea.x + Math.round((1 - fraction) / 2 * workArea.width);
-            this.y = pos_y;
 
             if (extendHeight) {
                 this.dash._container.set_width(this.width);
@@ -1063,6 +1061,9 @@ var DockedDash = GObject.registerClass({
                 this.dash._container.set_width(-1);
                 this.remove_style_class_name('extended');
             }
+
+            this.x = workArea.x + Math.round(workArea.width / 2 - this.dash._container.get_width() / 2);
+            this.y = pos_y;
         }
         else {
             this.height = Math.round(fraction * workArea.height);
@@ -1078,8 +1079,6 @@ var DockedDash = GObject.registerClass({
             }
 
             this.move_anchor_point_from_gravity(anchor_point);
-            this.x = pos_x;
-            this.y = workArea.y + Math.round((1 - fraction) / 2 * workArea.height);
 
             if (extendHeight) {
                 this.dash._container.set_height(this.height);
@@ -1089,6 +1088,9 @@ var DockedDash = GObject.registerClass({
                 this.dash._container.set_height(-1);
                 this.remove_style_class_name('extended');
             }
+
+            this.x = pos_x;
+            this.y = workArea.y + Math.round(workArea.height / 2 - this.dash._container.get_height() / 2);
         }
     }
 ```

**Comment by Tooniis** [comment] 2020-03-12 14:02
> I got tmp/gnome-3.36 centering itself correctly -- I'm not submitting a PR because I changed the previous logic without understanding it fully and don't know if the method I used includes any bad practices.
> 
> Hopefully it can be used to help ship a working 3.36 release, but if not it should at least help people get it working locally while we wait for a proper solution.
> 
> Relates to #1097 #1120 and probably #1116
> 
> ```
> diff --git a/docking.js b/docking.js
> index 235f6d3..234c239 100644
> --- a/docking.js
> +++ b/docking.js
> @@ -1052,8 +1052,6 @@ var DockedDash = GObject.registerClass({
>              }
>  
>              this.move_anchor_point_from_gravity(anchor_point);
> -            this.x = workArea.x + Math.round((1 - fraction) / 2 * workArea.width);
> -            this.y = pos_y;
>  
>              if (extendHeight) {
>                  this.dash._container.set_width(this.width);
> @@ -1063,6 +1061,9 @@ var DockedDash = GObject.registerClass({
>                  this.dash._container.set_width(-1);
>                  this.remove_style_class_name('extended');
>              }
> +
> +            this.x = workArea.x + Math.round(workArea.width / 2 - this.dash._container.get_width() / 2);
> +            this.y = pos_y;
>          }
>          else {
>              this.height = Math.round(fraction * workArea.height);
> @@ -1078,8 +1079,6 @@ var DockedDash = GObject.registerClass({
>              }
>  
>              this.move_anchor_point_from_gravity(anchor_point);
> -            this.x = pos_x;
> -            this.y = workArea.y + Math.round((1 - fraction) / 2 * workArea.height);
>  
>              if (extendHeight) {
>                  this.dash._container.set_height(this.height);
> @@ -1089,6 +1088,9 @@ var DockedDash = GObject.registerClass({
>                  this.dash._container.set_height(-1);
>                  this.remove_style_class_name('extended');
>              }
> +
> +            this.x = pos_x;
> +            this.y = workArea.y + Math.round(workArea.height / 2 - this.dash._container.get_height() / 2);
>          }
>      }
> ```
> 
> Edit: Looks like it doesn't update the position once you add new windows to the list... This might not be quite as usable as I was hoping (I'll have to dig deeper)

For me this just puts the dash in the bottom of the left edge instead of being centered.

**Comment by laichiaheng** [comment] 2020-03-12 14:04
In Manjaro, it becomes like this
![2020-03-12 22-03-45 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/76529523-5e27ae00-64ad-11ea-9c24-27abc494df70.png)

**Comment by prurigro** [comment] 2020-03-12 18:32
Hmm, sounds like there might be more factors at play here too-- there's a `factor` variable I took out because I couldn't get anything lined up with it, but I suspect it probably accounts for some scenarios that aren't in my own setup.

My solution also ended up lacking a recalculation when the items in the dash changed, so they'd extend the bar without repositioning. I'm not sure if that's because the event names changed in gnome 3.36 or because the get_width() value isn't updated after the initial construction. Either way, the more I play with my "fix" the more I'm convinced it's probably not in the direction of the correct solution.

**Comment by micheleg** [comment] 2020-03-12 22:40
I'm running the tmp/gnome-3.36 branch on an updated ubuntu 20.04 in a virtual macine and I can't reproduce the problem. Tha changes in that branch fixed the problem for me. Is anybody running ubuntu 20.04? Most people here seem on arch.

**Comment by mrpeabody** [comment] 2020-03-12 22:49
> I'm running the tmp/gnome-3.36 branch on an updated ubuntu 20.04 in a virtual macine and I can't reproduce the problem. Tha changes in that branch fixed the problem for me. Is anybody running ubuntu 20.04? Most people here seem on arch.

I have it on both Arch and Ubuntu, however, somehow on Ubuntu, Ubuntu dock makes it work correctly. If I turn off ubuntu dock, better yet, log in into vanilla gnome, the problem persists.

**Comment by mrpeabody** [comment] 2020-03-12 22:51
Also, it if helps, on Ubuntu I recall disabling/enabling parameters in dconf before it started working

**Comment by micheleg** [comment] 2020-03-12 22:54
@mrpeabody if you have a broken configuration, can you provide your configuration:
```dconf dump /org/gnome/shell/extensions/dash-to-dock/```

**Comment by mrpeabody** [comment] 2020-03-12 23:09
@micheleg I'll send you something within an hour, not around my laptop atm. If someone else can share their (I assume we all have the same problem), please don't hesitate :)

**Comment by brooksilg** [comment] 2020-03-12 23:18
Broken centering on any edge. Here is my conf dump on Arch

```
[/]
animate-show-apps=false
apply-custom-theme=false
autohide=true
autohide-in-fullscreen=false
background-color='#21232b'
custom-background-color=true
custom-theme-customize-running-dots=false
custom-theme-running-dots-border-width=4
custom-theme-shrink=true
dash-max-icon-size=32
dock-position='LEFT'
extend-height=false
force-straight-corner=false
height-fraction=0.90000000000000002
icon-size-fixed=false
intellihide=true
intellihide-mode='ALL_WINDOWS'
isolate-workspaces=false
multi-monitor=false
preferred-monitor=0
running-indicator-dominant-color=true
running-indicator-style='METRO'
scroll-action='switch-workspace'
show-mounts=false
show-running=true
show-show-apps-button=true
show-trash=false
show-windows-preview=true
unity-backlit-items=false
```

**Comment by gnloch** [comment] 2020-03-13 00:44
OS: Archlinux
dash-to-dock: branch `tmp/gnome-3.36` commit: `253fb3e45e838af2f3886abf5143886957aa34c9`

```
dconf dump /org/gnome/shell/extensions/dash-to-dock/
[/]
dock-position='BOTTOM'
icon-size-fixed=true
preferred-monitor=0
show-mounts=false
```

![Screenshot from 2020-03-12 21-43-17](https://user-images.githubusercontent.com/36160389/76579327-b10c6000-64c3-11ea-8d3d-850c29494fc8.png)

**Comment by Alexander-Huang** [comment] 2020-03-13 01:55
> Dock width is messed up on GNOME 3.36. Using the `gnome-3-36` branch.

It has a issue that is even worse...

**Comment by laichiaheng** [comment] 2020-03-13 02:02
By the way, the right click option is gone.

**Comment by Ste74** [comment] 2020-03-13 18:02
I m in Manjaro, Wayland session and what i can see is this:
dtd does not start when the session starts, i need to disable and re-enable the extension.
not centered as already reported
right click on the dots not work now.
We have built using the last /tmp/gnome3.36 branch commit.
I hope a solution for work in gnome 3.36 can be provided quickly because this are one of the no-go for release gnome 3.36 in our stable branch .. 
If a log are needed not esitate
BTW: we appreciate your work in this extension as always

**Comment by hrdwrrsk** [comment] 2020-03-13 22:34
hmm recently new commit (check `gnome-3-36` branch) the layout issue was fixed now. but right-clicking 'Show Applications' icon (for opening Dash to Dock settings) still doesn't work

**Comment by Tooniis** [comment] 2020-03-14 04:51
> hmm recently new commit (check `gnome-3-36` branch) the layout issue was fixed now. ~but right-clicking 'Show Applications' icon (for opening Dash to Dock settings) still doesn't work~ Edit: fixed in new latest commit

It's working for me now

**Comment by prurigro** [comment] 2020-03-14 05:36
Seems to work for me too-- awesome job 3v1n0! Thank you!

**Comment by sdolgikh** [comment] 2020-03-15 07:51
Reordering dock icons by dragging them still doesn't work for me. Positioning issue is now fixed, thanks.

**Comment by Sebdevar** [comment] 2020-03-16 13:49
Issue still present on arch linux.

**Comment by shawnzhu** [comment] 2020-03-18 19:00
after fetching changes on branch `gnome-3-36`, it works now on ArchLinux with Gnome 3.36.0

**Comment by laichiaheng** [comment] 2020-03-19 16:06
When is it going to be merged into master branch?

**Comment by faptaincrunch** [comment] 2020-03-30 16:17
Also being hit by this one on git and tmp/3.36. So its a gnome issue? With no PPA and not informed enough on how to build gnome from source im assuming im gonna live with this one for awhile.

**Comment by gnloch** [comment] 2020-03-30 17:33
> Also being hit by this one on git and tmp/3.36. So its a gnome issue? With no PPA and not informed enough on how to build gnome from source im assuming im gonna live with this one for awhile.

You should use `gnome-3-36` branch instead.

**Comment by faptaincrunch** [comment] 2020-03-30 23:42
> You should use `gnome-3-36` branch instead.
I cant believe I didn't try that.. thanks!

**Closed** 2020-04-19 19:29 UTC
