### ISSUE TITLE
Don't re-collapse "All Windows" list after closing window through it

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [micheleg/dash-to-dock#471] opened 2017-04-11 13:16 UTC
Currently right-clicking on an item in the dock means that I can expand "All Windows" and click the cross to close the window as well as opening it, however if I click the cross the list re-collapses which isn't very useful if you have many windows you wish to close.

So I propose to either change it so that it stays open when you close a window, or that there is a setting to modify this behaviour, or perhaps that pressing with shift held down close the window but leaves the list expanded, but a normal click also re-collapses the list. Something of some sort of this kind would be handy.

**Comment by micheleg** [comment] 2017-04-15 13:25
Thanks for spotting the bug. This is a regression due to bd2c3d7f88f86ab150db33a63e701c96e877805b.

**Comment by micheleg** [comment] 2017-04-15 13:26
Fixed now in master [72be0476ac6a16485d0253ad296760cb34ed8a44].

**Closed by micheleg** 2017-04-15 13:26 UTC
Labels: bug
