### ISSUE TITLE
Add 'Show Desktop' icon

### ISSUE THREAD

**Issue by bosyi** [micheleg/dash-to-dock#264] opened 2015-12-10 19:07 UTC
Hello. For users who have enabled Desktop this will be useful, very useful. Click should minimize all, next click should restore all. Extension TaskBar have such icon, maybe you would like to glance at code.

**Comment by micheleg** [comment] 2015-12-11 00:38
Thanks for the additional infomation. I'm closing this as it is a duplicate of #163.

**Closed by micheleg** 2015-12-11 00:38 UTC
Labels: duplicate
