### ISSUE TITLE
Windows text on Activities are behind dash to dock!

### ISSUE THREAD

**Issue by arthurbg951** [micheleg/dash-to-dock#1709] opened 2022-04-11 03:38 UTC
this is the error:
![image](https://user-images.githubusercontent.com/78566618/162661115-3b7434fc-ebed-4ecd-9f1d-afaf368d4942.png)
using fedora 35.

**Comment by 3v1n0** [comment] 2022-04-11 13:28
This should be fixed when using #1655.

In particular commit https://github.com/micheleg/dash-to-dock/pull/1655/commits/8a0356a30e33fb7256bb835137fc9b9291461bf0

Duplicate of #1608

**Closed by 3v1n0** 2022-04-11 13:28 UTC

**Comment by arthurbg951** [comment] 2022-04-11 16:02
thank you!!

**Comment by arthurbg951** [comment] 2022-04-11 16:55
So.. let me ask one question.. i cloned this repo https://github.com/3v1n0/dash-to-dock.git then installed with make and make install... But the problem persists.
![image](https://user-images.githubusercontent.com/78566618/162791058-1e517284-5131-4755-bf42-cc6d35e83c00.png)
What i have to do to fix it?

**Comment by arthurbg951** [comment] 2022-04-11 16:59
I must say that i got this error too after make and make install.
![image](https://user-images.githubusercontent.com/78566618/162792028-8d2126b0-c832-4427-9141-6747e7079b01.png)

**Comment by arthurbg951** [comment] 2022-04-11 17:04
With this source https://github.com/micheleg/dash-to-dock.git im getting same error..
![image](https://user-images.githubusercontent.com/78566618/162792696-fece37d0-74a6-4170-9668-156c0511c095.png)

**Comment by arthurbg951** [comment] 2022-04-15 18:40
Finally i got the solution. This is the steps for how i've fixed this issue:
1. Clone this repo: https://github.com/micheleg/dash-to-dock/tree/8a0356a30e33fb7256bb835137fc9b9291461bf0
2. Clone the official repo: https://github.com/micheleg/dash-to-dock
3. Move the file doking.js from the 1st step for the official repo folder
4. Execute make && make install
5. Press ALT + F2 then write r and press enter or just reboot your machine.

**Comment by arthurbg951** [comment] 2022-04-16 01:34
How i fixed it:
1. Cloned this repo: https://github.com/3v1n0/dash-to-dock/tree/41-fixes
2. Open the folder on terminal and use make && make install
3. Restart pc or press ALT + F2 then press ENTER.
