### ISSUE TITLE
Error While Launching Dash to Dock settings in Gnome ver-40.3.0

### ISSUE THREAD

**Issue by nikstarsc** [micheleg/dash-to-dock#1509] opened 2021-08-21 13:28 UTC
I am getting below error while launching Dash to Dock settings window:

`The settings of extension dash-to-dock@micxgx.gmail.com had an error:
```
Error: GSettings key preview-size-scale not found in schema org.gnome.shell.extensions.dash-to-dock
```

Stack trace:
```
_checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:563:23
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:515:30
_bindSettings@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:545:81
_init@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:219:14
buildPrefsWidget@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:1013:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
![image](https://user-images.githubusercontent.com/12734280/130323227-ce49c50d-60d8-4fe8-abd5-785186868aa9.png)
`
Linux version:

`Linux testpc 5.10.59-1-MANJARO #1 SMP PREEMPT Sun Aug 15 13:11:32 UTC 2021 x86_64 GNU/Linux`
Gnome version : 40.3.0

**Comment by validatedev** [comment] 2021-08-23 10:49
Please use https://github.com/micheleg/dash-to-dock/tree/ubuntu-dock, which works flawlessly for 40.4.0

**Comment by mosesontheweb** [comment] 2021-09-08 17:59
Well, the same happens to me. Working on Manjaro Linux, v69 is installed. GNOME is on 40.4.0. This extension comes with the system and so I do not know, how to fix this. 

The settings of extension dash-to-dock@micxgx.gmail.com had an error:
```
Error: GSettings key preview-size-scale not found in schema org.gnome.shell.extensions.dash-to-dock
```

Stack trace:
```
_checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:563:23
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:515:30
_bindSettings@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:545:81
_init@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:219:14
buildPrefsWidget@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:1013:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by ewlsh** [comment] 2021-10-05 04:58
Duplicate of #1475

See https://github.com/micheleg/dash-to-dock/issues/1475#issuecomment-880138403

**Closed by ewlsh** 2021-10-05 04:58 UTC
Labels: downstream
