### ISSUE TITLE
Preserve order of open window previews

### ISSUE THREAD

**Issue by simon-tarr** [micheleg/dash-to-dock#865] opened 2019-01-09 14:49 UTC
I use dash-to-docks 'previews of open windows feature' daily. However, I find the window behaviour to be very unintuitive. As an example, imagine that three windows are open for the same application. When you view Window 1, this will appear first in the preview pane of the three windows. If you then switch to Window 3, this window will then appear at position 1 in the preview pane (it has switched from 'last' to 'first').

I personally find this behaviour really difficult to deal with. I prefer to open documents in a particular order and know that "document 1" is always at position 1 in the preview pane, that "document 2" is aways at position 2 etc. As it stands at the moment, I have to keep in my memory a note of the last accessed document so that I can know where it will appear in the preview pane. 

A good example of when the current behaviour is particularly unintuitive is when you are working on two office documents, one snapped to each side of the screen. My brain naturally wants the document snapped on the left side to be "first" in the preview pane while the document snapped to the right of the screen to be "last" in the preview pane. At the moment, the previews will "switch" between first and last in the preview pane if you happen to switch to a different application and then return to the documents in a different order to which you last accessed them (I hope that makes sense!).

Would it be possible to include a toggle to fix the order of the preview pane so that windows aren't jumping all over the place? It's the only thing about the extension that's driving me to insanity.

If you would like an example of the expected behaviour, Windows 10 is the go-to example. The previews you see when mousing over the taskbar icon will always be order-preserved.

Thanks!

**Comment by micheleg** [comment] 2019-01-16 21:41
Duplicate of #858 (fixed in master).

**Closed by micheleg** 2019-01-16 21:41 UTC
Labels: duplicate
