### ISSUE TITLE
Dock disappearing on second monitor

### ISSUE THREAD

**Issue by gnolooo** [micheleg/dash-to-dock#2133] opened 2023-12-14 13:26 UTC
**Gnome version**: 45
**Linux distro**: Arch Linux

**Description**: When the focused application is maximized on my second monitor, the dock "blinks", disappearing and reappearing randomly. You can see more in the video below.

Some additional informations I discovered while testing (you can check all these things in the video below, I tried to trigger them in the following order):
* It's only a visual bug: as you can see, OBS does not record it. This is the reason I had to use a phone to record it (sorry for the poor quality).
* If I don't move my cursor, the dock stops blinking and remains transparent; it blinks only when I'm moving the cursor.
* Being it only a visual bug, the dock still works fine: if I click on the dock to launch a certain application while it's transparent, it still launches that application as expected.
* This just happens in the case I described above (the application has to be focused, maximized and on second monitor). If any of these conditions doesn't occur, it behaves as expected. In fact, you can see that as soon as I launch another application, the dock stops blinking: there's still an application maximized on second monitor, but it's no longer focused.

This is what I've been able to understand in the past weeks. I hope it's enough.

I'm forced to use Google Drive to share my video, as its file size is more than 10MB. If you have other solutions, let me know. [Video](https://drive.google.com/file/d/1maYWBVgxt5rWfQlY492bkbplzHexMoIW/view?usp=drive_link)

**Comment by vanvugt** [comment] 2024-01-04 07:36
Duplicate of #1381

**Closed by vanvugt** 2024-01-04 07:36 UTC
