### ISSUE TITLE
Top bar replacement

### ISSUE THREAD

**Issue by TheColorRed** [micheleg/dash-to-dock#280] opened 2016-01-27 02:38 UTC
It would be nice if a date/time item was on the dock and basically all the other items the come with the main top bar.

**Comment by micheleg** [comment] 2016-01-30 18:03
Closing as duplicate of #247. Please refer to that issue.

As said there, maybe what you want is a taskbar integrated into the panel?

**Closed by micheleg** 2016-01-30 18:03 UTC

**Comment by micheleg** [comment] 2016-01-30 22:04
By the way, there were proposed patches to include the dock in the topbar #125
