### ISSUE TITLE
dock crashes after locking the screen

### ISSUE THREAD

**Issue by April211** [micheleg/dash-to-dock#1902] opened 2023-01-17 01:03 UTC
Ubuntu 22.10 64 bit, Gnome 43.1

after locking the screen: 
![image](https://user-images.githubusercontent.com/53203590/212787001-219e63cc-b7a9-4784-92df-9db95e4ef2ae.png)

it seems that this issue only happened after you lock **from the desktop**, and when i try to disable this extention, all the icons come back, without a dock:

![image](https://user-images.githubusercontent.com/53203590/212787452-5166fe21-03e4-440c-8f2a-48cc67545d68.png)

and it won't help if you enable it again:
![image](https://user-images.githubusercontent.com/53203590/212787573-c7a3d8a4-a526-4b22-aec0-ca0ae8e564a9.png)

**Comment by vanvugt** [comment] 2023-01-17 02:16
Duplicate of #1852

**Closed by vanvugt** 2023-01-17 02:16 UTC
