### ISSUE TITLE
Drag file on icon (app apened) for top/show on front

### ISSUE THREAD

**Issue by AdsonCicilioti** [micheleg/dash-to-dock#882] opened 2019-02-10 09:10 UTC
Unlike #49 and #603 , it would be very interesting for UX if we could bring an app (open) window forward when dragging a file over the icon of this app (open). No need to have any advanced file type recognition relationship. none of this. just bring the app window forward to complete the native operation of dragging the file in this window.

This behavior is already present in several interfaces, and I believe it will make dash even more complete and intuitive.

**Comment by micheleg** [comment] 2019-02-23 16:36
Yesm this should be technically feasible. One question from a design perspective is what to do if there are more than one window opened from that app.

**Comment by AdsonCicilioti** [comment] 2019-02-23 18:06
Truth .. In this perspective I come to mind another new function - Montrar Miniatures. Thus moving to thumbnail of the desired window, it comes forward.

I do not know if this is also feasible, but it would be an incredible advance.

**Comment by skoruppa** [comment] 2019-02-23 20:24
@micheleg if I remember correctly it was handled by AWN in quite easy way. After dragging file for the first time, all windows were unminimized and one was bringed to the front. Now, without dropping the file you could move it out of application icon in the dock, and then back again at it. Action like that would bring another window to the front (just like scrolling action)

**Comment by 92Julian** [comment] 2019-03-13 07:37
> what to do if there are more than one window opened from that app.

Open the overview with only the windows of the hovered app like Unity do.

https://www.youtube.com/watch?v=wTWH_PQkzOg

**Comment by ghabit** [comment] 2020-03-06 15:57
I am also not able to drag and drop files.

**Comment by vanvugt** [comment] 2022-11-28 09:41
Duplicate of #49

**Closed by vanvugt** 2022-11-28 09:41 UTC
Labels: feature request
