### ISSUE TITLE
Drop and drag for file to dock icon to open

### ISSUE THREAD

**Issue by Dorro101** [micheleg/dash-to-dock#1738] opened 2022-05-11 03:42 UTC
Sorry for this spurious issue post. I have seen this request before here, but not recently which mentioned it is fairly complex to add. Has there been any progress and is there any chance that this feature will ever be supported? It is a habit I picked up on, using the dock on MacOS, but has been ages since I've used anything other than a Linux based distro. I am just curious, so feel free to close this ticket.

**Comment by 3v1n0** [comment] 2022-07-08 04:20
While this is quite possible in X11, wayland has still some limitations for this to happen

**Comment by jtojnar** [comment] 2022-11-17 23:26
Duplicate of #49.

**Comment by smedir** [comment] 2022-11-24 11:57
I have added support this in the extension Gtk4-desktop-icons-ng in version 22. The extension shows icons on the desktop. However it only works with file icons on the desktop. It does not work of course on icons dragged and dropped directly from Nautilus.

It is not true drag and drop, however, still useful enough.

**Comment by vanvugt** [comment] 2022-11-28 09:44
Duplicate of #49

**Closed by vanvugt** 2022-11-28 09:44 UTC
