### ISSUE TITLE
window resizeing after sleep

### ISSUE THREAD

**Issue by jothi-prasath** [micheleg/dash-to-dock#2035] opened 2023-06-06 18:27 UTC
distro: archlinux
gnome: 44.1(wayland)

window resizeing over dock after sleep/lockscreen

Before lockscreen
![Screenshot from 2023-06-06 23-55-11](https://github.com/micheleg/dash-to-dock/assets/64248628/c14e0bc3-6e4e-43f8-8a06-f49ccdbf28aa)
Afterlockscreen
![image](https://github.com/micheleg/dash-to-dock/assets/64248628/16dc93c5-f860-4751-b8da-7e11d0194068)

This is alacritty and it also happen in all windows like firefox, vscode

**Comment by vanvugt** [comment] 2023-06-07 09:13
Duplicate of #1370

**Closed by vanvugt** 2023-06-07 09:13 UTC
