### ISSUE TITLE
Delete file with drag and drop to trash icon

### ISSUE THREAD

**Issue by Fabioamd87** [micheleg/dash-to-dock#2128] opened 2023-11-29 15:25 UTC
Dear all,
I just tried to delete a file by dragging it on the trash can and it seems not to work.
Would it be possible to implement this feature?
you can find the reference here: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7225#note_1930386
Thanks

**Comment by vanvugt** [comment] 2023-11-30 03:20
Duplicate of #1907

**Closed by vanvugt** 2023-11-30 03:20 UTC
