### ISSUE TITLE
Icons remain for closed applications

### ISSUE THREAD

**Issue by sterndata** [micheleg/dash-to-dock#179] opened 2015-05-26 19:25 UTC
Just upgraded to version 46 and Fedora 22.  When I close an application, the icon stays on the dock.  There does not seem to be an option to have it stay or remove it. It does not become a favorite.

**Comment by micheleg** [comment] 2015-05-26 22:59
Hi,
thanks for you bug report. Does it happen for all applications or one in particular?
Michele

**Comment by sterndata** [comment] 2015-05-27 02:53
I've now noticed that not all applications that are started show up and sometimes the activity button doesn't work.  Restarting Gnome-shell generally sets things write for a while.

**Comment by micheleg** [comment] 2015-05-27 08:38
Please confirm if the problem occurs with no other extensions activated.

**Comment by sterndata** [comment] 2015-05-27 12:07
Good call... It seems to have to do with "Sticky Notes View"

**Comment by prdiewelt** [comment] 2015-06-02 21:59
I can confirm that running apps may not be marked as running in the dock, see
http://physiker-robert-diewelt.de/dash-to-dock-issue-1.png.
Clicking on the icon opens a new window. In this case, the new window is not assigned to the same app when using Alt+Tab, see
http://physiker-robert-diewelt.de/dash-to-dock-issue-2.png.
I never used “Sticky Notes View”. I use gnome-shell 3.16.2-2 on Arch. In metadata.json, the version is "".

**Comment by micheleg** [comment] 2015-09-25 23:56
I assume the problem was unrelated to this extension, thus I close this issue.

**Closed by micheleg** 2015-09-25 23:56 UTC

**Comment by dbogdanov** [comment] 2020-08-31 14:04
I have the same problem. Icons remain in the Dock for closed applications.

Disabling and enabling the extension in Tweaks Tools gets rid of closed apps.


GNOME Shell 3.34.3 
Ubuntu 19.10, GNOME Shell 3.34.3 
Using two monitors.

```
dconf dump /org/gnome/shell/extensions/dash-to-dock/
[/]
animate-show-apps=false
apply-custom-theme=false
click-action='minimize'
custom-theme-shrink=true
dash-max-icon-size=32
dock-fixed=false
dock-position='BOTTOM'
extend-height=false
force-straight-corner=false
height-fraction=0.90000000000000002
show-apps-at-top=true
show-mounts=false
show-show-apps-button=true
transparency-mode='DEFAULT'
```
