### ISSUE TITLE
[BUG] Ubuntu Dock - dock hides after pressing right-click of mouse on an icon and left click

### ISSUE THREAD

**Issue by D3vil0p3r** [micheleg/dash-to-dock#1892] opened 2022-12-18 01:52 UTC
Hello,
I'm using Ubuntu Dock and I'm noting that, if I right-click on one of its icons and then I left click somewhere (for example on the desktop or on one of the right-click menu entries), the Ubuntu Dock automatically hides. How can I prevent it hides?

For example:
Step 1: right-click on a Ubuntu Dock icon:
![image](https://user-images.githubusercontent.com/83867734/208275881-4c3122e6-dde2-48db-bbee-bcffa23b606e.png)

Step 2: left-click on one of the shown entries (i.e., Eject) causes Ubuntu Dock to hide:
![image](https://user-images.githubusercontent.com/83867734/208275911-bbcac11d-1f00-410b-8e9c-ac01f265aafc.png)

OS: Arch Linux with GNOME 43
Dash To Dock: Ubuntu Dock latest version

**Comment by vanvugt** [comment] 2023-01-05 02:49
Sounds like a duplicate of #1769 which is fixed in dash-to-dock 75 and ubuntu-dock 74ubuntu2.

**Closed by vanvugt** 2023-01-05 02:49 UTC

**Comment by D3vil0p3r** [comment] 2023-01-05 12:50
Hey @vanvugt I reinstalled it by cloning directly from the dash to dock repository and getting the ubuntu-dock branch by:
```
git clone https://github.com/micheleg/dash-to-dock.git -b ubuntu-dock
cd dash-to-dock
make
make install
```
and then logout and login.

After the installation, I'm still getting the issue reported above...

**Comment by vanvugt** [comment] 2023-01-09 06:45
@D3vil0p3r, unfortunately the git branch for ubuntu-dock is out of date and we are waiting for @3v1n0 to fix it.

**Comment by D3vil0p3r** [comment] 2023-01-09 07:27
Let's hope for @3v1n0 <3
