### ISSUE TITLE
[Bug?] VFunc get_id returns a transfer-none string.

### ISSUE THREAD

**Issue by bubi-luka** [micheleg/dash-to-dock#1946] opened 2023-02-28 07:54 UTC
Hi!

While using Gnome 44.beta and Dash to Dock v. 78 I get:

> VFunc get_id returns a transfer-none string. This is not supported (https://gitlab.gnome.org/GNOME/gjs/-/issues/519)

The extension does not load.

---

Info of the system:
| | Version |
|- |-|
|OS|Fedora 38 (branched)|
|Gnome Shell|44.beta|
|Dash to Dock|78|

**Comment by vanvugt** [comment] 2023-02-28 07:56
Duplicate of #1919

**Closed by vanvugt** 2023-02-28 07:56 UTC

**Comment by bubi-luka** [comment] 2023-02-28 08:00
@vanvugt Thank you for quick response. Sorry for the duplicate! I did check for it, but only with "VFunc get_id" string, and it showed nothing, so I posted it...
