### ISSUE TITLE
This extension is not compatible with your current version of GNOME.

### ISSUE THREAD

**Issue by Markellas** [micheleg/dash-to-dock#1781] opened 2022-07-29 07:53 UTC
Hello. I can't install an extension through the GNOME extension manager because dash to dock does not support this version of GNOME.

I have Fedora Workstation 36 with GNOME version 42.3.1 installed

Please help, it would be greatly appreciated.

**Comment by sammdu** [comment] 2022-07-30 00:31
#1750

**Comment by vanvugt** [comment] 2022-08-02 08:09
Duplicate of #1750

**Closed by vanvugt** 2022-08-02 08:09 UTC
