### ISSUE TITLE
Settings error

### ISSUE THREAD

**Issue by wildcard-f8** [micheleg/dash-to-dock#1482] opened 2021-07-15 05:43 UTC
The settings of extension dash-to-dock@micxgx.gmail.com had an error:
```
Error: GSettings key preview-size-scale not found in schema org.gnome.shell.extensions.dash-to-dock
```

Stack trace:
```
_checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:563:23
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:515:30
_bindSettings@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:545:81
_init@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:219:14
buildPrefsWidget@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:1013:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by Raj-Joshi-dev** [comment] 2021-07-15 07:04
Solved here: https://forum.manjaro.org/t/dash-to-dock-fails-and-default-desktop-view-changed-after-the-update/73521/19

**Comment by ewlsh** [comment] 2021-10-05 05:07
Duplicate of #1475

**Closed by ewlsh** 2021-10-05 05:07 UTC
