### ISSUE TITLE
Maximize windows are behind the dock after idle

### ISSUE THREAD

**Issue by Okanda** [micheleg/dash-to-dock#1895] opened 2023-01-02 17:40 UTC
Hello, 

My dock is on the left with no intellihide activated (like Ubuntu I think). 
I'm on EndeavourOS/Arch, Wayland 43.1 and Wayland. 

I keep some apps open and maximize on 2 workspaces (Quodlibet and Evolution). 

If I use computer everything's ok. 

If I leave, then screen go black (idle). I go back, wake up the screen,moving the mouse and then, the maximizes windows are maximize on the whole screen (except the top bar), including behind the dock. 
It's like the dock disappears during the idle. 

If I'm on workspace 2, bug only appears on other workspaces. 

Hope I'm clear, french guy inside. 

Thx

**Comment by vanvugt** [comment] 2023-01-05 02:56
Duplicate of #1370

**Closed by vanvugt** 2023-01-05 02:56 UTC
