### ISSUE TITLE
bug: Locking from overview crashes shell

### ISSUE THREAD

**Issue by skuperuser** [micheleg/dash-to-dock#2225] opened 2024-05-29 19:44 UTC
Hi,

When locking the screen from gnome overview (using shortcut), the shell seems to crash.

Fedora 40, gnome 46.2

This issue occurs on both X11 and Wayland, but:
On Wayland, the shell restarts itself, logging the user out.
On X11, the screen turns black (cursor is still shown), before sucessfully locking. When the pc is unlocked again, however, the user is presented with a window forcing them to log out due to a crash.

To reproduce:
press `SUPER` to enter overview
press `SUPER+L` to lock the screen (assuming default hotkey)

configs:
```shell
dconf dump /org/gnome/shell/extensions/dash-to-dock/
[/]
always-center-icons=true
apply-custom-theme=false
background-color='rgb(36,31,49)'
background-opacity=0.80000000000000004
custom-background-color=false
custom-theme-shrink=false
dash-max-icon-size=48
disable-overview-on-startup=false
dock-fixed=false
dock-position='BOTTOM'
extend-height=false
height-fraction=1.0
icon-size-fixed=false
intellihide-mode='FOCUS_APPLICATION_WINDOWS'
multi-monitor=false
preferred-monitor=-2
preferred-monitor-by-connector='DP-1'
running-indicator-style='DOTS'
transparency-mode='DYNAMIC'

```

some error logs:
```shell
May 29 21:12:31 fedora systemd-coredump[60303]: Process 58095 (gnome-shell) of user 1000 dumped core.
ELF object binary architecture: AMD x86-64
May 29 21:12:31 fedora gjs[60007]: Error reading events from display: Broken pipe
May 29 21:12:31 fedora gnome-shell[58893]: (EE) failed to read Wayland events: Broken pipe
May 29 21:12:31 fedora gnome-control-c[59881]: Error reading events from display: Broken pipe
May 29 21:12:31 fedora extension-manag[60000]: Error reading events from display: Broken pipe
May 29 21:12:31 fedora gnome-terminal-[59257]: Error reading events from display: Broken pipe
May 29 21:12:31 fedora xdg-desktop-por[58823]: Error reading events from display: Broken pipe
May 29 21:12:31 fedora xdg-desktop-por[58912]: Error reading events from display: Broken pipe
May 29 21:12:31 fedora evolution-alarm[58295]: Error reading events from display: Broken pipe
May 29 21:12:31 fedora gnome-calendar[59877]: Error reading events from display: Broken pipe
May 29 21:12:31 fedora gnome-software[58343]: Error reading events from display: Broken pipe
May 29 21:12:31 fedora gsd-media-keys[58266]: Error reading events from display: Broken pipe
May 29 21:12:31 fedora nextcloud[58414]: Error reading events from display: Broken pipe
May 29 21:12:31 fedora gsd-power[58269]: Error reading events from display: Broken pipe
May 29 21:12:31 fedora gsd-color[58258]: Error reading events from display: Broken pipe
May 29 21:12:31 fedora gsd-wacom[58323]: Error reading events from display: Broken pipe
May 29 21:12:31 fedora gsd-keyboard[58263]: Error reading events from display: Broken pipe
May 29 21:12:31 fedora systemd[50247]: org.gnome.SettingsDaemon.Color.service: Main process exited, code=exited, status=1/FAILURE
May 29 21:12:31 fedora systemd[50247]: org.gnome.Shell@wayland.service: Main process exited, code=dumped, status=11/SEGV
May 29 21:12:31 fedora systemd[50247]: org.gnome.SettingsDaemon.Keyboard.service: Main process exited, code=exited, status=1/FAILURE
May 29 21:12:31 fedora systemd[50247]: org.gnome.SettingsDaemon.MediaKeys.service: Main process exited, code=exited, status=1/FAILURE
May 29 21:12:31 fedora systemd[50247]: org.gnome.SettingsDaemon.Power.service: Main process exited, code=exited, status=1/FAILURE
May 29 21:12:31 fedora systemd[50247]: org.gnome.SettingsDaemon.Wacom.service: Main process exited, code=exited, status=1/FAILURE
May 29 21:12:31 fedora systemd[50247]: xdg-desktop-portal-gnome.service: Main process exited, code=exited, status=1/FAILURE
May 29 21:12:31 fedora systemd[50247]: xdg-desktop-portal-gnome.service: Failed with result 'exit-code'.
May 29 21:12:31 fedora systemd[50247]: xdg-desktop-portal-gtk.service: Main process exited, code=exited, status=1/FAILURE
May 29 21:12:31 fedora systemd[50247]: xdg-desktop-portal-gtk.service: Failed with result 'exit-code'.
May 29 21:12:31 fedora systemd[50247]: gnome-terminal-server.service: Main process exited, code=exited, status=1/FAILURE
May 29 21:12:31 fedora systemd[50247]: gnome-terminal-server.service: Failed with result 'exit-code'.
May 29 21:12:31 fedora systemd[50247]: gnome-terminal-server.service: Consumed 5.771s CPU time.
May 29 21:12:31 fedora systemd[50247]: dbus-:1.2-org.gnome.Calendar@0.service: Main process exited, code=exited, status=1/FAILURE
May 29 21:12:31 fedora systemd[50247]: dbus-:1.2-org.gnome.Calendar@0.service: Failed with result 'exit-code'.
May 29 21:12:31 fedora systemd[50247]: dbus-:1.2-org.gnome.Settings.SearchProvider@0.service: Main process exited, code=exited, status=1/FAILURE
May 29 21:12:31 fedora systemd[50247]: dbus-:1.2-org.gnome.Settings.SearchProvider@0.service: Failed with result 'exit-code'.
May 29 21:12:31 fedora systemd[50247]: dbus-:1.2-org.gnome.Settings.SearchProvider@0.service: Consumed 1.017s CPU time, 47.8M memory peak, 0B memory swap peak.
May 29 21:12:31 fedora systemd[50247]: org.gnome.SettingsDaemon.Color.service: Failed with result 'exit-code'.
May 29 21:12:31 fedora systemd[50247]: org.gnome.SettingsDaemon.Keyboard.service: Failed with result 'exit-code'.
May 29 21:12:31 fedora systemd[50247]: org.gnome.SettingsDaemon.MediaKeys.service: Failed with result 'exit-code'.
May 29 21:12:31 fedora systemd[50247]: org.gnome.SettingsDaemon.Power.service: Failed with result 'exit-code'.
May 29 21:12:31 fedora systemd[50247]: org.gnome.SettingsDaemon.Wacom.service: Failed with result 'exit-code'.
May 29 21:12:31 fedora systemd[50247]: vte-spawn.scope: Consumed 1.283s CPU time.
May 29 21:12:31 fedora systemd[50247]: app-gnome-org.gnome.Software-58343.scope: Consumed 11.266s CPU time.
May 29 21:12:31 fedora systemd[50247]: dbus-:1.2-org.gnome.Shell.Extensions@0.service: Main process exited, code=exited, status=1/FAILURE
May 29 21:12:31 fedora systemd[50247]: dbus-:1.2-org.gnome.Shell.Extensions@0.service: Failed with result 'exit-code'.
May 29 21:12:31 fedora systemd[50247]: dbus-:1.2-org.gnome.Shell.Extensions@0.service: Consumed 1.344s CPU time.
```

**Comment by vanvugt** [comment] 2024-06-03 07:06
Duplicate of #2179.

The fix is in progress upstream: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3252

**Closed by vanvugt** 2024-06-03 07:06 UTC
