### ISSUE TITLE
Wrong position

### ISSUE THREAD

**Issue by sharifzadesina** [micheleg/dash-to-dock#399] opened 2016-11-12 12:05 UTC
Hi
I have set the position of the dash to the bottom in the intelligent autohide mode with default settings but sometimes I should hover the mouse to bottom-left of the screen except bottom-center to showing it and for fixing this I need to restart the gnome-shell.
Gnome 3.22
ArchLinux

**Comment by micheleg** [comment] 2016-11-13 00:17
You mean the dock is in the right position (center) but the sensitive area is the bottom left side of the screen?

**Comment by sharifzadesina** [comment] 2016-11-13 09:06
No no no...
The dock is in bottom-center of the screen (right position) but I have to hover the mouse to the bottom-left for showing it.
Sry for my bad English...

**Comment by micheleg** [comment] 2016-11-13 19:56
Are you using a RTL (right to left) language? If so, could you check if in an English session you have the same issue?

**Comment by sharifzadesina** [comment] 2016-11-13 20:08
No, I am using English and LTR.

**Comment by micheleg** [comment] 2016-11-13 20:13
I can't reproduce this issue. Sorry for the tedious questions... any other extension installed that could interfere?

**Comment by sharifzadesina** [comment] 2016-11-13 20:17
I have just these extension enable:
![screenshot from 2016-11-13 23-44-29](https://cloud.githubusercontent.com/assets/15300551/20248520/23ec9b76-a9fb-11e6-8d70-9f1d4a4112df.png)

I will record a short screen cast if this happened again.

**Comment by micheleg** [comment] 2016-11-13 20:34
Nothing seems suspicious... it would be important if you could identify the situation in which it happens so that I can reproduce the bug. Also, please look for errors in the logs (there is some information here: https://micheleg.github.io/dash-to-dock/development.html#bugreporting)

**Comment by franglais125** [comment] 2016-11-13 21:49
Weird bug... I actually managed to reproduce this in VirtualBox. @sharifzadesina are you using a virtualized environment?

@micheleg I managed to reproduce this by changing the monitor size. After a Shell restart it starts working again. I didn't find any error in the logs...

I'll post a video of this shortly.

**Comment by sharifzadesina** [comment] 2016-11-13 22:31
@franglais125 No I am not using a virtualized environment.
I think opening chrome cause this issue, I am going to test it.

**Comment by franglais125** [comment] 2016-11-13 22:42
@sharifzadesina Is it something like this? https://youtu.be/E0z6mF1lBgc

Btw, I can't reproduce it anymore. It's going to be one of those hard-to-track bugs.
I'll keep an eye and see if it comes back at some point.

**Comment by sharifzadesina** [comment] 2016-11-13 22:45
@franglais125  Yes, I will record if it happened again, plz let issue stay open.

**Comment by micheleg** [comment] 2016-11-17 01:29
I experienced it as well on my system. I can trigger the bug by changing the scaling factor of the fonts in gnome-tweak tool.

**Comment by franglais125** [comment] 2016-12-16 21:41
@micheleg @sharifzadesina I managed to reproduce this consistantly, and finally found a fix [1].

At least in my case, to trigger the bug I need to disable and re-enable "Intelligent autohide".
To fix it, I simply added a small timeout before updating the dock's position, barrier, etc.
I tested this on 3.14 and 3.22 successfully (Stable and testing).

[1] https://github.com/franglais125/dash-to-dock/tree/fix_intellihide

**Comment by zeroepoch** [comment] 2016-12-27 21:29
I just wanted to say that I have this issue as well.  Running Fedora 25, Xorg, Nvidia driver, and a 4k 28" monitor.  With the dock on the left I need to push about 1/3 from the top of the screen rather than the center which would seem to make sense with my 1.5x font scaling.

**Comment by zeroepoch** [comment] 2016-12-27 21:40
I was going to try @franglais125's fix and report back, but it seems to be working now even after rebooting.  Based on how the fix works it must be a timing related issue.

**Comment by micheleg** [comment] 2017-01-15 00:54
Please have a look at https://github.com/micheleg/dash-to-dock/tree/fix_intellihide_wayland_2 (and maybe also  https://github.com/micheleg/dash-to-dock/tree/fix_intellihide_wayland) and see if it helps

**Comment by micheleg** [comment] 2017-01-17 22:36
I've merged the changes in master [d553004e014cef, 28c932d6e57e]. Should be fixed now.

**Closed by micheleg** 2017-01-17 22:36 UTC
Labels: bug

**Comment by zeroepoch** [comment] 2017-01-22 01:11
I tried the latest master branch and now it seems to show the dock anywhere on the edge of the screen not just the area for the dock.  In some ways that does make it work since pushing on the middle left side opens the dock always but probably not what you expected.

**Comment by micheleg** [comment] 2017-01-22 15:38
@zeroepoch : what you describe is actually the intended behaviour after commit 39041f4f902f354fb39f3, while the specific issue was fixed by the above mentioned commits (d553004, 28c932d).

**Comment by zeroepoch** [comment] 2017-01-26 02:09
It would be nice if there was an option to only have the dock part active instead of the screen edge because it seems to have some effect on the top-left corner activation and also seems more natural.  I can understand though if you didn't want to add yet another option.

**Comment by micheleg** [comment] 2017-01-27 21:33
I'd rather keep a single behaviour, but let me see. Thanks for pointing out the issue with the show activities button (I've opened an issue here #441).

**Comment by c0d0g3n** [comment] 2017-09-30 15:21
I still experience this issue from time to time on Korora 25 (wayland). The cause is unclear to me but it can be mitigated by briefly changing the dock position. My dock is placed at the bottom of the screen.

**Comment by micheleg** [comment] 2017-10-01 00:03
@c0d0g3n are you running the latest versoin of dash-to-dock?

**Comment by c0d0g3n** [comment] 2017-10-01 14:43
@micheleg Settings say `0.55.git5e531c0b16f3db4b8a7aa5588e757f4bfb7a1b8a`, can't immediately find the current version. `dnf update` has nothing to do.

**Comment by micheleg** [comment] 2017-10-01 14:46
That seems to be version 55, while we are at versio 61. I would encourrage to try to manually install an updated version and check if the bug persists.

https://micheleg.github.io/dash-to-dock/download.html

**Comment by c0d0g3n** [comment] 2017-10-01 15:03
I have now updated to version 61. I'll report here if the issue still happens. Thank you.
