### ISSUE TITLE
Indicator dots overlap app icons in gnome-shell 46.2

### ISSUE THREAD

**Issue by shelvaldes** [micheleg/dash-to-dock#2222] opened 2024-05-27 15:36 UTC
Fedora 40, the white dots that indicate an active app are overlapping the actual icon in any case. Here a screenshot.

![white points dock](https://github.com/micheleg/dash-to-dock/assets/35204421/10a15b56-6e7b-4ea2-b285-73d97cb3f999)

**Comment by andreglatz** [comment] 2024-05-27 16:39
I have the same problem on Arch Linux with Gnome 46.2

![image](https://github.com/micheleg/dash-to-dock/assets/54822067/25e9dedd-d987-494f-ad9a-18147dc175ab)

**Comment by Calosis** [comment] 2024-05-27 17:37
Same issue here on 46.2

**Comment by kenny-kelley** [comment] 2024-05-27 19:02
May be related to previous a issue and fix: #2160 and #2168

I had this problem pre-`v90` on any GNOME 46. It's back in GNOME 46.2 + Dash to Dock 92.

I'm also on Fedora 40 using the `dnf` package for Dash to Dock. 100% scaling on a 2560x1440, 27 inch monitor. Seeing similar behavior on my laptop's much smaller monitor too.

These are my settings:
![Screenshot from 2024-05-27 14-57-13](https://github.com/micheleg/dash-to-dock/assets/16879853/8eaded6b-2693-4b9c-a08b-e6b4d0d0f03b)

Toggling on "Use built-in theme" definitely improves it.

**Comment by akashdiphazra** [comment] 2024-05-29 07:05
This thing appears after recent gnome-shell updates in fedora 40, toggling back indicators from square to dots fixes the issue.

**Comment by dm1cael** [comment] 2024-05-29 22:01
Same issue with Fedora 40. As @akashdiphazra said, changing from default (or, in his case, square) to dots fixed the issue.

**You can find this option on the "appearence" page.**
![image](https://github.com/micheleg/dash-to-dock/assets/167719716/69d7a6c5-872f-4041-89eb-feff1180047a)

**Comment by kenny-kelley** [comment] 2024-05-29 23:55
The "Dots" option is slightly different from "Default".

For example, "Default" does a single dot for applications that you have multiple windows of while "Dots" does multiple dots.

**Comment by GazimSoliev** [comment] 2024-05-30 01:32
I have the same ui issue

**Comment by ArchUser123** [comment] 2024-05-31 04:20
Changing this option to **"Dots"** instead of Default fixes it for me!
![image](https://github.com/micheleg/dash-to-dock/assets/147475208/5af12912-f2b4-4fd6-a729-5d802a5fd11b)

**Comment by v9lu** [comment] 2024-06-03 01:14
Same problem here, but when I compare old screenshot with "Default" and new screenshot with "Dots", the "Default" option looks small and better for me, so fix it pleaseeee :<

**Comment by pchmykh** [comment] 2024-06-03 05:38
Also built-in theme color mismatches with default system dock.

**Comment by vanvugt** [comment] 2024-06-04 05:48
It's a regression/feature in gnome-shell 46.2 so we just need to adapt...
```
6f215fa55d1ba477ca2c8950344a249742762c36 is the first bad commit
commit 6f215fa55d1ba477ca2c8950344a249742762c36
Author: Sebastian Keller <skeller@gnome.org>
Date:   Sun Mar 17 12:43:03 2024 +0100

    appDisplay: Set running indicator dot offset via CSS
    
    The offset was given as a hardcoded (physical) pixel value and did not
    take scaling into account. This lead to it being shifted closer towards
    the icon as the scale increased.
    
    This now replaces the hardcoded value with a CSS property which
    automatically includes the scale factor.
    
    Further this allows simplifying some calculations that previously were
    trying to counteract the hardcoded offset using margins by using the
    intended offset directly.
    
    With this the dot in the dash is also now placed at exactly the bottom
    of the hover highlight, while previously there was an unintentional 1px
    space.
    
    Closes: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7488
    Part-of: <https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3245>
    (cherry picked from commit 31997fa2f9f3183d97c22f073e878b308331f288)

 data/theme/gnome-shell-sass/widgets/_app-grid.scss | 4 ++--
 data/theme/gnome-shell-sass/widgets/_dash.scss     | 2 +-
 js/ui/appDisplay.js                                | 7 ++++++-
 3 files changed, 9 insertions(+), 4 deletions(-)
```

**Comment by vanvugt** [comment] 2024-06-04 05:50
:arrow_up: Sound like fun, @sergio-costas ? Though I fear that backward compatibility will be a pain.

**Comment by sergio-costas** [comment] 2024-06-04 10:32
I'll give it a check...

**Comment by proninyaroslav** [comment] 2024-06-21 08:13
Is it possible to fix this?

**Comment by sergio-costas** [comment] 2024-06-21 08:25
I have to check it, but I think that I have an idea.

**Comment by proninyaroslav** [comment] 2024-08-16 18:04
@sergio-costas 
I think if this can't be fixed, it should be removed, as it clearly doesn't work properly. A replacement would be to set the `Dots` as default, and add the ability to display one dot (regardless of the windows count).

**Comment by proninyaroslav** [comment] 2024-08-21 17:32
As a possible solution, I added an indicator with a single point, as similar as possible to the default indicator: https://github.com/micheleg/dash-to-dock/pull/2265

**Comment by linesquarecube** [comment] 2024-09-14 21:55
Thanks a lot for trying to fix this! Unfortunately, using 'dot' in v96 doesn’t change anything for me in Gnome 46.4 on Debian. The indicator is still stuck somewhere 'inside' the icon.
![grafik](https://github.com/user-attachments/assets/9dbcc992-3a10-4644-89d0-3fdb82b7c853)
Only switching to 'Use Built-in Theme' helps, but it also breaks the whole look for me and causes unpinned applications to stay visible, even if they’re not running.
![grafik](https://github.com/user-attachments/assets/c24ea66a-09e0-4f2e-9f8d-abef4e69f97b)
Anyway, I really appreciate you trying to fix this! :)

**Comment by proninyaroslav** [comment] 2024-09-15 07:32
@linesquarecube 
I'm using 46.4, but on Fedora with the default theme. Works fine. Have you tried using "Dots"? If "Dot" doesn't work for you, then "Dots" shouldn't work either, since it uses the same drawing, except that it draws one dot instead of multiple.

**Comment by linesquarecube** [comment] 2024-09-16 20:10
@proninyaroslav I've tried all available options without any luck. Everything works as expected with the integrated theme. However, after some back-and-forth with the options, now all applications disappear when I deselect the integrated theme. I haven't changed anything else. I'm a bit confused right now :confused:   

Using integrated theme:
![grafik](https://github.com/user-attachments/assets/95cfb761-0853-48e3-89ff-0e00a376b4d9)
Deselect the integrated theme:
![Bildschirmfoto vom 2024-09-16 22-05-17](https://github.com/user-attachments/assets/b502bba7-3937-48f5-a8b8-ce7497be8bde)

**Comment by proninyaroslav** [comment] 2024-09-16 20:18
@linesquarecube 
Yes, something is definitely broken in the styles. Maybe there are other extensions that change the styles? For example, transparency.

**Comment by 3v1n0** [comment] 2024-09-24 23:17
This should have been fixed via #2285 and #2287

**Comment by vanvugt** [comment] 2024-09-25 01:14
Reopened. Sounds like @3v1n0 was commenting on the wrong bug there.

**Comment by linesquarecube** [comment] 2024-09-25 19:20
@proninyaroslav The are three additional extension with influence on the look I have installed
- [Transparent Top Bar](https://github.com/lamarios/gnome-shell-extension-transparent-top-bar)
- [Just Perfection](https://gitlab.gnome.org/jrahmatzadeh/just-perfection)
- [Rounded Window Corners](https://github.com/flexagoon/rounded-window-corners)
I've already tried to deactivate and also uninstall the other extensions, unfortunately without any change.

Is there a possibility to clear all additional configuration caused by extensions? I do not fear to reconfigure them.

**Comment by proninyaroslav** [comment] 2024-09-25 19:37
@linesquarecube 
You can use dconf editor and reset everything you need in the `/org/gnome/shell/extensions/` branch and others.

**Comment by sergio-costas** [comment] 2024-10-03 17:58
I'm testing it right now in a fresh-installed Fedora 40. After updating with DNF, it fails as indicated. I'll try to fix it.

![imagen](https://github.com/user-attachments/assets/b2db489f-e9cc-4605-8875-65a6cf2d1536)

@linesquarecube Can you enable the integrated theme, open a terminal, run `journalctl -f`, disable the integrated theme and copy/paste here the errors that (I presume) should appear in the terminal, please?

**Closed** 2024-10-08 07:24 UTC

**Comment by proninyaroslav** [comment] 2024-10-08 08:06
#2315  tested on Fedora 40, works fine.
