### ISSUE TITLE
Not working with Fedora32

### ISSUE THREAD

**Issue by ran000** [micheleg/dash-to-dock#1125] opened 2020-03-17 17:16 UTC
Not working with Fedora32. Here is an errot:
Mar 17 20:12:33 notebook gnome-shell[1668]: JS WARNING: [/home/ran/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/utils.js 25]: Array.slice is deprecated; use Array.prototype.slice instead
Mar 17 20:12:33 notebook gnome-shell[1668]: JS WARNING: [/home/ran/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/utils.js 25]: Array.concat is deprecated; use Array.prototype.concat instead
Mar 17 20:12:33 notebook gnome-shell[1668]: JS WARNING: [/home/ran/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIcons.js 1051]: reference to undefined property "_onLeaveEvent"
Mar 17 20:12:33 notebook gnome-shell[1668]: JS ERROR: Extension dash-to-dock@micxgx.gmail.com: TypeError: appIconPrototype._onLeaveEvent is undefined
                                            _init@/home/ran/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIcons.js:1051:9
                                            _init@/home/ran/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/dash.js:225:30
                                            _init@/home/ran/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:220:21
                                            _createDocks@/home/ran/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1701:20
                                            DashToDock_DockManager@/home/ran/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1593:14
                                            enable@/home/ran/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/extension.js:16:5

**Comment by 3v1n0** [comment] 2020-03-18 00:23
Duplicate of #1097

**Closed by 3v1n0** 2020-03-18 00:23 UTC
