### ISSUE TITLE
rounding of non-pinned apps in dock when switching rapidlly messed up

### ISSUE THREAD

**Issue by MaxBrandtner** [micheleg/dash-to-dock#1956] opened 2023-03-04 04:58 UTC
# How to reproduce
1. enable isolate workspaces
2. focus on an application that isn't in a favorite
3. go to overview(to see the dock)
4. quickly switch workspaces

# Results
The icon either disappears or the rounding around it will be squarish. 

# Expected result
because the switching is so rapid, the animation should be skipped and the icon with the circular backdrop should appear

**Comment by vanvugt** [comment] 2023-03-07 05:53
Duplicate of #1817

**Closed by vanvugt** 2023-03-07 05:53 UTC
