### ISSUE TITLE
shell doesn't recover when suspend is activated from overview

### ISSUE THREAD

**Issue by LostinSpacetime** [micheleg/dash-to-dock#2243] opened 2024-06-29 10:48 UTC
A stated in the title, the Gnome Shell doesn't recover from suspend when the suspend state is activated from the overview screen. This only happens if the dash-to-dock extension is active.

I encountered this issue on a Fedora 40 with Gnome 46 wayland and xorg. I didn't have this issue with Gnome 45.

This can be a problem for people (like me) who have an OLED screen and hide the top panel to avoid burn-in.

**Comment by alex27riva** [comment] 2024-06-29 15:15
Hi, I have the same issue when locking the screen on the "activities" view.

**Comment by vanvugt** [comment] 2024-07-01 07:25
Duplicate of #2179.

The proposed fix is in gnome-shell itself: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3252

**Closed by vanvugt** 2024-07-01 07:25 UTC
