### ISSUE TITLE
Dock shown on login screen

### ISSUE THREAD

**Issue by xbonio** [micheleg/dash-to-dock#488] opened 2017-04-25 07:47 UTC
Since the latest update, dock is shown on login screen after the screen is locked (CTRL+ALT+L).
I don't know whether it's bug or feature but I have not seen anything similar in other DEs.

Ubuntu 16.04
GNOME Shell 3.20.4
Dash to dock version: 57
![screenshot from 2017-04-25 09-41-16](https://cloud.githubusercontent.com/assets/14818302/25373997/1ee80626-299c-11e7-9748-853772d9fe32.png)

**Comment by micheleg** [comment] 2017-04-26 23:58
Hi,
this is definitely a bug. The extension doesn't get correctly unloaded and therefore stay active. Is it reproducible or did it happen only once?

It could be due to some conflict with other extensions. Could you try disable them and see if the problem persists?

Moreover, it could help if you could look for some error logs. This command (might require sudo) should give some information:

```journalctl   /usr/bin/gnome-shell```

**Comment by xbonio** [comment] 2017-04-27 09:55
It was reproducible until I have forced system reboot or until I have fiddled with other extensions installed. For now, the problem is gone. If I manage to reproduce it again, I will look into the journal and post logs here.

**Comment by micheleg** [comment] 2017-04-27 20:56
I'm closing this issue, but feel free to reopen it if the bug reoccurs.

**Closed by micheleg** 2017-04-27 20:56 UTC

**Comment by wagneja4** [comment] 2022-02-06 02:26
Happens to me, when my system suspends on inactivity.
