### ISSUE TITLE
Weird visual glitch on Fedora 36 (Gnome 42.2, Wayland)

### ISSUE THREAD

**Issue by Aplicat0r** [micheleg/dash-to-dock#1825] opened 2022-09-19 18:54 UTC
![image](https://user-images.githubusercontent.com/76044844/191093790-ff387f4a-0ae0-499f-9793-2f0d8db40730.png)

**Comment by vanvugt** [comment] 2022-09-20 05:55
Duplicate of #1623

**Closed by vanvugt** 2022-09-20 05:55 UTC
