### ISSUE TITLE
Not work at ArchLinux 3.35.91

### ISSUE THREAD

**Issue by cathaysia** [micheleg/dash-to-dock#1116] opened 2020-03-09 09:35 UTC
Hi !
Thanks for your work at dash to dock! My archlinux bring a lot of software update today. And my Gnome Shell update to 3.35.91, it cause many plug-in can't work. dash to dock is one of them.

Dash to dock can't bring any new thing after I installed, there is a big "ERROR" at https://extensions.gnome.org/extension/307/dash-to-dock/ after I installed.

Well， the result  `gnome-shell --version` is "GNOME Shell 3.36.0", but the version of setting show is 3.35.91……

**Comment by hrdwrrsk** [comment] 2020-03-09 09:49
Use git version if you updated to 3.36 (get it from `tmp/gnome-3.36` branch, but expect some issues like #1113)

**Comment by cathaysia** [comment] 2020-03-09 10:09
OK. Thanks for your reply

**Comment by sdolgikh** [comment] 2020-03-09 10:21
Another option is to downgrade gnome to 3.34.4, I used that archived repo:

```
Server = https://archive.archlinux.org/repos/2020/03/06/$repo/os/$arch
```
and then pacman -Syyuu

**Comment by dvorapa** [comment] 2020-03-09 13:47
> Another option is to downgrade gnome to 3.34.4, I used that archived repo:
> 
> ```
> Server = https://archive.archlinux.org/repos/2020/03/06/$repo/os/$arch
> ```
> 
> and then pacman -Syyuu

Not a good option for regular Arch Linux users. Anyway this issue is a duplicate of #1084, can be solved using #1097:

> Use git version if you updated to 3.36 (get it from `tmp/gnome-3.36` branch, but expect some issues like #1113)

**Comment by maboleth** [comment] 2020-03-10 01:44
I hope devs will sort this asap. Of all big extensions I tried, this is the only one that still doesn't offer 3.36 support, yet it's the only one that fits my usage. Duh!

**Comment by Scotty-Trees** [comment] 2020-03-10 04:14
GNOME 3.36 is going to be released March 11 and I like your extension very much and hope it can be updated to include support for GNOME 3.36. Keep up the great work!

**Comment by MasterB0t** [comment] 2020-03-10 05:01
> Use git version if you updated to 3.36 (get it from `tmp/gnome-3.36` branch, but expect some issues like #1113)

Can you explain me how to get it from "tmp/gnome-3.36" ? 
Thanks..

**Comment by ismaail** [comment] 2020-03-10 05:29
@MasterB0t steps to install from the source

First remove the extension folder in `.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com`

In the Terminal, run the follwing commands:

```sh
cd /tmp
git clone -b tmp/gnome-3.36 https://github.com/micheleg/dash-to-dock.git
cd dash-to-dock
make
make install
```
Reload the Shell with `Alt +F2`, enter the letter `r` and hit `Enter` key

**Comment by esa1975** [comment] 2020-03-10 23:48
For what it's worth, I just used the tmp option above and I don't have the layout issue. Maybe it has been addressed?

**Comment by luca-viggiani** [comment] 2020-03-13 07:29
In my case it shows misplaced in GS 3.36, Wayland and HiDPI screen (tmp/gnome-3.36 branch)
![Schermata da 2020-03-13 08-24-03](https://user-images.githubusercontent.com/25035914/76599093-8abae480-6504-11ea-902d-7a8e51d90d18.png)

**Comment by mathieu-lemay** [comment] 2020-03-15 16:07
Most problems seem to be fixed now in the `gnome-3-36` branch.

**Comment by maboleth** [comment] 2020-03-15 17:40
If it's working, why this extension isn't official already? I'm sure even with slight misalignment, people would still be satisfied and get the job done.

So far I've been using Floating Dock extension. It's very nice but some features like auto-hide is missing, there's always one big blue dot on the screen. But overall, I'd switch easily to it if it had auto-hide working.

**Comment by 3v1n0** [comment] 2020-03-18 00:24
Duplicate of #1123

**Closed** 2020-03-18 00:50 UTC
