### ISSUE TITLE
Why Dash to dock is showing 2 instances when there is only one running?

### ISSUE THREAD

**Issue by abinlatheef** [micheleg/dash-to-dock#1659] opened 2022-01-26 03:31 UTC
Dash to dock showing more instances when there is only one running for some applications. I think it is considering other background processes too.
Sometimes it shows dots when no instance is running too.

See the two dots under the firefox icon. I have only one open now.
![Screenshot from 2022-01-26 08-56-18](https://user-images.githubusercontent.com/63762448/151099211-ef71e475-371b-4d1d-badb-83a6c26567d2.jpg)

**Comment by 3v1n0** [comment] 2022-01-26 04:09
Duplicate of #1629

**Closed by 3v1n0** 2022-01-26 04:09 UTC

**Comment by abinlatheef** [comment] 2022-01-28 10:11
To all those are here, if you are on Arch, install the git package instead of the main one. It worked for me.
![image](https://user-images.githubusercontent.com/63762448/151528466-9502e38e-d038-47ea-927e-81192294a622.png)

Others git clone I guess.
