### ISSUE TITLE
Desktop crash if you try to lock your screen from overview

### ISSUE THREAD

**Issue by J0hn-C77n** [micheleg/dash-to-dock#2216] opened 2024-05-05 10:16 UTC
Hello!

I noticed that I have some issues with my system when I use dash to dock. 

first thing is that on my 2k screen there's a broken default color scheme
![image](https://github.com/micheleg/dash-to-dock/assets/154112993/39dba329-1551-4acc-ad81-92aef0028eeb)

while on my 1080p everything is OK
![image](https://github.com/micheleg/dash-to-dock/assets/154112993/9c7ea565-b9da-4bce-8cb1-6bdd452336e2)

also if you press super + L from this view, you'll get a gnome crash screen and you'll be forced to logout 
![image](https://github.com/micheleg/dash-to-dock/assets/154112993/2b0b1901-1c71-4966-8da3-90e496beaacd)

Here's my system specs:

## Hardware Information:
- **Hardware Model:**                              Lenovo ThinkBook 16 G4+ IAP
- **Memory:**                                      16.0 GiB
- **Processor:**                                   12th Gen Intel® Core™ i9-12900H × 20
- **Graphics:**                                    Intel® Graphics (ADL GT2)
- **Graphics 1:**                                  NVIDIA GeForce RTX™ 2050
- **Disk Capacity:**                               1.5 TB

## Software Information:
- **Firmware Version:**                            HYCN48WW
- **OS Name:**                                     Debian GNU/Linux trixie/sid
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            X11
- **Kernel Version:**                              Linux 6.7.12-amd64

And also extensions that I use
![image](https://github.com/micheleg/dash-to-dock/assets/154112993/70997ab5-6332-4384-bab8-218a7bb2300b)

if you need it

**Comment by MarvvanPal** [comment] 2024-05-07 08:32
Regarding the crash see #2214

**Comment by sergio-costas** [comment] 2024-05-07 14:52
I've been able to reproduce the crash when locking the system while in the overview mode. I wrote a workaround.

**Comment by vanvugt** [comment] 2024-05-27 08:49
Duplicate of #2179

**Closed by vanvugt** 2024-05-27 08:49 UTC
