### ISSUE TITLE
JS ERROR: TypeError: monitor is undefined

### ISSUE THREAD

**Issue by Hyphaed** [micheleg/dash-to-dock#1715] opened 2022-04-17 10:39 UTC
Apr 17 12:37:01 z590i gnome-shell[17116]: JS ERROR: TypeError: monitor is undefined#012_prepareMainDash/<@/home/ferran/.local/share/gnome-shell/extensions/dash-to-dock@tauos.co/docking.js:2166:33#012vfunc_allocate@resource:///org/gnome/shell/ui/workspacesView.js:555:25#012vfunc_allocate@resource:///org/gnome/shell/ui/workspacesView.js:711:30#012vfunc_unmap@resource:///org/gnome/shell/ui/overviewControls.js:702:15#012hideOverview@resource:///org/gnome/shell/ui/layout.js:339:28#012_hideDone@resource:///org/gnome/shell/ui/overview.js:580:32#012_animateNotVisible/<@resource:///org/gnome/shell/ui/overview.js:558:55#012onStopped@resource:///org/gnome/shell/ui/overviewControls.js:741:21#012_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22#012_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

**Comment by 3v1n0** [comment] 2022-04-18 15:43
What version are you running?

**Comment by veyselerden** [comment] 2022-04-21 20:41
Got the same issue after a fresh install of Ubuntu 22.04 stable release. Dock is not shown or work at all. Version says "71" [https://pastebin.com/raw/QBZp9pG1](url) (error output)

**Comment by oguzkarayemis** [comment] 2022-04-28 06:19
Do you use Turkish locale? If so, your issue may be related to this: https://github.com/micheleg/dash-to-dock/issues/1687

**Comment by 3v1n0** [comment] 2022-04-28 20:41
Duplicate of #1687

**Closed by 3v1n0** 2022-04-28 20:41 UTC

**Comment by veyselerden** [comment] 2022-04-28 21:56
> Do you use Turkish locale? If so, your issue may be related to this: #1687

Yes I do actually. Didn't know it was related to the #1687. Sorry.
