### ISSUE TITLE
[Multi Monitor] Dock traps mouse in fullscreen apps

### ISSUE THREAD

**Issue by hexnut** [micheleg/dash-to-dock#523] opened 2017-06-15 16:08 UTC
ENVIRONMENT
Multi-monitor setup with identical monitors, primary display is on the right. Dock positioned on the left side of primary display as shown.
Dash to Dock Settings:
 Show the dock on: primary monitor
 Position on screen: Left
 Intelligent autohide: On

Intelligent Autohide Settings:
 Enable in fullscreen mode: Checked
 Push to show: Unchecked

BEHAVIOR
Put Gnome Terminal in fullscreen mode on primary monitor. Attempt to move mouse pointer left to secondary display. Mouse pointer will not move past fullscreen app boundary. Put Gnome Terminal back in windowed mode. Mouse pointer moves freely between displays.

EXPECTED BEHAVIOUR
Mouse pointer able to move freely between displays

WORKAROUND
Checking Push to show setting in Intelligent autohide settings causes Dock to appear in fullscreen app mode and allow mouse pointer to move freely between displays.

**Comment by franglais125** [comment] 2017-06-15 18:49
I didn't manage to reproduce the problem (on X/Gnome 3.22) yet. I have a few more questions:

1) When you say multi-monitor, does it mean you are using the "Show on all monitors" option?
2) What gnome-shell version are you running, and is it on Wayland/X?
3) Any related errors if you run `sudo journalctl /usr/bin/gnome-shell -f`?
4) What version of dash-to-dock are you running? "About" tab in the settings panel.

Thanks!

**Comment by micheleg** [comment] 2017-06-15 19:04
Yes, I can reproduce it. @franglais125 : It's not linked to the new multi-monitor settings. It is just due to the fact that we have a barrier in place, but as the dock gets never shown with the enable in fullscreen option disabled (which remove the barrier https://github.com/micheleg/dash-to-dock/blob/master/docking.js#L730:L735) it never lets the mouse leave the screen.

**Comment by franglais125** [comment] 2017-06-15 19:42
>Enable in fullscreen mode: Checked
>Push to show: Unchecked

Ah, I see, this happens with the opposite conditions.

**Comment by micheleg** [comment] 2017-06-15 20:26
This should fix the issue: https://github.com/micheleg/dash-to-dock/tree/fix_fullscreen_trap

**Comment by micheleg** [comment] 2017-06-16 21:32
I've merged the fix into master [fcbfccf9ceeab].

**Closed by micheleg** 2017-06-16 21:32 UTC
Labels: bug
