### ISSUE TITLE
[solved with v99] Dodging screen border no longer works since v96

### ISSUE THREAD

**Issue by pawlowskatze** [micheleg/dash-to-dock#2306] opened 2024-10-02 11:22 UTC
Hi,

in the settings, under "intelligent auto hide", there is the option to only raise the dock when dodging the screen border.
With v96, the behaviour has changed: The dodging requirement no longer works, which means that the dock is not displayed when dodging the border.
(It is however displayed when the "dodging" option is deactivated and the mouse pointer hovers at the screen border for like 200ms)

Strange enough: When in the settings dialog, it is sufficient to disable "intelligent auto-hide" and directly re-enable it.
This will immediately work, so that dodging displays the dock. However, this isn't persisted across sessions. Upon the next sign-in, the dock no longer is shown when dodging. Disable/Enable intelligent auto-hide brings it back (for the duration of the gnome session).

Fedora 40
Gnome 46 with X11
Dash-To-Dock v96

**Comment by pawlowskatze** [comment] 2024-10-04 07:43
+++ Seems having been fixed +++

Update/addendum:
On my other machine, running the same X11, Gnome and Fedora versions, the problem didn't occur.
(Neither with v96, v97 nor v98). Perhaps it's related to another gnome extension, setting... whatever. 

**But anyways:**
v99 seems to have fixed the issue (although the change log didn't reveal anything obviously related to my issue).

I'll check behaviour over the next 2 days to make sure the problem is gone for good.
Many thanks for maintaining and supporting dash-to-dock!

Cheers, 
Thomas

**Comment by pawlowskatze** [comment] 2024-10-04 09:59
**+++ UPDATE : RESOLVED! +++**

With v99, "dodging" works again (across shutdowns, logoffs, locks)
Thanks a ton!

Cheers, Thomas

**Comment by 3v1n0** [comment] 2024-10-04 13:01
Thanks, I think it was one of the issues caused by commit https://github.com/micheleg/dash-to-dock/commit/611690cc3300a19bdb167ac0e0c82f5a3311a777

Duplicate of #2297

**Closed by 3v1n0** 2024-10-04 13:01 UTC
Labels: regression
