### ISSUE TITLE
switch workspace by scrolling on dock / change size of area

### ISSUE THREAD

**Issue by sevachka** [micheleg/dash-to-dock#192] opened 2015-07-05 08:38 UTC
hello,
since the last "big" update I am missing an option: I cannot set the size of the area which is sensitive to scroll for switching the workspace. Just the app-icon and the very edge is not very handy... please enable it again like it was before the update.

Thank you for your work. I love dash-to-dock!

**Comment by micheleg** [comment] 2015-07-05 12:38
Hi, 

This is a duplicate of #174. I had to to remove those features at least temporary to include the scrolling of the application launchers. It will be reconsidered in the future. If you really miss this option I suggest you to downgrade to version 42 http://micheleg.github.io/dash-to-dock/releases.html.

**Closed by micheleg** 2015-07-05 12:38 UTC
Labels: duplicate
