### ISSUE TITLE
The settings of extension dash-to-dock@micxgx.gmail.com had an error:

### ISSUE THREAD

**Issue by ben001109** [micheleg/dash-to-dock#1210] opened 2020-05-07 10:22 UTC
The settings of extension dash-to-dock@micxgx.gmail.com had an error:
```
GLib.FileError: 開啟檔案「/home/ben001109/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas/gschemas.compiled」失敗：open() 失敗：沒有此一檔案或目錄
```

Stack trace:
```
getSettings@resource:///org/gnome/Shell/Extensions/js/misc/extensionUtils.js:142:31
DashToDock_Settings@/home/ben001109/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:86:41
buildPrefsWidget@/home/ben001109/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:869:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
how can i do

**Comment by vanvugt** [comment] 2022-10-24 06:34
Duplicate of #1170

**Closed by vanvugt** 2022-10-24 06:34 UTC
