### ISSUE TITLE
extension not working after system upgrade - manjaro os

### ISSUE THREAD

**Issue by ASACHIT** [micheleg/dash-to-dock#1481] opened 2021-07-15 01:32 UTC
Error occurred-

The settings of extension dash-to-dock@micxgx.gmail.com had an error:
```
Gtk.BuilderError: /home/sachit/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/Settings.ui:13:35 Invalid property: GtkBox.margin_left
```

Stack trace:
```
DashToDock_Settings@/home/sachit/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:92:23
buildPrefsWidget@/home/sachit/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:869:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by Raj-Joshi-dev** [comment] 2021-07-15 07:05
Try this : https://forum.manjaro.org/t/dash-to-dock-fails-and-default-desktop-view-changed-after-the-update/73521/19

**Comment by ewlsh** [comment] 2021-10-05 05:01
Duplicate of #1358

**Closed by ewlsh** 2021-10-05 05:01 UTC
