### ISSUE TITLE
Touch Support / Opens Chrome app window twice

### ISSUE THREAD

**Issue by plopp37** [micheleg/dash-to-dock#128] opened 2014-12-23 14:45 UTC
When opening pinned any Chrome app, it creates two windows instead of just one. Experiencing on gnome-shell 3.14.1 in Ubuntu Gnome 14.10

**Comment by micheleg** [comment] 2015-05-04 14:46
A similar problem was reported by Corey in Debian 8

>I noticed a bug in it.
>
> Clicking my Chrome icon always opens a new window instead of the
 bringing an exiting window to focus.
 Other apps behave normally, it's just Chrome. Not sure it that's
 something that can be fixed or not.

**Comment by schuhumi** [comment] 2015-06-20 08:32
I can confirm the bug. Touching AppOverview seem to trigger it twice. Once when the finger touches the glass and once it leaves again (overview can also be opened by holding down the finger).

Also scrolling doesn't work (both workspace scrolling and app list scrolling when fixed icon size is activated)

**Comment by micheleg** [comment] 2015-06-26 20:37
Thanks for the additional information. However I'm really unable to test any touch related feature.

**Comment by tuomasjjrasanen** [comment] 2016-05-19 12:32
I think this issue has nothing to do with dash-to-dock per se. It seems to happen only when an app is launched by touching a touchscreen. Occasionally, a touch event is recognized as two consecutive clicked-events. And it happens also with panel actors.

I reproduced the issue by just adding a simple button to the panel and logged all clicked-events. Sometimes, a single touch produced two clicked-events, sometimes just one. If I connected button-press-event, I got only one per touch.

But I'm not sure at which level the event mismatch happens. I checked the input stream from the corresponding event device (``/dev/input/eventX``) and it seemed just fine, so it's not a touchscreen-specific issue.

Anyone has any ideas?

**Comment by elman22** [comment] 2016-12-13 14:50
I can confirm this issue as well. I have made these tests:
- Manjaro Linux, Gnome 3.22, kernel 4.4 and 4.8, 2 laptops - issue is present in all configurations,
- Apricity OS, Gnome 3.22, kernel 4.4, 2 laptops - issue is present in all configurations,
- Korora 25, Gnome 3.22, kernel 4.8, 1 laptop - issue is NOT present, everything works as expected.

First I thought it might be Arch issue, but #196 says bug is also present on Ubuntu. Then I thought it might be kernel 4.4 issue, but after upgrading Manjaro kernel to 4.8, issue is still present.

What is doing Fedora/Korora differently?

**Comment by micheleg** [comment] 2016-12-18 18:45
@elman22, @tuomasjjrasanen  Can you confirm if the issue occurs also with the default dash or in the appgrid overview?

I have no easy way to debug touch events. I've always assumed that I was missing something in my code to avoid the duplicate event, but from you comments it seems the problem is at an higher level

**Comment by elman22** [comment] 2016-12-19 23:35
Just checked Manjaro and this issue does not occur with default dash in app grid overview. Apps show up as expected.

Also I just realized that Manjaro and Apricity run X11 sessions and Korora runs Wayland session. So maybe that is reason why Korora works fine.

**Comment by Turbito** [comment] 2017-02-23 12:22
Hello, I'm using arch linux. The bug it's only present when using X11. Wayland it's unaffected

**Comment by micheleg** [comment] 2017-02-25 15:19
Thanks for the additional information.

**Comment by micheleg** [comment] 2017-02-25 15:22
You say that there's no problem without the extension. Could you please check if the problem occurs with the extension enabled when  you choose  the "rise window option" in the click action settings?

**Comment by Turbito** [comment] 2017-02-25 15:41
Hmm, It keeps happening :(

**Comment by elman22** [comment] 2017-02-26 18:04
> The bug it's only present when using X11. Wayland it's unaffected. The same happens with dash to panel extension.

This make sense. Touch events on X11 are just an emulation to a pointer event. On Wayland the touch is part of the core input protocol and does not emulate pointer events.

**Comment by LuccoJ** [comment] 2017-05-01 23:45
For me, too, choosing "Raise window" doesn't solve the problem.

**Comment by teohhanhui** [comment] 2017-11-30 15:25
I switched to Wayland (on Manjaro GNOME) and this bug disappeared (or at least it's much better). But I cannot touch to minimize (touch to restore works though). Click to minimize works fine with the mouse and touchpad.

**Comment by PJSingh5000** [comment] 2018-09-20 00:53
Still an issue when using X11.

$ lsb_release --all
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

$ uname -r
4.15.0-32-generic

$ gnome-shell --version
GNOME Shell 3.28.2

**Comment by PJSingh5000** [comment] 2018-09-20 01:02
Question:
If we are emulating pointer events, do we know why it seems that two (or more) events are generated in X11?

Also, I only experience this "double" event situation in the Dash. I can interact with windows on the desktop (maximize, minimize, close, etc.) without issue.

I can even interact with the topbar without issue.

However, only the Dash-to-Dock exhibits this issue. (If I disable Dash-to-Dock) I can interact wit the gnome (pop-out) Dash just fine.

Thought:
Perhaps, there is only one emulated pointer event, but its ***handler is called twice***?

**Comment by PJSingh5000** [comment] 2018-09-20 01:46
**Another Question...**

When an item is selected from the Gnome Dash, how does Gnome Shell know to close the Activities Overview?

Is it because an application has just opened? Or does Gnome Shell handle the touch event twice in some funny way?

**I tried a couple of experiments...**

**Experiment # 1**

1. I disabled the Dash-to-Dock extension.
2. I opened a terminal, and I entered the following command:
3. `$ sleep 5; gedit`
4. I tapped on the Activities "button" at the top left of my screen to bring up the Gnome-Dash and the Activities Overview.
5. I waited about 5 seconds.
6. Gedit opened automatically, but activities Overview did _not_ close.

Obviously, Gnome shell doesn't use the opening of an application as a trigger to close the Activities-Overview.

**Experiment # 2**

1. I enabled the Dash-to-Dock extension.
2. I enabled the Autohide option.
3. I opened an application (Calculator), and I moved the window near the left edge of the screen, so the Dash would automatically hide.
4. I tapped on the Activities "button" at the top left of my screen to bring up the Gnome-Dash and the Activities Overview.
5. I tapped on the gedit icon in my Dash.
6. Only *one* instance of Gedit opened!
7. I closed gedit.
8. I then moved Calculator away from the left edge of the screen, so the Dash would automatically un-hide.
9. I tapped on the gedit icon in my Dash.
10. *Two* instances of Gedit opened!!

**Conclusion**

This leads me to believe that Gnome Shell _must_ be handling the touch even in the Dash _twice_. Once to launch the application, and a second time to close the Activities Overview.

When the Dash is always visible with the Dash-to-Dock extension, perhaps Gnome-Shell calls the Dash's icon-clicked event handler (or whatever it is named) twice?

**Comment by 3v1n0** [comment] 2018-10-25 04:45
This is fixed with this: https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/272

In the mean time, it can also be workarounded at extension level by doing something like:

```diff
diff --git a/appIcons.js b/appIcons.js
@@ -357,6 +367,9 @@ var MyAppIcon = new Lang.Class({
         let modifiers = event ? event.get_state() : 0;
         let focusedApp = tracker.focus_app;
 
+        if (event.type() == Clutter.EventType.TOUCH_END && event.is_pointer_emulated())
+            return;
+
         // Only consider SHIFT and CONTROL as modifiers (exclude SUPER, CAPS-LOCK, etc.)
         modifiers = modifiers & (Clutter.ModifierType.SHIFT_MASK | Clutter.ModifierType.CONTROL_MASK);
```

**Comment by 3v1n0** [comment] 2018-11-26 21:35
This is now fixed for latest gnome-shell and cherry-picked to 3.28 and 3.30.

If there's interest we could fix this at extension level either for older shell versions, it can be done as explained in https://github.com/micheleg/dash-to-dock/issues/196#issuecomment-432913465

I think we can close the bug here, unless there's interest in workaround the issue at this level.

**Closed by 3v1n0** 2018-11-26 21:35 UTC
Labels: bug, touch

**Comment by Freeedim** [comment] 2019-02-28 09:17
There is still a "double launch" of a touched application in gnome-shell 3.30.1
(On a Lenovo T480 with libinput only)

**Comment by CatalinH** [comment] 2023-03-15 00:58
'Double launch' also happens on Ubuntu 22.04, but I don't think it is related to this extenstion. It might be related to [this issue](https://askubuntu.com/questions/1030450/touchscreen-tap-counts-as-double-left-click-on-ubuntu-18-04) and [this gnome-shell fix](https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1745888) , but `$ gnome-shell --version` gives me `GNOME Shell 42.5`. I would have expected to be fixed :man_shrugging:. Any way those double events can be prevented with the extension?

**Comment by PJ-Singh-001** [comment] 2023-03-15 01:19
@CatalinH,

I am running 22.10, and I do not experience this issue. I do not recall this being an issue in 22.04, either.

**Comment by CatalinH** [comment] 2023-03-15 08:02
@PJ-Singh-001, for me it happened before installing dash-to-dock (I was hoping the extension would fix it), and this happens only on the left side, for the dock. For example, touching the top-right zone (power settings, wifi, sound), it works normally (just opens the pannel). 
On the dock has a bit strange behaviour: if the app that I am touching has no opened instance, it opens 2. If it has at least 1, it only focuses on that window.

**Comment by domolys** [comment] 2024-01-06 22:36
It fixes my issue:

https://askubuntu.com/questions/978223/tapping-on-ubuntu-dock-on-a-touch-screen-opens-two-instances-of-a-program

**Comment by DjDiabolik** [comment] 2024-04-03 00:45
@domolys if you know if this patch it's also work for preventing potential erroneous double click on current Gnome dock in Ubuntu 22.04.4 ?

**Comment by domolys** [comment] 2024-04-03 02:52
> @domolys if you know if this patch it's also work for preventing potential erroneous double click on current Gnome dock in Ubuntu 22.04.4 ?

Yes, I patched it on Ubuntu 22.04.4

**Comment by DjDiabolik** [comment] 2024-04-08 09:31
@domolys Sorry for asking but is the default bar on the left of Ubuntu something similar?
If i install this i have to disable the default left bar ?

**Comment by domolys** [comment] 2024-04-08 11:50
This patch only fix issues with touchscreen, it has nothing to do with anythings else...

**Comment by DjDiabolik** [comment] 2024-04-12 06:14
@domolys and couldn't a double tap be similar to a double click?
