### ISSUE TITLE
Dash to Dock flickering on Wayland

### ISSUE THREAD

**Issue by rodrigofructuoso** [micheleg/dash-to-dock#1868] opened 2022-11-04 14:19 UTC
As reported on this [reddit post](https://www.reddit.com/r/gnome/comments/ye9yzu/dash_to_dock_flickering/), when an app is fit to screen and intellihide is enabled, Dash to Dock flickers wildly.

The user "[SomeGenericUsername](https://www.reddit.com/user/SomeGenericUsername/)" proposed the following workaround:
Press **Alt+F2**, **lg** and then enter **Meta.disable_unredirect_for_display(global.display)** in the console. It resolves the problem, but isn't a permanent setup, will be needed to run the command again on restart.

Would be nice if the extension handle this exception natively.

**Comment by taoky** [comment] 2022-11-07 03:17
Maybe duplicate with #1381 and #1813?

**Comment by vanvugt** [comment] 2023-02-28 03:43
Duplicate of #1381

**Closed by vanvugt** 2023-02-28 03:43 UTC
