### ISSUE TITLE
Auto hide dock is buggy when we hover it

### ISSUE THREAD

**Issue by YoAlejoDev** [micheleg/dash-to-dock#2186] opened 2024-03-29 22:32 UTC
The bug is when we hover the dock in full screen, it shows and hide, the funny thing is that it let me use it normally, but is awfull see it.

I'll try to fix it

**Comment by vanvugt** [comment] 2024-04-02 06:50
Duplicate of #1381

**Closed by vanvugt** 2024-04-02 06:50 UTC
