### ISSUE TITLE
Customize the dash color feature breaking other

### ISSUE THREAD

**Issue by Keqwerty** [micheleg/dash-to-dock#2294] opened 2024-09-23 16:04 UTC
Push to Show feature just doesn't work, nor does Dash's dynamic transparency with Dash's custom color enabled.

https://github.com/user-attachments/assets/5098aef2-2f51-45e2-bb5f-4aebe81711e6

**Comment by martin640** [comment] 2024-09-24 08:25
Same issue here,
adding logs from journalctl
```logs
sep 24 10:21:51 martin-pc gnome-shell[3706]: Registering session with GDM
sep 24 10:21:51 martin-pc gnome-shell[3706]: JS ERROR: TypeError: (intermediate value).Color is undefined
                                             _updateDashColor@file:///usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:171:34
                                             updateCustomTheme@file:///usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:229:14
                                             _initialize@file:///usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:463:28
                                             _init/<@file:///usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:401:39
                                             @resource:///org/gnome/shell/ui/init.js:21:20
...
```

**Comment by vanvugt** [comment] 2024-09-24 09:33
Duplicate of #2284

**Closed by vanvugt** 2024-09-24 09:33 UTC
