### ISSUE TITLE
Breaks window management after screen is locked.

### ISSUE THREAD

**Issue by ahears** [micheleg/dash-to-dock#2169] opened 2024-03-23 06:00 UTC
When the extension is enabled and the desktop is locked and unlocked, the desktop becomes unstable. Some windows can be minimized but the image of the window does not actually go away. Some other windows cannot be handled at all. Eventually the whole desktop might become unresponsive.

The bug does not always occur the first time the system is locked and unlocked.

Enable extension and one or more of the effects.
Lock the screen.
Unlock the screen.
Try to move, minimize, un-minimize, close windows.

 I found the extension "Dash to Dock" may be the culprit. It does not re-enable correctly after unlocking/un-suspend on Ubuntu 22.04 and the button to turn it on and off works in reverse after crashing. Turning it off seems to correct the problem for me and my system returns to normal and becomes responsive again. Note the desktop crashed and I was working on the CLI to reopen the gnome-extensions-app to address this issue. I have not verified if this issue exists only while using the extensions combined with @Schneegans extensions (burn my windows etc) or if this issues exists regardless. All other extensions are system built in only.  Also note the problem was also intermittent and the desktop didn't crash or become unresponsive every time after unlocking/un-suspend. I put the output below and highlighted an area of interest because this error does not appear after disabling the "Dash to Dock" extensions as you can see. I apologize in advance for my inability to make this output shorter. This post may be better handled by the developer of "Dash to Dock".

SYSTEM: Ubuntu 22.04, Nvidia Driver 525.147.05, GNOME

`LOG OUTPUT AFTER CRASH`

USER@MYDESKTOP:~$ journalctl -b -e -o cat

_create/object[name]@/usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/utils.js:296:68
_ensureLocations/<@/usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/docking.js:1713:60
_create/object[name]@/usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/utils.js:296:68
_ensureLocations/<@/usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/docking.js:1713:60
_create/object[name]@/usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/utils.js:296:68
_ensureLocations/<@/usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/docking.js:1713:60
_create/object[name]@/usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/utils.js:296:68
_ensureLocations/<@/usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/docking.js:1713:60
_create/object[name]@/usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/utils.js:296:68
_ensureLocations/<@/usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/docking.js:1713:60
_create/object[name]@/usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/utils.js:296:68
_redisplay@/home/USER/.local/share/gnome-shell/extensions/[dash-to-dock@micxgx.gmail.com](mailto:dash-to-dock@micxgx.gmail.com)/dash.js:745:39
resetAppIcons@/home/USER/.local/share/gnome-shell/extensions/[dash-to-dock@micxgx.gmail.com](mailto:dash-to-dock@micxgx.gmail.com)/dash.js:1038:14
_init/<@/home/USER/.local/share/gnome-shell/extensions/[dash-to-dock@micxgx.gmail.com](mailto:dash-to-dock@micxgx.gmail.com)/docking.js:370:29
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
updateCustomTheme@/home/USER/.local/share/gnome-shell/extensions/[dash-to-dock@micxgx.gmail.com](mailto:dash-to-dock@micxgx.gmail.com)/theming.js:233:14
_initialize@/home/USER/.local/share/gnome-shell/extensions/[dash-to-dock@micxgx.gmail.com](mailto:dash-to-dock@micxgx.gmail.com)/docking.js:460:28
_init/<@/home/USER/.local/share/gnome-shell/extensions/[dash-to-dock@micxgx.gmail.com](mailto:dash-to-dock@micxgx.gmail.com)/docking.js:398:39

(--) NVIDIA(GPU-0): DFP-0: disconnected
(--) NVIDIA(GPU-0): DFP-0: Internal TMDS
(--) NVIDIA(GPU-0): DFP-0: 165.0 MHz maximum pixel clock
(--) NVIDIA(GPU-0):
(--) NVIDIA(GPU-0): DFP-1: disconnected
(--) NVIDIA(GPU-0): DFP-1: Internal DisplayPort
(--) NVIDIA(GPU-0): DFP-1: 2670.0 MHz maximum pixel clock
(--) NVIDIA(GPU-0):
(--) NVIDIA(GPU-0): DFP-2: disconnected
(--) NVIDIA(GPU-0): DFP-2: Internal TMDS
(--) NVIDIA(GPU-0): DFP-2: 165.0 MHz maximum pixel clock
(--) NVIDIA(GPU-0):
(--) NVIDIA(GPU-0): DFP-3: disconnected
(--) NVIDIA(GPU-0): DFP-3: Internal DisplayPort
(--) NVIDIA(GPU-0): DFP-3: 2670.0 MHz maximum pixel clock
(--) NVIDIA(GPU-0):
(--) NVIDIA(GPU-0): DFP-4: disconnected
(--) NVIDIA(GPU-0): DFP-4: Internal TMDS
(--) NVIDIA(GPU-0): DFP-4: 165.0 MHz maximum pixel clock
(--) NVIDIA(GPU-0):
(--) NVIDIA(GPU-0): CSO (DFP-5): connected
(--) NVIDIA(GPU-0): CSO (DFP-5): Internal DisplayPort
(--) NVIDIA(GPU-0): CSO (DFP-5): 2670.0 MHz maximum pixel clock
(--) NVIDIA(GPU-0):
[session uid=1000 pid=195857] Successfully activated service 'org.gnome.ArchiveManager1'
DING: Detected async api for thumbnails
DING: GNOME nautilus 42.6
**JS ERROR: Impossible to enumerate trash children: TypeError: this.location is null**
_updateTrash@/usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/locations.js:668:40
async*_init@/usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/locations.js:597:14
LocationAppInfo@/usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/locations.js:95:4
TrashAppInfo@/usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/locations.js:564:1
_ensureApp@/usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/locations.js:1099:22
getApp@/usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/locations.js:1105:14
wrapFileManagerApp@/usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/locations.js:1049:22
_ensureLocations@/usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/docking.js:1708:50
DashToDock_DockManager@/usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/docking.js:1606:14
conditionallyenabledock@/usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/extension.js:52:23
enable@/usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/extension.js:27:5
_callExtensionEnablehttps://github.com/resource:///org/gnome/shell/ui/extensionSystem.js:183:32
_onEnabledExtensionsChanged/<https://github.com/resource:///org/gnome/shell/ui/extensionSystem.js:532:35
_onEnabledExtensionsChangedhttps://github.com/resource:///org/gnome/shell/ui/extensionSystem.js:532:14
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:665:14
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
_sync@resource:///org/gnome/shell/ui/sessionMode.js:206:14
popMode@resource:///org/gnome/shell/ui/sessionMode.js:174:14
_continueDeactivate@resource:///org/gnome/shell/ui/screenShield.js:581:30
deactivate/<@resource:///org/gnome/shell/ui/screenShield.js:572:44
finish@resource:///org/gnome/shell/gdm/authPrompt.js:682:13
finish@resource:///org/gnome/shell/ui/unlockDialog.js:863:26
deactivate@resource:///org/gnome/shell/ui/screenShield.js:572:26
ScreenShield/</<@resource:///org/gnome/shell/ui/screenShield.js:118:57
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
_convertToNativeSignal@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:152:19>

`LOG OUTPUT WHEN DASH TO DOCK IS DISABLED (desktop does not crash):`

USER@MYDESKTOP:~$ journalctl -b -e -o cat

https://github.com/Schneegans/Burn-My-Windows/pull/19 55ef86b3a4a0 i resource:///org/gnome/shell/ui/unlockDialog.js:863 (2b57fb0e6b50 @ 59)
https://github.com/Schneegans/Burn-My-Windows/issues/20 55ef86b3a418 i resource:///org/gnome/shell/ui/screenShield.js:572 (2b57fb0bcfb0 @ 50)
https://github.com/Schneegans/Burn-My-Windows/pull/21 55ef86b3a390 i resource:///org/gnome/shell/ui/screenShield.js:118 (2b57fb0bc470 @ 13)
https://github.com/Schneegans/Burn-My-Windows/issues/22 7ffcf1221c20 b resource:///org/gnome/gjs/modules/core/_signals.js:114 (29017b7d3920 @ 433)
https://github.com/Schneegans/Burn-My-Windows/issues/23 55ef86b3a2e8 i resource:///org/gnome/gjs/modules/core/overrides/Gio.js:152 (29017b7cd470 @ 39)
== Stack trace for context 0x55ef4cbd6190 ==
#0 7ffcf121e4c0 b /usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/utils.js:147 (357e57a1f970 @ 358)
https://github.com/Schneegans/Burn-My-Windows/issues/1 7ffcf121e630 b /usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/utils.js:78 (357e57a1f5b0 @ 501)
https://github.com/Schneegans/Burn-My-Windows/issues/2 7ffcf121ed90 b /usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/docking.js:2049 (357e57a1e1a0 @ 348)
https://github.com/Schneegans/Burn-My-Windows/issues/3 55ef86b3ac50 i /usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/docking.js:1917 (357e57a1de20 @ 516)
https://github.com/Schneegans/Burn-My-Windows/issues/4 55ef86b3abb8 i /usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/docking.js:1610 (357e57a1ce70 @ 629)
https://github.com/Schneegans/Burn-My-Windows/issues/5 55ef86b3ab20 i /usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/extension.js:52 (357e57a098d0 @ 98)
https://github.com/Schneegans/Burn-My-Windows/issues/6 55ef86b3aa88 i /usr/share/gnome-shell/extensions/[ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)/extension.js:27 (357e57a09830 @ 51)
https://github.com/Schneegans/Burn-My-Windows/issues/7 55ef86b3a9c8 i resource:///org/gnome/shell/ui/extensionSystem.js:183 (2e620b4a790 @ 561)
https://github.com/Schneegans/Burn-My-Windows/issues/8 55ef86b3a940 i resource:///org/gnome/shell/ui/extensionSystem.js:532 (2e620b4afb0 @ 15)
https://github.com/Schneegans/Burn-My-Windows/issues/9 7ffcf121fa00 b self-hosted:202 (29017b7e2e70 @ 272)
https://github.com/Schneegans/Burn-My-Windows/pull/10 55ef86b3a8b8 i resource:///org/gnome/shell/ui/extensionSystem.js:532 (2e620b4af10 @ 67)
https://github.com/Schneegans/Burn-My-Windows/pull/11 55ef86b3a830 i resource:///org/gnome/shell/ui/extensionSystem.js:665 (2e620b50510 @ 17)
https://github.com/Schneegans/Burn-My-Windows/issues/12 7ffcf1220630 b self-hosted:1178 (29017b7b0a10 @ 423)
https://github.com/Schneegans/Burn-My-Windows/issues/13 7ffcf1220730 b resource:///org/gnome/gjs/modules/core/_signals.js:114 (29017b7d3920 @ 433)
https://github.com/Schneegans/Burn-My-Windows/issues/14 7ffcf1220eb0 b resource:///org/gnome/shell/ui/sessionMode.js:206 (2b57fb0c89c0 @ 283)
https://github.com/Schneegans/Burn-My-Windows/pull/15 55ef86b3a6d8 i resource:///org/gnome/shell/ui/sessionMode.js:174 (2b57fb0c88d0 @ 142)
https://github.com/Schneegans/Burn-My-Windows/pull/16 55ef86b3a648 i resource:///org/gnome/shell/ui/screenShield.js:581 (2b57fb0bf0b0 @ 79)
https://github.com/Schneegans/Burn-My-Windows/issues/17 55ef86b3a5c0 i resource:///org/gnome/shell/ui/screenShield.js:572 (2b57fb0bf060 @ 17)
https://github.com/Schneegans/Burn-My-Windows/pull/18 55ef86b3a530 i resource:///org/gnome/shell/gdm/authPrompt.js:682 (2b57fb0d1ba0 @ 64)
https://github.com/Schneegans/Burn-My-Windows/pull/19 55ef86b3a4a0 i resource:///org/gnome/shell/ui/unlockDialog.js:863 (2b57fb0e6b50 @ 59)
https://github.com/Schneegans/Burn-My-Windows/issues/20 55ef86b3a418 i resource:///org/gnome/shell/ui/screenShield.js:572 (2b57fb0bcfb0 @ 50)
https://github.com/Schneegans/Burn-My-Windows/pull/21 55ef86b3a390 i resource:///org/gnome/shell/ui/screenShield.js:118 (2b57fb0bc470 @ 13)
https://github.com/Schneegans/Burn-My-Windows/issues/22 7ffcf1221c20 b resource:///org/gnome/gjs/modules/core/_signals.js:114 (29017b7d3920 @ 433)
https://github.com/Schneegans/Burn-My-Windows/issues/23 55ef86b3a2e8 i resource:///org/gnome/gjs/modules/core/overrides/Gio.js:152 (29017b7cd470 @ 39)
Initializing nautilus-image-converter extension
Initializing
[1710048932.3045] agent-manager: agent[255a67305d3c450b,:1.1287/org.gnome.Shell.NetworkAgent/1000]: agent registered
[session uid=1000 pid=195857] Successfully activated service 'org.freedesktop.FileManager1'
unable to update icon for software-update-available
unable to update icon for livepatch
unable to update icon for variety
[session uid=1000 pid=195857] Activating service name='org.gnome.ArchiveManager1' requested by ':1.7504' (uid=1000 pid=426865 comm="gjs /usr/share/gnome-shell/extensions/ding@rasters" label="unconfined")
(--) NVIDIA(GPU-0): DFP-0: disconnected
(--) NVIDIA(GPU-0): DFP-0: Internal TMDS
(--) NVIDIA(GPU-0): DFP-0: 165.0 MHz maximum pixel clock
(--) NVIDIA(GPU-0):
(--) NVIDIA(GPU-0): DFP-1: disconnected
(--) NVIDIA(GPU-0): DFP-1: Internal DisplayPort
(--) NVIDIA(GPU-0): DFP-1: 2670.0 MHz maximum pixel clock
(--) NVIDIA(GPU-0):
(--) NVIDIA(GPU-0): DFP-2: disconnected
(--) NVIDIA(GPU-0): DFP-2: Internal TMDS
(--) NVIDIA(GPU-0): DFP-2: 165.0 MHz maximum pixel clock
(--) NVIDIA(GPU-0):
(--) NVIDIA(GPU-0): DFP-3: disconnected
(--) NVIDIA(GPU-0): DFP-3: Internal DisplayPort
(--) NVIDIA(GPU-0): DFP-3: 2670.0 MHz maximum pixel clock
(--) NVIDIA(GPU-0):
(--) NVIDIA(GPU-0): DFP-4: disconnected
(--) NVIDIA(GPU-0): DFP-4: Internal TMDS
(--) NVIDIA(GPU-0): DFP-4: 165.0 MHz maximum pixel clock
(--) NVIDIA(GPU-0):
(--) NVIDIA(GPU-0): CSO (DFP-5): connected
(--) NVIDIA(GPU-0): CSO (DFP-5): Internal DisplayPort
(--) NVIDIA(GPU-0): CSO (DFP-5): 2670.0 MHz maximum pixel clock
(--) NVIDIA(GPU-0):
[session uid=1000 pid=195857] Successfully activated service 'org.gnome.ArchiveManager1'
DING: Detected async api for thumbnails
DING: GNOME nautilus 42.6
Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).

**Comment by vanvugt** [comment] 2024-03-25 05:56
Duplicate of #1992.

Please avoid loading dash-to-dock and ubuntu-dock at the same time.

**Closed by vanvugt** 2024-03-25 05:56 UTC

**Comment by ahears** [comment] 2024-03-25 06:07
> Duplicate of #1992.
> 
> Please avoid loading dash-to-dock and ubuntu-dock at the same time.

Solved. Thank you.
