### ISSUE TITLE
Dock goes to hiding when you empty trash

### ISSUE THREAD

**Issue by mi16087** [micheleg/dash-to-dock#1839] opened 2022-10-01 22:18 UTC
When I empty trash from the dock isolated trash icon, dock stats hiding like there's a window that it needs to dodge. You can make it appear again with a mouse hover, but it still dodges empty screen like there's a full screen application opened and it only get fixed when you disable and re-enable it.

**Comment by vanvugt** [comment] 2022-10-03 03:47
Duplicate of #1769

**Closed by vanvugt** 2022-10-03 03:47 UTC
