### ISSUE TITLE
use mouse wheel to switch between opened apps like in Xfce

### ISSUE THREAD

**Issue by crysman** [micheleg/dash-to-dock#1274] opened 2020-07-18 10:40 UTC
Would be nice to be able to switch between opened apps with mouse wheel (scrolling button) when mouse pointer is located in main left menu area - like in Xfce.

Why? Because it's faster.

Or is it somehow already tunable somewhere?

Thanks!

backlink here: https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/1886075

**Comment by DoctorRover** [comment] 2020-07-18 22:00
There is this function in Dash to Dock.
It can be activated using Dconf Editor. Set the parameter 'org.gnome.shell.extensions.dash-to-dock' to be equal to 'cycle-windows'.
It can also be easily done by running this command:

`gsettings set org.gnome.shell.extensions.dash-to-dock scroll-action 'cycle-windows'`

Most likely, it can be done through the Dash to Dock extension settings. I'm not sure since I use Ubuntu Dock.

**Comment by crysman** [comment] 2020-07-20 23:09
I would like to see it in GNOME tweaks:

**Comment by vanvugt** [comment] 2020-07-21 01:40
It's an extension so Gnome Tweaks is not appropriate. Instead the extension would need to be given a configuration GUI of its own that you would access in the Extensions app.

**Comment by crysman** [comment] 2020-07-26 20:02
OK, I've installed manually [dash-to-dock GNOME extension](https://micheleg.github.io/dash-to-dock/index.html) and it works, thanks a lot!

What is very strange, though, is that it works even with the extension actually disabled in gnome-tweaks:
![image](https://user-images.githubusercontent.com/5269350/88488050-f91bb300-cf8a-11ea-988a-bbe770511e19.png)

restarting gnome shell (ALT+F2 -> r -> ENTER) does not help.

I believe this is a bug - isn't it? Or any explanation? Thanks


And one bonus question:
Do you know any way how to switch between all opened apps using mousewheel while cursor is on the empty space of the bar?

**Comment by DoctorRover** [comment] 2020-07-27 22:35
You cannot disable the built-in extensions (like Ubuntu Dock) from Gnome Tweaks. You can turn off the switcher there but the extension remains active. This is how it has been from the moment of switching from Unity to Gnome sHell.
To disable the built-in extensions, use Extensions application. This is a dedicated app to deal with extensions.

**Comment by DoctorRover** [comment] 2020-07-31 14:38
I suggest closing this issue since the feature which was initially requested is actually already available in DtD.

**Comment by crysman** [comment] 2020-08-10 09:06
well, although I have it disabled in **extensions**:
![image](https://user-images.githubusercontent.com/5269350/89766944-43f40980-daf9-11ea-8952-7bbafa792408.png)


it still works (switching apps via mousewheel) - that is weird, isn't it? Obviously, **the extension IS active despite it looks like INACTIVE**. One more proof: I can see little squares instead of default little circles:
![image](https://user-images.githubusercontent.com/5269350/89767008-6128d800-daf9-11ea-8c22-0dc001fddc57.png)

Shouldn't we make a separate issue on this?

**Comment by DoctorRover** [comment] 2020-08-10 11:34
No, DtD is not active. This is Ubuntu Dock which is active in your situation.

No, it is not weird. It is just a nature of Ubuntu Dock. Ubuntu Dock is a "soft fork" of DtD which means it supports all options of DtD. Moreover, it shares its settings with DtD, i.e. Ubuntu Dock gets its options from the same place in _gsettings_ where DtD stores them. It just doesn't install the DtD extintion settings GUI. As a result, if you change any options via _gsettings_ (similar to what I described in [my first reply](https://github.com/micheleg/dash-to-dock/issues/1274#issuecomment-660548520) to this issue) if will affect Ubuntu Dock. If you install DtD and change any settings in its GUI, Ubuntu Dock reflects the changes. So, the behavior you observe is by design.

No, you shouldn't make a new issue since everything goes as intended in your case.

**Comment by vanvugt** [comment] 2023-05-02 08:16
Duplicate of #811

**Closed by vanvugt** 2023-05-02 08:16 UTC
