### ISSUE TITLE
Locking while in overview mode crashes gnome

### ISSUE THREAD

**Issue by bill88t** [micheleg/dash-to-dock#2206] opened 2024-04-22 13:36 UTC
Arch (reproduced on arm and x86), gnome-shell 1:46.1-1, dash-to-dock v91.

While in overview mode, pressing the key combination to lock the system (Default: Super + L) causes gnome to crash.
`systemd-coredump[8890]: [🡕] Process 8304 (gnome-shell) of user 1000 dumped core.`

Disabling dash-to-dock makes this go away.

**Comment by vanvugt** [comment] 2024-04-23 06:41
Please report the crash to your OS vendor (Arch) for retracing.

Alternatively, if there are any more details in the system log at the time of the crash then please paste them here.

**Comment by vanvugt** [comment] 2024-04-23 06:43
Come to think of it, locking while in overview mode sounds like https://github.com/micheleg/dash-to-dock/issues/2179 which now has a fix proposed in https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3252

**Comment by vanvugt** [comment] 2024-04-23 06:44
Duplicate of #2179

**Closed by vanvugt** 2024-04-23 06:44 UTC
Labels: unconfirmed
