### ISSUE TITLE
[Feature Request]: Drag'n'Drop feature

### ISSUE THREAD

**Issue by ivanmood0** [micheleg/dash-to-dock#1633] opened 2022-01-11 12:19 UTC
Add (if possible) a Drag'n'Drop feature when dragging a file/text on the dock icon (this means deploying the program by dragging a block of text or a file onto it).

**Comment by 3v1n0** [comment] 2022-01-21 01:38
While I've been working a bit in getting this working, sadly it wouldn't work properly in Wayland yet, so I'd prefer to avoid adding something that isn't working equally in both X11 and Wayland.

**Comment by andrewaclear** [comment] 2022-02-28 08:36
I was going to ask for this also, this is a big one. It's super helpful to be able to open files with different applications by dragging them onto that application.

**Comment by jtojnar** [comment] 2022-11-17 23:26
Duplicate of #49.

**Comment by stephanbogner** [comment] 2022-11-24 03:03
@3v1n0 
> While I've been working a bit in getting this working, sadly it wouldn't work properly in Wayland yet, so I'd prefer to avoid adding something that isn't working equally in both X11 and Wayland.

I really really like Dash-to-Dock except for this missing feature.

I am a frontend-developer and recently switched from Mac to Ubuntu (I am on Wayland) so if you think I can contribute, let me know. Having drag-and-drop would speed up my workflow so much.

**Comment by vanvugt** [comment] 2022-11-28 09:44
Duplicate of #49

**Closed by vanvugt** 2022-11-28 09:44 UTC
