### ISSUE TITLE
Gnome-shell crashing when the dash-to-dock is set to autohide

### ISSUE THREAD

**Issue by petr-hybler-ofti** [micheleg/dash-to-dock#2255] opened 2024-07-22 17:43 UTC
When I set the dash-to-dock to autohide and I suspend the laptop, upon awaking it, the gnome shell crashing .. in the gnome-shell journalctl I can see this:

```
JS ERROR: TypeError: dockManager is null
                                          getApps@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:1266:9
                                          getRunningApps@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:1276:12
                                          _ensureLocations/<@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/docking.js:1714:56
                                          _create/object[name]@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/utils.js:296:68
                                          _syncRunningApplications@resource:///org/gnome/shell/misc/introspect.js:74:36
                                          IntrospectService/<@resource:///org/gnome/shell/misc/introspect.js:42:34
                                          updateSensitivity@resource:///org/gnome/shell/gdm/authPrompt.js:578:18
                                          _activateNext@resource:///org/gnome/shell/gdm/authPrompt.js:269:14
                                          _initInputRow/</<@resource:///org/gnome/shell/gdm/authPrompt.js:214:26
```
                                          
 ` Spurious clutter_actor_allocate called for actor 0x55655bb70430/<dashtodockContainer>[<Gjs_ubuntu-dock_ubuntu_com_docking_DashToDock>:0x55655bb70430] which isn't a des>`

`Object .Gjs_ubuntu-dock_ubuntu_com_dash_DockDash (0x55655bbd7330), has been already disposed — impossible to access it. This might be caused by the object having been `

Steps to repeat:

- enable Intelligent autohide
- suspend the laptop
- awake the laptop
- all pinned (favorite) apps are gone .. only "activities" icon is available 

When the activites icon is clicked, the system kinda frozes ...

Steps to fix:
- CTRL ALT F3 -> login as the same user ... run `sudo killall -1 gnome-shell` 
- CTRL ALT F2 -> when the gnomeshell restarts, it's all back to normal 

`$ gnome-shell --version
GNOME Shell 42.9
`
System: ubuntu 22.04.4 LTS
Windowing system: X11

PS: Wayland seems to be working fine tho

**Comment by vanvugt** [comment] 2024-07-23 01:48
This looks like a duplicate of https://github.com/micheleg/dash-to-dock/issues/1992

According to [the Ubuntu bug](https://bugs.launchpad.net/bugs/2003168), it might be fixed in Ubuntu 24.04 and later. Or you can just be sure to disable all unused dock extensions.

**Closed by vanvugt** 2024-07-23 01:48 UTC
