### ISSUE TITLE
Randomly Dash-to-Dock doesn't load system icons properly on Wayland  after gnome-shell started

### ISSUE THREAD

**Issue by ceyhunnabiyev** [micheleg/dash-to-dock#663] opened 2017-12-30 09:35 UTC
It doesn't matter which icons is selected from Gnome-Tweaks. For example I use Papirus-icon-theme.
Screenshot:
![screenshot from 2017-12-30 13-00-26](https://user-images.githubusercontent.com/5506156/34452895-d9a2287c-ed62-11e7-9bbd-d9ee72a4b26d.png)
**Seems like  Wayland firstly loads Adwaita, then it changes to user selected icons, and on Dash-to-Dock this change hasn't been done properly.** 
After re-enable the extension, it loads correctly:
![screenshot from 2017-12-30 13-05-51](https://user-images.githubusercontent.com/5506156/34452963-332ced00-ed63-11e7-9e58-c524ae6f7a8f.png)

**Comment by dvorapa** [comment] 2018-03-05 07:48
Is this duplicate of #640?

**Comment by ceyhunnabiyev** [comment] 2018-03-05 07:53
Yes

**Closed** 2018-03-05 07:53 UTC
