### ISSUE TITLE
another dock in activities overview , over lapping actual dock

### ISSUE THREAD

**Issue by vamshi9666** [micheleg/dash-to-dock#777] opened 2018-07-26 03:11 UTC
I am using ubuntu 18.04 with gnome desktop environment. i love this extension , which feels mostly same as mac OS dock .
Issue is : 
dock looks in desired way in any normal conditions. 
**But entering activities overview with super key shows another dock with larger size .** 
this dock is overlapping the actual dock , resulting the following view 
![screenshot from 2018-07-26 08-40-40](https://user-images.githubusercontent.com/28837336/43239381-a789c64c-90af-11e8-892a-3cbcb98ca390.png)

**Comment by mgoulao** [comment] 2018-07-26 18:01
This is a duplicate of [#649](https://github.com/micheleg/dash-to-dock/issues/649). The issue is closed but the problem persists.

**Comment by micheleg** [comment] 2018-07-29 17:50
Plese have a look at #649 as suggested. I believe it's aconflict with ubuntu-dock.

**Closed by micheleg** 2018-07-29 17:50 UTC
