### ISSUE TITLE
Manjaro Linux_Gnome 40.2.0_Wayland - error on open settings dash-to-dock

### ISSUE THREAD

**Issue by SteelSons** [micheleg/dash-to-dock#1476] opened 2021-07-14 04:24 UTC
The settings of extension dash-to-dock@micxgx.gmail.com had an error:
```
GLib.FileError: Could not open file '/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/Settings.ui': No such file or directory
```

Stack trace:
```
_init@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:198:27
buildPrefsWidget@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:1013:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by Zappo-II** [comment] 2021-07-14 11:57
potential duplicate of #1475

**Comment by ewlsh** [comment] 2021-10-05 05:01
Duplicate of #1475 and/or tracked in #1525

**Closed by ewlsh** 2021-10-05 05:01 UTC
