### ISSUE TITLE
While this extension is active, typing into the GNOME Search bar results in double-typed letters

### ISSUE THREAD

**Issue by NateNate60** [micheleg/dash-to-dock#1858] opened 2022-10-19 02:09 UTC
Here's a GIF of the issue. When I press the super key to enter the Activities overview, then start typing (which automatically moves the text cursor to the search bar), the first letter I type will be entered twice. However, when I click on the search bar with my mouse first, it works normally.

Edit: please click the GIF to view it clearly in a new tab

![bug-2022-10-18_19 06 36](https://user-images.githubusercontent.com/41277019/196580548-6a1b85a0-92ae-4e7a-90fe-b83626c0d066.gif)

I couldn't reproduce this bug on a fresh user account, but clearing the DCONF and removing all of my other extensions (or my entire ~/.local/share and then re-installing only this extension) still doesn't cause it to go away. However, when I disable this extension, the issue goes away after a logout.

Either the issue is caused by this extension, or this extension causes something else to go wrong which causes this issue, or a combination of both.

**Comment by vanvugt** [comment] 2022-10-19 02:14
Duplicate of #1855

**Closed by vanvugt** 2022-10-19 02:14 UTC
