### ISSUE TITLE
First character appears twice in Activities Overview 

### ISSUE THREAD

**Issue by acyment** [micheleg/dash-to-dock#1869] opened 2022-11-07 20:47 UTC
After installing version 75-1 the first character I write in Gnome's Activities Overview appears twice. I can only use the command after I delete the extra character. For example, if I want to write “firefox” I have to press “f”, “ff” shows in the text box, I then press BACKSPACE, and then I can write “irefox”
You can see the bug in [the following video](https://imgur.com/a/3C6FLnF). 
Downgrading to 74-1 fixes the bug.

Gnome Shell 42.5
Manjaro 22.0 (testing branch)
3 monitor-setting
config:
```
[/]
background-opacity=0.80000000000000004
dash-max-icon-size=48
dock-fixed=false
dock-position='LEFT'
extend-height=false
height-fraction=0.90000000000000002
multi-monitor=false
preferred-monitor=-2
preferred-monitor-by-connector='DP-4'

```

**Comment by jfcaraujo** [comment] 2022-11-08 09:51
Duplicate of issue #1855

**Comment by vanvugt** [comment] 2022-11-08 15:33
Duplicate of #1855

**Closed by vanvugt** 2022-11-08 15:33 UTC
