### ISSUE TITLE
icons not changing after reboot

### ISSUE THREAD

**Issue by PhazonicRidley** [micheleg/dash-to-dock#690] opened 2018-02-20 21:12 UTC
Hello! I have changed my icons to the Papiurs and when I rebooted my computer dash to dock showed the default icons (awaita) I am using arch linux.

**Comment by crazymaster** [comment] 2018-03-01 12:15
Is this duplicate of #663?

**Comment by micheleg** [comment] 2018-03-31 20:01
I'm closing this as a duplicate of #640.

**Closed by micheleg** 2018-03-31 20:01 UTC
