### ISSUE TITLE
GLib.FileError: Failed to open file “/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas/gschemas.compiled”: open() failed: No such file or directory

### ISSUE THREAD

**Issue by araul3927** [micheleg/dash-to-dock#1484] opened 2021-07-16 08:25 UTC
GLib.FileError: Failed to open file “/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/Settings.ui”: No such file or directory

Stack trace:
_init@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:198:27
buildPrefsWidget@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:1013:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by araul3927** [comment] 2021-07-16 08:30
GLib.FileError: Failed to open file “/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/Settings.ui”: No such file or directory

Stack trace:
  _init@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:198:27
  buildPrefsWidget@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:1013:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by VersedXth** [comment] 2021-07-17 10:07
what helped me was:

remove the Extention
remove the folder manually as root: /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com
reinstall the Extention and restart gnome-shell

**Comment by araul3927** [comment] 2021-07-19 07:58
worked but there are some bugs

**Comment by ewlsh** [comment] 2021-10-05 04:55
Probably a duplicate of #1475

See https://github.com/micheleg/dash-to-dock/issues/1475#issuecomment-880138403

**Comment by ewlsh** [comment] 2021-10-05 04:56
If not, also potentially tracked in #1525 (the `open()` error)

**Closed by ewlsh** 2021-10-05 04:55 UTC
