### ISSUE TITLE
Read all the requests, most of the comments and this is just a feedback for the DevTeam

### ISSUE THREAD

**Issue by ze3rax** [micheleg/dash-to-dock#722] opened 2018-04-10 19:03 UTC
Hello gentlemen,

I was astonished by the work accomplished. Congrats! 

What your focus should be with the future version of your extension is NOT to:
- add removable media links to dock
- add folder groups
- add blinking icons
- add styles under the active applications

You are doing no work with things like these. People have asked you to add simple drag&drop future in order for them to ask whatever they want. No matter whether it is the trash icon, a random folder out from Nautilus etc etc etc.

Do this first!

There is the application RocketDock. Have a look at it. Do what you can, but leave the sugary when the application is ready.

**Comment by micheleg** [comment] 2018-04-10 19:51
Hi Todor, I'm sure you understand that you cannot easily affect people motivations, interests, and personal necessities (regardless of the level of sugar involved) which is what drive the development of projects like this :) 

Regarding an extensive drag and drop support, which I understand is what you would be putting effort in, unfortunately we are severely hindered by the lack of support in the shell toolkit (you have probably already seen this #49).

**Comment by micheleg** [comment] 2018-04-29 18:29
Closing as duplicate of #49.

**Closed by micheleg** 2018-04-29 18:29 UTC
Labels: duplicate
