### ISSUE TITLE
Dock autohides always (ignoring autohide only when window is over the dock) after context menu action

### ISSUE THREAD

**Issue by jeroni** [micheleg/dash-to-dock#1769] opened 2022-06-28 09:27 UTC
It happens after executing any action from the context menu.
As an example, right click Nautilus and open a new instance from the context menu.
The dock will auto hide even without any window over it.
To make it appear again you can disable - enable auto hide from the settings or push with any window to make it has the default behaviour again.

gnome-shell-extension-dash-to-dock 1:72+5+g24fd566-1
Gnome 42.2
Archlinux

https://user-images.githubusercontent.com/9005992/176144203-c0fc35f2-4d7b-4522-82a9-c8285c2acabd.mp4

**Comment by vanvugt** [comment] 2022-07-11 07:16
Duplicate of #1755. Fixed in #1751 so we're waiting for v73.

**Comment by webmastak** [comment] 2022-07-11 19:54
I confirm the same is happening.

**Comment by TheBakerCat** [comment] 2022-07-21 19:23
same issue

**Comment by Bananaman** [comment] 2022-07-27 17:47
@micheleg @3v1n0 

Very good bug report. You really covered all the issues and workarounds correctly. I confirm that auto-hide is broken.

I have verified it on:

- Dash to Dock compiled from GIT Master on July 20th, 2022. This commit is what I run: https://github.com/micheleg/dash-to-dock/commit/0fc9d94b59e91e1c08ad38762ebc55b7deaf99ab
- GNOME 42.3 (Fedora Workstation 36)
- Both X11 and Wayland.
- With Caffeine/Espresso extension disabled, Dash to Dock is still broken. I just tried it because of #1744
- You don't have to select any menu item. Just the action of opening the context menu is enough to bug out Dash to Dock. So you can right-click an app, then right-click the app again to close the menu, and now the dock will be bugged and stuck in auto-hide.

**Comment by vanvugt** [comment] 2022-08-01 04:23
Downstream Ubuntu bug: https://launchpad.net/bugs/1983130

**Comment by Bananaman** [comment] 2022-08-07 02:36
Spontaneously, it seems likely that the bug is that Dash to Dock thinks the popup menu is a window that's overlapping with the dock, and therefore hides itself. And then D2D probably doesn't get any "window closed/moved" event regarding the popup menu when it closes, so D2D never re-appears.

@vanvugt Great to see the downstream bug report too. This is an annoying one, so the more eyes the better.

**Comment by Bananaman** [comment] 2022-08-20 17:52
This earlier, merged pull request seems related:

https://github.com/micheleg/dash-to-dock/pull/1751

**Comment by maxborowsky** [comment] 2022-09-06 12:54
This is never fixed in DtD 73. I just installed version 73 from the Fedora 36 repo and the problem remains: I right-click on the dock, call the menu and the dock is immediately hidden. You can return it only by calling the DtD settings again.

**Comment by 3v1n0** [comment] 2022-10-09 23:31
This is a regression of 77dac94755ee80fceec9d8b2aa0ed0a550bcc531 and it should be handled by #1849

**Closed** 2022-10-13 19:14 UTC

**Comment by D3vil0p3r** [comment] 2023-01-06 00:22
When the ubuntu-dock 74ubuntu2 version will be released? It should contain the fix of this issue.

If I clone the repository, I'm still getting `ubuntu-dock 74ubuntu1`.

**Comment by vanvugt** [comment] 2023-01-06 01:37
Yes @3v1n0 just forgot to push 74ubuntu2 [to git](https://github.com/micheleg/dash-to-dock/tree/ubuntu-dock) when it was [released to Ubuntu](https://launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/74ubuntu2). I'm sure he'll fix it soon.

**Comment by D3vil0p3r** [comment] 2023-01-06 01:38
> Yes @3v1n0 just forgot to push 74ubuntu2 [to git](https://github.com/micheleg/dash-to-dock/tree/ubuntu-dock) when it was [released to Ubuntu](https://launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/74ubuntu2). I'm sure he'll fix it soon.

Thank you guys. Let me know when it will be pushed to git please.
