### ISSUE TITLE
Dock minimizes on mouse move (within dock)

### ISSUE THREAD

**Issue by oafasting** [micheleg/dash-to-dock#199] opened 2015-07-24 13:00 UTC
Hello!
The dock minimizes often when moving the mouse. This seems to always happen in (but is not limited to) situations where there is a window in the background that would normally (on mouse-over with no dock present) invoke a tooltip or cursor change.
As it stands, it is very hard to use the dock in smart hide mode, due to the constant minimizing of the dock, due to the windows underneath it...

Edit: Setting panel mode to on seems to fix this, even though autohide is on...

**Comment by micheleg** [comment] 2015-07-24 19:11
This should not happen, A window below the dock should not receive the mouse events. Can you give me an example of one application that cause the bug? I can't reproduce it in my system.  Which GNOME Shell/dash-to-dock versions are you using?

**Comment by oafasting** [comment] 2015-07-25 11:49
I have tested it with all kinds of windows from nautilus to non natives like chrome, and it happens with them all.
I am running Gnome 3.16.2 on a clean install of Arch. Dash to dock is version 46 (from extensions page).
I did notice that Gnome is running on Wayland. Maybe that is the reason?

**Comment by micheleg** [comment] 2015-07-25 14:00
Good point. Could you run it in  X and see if the problem persist?

**Comment by micheleg** [comment] 2015-07-25 14:05
I can't reproduce the bug in wayland, but I tested it on GNOME 3.14.

**Comment by oafasting** [comment] 2015-07-25 15:45
I am having some serious issues with xorg and proprietary nvidia drivers atm. Ill tinker some more and see if I can get xorg running tonight

**Comment by micheleg** [comment] 2017-03-27 00:46
Closing as probably outdated. Please feel free to reopen the issue if you are still experiencing this sort of bugs.

**Closed by micheleg** 2017-03-27 00:46 UTC
Labels: bug
