### ISSUE TITLE
[bug] When the dock is positioned on the right side, it paints over the workspace switcher in overview.

### ISSUE THREAD

**Issue by trusktr** [micheleg/dash-to-dock#260] opened 2015-11-30 20:13 UTC
Normally in overview, the app dock is on the left, and the workspaces switcher is on the right. When we select the option to place the dock on the right, it causes the workspace switcher to be clipped:

![screenshot from 2015-11-30 12-12-53](https://cloud.githubusercontent.com/assets/297678/11483138/b8eb3628-975b-11e5-92e7-0f7083041cb1.png)

**Comment by trusktr** [comment] 2015-11-30 20:15
It'd be great if perhaps you can add an option to move the workspace switcher to the left when in overview mode. As a bonus, maybe there can be an option so that we can also reveal the workspace switcher the same as the dock, by pushing on the edge of the screen, with intelligent auto-hide, etc.

There's also this plugin you might get some idea from: https://extensions.gnome.org/extension/427/workspaces-to-dock/

**Comment by trusktr** [comment] 2015-11-30 20:16
Oops, I guess it's not clipped, it's just hiding like normal, but it's just not on the edge of the screen, which looks funky:

![screenshot from 2015-11-30 12-16-24](https://cloud.githubusercontent.com/assets/297678/11483230/33f277d2-975c-11e5-8b36-ae5900328ada.png)

**Comment by trusktr** [comment] 2015-11-30 20:25
Actually, I just discovered that I can add the outside-of-overiew docking ability to the workspace switcher and move it to the left side with the previously mentioned workspaces-to-dock extension, so then it doesn't conflict with dash-to-dock:

![screenshot from 2015-11-30 12-23-05](https://cloud.githubusercontent.com/assets/297678/11483501/6b0140e0-975d-11e5-9777-d2dc42e14085.png)

I think it'd still be nice if you had some options like this in Dash to Dock itself. :)

**Comment by micheleg** [comment] 2015-11-30 20:29
How did you end up with the condition in the first screenshot? Maybe there is a bug. The right behaviour is what you see in the second  one. I honestly have no plan to tweak the workspace switcher. I know the extension you cited, it was actually originally based on this. I know that the right position is a bit weird, and the top is even worse, but I'm trying to avoid completely rewriting the overview, also because there is already another extension taking care of customizing the workspace switcher and I would not do much better that that.

**Comment by trusktr** [comment] 2015-11-30 20:36
Aha, workspaces-to-dock is aware of dash-to-dock:

![screenshot from 2015-11-30 12-35-14](https://cloud.githubusercontent.com/assets/297678/11483730/efbe5100-975e-11e5-9be2-0e3ed2226256.png)

**Comment by trusktr** [comment] 2015-11-30 23:54
@micheleg That behavior (the first and second screenshots) is from Gnome 3.18 (without any extensions enabled). The workspaces are hidden off to the side while in over view mode, like this (without any extensions and only dash-to-dock on the left):

![hidden-workspaces](https://cloud.githubusercontent.com/assets/297678/11488336/a0cce5cc-977a-11e5-89b9-2591e7ece083.png)

**Comment by micheleg** [comment] 2015-11-30 23:57
But what is the difference between the first and second screenshot? How can I reproduce the first screenshot condition? I'm just trying to understand if there is a bug involved.

**Comment by trusktr** [comment] 2015-12-01 00:02
In the first screenshot, I simply set dash-to-dock to the right (with other plugins installed). In this shot, dash-to-dock is the only plugin active, and the workspace panel un-hides while dash-to-dock is on the right:

![unhides](https://cloud.githubusercontent.com/assets/297678/11488497/c2fd081a-977b-11e5-9540-9cafc879f89c.png)

**Comment by trusktr** [comment] 2015-12-01 00:03
Maybe in that case (dock on the right) you should just automatically switch the workspaces to the left?

**Comment by mbicknese** [comment] 2015-12-01 20:40
Came here to report the same bug. So adding more information to this report instead. My setup (Arc theme) seems to be even less compatible.

- Arch Linux
- Gnome-shell 3.18.3-1
- Linux 4.2.5-1 
- Dash to Dock 49

![screenshot from 2015-12-01 21-36-44](https://cloud.githubusercontent.com/assets/5147934/11513471/b06bd19c-9873-11e5-95e1-7d7f4bc13603.png)

Most preferred solution would be to swap the workspace switchers and dashes location. Though moving the dash temporary to the left is a perfectly fine solution too.

**Comment by micheleg** [comment] 2016-02-21 18:19
I don't consider the this a bug, but a reasonable although ugly behaviour.  Workspace to dock is already available to move the workspace on the other side of the screen, so I'm closing this issue.

**Closed by micheleg** 2016-02-21 18:19 UTC
