### ISSUE TITLE
First character typed into the Gnome search bar repeats.

### ISSUE THREAD

**Issue by linxpatrick** [micheleg/dash-to-dock#1939] opened 2023-02-27 20:31 UTC
With some installations, Dash to Dock causes the first character typed into the Gnome search bar to repeat. So, if I want to find extensions when I type the first e it comes out as ee. It's possible to backspace one time and continue typing the search term.

Using OpenSuSE. When upgrading from 15.3 to 15.4 the search bar works OK. On a fresh installation of 15.4 the problem exists. Currently using version 77 of Dash to Dock but older versions have the same problem.

**Comment by vanvugt** [comment] 2023-02-28 01:53
Duplicate of #1855

**Closed by vanvugt** 2023-02-28 01:53 UTC
