### ISSUE TITLE
Not working on gnome 3.36 Ubuntu 20.04 Beta.

### ISSUE THREAD

**Issue by jcarmona1050** [micheleg/dash-to-dock#1130] opened 2020-03-20 20:05 UTC
Not working on gnome 3.36 Ubuntu 20.04 Beta.

**Comment by neptu39701** [comment] 2020-03-21 09:24
not working in arch gnome 3.36 wayland too

**Comment by hachiimam** [comment] 2020-03-22 02:12
> not working in arch gnome 3.36 wayland too

same problem, i hope is cooking.

**Comment by githubgeeker** [comment] 2020-03-22 10:50
Same problem gnome-shell 3.36.0 manjaro linux.
The error in looking glass is:
TypeError: appIconPrototype._onLeaveEvent is undefined

**Comment by aliasbody** [comment] 2020-03-22 10:59
The gnome-3-36 branch should work https://github.com/micheleg/dash-to-dock/tree/gnome-3-36 (it works for me using Arch Linux).

You only need to:
```bash
$ git clone https://github.com/micheleg/dash-to-dock.git -b gnome-3-36
$ cd dash-to-dock/
$ make
$ make install
```

And then just restart gnome shell
```
ALT + F2 and then type 'r' and enter
```

As for the time of this comment, everything is working except drag and drop of icons which is somehow messy, but its a WIP that should be integrated soon into a final release (I hope).

**Comment by githubgeeker** [comment] 2020-03-22 11:21
Hi, I have tried but not working

Il dom 22 mar 2020, 12:00 Luis Manuel Ramos Da Costa <
notifications@github.com> ha scritto:

**Comment by aliasbody** [comment] 2020-03-22 11:46
@githubgeeker What is the error you're having? Maybe I can help.

**Comment by githubgeeker** [comment] 2020-03-22 11:51
I've try again with your suggest option "*-b gnome-3-36*" and works great!
Thanks man!!!!!

Il giorno dom 22 mar 2020 alle ore 12:00 Luis Manuel Ramos Da Costa <
notifications@github.com> ha scritto:

**Comment by avbor** [comment] 2020-03-23 09:45
Hi, with gnome-3-36 branch its work on fedora 32 beta but cant open extension settings:
![image](https://user-images.githubusercontent.com/32452033/77303463-12260600-6d04-11ea-989f-57838dba29de.png)
![image](https://user-images.githubusercontent.com/32452033/77303515-27029980-6d04-11ea-9e9f-862b9d8dbfdf.png)

**Comment by avbor** [comment] 2020-03-23 10:11
> a

Fixed for me by installing gnome-extensions-app =)

**Comment by vageliskatsiotis** [comment] 2020-03-23 12:33
> The gnome-3-36 branch should work https://github.com/micheleg/dash-to-dock/tree/gnome-3-36 (it works for me using Arch Linux).
> 
> You only need to:
> 
> ```shell
> $ git clone https://github.com/micheleg/dash-to-dock.git -b gnome-3-36
> $ cd dash-to-dock/
> $ make
> $ make install
> ```
> 
> And then just restart gnome shell
> 
> ```
> ALT + F2 and then type 'r' and enter
> ```
> 
> As for the time of this comment, everything is working except drag and drop of icons which is somehow messy, but its a WIP that should be integrated soon into a final release (I hope).

 @aliasbody worked like a charm! thank you.

**Comment by Razer0123** [comment] 2020-03-24 14:23
Not working for me, getting "error loading extension"

**Comment by 3v1n0** [comment] 2020-03-26 01:32
Duplicate of #1123

**Closed by 3v1n0** 2020-03-26 01:32 UTC

**Comment by radumiron** [comment] 2020-05-27 09:51
> a



> > The gnome-3-36 branch should work https://github.com/micheleg/dash-to-dock/tree/gnome-3-36 (it works for me using Arch Linux).
> > You only need to:
> > ```shell
> > $ git clone https://github.com/micheleg/dash-to-dock.git -b gnome-3-36
> > $ cd dash-to-dock/
> > $ make
> > $ make install
> > ```
> > 
> > 
> > And then just restart gnome shell
> > ```
> > ALT + F2 and then type 'r' and enter
> > ```
> > 
> > 
> > As for the time of this comment, everything is working except drag and drop of icons which is somehow messy, but its a WIP that should be integrated soon into a final release (I hope).
> 
> @aliasbody worked like a charm! thank you.

It did work like a charm. Excellent work, thank you!
