### ISSUE TITLE
Settings Menu not opeining in dash to dock

### ISSUE THREAD

**Issue by gauravdighe** [micheleg/dash-to-dock#271] opened 2015-12-26 06:38 UTC
Hello,

I have Fedora23. I have installed dash to dock extension. But the settings menu inside dash to dock is not opeining.

**Comment by micheleg** [comment] 2015-12-26 13:56
This is a known issue caused by a bug in librsvg, A workaround has been applied in current master, have a look at #262. Closing as duplicate.

**Closed by micheleg** 2015-12-26 13:56 UTC
Labels: duplicate
