### ISSUE TITLE
Have Trash icon option

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [micheleg/dash-to-dock#321] opened 2016-05-28 20:23 UTC
The only real thing I miss from Docky in this is that there is no Trash icon, so I think that there should be the ability to have a little divisory line on the right after which is a little Trash icon which shows differently when something is in the Trash, when clicked launches the default file manager to the location of Trash, and when right-clicked upon gives the option to empty the Trash (though should also then show at least some of the items in Trash).

**Comment by Sancho-Panza** [comment] 2016-05-28 21:54
Duplicate of #173.

**Closed** 2016-05-28 22:16 UTC
