### ISSUE TITLE
In Gnome 3.30 v64 sometimes stays visible in the lock screen

### ISSUE THREAD

**Issue by rocky7x** [micheleg/dash-to-dock#829] opened 2018-11-07 14:33 UTC
In Gnome 3.30 (Manjaro 18) the version 64 sometimes stays visible in the lock screen. The stack trace points to the following lines of codes:
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:416
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:415
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:424
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:89
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:456

It means that there is an issue with destroying the object with label transparency as this is the function that causes it to fail: `this._transparency.destroy();`

Can you please have a look what is ging wrong here?

The problem is that the issue is not reproducible always, just sometimes, but it only started with Gnome 3.30 and v64.

**Comment by rugk** [comment] 2018-11-13 22:15
Dupe of https://github.com/micheleg/dash-to-dock/issues/762, https://github.com/micheleg/dash-to-dock/issues/726, https://github.com/micheleg/dash-to-dock/issues/641 and https://github.com/micheleg/dash-to-dock/issues/649(?).
(does anyone maintain that issue tracker, here??)

**Comment by micheleg** [comment] 2018-12-02 19:13
Closing as duplicate  of #641.

**Closed by micheleg** 2018-12-02 19:13 UTC
Labels: bug, duplicate

**Comment by rocky7x** [comment] 2018-12-04 15:39
But this is in Manjaro. I don't use the Ubuntu dock in Manjaro and the fix that was done in #641 was done for Ubuntu dock. I don't see how I can implement the same modifications in Dash to dock itself. Any idea?

**Comment by rugk** [comment] 2018-12-04 18:12
I am also affected in Fedora, so I think this issue is not only about Ubuntu, so https://github.com/micheleg/dash-to-dock/issues/641 should cover all distros.

**Comment by rocky7x** [comment] 2018-12-04 22:45
Hi,

Yes, I can confirm that the error always relates to the destroy command for transparency (at least for all instances of the error I investigated, it always related to that line if code).

**Comment by theoneone** [comment] 2018-12-05 00:04
Hi,

Same issue here.

I'm running Gnome 3.30 on CentOS 7, the ubuntu-dock fix of the other thread desn't apply here.

**Comment by rugk** [comment] 2018-12-05 08:40
> can you confirm that the error reported is always the same? I.e. with respecct to this._transparency.destroy();?

No, I don't even know how I would get to this error report. :smile:

**Comment by rocky7x** [comment] 2018-12-05 08:49
When it happens, check the journalctl for the dash-to-dock stack trace. You will see references to certain lines of code in certain files (similar to mine log in the top message of this issue) - something like this:

/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:416

when you trace the lines of code through the files from top to bottom, by the time you get to the 5th or 6th reference, you will probably run into the code line this._transparency.destroy(); . That is what franglais125 had in mind.

**Comment by micheleg** [comment] 2018-12-05 22:03
Anybody can post a more complete log? What is the actual error? I cannot reproduce the bug yet.

**Comment by rocky7x** [comment] 2018-12-06 08:48
Hi,

I have not used the extension recently, because it annoyed me, having to deal with that, but I have turned it on now and will wait for a new occurence. Once I have it I will post the complete stack trace from the journalctl and also check for any errors in the Looking Glass. The problem is that it also happens for me sporadically, so I am not able to successfully reproduce it at will.

**Comment by rocky7x** [comment] 2018-12-17 22:08
Just wanted to let you know that when I switched to Wayland, the bug seems to be gone. I haven't experienced it since the switch to Wayland..

**Comment by rugk** [comment] 2018-12-17 22:18
I am all the time on Wayland, so this does not seem to be the reason. Maybe just a coincidence?

**Comment by rocky7x** [comment] 2018-12-18 08:41
Might be. For me it hasn't happened yet on Wayland, while on Xorg it was happening at least once a day. But, as soon as I get the occurrence on Wayland, I'll drop a message here...

**Comment by rocky7x** [comment] 2019-01-02 13:52
OK, I can now confirm that it is not Xorg/Wayland related - happened to me on Wayland as well. The error stack is the same. So this is still an open issue, not Ubuntu related.
