### ISSUE TITLE
Dock disappears after a few minutes inactivity

### ISSUE THREAD

**Issue by bastienho** [micheleg/dash-to-dock#2227] opened 2024-05-31 11:17 UTC
Since a while, I got a strange behavior, after about 20 minutes of inactivity, without sleep or screen lock, the dock disappears.
Even the `alt+tab` trigger do not shows anything.

`alt+F2` + `r` fails and asks me to restart the session.

This time, before restarting, I looked in `syslog` and found this:

```
2024-05-31T13:01:25.862045+02:00 localhost gnome-shell[5002]: JS ERROR: TypeError: dockManager is null#012getApps@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:1447:9#012getRunningApps@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:1460:12#012_ensureLocations/<@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/docking.js:1847:56#012_create/object[name]@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/utils.js:326:37#012_ensureLocations/<@file:///home/bastienho/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1846:60#012_create/object[name]@file:///home/bastienho/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/utils.js:326:37#012_syncRunningApplications@resource:///org/gnome/shell/misc/introspect.js:75:36#012IntrospectService/<@resource:///org/gnome/shell/misc/introspect.js:43:18#012@resource:///org/gnome/shell/ui/init.js:21:20
2024-05-31T13:01:32.336590+02:00 localhost gnome-shell[5002]: message repeated 3 times: [ JS ERROR: TypeError: dockManager is null#012getApps@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:1447:9#012getRunningApps@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:1460:12#012_ensureLocations/<@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/docking.js:1847:56#012_create/object[name]@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/utils.js:326:37#012_ensureLocations/<@file:///home/bastienho/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1846:60#012_create/object[name]@file:///home/bastienho/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/utils.js:326:37#012_syncRunningApplications@resource:///org/gnome/shell/misc/introspect.js:75:36#012Introspe]
```

Any idea ?

**Comment by vanvugt** [comment] 2024-06-03 07:09
Duplicate of #1992

**Closed by vanvugt** 2024-06-03 07:09 UTC
