### ISSUE TITLE
The overview is disabled after returning from sleep

### ISSUE THREAD

**Issue by hidehic0** [micheleg/dash-to-dock#2313] opened 2024-10-04 05:59 UTC
Environment
![Screenshot from 2024-10-04 14-49-42](https://github.com/user-attachments/assets/eb686d55-ad93-4084-85cb-cd72f6ed8e8f)

Image↓
![Screenshot from 2024-10-04 14-47-37](https://github.com/user-attachments/assets/c1231bb8-4be2-489e-9c3c-a86773dd919c)

Specifically
When you open the overview after the first sleep, you will see the dock with the wrong size behind the dock that is displayed normally.
If you open the overview after waking from sleep for the second time, it will look like the image above.
By the way, I am using blur my shell
Only the dock is displayed like this, and the search function is disabled.
Appmenu is no good at all

With all due respect, I haven't looked at the source code at all, but I created the issue because it's inconvenient.

**Comment by 3v1n0** [comment] 2024-10-04 12:59
Can you provide gnome shell logs? `journalctl /usr/bin/gnome-shell`

**Comment by hidehic0** [comment] 2024-10-04 23:54
[log.txt](https://github.com/user-attachments/files/17264536/log.txt)
Logged out.

**Comment by vanvugt** [comment] 2024-10-07 05:43
Looks like another case of #1992. Please disable either dash-to-dock or ubuntu-dock.

**Comment by vanvugt** [comment] 2024-10-07 05:44
Duplicate of #1992

**Closed by vanvugt** 2024-10-07 05:44 UTC
