### ISSUE TITLE
Scroll action does not work when Intelligent Auto Hide is disabled.

### ISSUE THREAD

**Issue by pnka** [micheleg/dash-to-dock#2039] opened 2023-06-13 07:33 UTC
I'm using Debian 12 with X11 and Gnome 43.4.  Dash to dock version is 82.

My Scroll action setting is "Switch workspace". I can scroll my mouse wheel on the dock and it can switch between workspaces as intented. But if I disable Intelligent autohide, switching workspaces feauture doesnt work.

**Comment by 3v1n0** [comment] 2023-06-13 11:09
Duplicate of #2032

**Closed as completed by 3v1n0** 2023-06-13 11:09 UTC
