### ISSUE TITLE
Desktop icons grid when intellihide enabled

### ISSUE THREAD

**Issue by albertsegura** [micheleg/dash-to-dock#630] opened 2017-10-29 15:32 UTC
Hi,

first of all, thank you for this extension, it's a must have to make gnome shell usable.

**ISSUE:**
When intellihide is enabled the desktop icons grid is displaced to the left to "fill" the whole area of the desktop (with dash pinned to the left like unity dock). When in the desktop (no window open, and if the dock is enabled to be displayed), the dock overlaps with the desktop icons as the grid was pushed to the left. 

Image to show the problem:
![intellihide](https://user-images.githubusercontent.com/1588785/32145302-3a4cd60e-bcc6-11e7-8faf-016c26c616d5.png)

**SUGGESTION:**
I suggest that the change to the grid positioning is only applied if the intellihide is enabled and the dock is visible when no window is open (option "Dodge windows" disabled).

Running Ubuntu 17.10, dash to dock version 61.

**Comment by micheleg** [comment] 2017-11-05 00:54
As the desktop is drawn by nautilus, unfortunately there's no way we can control it from the extension.  Closing as duplicate of #17.

**Closed by micheleg** 2017-11-05 00:54 UTC
Labels: duplicate
