### ISSUE TITLE
Got a error when i enabled the extension. Please Help.

### ISSUE THREAD

**Issue by ShriBatman** [micheleg/dash-to-dock#906] opened 2019-03-12 09:48 UTC
TypeError: ExtensionUtils.initTranslations is not a function

Stack trace:
  init@/home/tolexo/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:853:5
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:76:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43

**Comment by micheleg** [comment] 2019-03-17 22:26
If you are running master on Gnome shell <3.32 ths is expected. Duplicate of #902.

**Closed by micheleg** 2019-03-17 22:26 UTC
Labels: duplicate, invalid
