### ISSUE TITLE
Issue after wake-on on Ubuntu 20.04

### ISSUE THREAD

**Issue by camelator** [micheleg/dash-to-dock#1727] opened 2022-04-30 13:50 UTC
On Ubuntu 20.04,
Extension works perfectly after a reboot,
but if I suspend the computer, and I wake on the computer by typing a key for exemple,
Then I have the User/password screen,
After typing my passord, the desktop is displayed with both the Ubuntu icons and the dash to dock icons.
There are two sets of icons in the same location!
And the mechanism to hide and show dash and dock does not work => I have to reboot the computer to make it working.

**Comment by emansom** [comment] 2022-05-05 05:09
Duplicate of #1700. Ubuntu ships a fork of dash to dock that's enabled by default.

**Comment by vanvugt** [comment] 2022-05-18 08:24
Duplicate of #1700

**Closed by vanvugt** 2022-05-18 08:24 UTC
