### ISSUE TITLE
Smart auto-hide not working with Wayland / multiscreen

### ISSUE THREAD

**Issue by phocean** [micheleg/dash-to-dock#427] opened 2017-01-06 19:53 UTC
In a Fedora 25 Wayland session, the dash still auto hide as expected as long as a single monitor is used.
When external screens are connected, Dash stop reacting to maximized windows events.

I checked that it works fine in Fedora 25 / Xorg, so it is definitely related to Wayland.

Note that I made these tests on the master git branch.

(And as a final note I want to thank you for that great and must-have extension).

**Comment by micheleg** [comment] 2017-01-10 21:19
Most likely a duplicate of #255 and #423.

**Comment by micheleg** [comment] 2017-01-14 23:55
Please have a look to the branch https://github.com/micheleg/dash-to-dock/tree/fix_intellihide_wayland and check if it solve the issue.

**Comment by oidualc** [comment] 2017-01-16 13:58
@micheleg I had the same issue and (at least for me) https://github.com/micheleg/dash-to-dock/tree/fix_intellihide_wayland is working properly, thank you!

**Comment by micheleg** [comment] 2017-01-16 21:45
Fixed by d553004e014cefb981.

**Closed by micheleg** 2017-01-16 21:45 UTC
Labels: bug
