### ISSUE TITLE
Latest version fails to install on Arch

### ISSUE THREAD

**Issue by bulletmark** [micheleg/dash-to-dock#96] opened 2014-03-28 03:20 UTC
The latest update from the gnome extensions site fails to install on current arch x64 with gnome shell 3.10.4-1. You click on the "on" button, the browser prompts to download, you say yes, and then after a few secs the button goes off. Does this every time. Of course there is no error message etc due to the rubbish design of the gnome extensions site. I have been running previous versions of this extension without issue.

I'll add that it has this same problem in both Chrome and Firefox. I also updated in an arch VM guest and the same problem occurs there (in both browsers also).

**Comment by micheleg** [comment] 2015-01-18 15:58
It might be related to this https://bugzilla.gnome.org/show_bug.cgi?id=688973

**Comment by bulletmark** [comment] 2015-01-19 01:14
Just a note that I updated to extension version 37 today on my PC with current Arch X64 with gnome-shell 3.14.3-2 and had to do the same dance. Same problem on two other VirtualBox Arch guests. Reloading gnome-shell one or more times eventually gets it there.

**Comment by micheleg** [comment] 2015-01-19 01:20
If bug above is the only reason for the fail on the extension update, which means I have to reconsider how I did few things, the way to make the extension works for sure is removing the extension, reloading the shell, install it again

1. delete ~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/ directory
2. restart  the shell  (logout - login or alt+F2 then r )
3. reinstall the extension from the extension site

I apologise for the inconvenience. Once installed it should work flawlessly.

**Comment by bulletmark** [comment] 2015-01-19 01:29
My experience is that your procedure above will certainly install the extension correctly.

Note that this not at all an inconvenience to me because I know what is going on and can always get it installed. As far as I am concerned this extension is absolutely fantastic, exudes class and quality, and receives frequent fixes and improvements. I consider this the only "must-have" gnome-shell extension.  I only update this bug to let you know it is still happening because it is an issue that is likely to be "unnerving" to newbies so hopefully it remains on the back-burner.

**Comment by micheleg** [comment] 2015-01-31 02:54
Hi @bulletmark, As it seems you are able to reproduce the bug, while I can't. I tried to workaround the problem on the update_fails branch. Could you test if that solves the problem?. Just install this version and then update to the one in extensions.gnome.org in the conditions which are causing the problem and check if now the update works. Thank you.

**Comment by bulletmark** [comment] 2015-01-31 04:26
I installed the "update_fails" version but when I visit extensions.gnome.org/local/ in Firefox I don't get the update flag/button appear?

**Comment by micheleg** [comment] 2015-01-31 15:53
My fault. I updated that branch, now you should have the update button.

**Comment by bulletmark** [comment] 2015-01-31 23:56
Installed that new version and restarted gnome-shell. Went to extensions site and saw it showing a new version. Rebooted my PC just to make sure and then pressed the update button. New version seemed to install OK. Then restarted gnome-shell but dash-to-dock was not running. Looked in tweak tool and the extension was now set off. Turned it on but the extension would not run (although the preferences window would open ok). Closed tweak tool and then re-opened but every time I opened it dash-to-dock was off and even though I could turn in on the extension was not running. Started GS LG and it said dash-to-dock had no errors. Then rebooted my PC and it came up with the new dash-to-dock running.

**Comment by micheleg** [comment] 2015-02-03 01:18
This is even more strange. So now it was failing after installing properly?

**Comment by bulletmark** [comment] 2015-02-03 01:25
Well it seemed to install "properly" but clearly it wasn't because after restarting GS it was not working. Reboot of box fixed it though. Obviously there is something very odd with this stuff,

**Comment by nekohayo** [comment] 2015-02-03 04:31
Again sounds like a race condition to me... you can try repeatedly reloading the shell and it would probably do the same as the reboot did.

**Comment by micheleg** [comment] 2015-03-02 01:35
I made another attempt. Could you try the <code>test_noGobjectSUbclass</code> branch. This seem to avoid the update problem for me.

Could you also give another try to the <code>update_fails</code> . Didn't change anything, but that was working too for me.

**Comment by bulletmark** [comment] 2015-03-03 07:12
I retested about 4 times using the update_fails branch and it worked ok, sometimes just restarting gnome-shell, other times rebooting in between. Also tried test_noGobjectSUbclass a couple of times and it worked ok.

**Comment by micheleg** [comment] 2015-03-04 00:03
I'merged test_noGobjectSUbclass into master - ce3d64b1417d415a7b0ebac9d33d4914685013d5, 568358a484807661467f9a0e343252fc76b3ee9e and 94a3718244e12b74cfeb771a201100b0a0533a52 -  I hope the issue is gone now.

**Comment by micheleg** [comment] 2015-04-02 23:35
I haven't heard about any problem updating the extension for the recent versions, so I do believe the problem is finally solved (although the solution made the code much uglier).

**Closed by micheleg** 2015-04-02 23:35 UTC
Labels: bug
