### ISSUE TITLE
Doesn't work with gnome 40

### ISSUE THREAD

**Issue by sallyahaj** [micheleg/dash-to-dock#1389] opened 2021-02-13 09:38 UTC
Hello there, when I tried installing the extension on gnome-shell 40 on Fedora 34 prerelease, I get this message:

`Gtk.BuilderError: /home/myusername/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/Settings.ui:13:35 Invalid property: GtkBox.margin_left

Stack trace:
  DashToDock_Settings@/home/myusername/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:92:23
  buildPrefsWidget@/home/myusername/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:869:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  `

**Comment by silviobierman** [comment] 2021-02-13 21:59
Same here.  I can't wait until D2D works one Gnome 40. The Gnome geniuses have made vanilla Gnome even less usable than before (which is a remarkable feat on itself). You still click top-left to reveal the dash only to discover that it has been moved to the bottom of the screen. Working on my laptop using the touch pad now gives me RSI within ten minutes.

Consider me even more helpless without D2D than ever before.

**Comment by hrdwrrsk2** [comment] 2021-03-22 00:50
now GNOME shell version 40.0 is available (although it still not in Arch repo until some days/weeks)

waiting for GS40 compat PR for now

**Comment by ijuma** [comment] 2021-03-25 02:57
FYI, A porting guide was published:
https://blogs.gnome.org/shell-dev/2021/03/20/extensions-rebooted-porting-your-existing-extensions-to-gnome-40/

**Comment by hrdwrrsk2** [comment] 2021-03-28 21:25
the (WIP) GS40 compat PR now available at #1402

**Comment by vanvugt** [comment] 2021-03-29 01:25
Please close this as a duplicate of #1358.

**Comment by ginhiki** [comment] 2021-05-01 09:20
it still doesn't work right, or is it fixed?

**Comment by ewlsh** [comment] 2021-10-05 05:18
Duplicate of #1358

**Closed by ewlsh** 2021-10-05 05:18 UTC

**Comment by bug1ess** [comment] 2021-10-16 12:36
> Same here. I can't wait until D2D works one Gnome 40. The Gnome geniuses have made vanilla Gnome even less usable than before (which is a remarkable feat on itself). You still click top-left to reveal the dash only to discover that it has been moved to the bottom of the screen. Working on my laptop using the touch pad now gives me RSI within ten minutes.
> 
> Consider me even more helpless without D2D than ever before.

You can also press **start** button
