### ISSUE TITLE
dash-to-dock crashes randomly (possibly when opening lid?)

### ISSUE THREAD

**Issue by rusins** [micheleg/dash-to-dock#820] opened 2018-10-16 01:16 UTC
After upgrading to Gnome 3.30 (now on 3.30.1), dash-to-dock seems to crash every now and then. Have been trying to monitor when it happens, and from the attached journalctl log it appears opening the lid of my laptop triggered it. (Possibly related: I once locked my screen but still had the dock showing above the lock-screen. Moving my mouse off the dock hid it, and thankfully it didn't show up again when I moved my mouse back. I.e., stayed disabled like it should be, until I unlocked my session.)

Will try to catch it crashing again, to see if it really is the laptop lid / desktop locking triggering it. Sometimes all my extensions get disabled, but in this instance only dash-to-dock stopped working, so I believe it is the culprit.

```
10月 16 01:48:57 tanks systemd-logind[600]: Lid opened.
10月 16 01:48:59 tanks gnome-shell[1121]: ../glib/gobject/gsignal.c:2641: instance '0x562aa3960bd0' has no handler with id '351609'
10月 16 01:48:59 tanks gnome-shell[1121]: ../glib/gobject/gsignal.c:2641: instance '0x562aa3960bd0' has no handler with id '351610'
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: == Stack trace for context 0x562aa1382220 ==
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #0   562ab6da9e30 i   resource:///org/gnome/gjs/modules/overrides/GObject.js:468 (7f98cdacc040 @ 25)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #1   562ab6d7e098 i   /home/raitis/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:416 (7f9893ab1940 @ 20)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #2   7fff3006dfe0 b   self-hosted:261 (7f98cdac1dc0 @ 223)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #3   562ab6d7dfe0 i   /home/raitis/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:415 (7f9893ab18b0 @ 172)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #4   7fff3006f0e0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f98cdab0b80 @ 71)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #5   562ab6d7df60 i   /home/raitis/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:424 (7f9893ab19d0 @ 17)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #6   7fff30070040 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f98cdab0b80 @ 71)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #7   562ab6d7dee0 i   /home/raitis/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:89 (7f9893ab10d0 @ 42)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #8   7fff30070fa0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f98cdab0b80 @ 71)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #9   562ab6d7de58 i   /home/raitis/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:456 (7f9893a9bee0 @ 82)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #10   7fff30071f00 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f98cdab0b80 @ 71)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #11   562ab6d7ddc0 i   /home/raitis/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1784 (7f9893aa8310 @ 116)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #12   7fff30072e60 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f98cdab0b80 @ 71)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #13   562ab6d7dd40 i   /home/raitis/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1903 (7f9893aa8700 @ 37)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #14   7fff30073dc0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f98cdab0b80 @ 71)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #15   562ab6d7dcc8 i   /home/raitis/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/extension.js:20 (7f9893a9b700 @ 12)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #16   562ab6d7dc08 i   resource:///org/gnome/shell/ui/extensionSystem.js:83 (7f98cd854af0 @ 436)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #17   562ab6d7db88 i   resource:///org/gnome/shell/ui/extensionSystem.js:354 (7f98cd85b670 @ 13)
10月 16 01:48:59 tanks gnome-shell[1121]: ../glib/gobject/gsignal.c:2641: instance '0x562aa3961390' has no handler with id '351611'
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #18   7fff30074f00 b   self-hosted:261 (7f98cdac1dc0 @ 223)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #19   562ab6d7db08 i   resource:///org/gnome/shell/ui/extensionSystem.js:353 (7f98cd85b5e0 @ 64)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #20   562ab6d7da88 i   resource:///org/gnome/shell/ui/extensionSystem.js:371 (7f98cd85b700 @ 87)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #21   7fff30076030 b   resource:///org/gnome/gjs/modules/signals.js:128 (7f98cdac18b0 @ 386)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #22   7fff30076e50 b   resource:///org/gnome/shell/ui/sessionMode.js:206 (7f98cd544040 @ 254)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #23   7fff30077ac0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f98cdab0b80 @ 71)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #24   562ab6d7d870 i   resource:///org/gnome/shell/ui/sessionMode.js:175 (7f98cd541e50 @ 100)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #25   7fff30078a30 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f98cdab0b80 @ 71)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #26   562ab6d7d7d8 i   resource:///org/gnome/shell/ui/screenShield.js:922 (7f98cd526f70 @ 55)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #27   7fff3007a180 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f98cdab0b80 @ 71)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #28   562ab6d7d718 i   self-hosted:975 (7f98cdaedf70 @ 392)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #29   562ab6d7d690 i   resource:///org/gnome/shell/ui/tweener.js:91 (7f98cdaccf70 @ 37)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #30   562ab6d7d5f0 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:208 (7f98cdadd790 @ 54)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #31   562ab6d7d4d0 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:342 (7f98cdadd820 @ 1742)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #32   562ab6d7d440 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:355 (7f98cdadd8b0 @ 100)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #33   562ab6d7d3c8 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:370 (7f98cdadd940 @ 10)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #34   562ab6d7d2f8 i   resource:///org/gnome/gjs/modules/signals.js:128 (7f98cdac18b0 @ 386)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #35   562ab6d7d268 i   resource:///org/gnome/shell/ui/tweener.js:207 (7f98cdad9790 @ 159)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #36   562ab6d7d1c0 i   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f98cdab0b80 @ 71)
10月 16 01:48:59 tanks org.gnome.Shell.desktop[1121]: #37   562ab6d7d140 i   resource:///org/gnome/shell/ui/tweener.js:182 (7f98cdad9700 @ 15)
10月 16 01:48:59 tanks gnome-shell[1121]: ../glib/gobject/gsignal.c:2641: instance '0x562aa3961390' has no handler with id '351612'
10月 16 01:48:59 tanks gnome-shell[1121]: Object Meta.WindowActor (0x562aa4c7cf90), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
```

**Comment by pwd-github** [comment] 2018-10-24 22:40
It's literally crashing for me every time I unlock the screensaver.

**Comment by crash83k** [comment] 2018-10-26 23:11
I'm having the same issue. When I wake my laptop, Dash to Dock is overlaid on the lock screen. The lock screen is basically frozen. I have to sleep the computer again, then wake it, and the lock screen is accessible, but the dash to dock is frozen completely. I have to restart Gnome to get back to normal.

I'm on Gnome 3.30.

**Comment by BjoernDaase** [comment] 2018-10-28 15:50
I can confirm this problem in Ubuntu 18.10, which has Gnome 3.30 also and (a fork of?) this extension enabled by default.

**Comment by micheleg** [comment] 2018-10-28 18:28
Can you paste the output of: `dconf dump /org/gnome/shell/extensions/dash-to-dock/`?

**Comment by micheleg** [comment] 2018-10-28 18:30
Also, please confirm if running in Xorg or Wayland

**Comment by BjoernDaase** [comment] 2018-10-28 18:57
Here is the output:
```
[/]
extend-height=true
dock-fixed=true
click-action='minimize'
multi-monitor=false
dock-position='LEFT'
icon-size-fixed=false
preferred-monitor=0
height-fraction=0.90000000000000002
dash-max-icon-size=46

```

And it's Xorg.

**Comment by pwd-github** [comment] 2018-10-28 19:00
Here's the output of mine, which causes Ubuntu to crash every time I unlock the screensaver:
`
show-apps-at-top=true
shift-click-action='minimize'
shift-middle-click-action='launch'
customize-alphas=true
extend-height=true
running-indicator-dominant-color=true
force-straight-corner=false
max-alpha=0.80000000000000004
custom-background-color=false
custom-theme-customize-running-dots=false
apply-custom-theme=false
custom-theme-running-dots=true
unity-backlit-items=false
custom-theme-shrink=false
background-opacity=1.0
running-indicator-style='DOTS'
middle-click-action='launch'
background-color='#000000'
transparency-mode='FIXED'
`
Also on Xorg.

**Comment by crash83k** [comment] 2018-10-28 19:03
Since it couldn't be produced in a VM, it might have something to do with graphics drivers. I'm running Nvidia 410 drivers.

Anyone else?

**Comment by BjoernDaase** [comment] 2018-10-28 19:11
@crash83k I have no dedicated graphics card, just an Intel UHD 620.

**Comment by crash83k** [comment] 2018-10-28 19:15
Good to know.

**Comment by datenstau** [comment] 2018-10-29 18:30
Maybe I'm facing the same issue. When I open the lid after a few standby cycles, the lock screen isn't showing, the screen seems in a flickering loop and the dock behaves in a strange way (double icons in different sizes, sometimes not responding to clicks).
After I switch to the lock screen manually with CTRL+ALT+F1 and restart gnome, everything works fine until the next wakeup.

`[/]
animate-show-apps=true
show-apps-at-top=false
show-windows-preview=true
extend-height=true
force-straight-corner=false
click-action='cycle-windows'
multi-monitor=true
scroll-action='cycle-windows'
apply-custom-theme=false
dock-position='LEFT'
custom-theme-shrink=true
background-opacity=0.34000000000000002
running-indicator-style='DOTS'
transparency-mode='ADAPTIVE'
isolate-workspaces=false
`
Intel UHD 620, Manjaro

**Comment by nkestrel** [comment] 2018-10-30 14:36
I get the exact same stack trace on Wayland. The failure happens in code related to transparency so I tried setting `transparency-mode='FIXED'` and `background-opacity=1.0` and it's been three days without failure when it used to fail multiple times a day.

**Comment by rusins** [comment] 2018-10-30 16:13
@nkestrel Thanks for finding a workaround! Speaking about transparency / color of the dock, I thought I'd mention that it is quite annoying at times that its usual color is different from that of when it is shown in the activities overview. (Video of that: https://youtu.be/cN8E-psbw4I)

**Comment by BjoernDaase** [comment] 2018-10-31 15:05
@micheleg 
Just for your information, that's how it looks for me when it crashes:![img_20181031_160103](https://user-images.githubusercontent.com/24682367/47797365-7d91c100-dd26-11e8-93f1-8d05c27ed22c.jpg)

**Comment by jonian** [comment] 2018-11-01 00:47
I can confirm this too. It happens when the screen locks and it is random.

System Information:

| Extension Version | 64              |
| :---------------------- | -------------: |
| Distribution            | Arch Linux |
| GNOME Shell        | 3.30.1        |

Settings: 

```toml
show-favorites=true
animate-show-apps=true
show-apps-at-top=true
customize-alphas=false
extend-height=true
dock-fixed=true
custom-theme-running-dots-color='#ffffff'
click-action='previews'
running-indicator-dominant-color=true
force-straight-corner=true
preferred-monitor=0
intellihide-mode='FOCUS_APPLICATION_WINDOWS'
scroll-action='cycle-windows'
custom-background-color=true
custom-theme-customize-running-dots=false
max-alpha=0.90000000000000002
apply-custom-theme=false
show-running=true
custom-theme-running-dots=true
unity-backlit-items=false
custom-theme-shrink=false
background-opacity=0.5
min-alpha=0.40000000000000002
dash-max-icon-size=24
background-color='#000000'
running-indicator-style='DOTS'
icon-size-fixed=true
transparency-mode='DYNAMIC'
```

Related logs `journalctl -r /usr/bin/gnome-shell`:

```
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #37   7ffee9f0e810 b   resource:///org/gnome/shell/ui/tweener.js:182 (7f50022d9700 @ 15)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #36   7ffee9f0e770 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f50022b0b80 @ 71)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #35   7ffee9f0e6a0 b   resource:///org/gnome/shell/ui/tweener.js:207 (7f50022d9790 @ 159)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #34   7ffee9f0e5f0 b   resource:///org/gnome/gjs/modules/signals.js:128 (7f50022c18b0 @ 386)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #33   7ffee9f0e500 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:370 (7f50022dd940 @ 10)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #32   7ffee9f0e470 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:355 (7f50022dd8b0 @ 100)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #31   7ffee9f0e3c0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:342 (7f50022dd820 @ 1742)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #30   7ffee9f0e270 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:208 (7f50022dd790 @ 54)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #29   55a1ee4e8030 i   resource:///org/gnome/shell/ui/tweener.js:91 (7f50022ccf70 @ 37)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #28   7ffee9f0c0a0 b   self-hosted:975 (7f50022edf70 @ 392)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #27   7ffee9f0b4d0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f50022b0b80 @ 71)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #26   55a1ee4e80b8 i   resource:///org/gnome/shell/ui/screenShield.js:922 (7f5001e293a0 @ 55)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #25   7ffee9f0a570 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f50022b0b80 @ 71)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #24   55a1ee4e8150 i   resource:///org/gnome/shell/ui/sessionMode.js:175 (7f5001e44280 @ 100)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #23   7ffee9f09600 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f50022b0b80 @ 71)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #22   7ffee9f08990 b   resource:///org/gnome/shell/ui/sessionMode.js:206 (7f5001e44430 @ 254)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #21   7ffee9f07da0 b   resource:///org/gnome/gjs/modules/signals.js:128 (7f50022c18b0 @ 386)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #20   55a1ee4e8298 i   resource:///org/gnome/shell/ui/extensionSystem.js:371 (7f5001f5b700 @ 87)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #19   55a1ee4e8318 i   resource:///org/gnome/shell/ui/extensionSystem.js:353 (7f5001f5b5e0 @ 64)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #18   7ffee9f06c70 b   self-hosted:261 (7f50022c1dc0 @ 223)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #17   55a1ee4e8398 i   resource:///org/gnome/shell/ui/extensionSystem.js:354 (7f5001f5b670 @ 13)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #16   55a1ee4e8418 i   resource:///org/gnome/shell/ui/extensionSystem.js:83 (7f5001f54af0 @ 436)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #15   55a1ee4e84d8 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/extension.js:20 (7f4fde66da60 @ 12)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #14   7ffee9f05b30 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f50022b0b80 @ 71)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #13   55a1ee4e8550 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1903 (7f4fde682a60 @ 37)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #12   7ffee9f04bd0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f50022b0b80 @ 71)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #11   55a1ee4e85d0 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1784 (7f4fde682670 @ 116)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #10   7ffee9f03c70 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f50022b0b80 @ 71)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #9   55a1ee4e8668 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:456 (7f4fde67d280 @ 82)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #8   7ffee9f02d10 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f50022b0b80 @ 71)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #7   55a1ee4e86f0 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:89 (7f4fde687430 @ 42)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #6   7ffee9f01db0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f50022b0b80 @ 71)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #5   55a1ee4e8770 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:424 (7f4fde687d30 @ 17)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #4   7ffee9f00e50 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7f50022b0b80 @ 71)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #3   55a1ee4e87f0 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:415 (7f4fde687c10 @ 172)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #2   7ffee9effd50 b   self-hosted:261 (7f50022c1dc0 @ 223)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #1   55a1ee4e88a8 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:416 (7f4fde687ca0 @ 20)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #0   55a1ee4e8928 i   resource:///org/gnome/gjs/modules/overrides/GObject.js:468 (7f50022cc040 @ 25)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: == Stack trace for context 0x55a1eab3f1e0 ==
Nov 01 02:10:55 vostro gnome-shell[778]: Object Meta.WindowActor (0x55a1edee73b0), has been already deallocated — impossible to access it. This might be caused by the object having been>
Nov 01 02:10:55 vostro gnome-shell[778]: ../glib/gobject/gsignal.c:2641: instance '0x55a1edee6fd0' has no handler with id '235390'
Nov 01 02:10:55 vostro gnome-shell[778]: ../glib/gobject/gsignal.c:2641: instance '0x55a1edee6fd0' has no handler with id '235389'
Nov 01 02:10:55 vostro gnome-shell[778]: ../glib/gobject/gsignal.c:2641: instance '0x55a1ece70bb0' has no handler with id '235386'
Nov 01 02:10:55 vostro gnome-shell[778]: ../glib/gobject/gsignal.c:2641: instance '0x55a1ece70bb0' has no handler with id '235385'
```

Only DTD references in logs (`journalctl -r /usr/bin/gnome-shell | grep dash-to-dock`):

```
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #15   55a1ee4e84d8 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/extension.js:20 (7f4fde66da60 @ 12)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #13   55a1ee4e8550 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1903 (7f4fde682a60 @ 37)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #11   55a1ee4e85d0 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1784 (7f4fde682670 @ 116)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #9   55a1ee4e8668 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:456 (7f4fde67d280 @ 82)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #7   55a1ee4e86f0 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:89 (7f4fde687430 @ 42)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #5   55a1ee4e8770 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:424 (7f4fde687d30 @ 17)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #3   55a1ee4e87f0 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:415 (7f4fde687c10 @ 172)
Nov 01 02:10:55 vostro org.gnome.Shell.desktop[778]: #1   55a1ee4e88a8 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:416 (7f4fde687ca0 @ 20)
```

**Comment by nkestrel** [comment] 2018-11-05 05:14
After further testing, setting `transparency-mode` to `ADAPTIVE` (default) or `DYNAMIC` definitely causes the failure and setting it to `FIXED` avoids it.

**Comment by philschenker** [comment] 2018-12-06 16:21
> After further testing, setting `transparency-mode` to `ADAPTIVE` (default) or `DYNAMIC` definitely causes the failure and setting it to `FIXED` avoids it.

I can confirm @nkestrel. I had the same issue. I am using Manjaro with gnome 3.30.2. This setting is by default enabled in Manjaro, disabling it seemed to solve the issue for me. I will further use it with FIXED setting and, if the error occures again I will report it here.

**Comment by philschenker** [comment] 2019-01-08 14:01
I had the issue again here the details:

Machine:
Dash to Dock version 64
Manjaro 18 with kernel 4.19.12

`$ dconf dump /org/gnome/shell/extensions/dash-to-dock/
[/]
show-apps-at-top=false
max-alpha=0.75
multi-monitor=false
apply-custom-theme=false
isolate-monitors=false
dock-position='LEFT'
transparency-mode='ADAPTIVE'
min-alpha=0.10000000000000001
isolate-workspaces=false`

Excerpt of the log:
`Jan 08 14:06:12 philippe-pc org.gnome.Shell.desktop[2060]: == Stack trace for context 0x5614e3a751b0 ==
Jan 08 14:06:12 philippe-pc org.gnome.Shell.desktop[2060]: #0   7ffda4bb33c0 b   resource:///org/gnome/gjs/modules/overrides/GObject.js:468 (7faaeafcc040 @ 25)
Jan 08 14:06:12 philippe-pc org.gnome.Shell.desktop[2060]: #1   7ffda4bb3460 b   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:416 (7faae809c040 @ 20)
Jan 08 14:06:12 philippe-pc org.gnome.Shell.desktop[2060]: #2   7ffda4bb3550 b   self-hosted:261 (7faaeafc1dc0 @ 223)
Jan 08 14:06:12 philippe-pc org.gnome.Shell.desktop[2060]: #3   7ffda4bb3610 b   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:415 (7faae8098f70 @ 172)
Jan 08 14:06:12 philippe-pc org.gnome.Shell.desktop[2060]: #4   7ffda4bb36d0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7faaeafb0b80 @ 71)
Jan 08 14:06:12 philippe-pc org.gnome.Shell.desktop[2060]: #5   5614e7a51a48 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:424 (7faae809c0d0 @ 17)
Jan 08 14:06:12 philippe-pc org.gnome.Shell.desktop[2060]: #6   7ffda4bb4630 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7faaeafb0b80 @ 71)
Jan 08 14:06:12 philippe-pc org.gnome.Shell.desktop[2060]: #7   5614e7a519c8 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:89 (7faae8098790 @ 42)
Jan 08 14:06:12 philippe-pc org.gnome.Shell.desktop[2060]: #8   7ffda4bb5590 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7faaeafb0b80 @ 71)
Jan 08 14:06:12 philippe-pc org.gnome.Shell.desktop[2060]: #9   5614e7a51940 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:456 (7faae808c5e0 @ 82)
Jan 08 14:06:12 philippe-pc org.gnome.Shell.desktop[2060]: #10   7ffda4bb64f0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7faaeafb0b80 @ 71)
Jan 08 14:06:12 philippe-pc org.gnome.Shell.desktop[2060]: #11   5614e7a518a8 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1784 (7faae80909d0 @ 116)
Jan 08 14:06:12 philippe-pc org.gnome.Shell.desktop[2060]: #12   7ffda4bb7450 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7faaeafb0b80 @ 71)
Jan 08 14:06:12 philippe-pc org.gnome.Shell.desktop[2060]: #13   5614e7a51820 i   /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1662 (7faae8090790 @ 17)
Jan 08 14:06:12 philippe-pc org.gnome.Shell.desktop[2060]: #14   7ffda4bb83c0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7faaeafb0b80 @ 71)
Jan 08 14:06:12 philippe-pc org.gnome.Shell.desktop[2060]: #15   7ffda4bb8490 b   self-hosted:979 (7faaeafedf70 @ 440)`

Please email me for the full log.

**Comment by azzar1** [comment] 2019-01-17 09:33
Fixed by #868

**Closed by azzar1** 2019-01-17 09:33 UTC
Labels: bug

**Comment by LorisZ** [comment] 2019-02-21 07:30
> Fixed by #868

Is this in version 65? Because I still experience the same crashes on screen unlock.

**Comment by dvorapa** [comment] 2019-10-08 12:34
@LorisZ Have you tried version 66 or 67?

**Comment by LorisZ** [comment] 2019-10-08 17:36
@dvorapa I solved the problem by ditching gnome, switched from Ubuntu to Kubuntu. LTS version of Ubuntu has ancient gnome that isn't supported anymore and the other Ubuntu versions only have 6 months of support. So no, I have not tried anything new anymore.

**Comment by dvorapa** [comment] 2019-10-08 18:51
I see. I switched from Ubuntu to anything supporting pure Gnome without loads of notworking extension shit similarly :D

**Comment by Sshahar** [comment] 2024-02-04 12:13
Ubuntu 22.04.3. Any solutions yet?
```
$ dconf dump /org/gnome/shell/extensions/dash-to-dock/
[/]
background-opacity=0.34999999999999998
dash-max-icon-size=48
dock-position='BOTTOM'
extend-height=false
height-fraction=0.90000000000000002
preferred-monitor=-2
preferred-monitor-by-connector='DP-1-0'
transparency-mode='FIXED'
```

**Comment by Humam-Hamdan** [comment] 2024-06-17 22:11
Ubuntu 24.04 LTS Gnome 46, crashing when awaking from sleep + when disabling/enabling/editing the extension.

**Comment by Unexp1ainable** [comment] 2024-09-20 10:35
Same here, looks like problem went away when I run
`gnome-extensions disable ubuntu-dock@ubuntu.com`
