### ISSUE TITLE
Can't make dock always visible over fullscreen windows

### ISSUE THREAD

**Issue by rafaelribeiroo** [micheleg/dash-to-dock#1726] opened 2022-04-29 18:32 UTC
I'm using Ubuntu 22.04 LTS a few weeks and doing some modifications at Wayland, I just want to know if there's one way to put dock-fixed in fullscreen mode without "push" windows up, like image below.

![image](https://user-images.githubusercontent.com/19275140/166004174-63d934a8-f8fa-4a20-adcb-64559346afd4.png)

**Comment by vanvugt** [comment] 2022-05-18 09:10
Feels like a bug to me. I would expect this to work:
```
gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false
gsettings set org.gnome.shell.extensions.dash-to-dock intellihide true
gsettings set org.gnome.shell.extensions.dash-to-dock intellihide-mode 'ALWAYS_ON_TOP'
gsettings set org.gnome.shell.extensions.dash-to-dock autohide false
gsettings set org.gnome.shell.extensions.dash-to-dock autohide-in-fullscreen false
```

**Comment by vanvugt** [comment] 2022-10-10 07:36
Duplicate of #1190

**Closed by vanvugt** 2022-10-10 07:36 UTC
