### ISSUE TITLE
org.gnome.Nautilus windows appear in Nautilus windows preview

### ISSUE THREAD

**Issue by Striffly** [micheleg/dash-to-dock#1644] opened 2022-01-18 23:44 UTC
Hi

Sometimes I got `org.gnome.Nautilus` windows who appear in previews.

![Screenshot from 2022-01-19 00-41-57](https://user-images.githubusercontent.com/13284087/150036423-96f7d142-6975-44c0-8a89-f6856b072527.png)

Even with a reinstallation of the plugin, or a reset of all settings via dconf, the problem remains.

- Arch Linux
- Dash to Dock version 71
- GNOME nautilus 41.2

**Comment by 3v1n0** [comment] 2022-01-21 01:07
Mh, would be interesting to have some more infos about the windows that are listed, could you maybe try to inspect it to figure out the properties?

I've the feeling those are marked `skip_taskbar`, but we don't ignore them...

**Comment by 3v1n0** [comment] 2022-01-21 04:04
Duplicate of #1629

**Closed by 3v1n0** 2022-01-21 04:04 UTC
