### ISSUE TITLE
Intelligent autohide feature doesn't work properly at login

### ISSUE THREAD

**Issue by franciscombaa** [micheleg/dash-to-dock#1938] opened 2023-02-27 18:35 UTC
Upon login, when an application covers the dock, it does not show up again by mouse hover on the screen edge. One fix is to disable and re-enable intelligent autohide.
[Video demo](https://user-images.githubusercontent.com/62038135/221651734-d0999301-09c6-47ea-a309-5b54dac45f13.webm)

**PS:** It may also be worth noting that the dock's theme also doesn't load properly, and only when opening an application does the proper (transparent) look apply.

**Comment by vanvugt** [comment] 2023-02-28 03:36
Duplicate of #1157

**Closed by vanvugt** 2023-02-28 03:36 UTC
