### ISSUE TITLE
Icon list isnt being refreshed after I open a new application or close?

### ISSUE THREAD

**Issue by davidv171** [micheleg/dash-to-dock#626] opened 2017-10-23 18:09 UTC
This is my current settings page:

https://i.imgur.com/Qzw7LiI.png

If I turn the Show running applications off then back on the Icon list refreshes. 

Any idea? 

16.04 Ubuntu. Downloaded from Gnome Extension Lists using my browser.

**Comment by micheleg** [comment] 2017-12-23 21:37
Hi,

sorry for the late reply. Are you still experiencing this issue? Does it happen with a specific application?

**Comment by dvorapa** [comment] 2018-03-05 08:39
Maybe a duplicate of #293?

**Comment by cunidev** [comment] 2018-06-09 17:16
Also experiencing this issue on Solus 3 GNOME

**Comment by micheleg** [comment] 2019-03-17 22:45
Closing as duplicated of #293

**Closed by micheleg** 2019-03-17 22:45 UTC
