### ISSUE TITLE
Problems with dots in dash

### ISSUE THREAD

**Issue by vladamarek** [micheleg/dash-to-dock#1778] opened 2022-07-22 10:51 UTC
After some recent upgrade dots in apps notification bar (dash) started to work wrong.

- Dots are placed into app icon directly
- There is only one dot for multiple instances of application

![image](https://user-images.githubusercontent.com/82888469/180423831-e4c4537d-d2ea-4fc4-8c0d-cd6b9201b707.png)

Observed with the Gnome 42.3 with the latest stable version of Manjaro distribution.

**Comment by maxborowsky** [comment] 2022-07-22 13:57
Dash to Dock -> Settings -> Appearance -> Customize windows counter indicator -> Dots
+ (Optional) Gear icon -> Use dominant color

With these settings, dot (or dots if multiple instances of the application are running) are shown to the _left_ of the application icon and does not merge with the icon.

This does not fix the simple default view, but it works as it should.

**Comment by vanvugt** [comment] 2022-07-26 01:47
Duplicate of #1757

**Closed by vanvugt** 2022-07-26 01:47 UTC
