### ISSUE TITLE
Overview windows behaving strange with dash on botton

### ISSUE THREAD

**Issue by marciosr** [micheleg/dash-to-dock#132] opened 2015-01-10 21:12 UTC
Using the new version of dash2dock with the extension workspace2dock the opened windows use a half of the horizontal screen space on the gnome-shell overview.
Using just dash2dock the overview works normally.
![captura de tela de 2015-01-10 18 48 02](https://cloud.githubusercontent.com/assets/1645395/5693260/428f260a-98fc-11e4-9421-9d52da0149f4.png)

**Comment by micheleg** [comment] 2015-01-10 21:19
This is a duplicate of issue #130 and it's due to the workspace to dock extensions still not supporting the bottom positioned dash. See also https://github.com/passingthru67/workspaces-to-dock/pull/29, which contain a temporary workaround.

**Closed** 2015-01-12 20:03 UTC
Labels: bug, duplicate
