### ISSUE TITLE
Dash to dock can prevent from moving mouse pointer between monitors

### ISSUE THREAD

**Issue by luispabon** [micheleg/dash-to-dock#930] opened 2019-04-23 10:13 UTC
Something on the intelligent auto-hide is causing trouble on multi monitor setups when an app goes full screen 

Steps to reproduce:
  * Have 2+ monitors, one to the left of the other
  * Enable d2d
  * Set to appear "left"
  * Set to appear in all monitors
  * Enable intelligent autohide - leave in default settings

At this point, so far so good. You can move your mouse pointer between both screens no problem. Continue:

  * Open an app that can go full screen (eg Firefox) and place it on the left monitor
  * Make it go full screen

At this point, you'll be able to move the mouse pointer from monitor left to monitor right, but then pointer is trapped in monitor right. It cannot cross the boundary between right and left monitor in that direction. This is permanent, until you disable intellihide in d2d or disable the extension (un-full-screening the example app won't fix it).

On a three monitor setup where the third one is below, you can move the pointer to the monitor below then from there to the monitor on the left.

**Comment by luispabon** [comment] 2019-04-23 10:15
This is in Pop 19.04. Another laptop running Ubuntu 19.04 shows the same issue with ubuntu's version of d2d.

**Comment by luispabon** [comment] 2019-04-23 10:18
Problem doesn't occur with "push to show" disabled, but that makes it really difficult to bring up the doc on the right monitor.

**Comment by luispabon** [comment] 2019-04-23 10:22
Weird thing. The problem doesn't re-occur after re-enabling "push to show", or at least not so far. Obvs this option is not available on ubuntu's version of the dock.

**Comment by micheleg** [comment] 2019-04-26 11:15
Thank you for your bug reports. The problem originate from the barrier for the mouse we need to place in order to capture the pressure (that's why if you disable pressure the problem disappears). In principle, the barrier is removed when the dock is shown after enough pressure is applied (not optimal, but at least this frees the mouse pointer and I haven't found a better implementation). It look like the barrier was placedin a situation when the dock will never be shown (fullscreen), so the mouse is never freed. It's probably a bug (resettintgthe push to show option might just temporary reset the state). 

Can you confirm the problem is (deterministically) reproducible with the steps above?

**Comment by micheleg** [comment] 2019-04-26 11:17
I believe this is the same bug (#743), thus closing this as duplicate.

**Closed** 2019-04-26 11:18 UTC
Labels: duplicate

**Comment by luispabon** [comment] 2019-04-26 11:38
Looks like it's the same problem :+1: to answer your question, @micheleg, yes it's 100% reproducible.
