### ISSUE TITLE
New Feature: click action -> present all windows of a running application

### ISSUE THREAD

**Issue by dmarrazzo** [micheleg/dash-to-dock#304] opened 2016-04-06 12:56 UTC
I have seen this feature on Unity and I found it quite cool and efficient.
When a running application has many open windows, if you click on the dash icon you will get an overview of all windows for that application.

**Comment by micheleg** [comment] 2016-04-07 19:10
Yes, this is something I have been wondering for a while, but without satisfactory results. I'm closing this issue as it is a duplicate of #216.

**Closed by micheleg** 2016-04-07 19:10 UTC
Labels: duplicate
