### ISSUE TITLE
[Feature Request] Open application upon Drag-n-Drop onto Dock

### ISSUE THREAD

**Issue by PJ-Singh-001** [micheleg/dash-to-dock#1378] opened 2021-01-27 15:54 UTC
When a file is dragged-and-dropped onto an icon in the dock, (attempt to) open the file in the application represented by the dock icon.

For example,...
1. If I drag  my_file.txt file onto Gedit in the dock, Gedit should open and display the contents of my_file.txt.
2. If I drag  my_file.txt file onto Libreoffice Writer in the dock, Libreoffice Writer should open and display the contents of my_file.txt.
3. If I drag  my_file.txt file onto Image Viewer in the dock, Image Viewer should open. Since  Image Viewer can not handle text files, it should use its own application specific behavior when an unrecognized file is opened. (In this case, Image Viewer displays a message "Could not load image ...").

**Comment by vanvugt** [comment] 2022-11-28 09:43
Duplicate of #49

**Closed by vanvugt** 2022-11-28 09:43 UTC
