### ISSUE TITLE
Manjaro Linux_Gnome 40.2.0_X - error on open settings dash-to-dock

### ISSUE THREAD

**Issue by Zappo-II** [micheleg/dash-to-dock#1477] opened 2021-07-14 08:24 UTC
```
Error: GSettings key preview-size-scale not found in schema org.gnome.shell.extensions.dash-to-dock

Stack trace:
  _checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:563:23
  createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:515:30
  _bindSettings@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:545:81
  _init@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:219:14
  buildPrefsWidget@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:1013:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  ```

**Comment by nhu** [comment] 2021-07-14 11:53
I guess #1475 is the same

**Comment by Zappo-II** [comment] 2021-07-14 11:55
Shure, but that one explicitly states `wayland`...

**Comment by rgelber** [comment] 2021-07-14 16:40
I'm having the same issue with X11. 
![image](https://user-images.githubusercontent.com/33894087/125659893-9293572c-3168-4fff-b9e2-9dbd4bc82348.png)
the-overlord ~> echo $XDG_SESSION_TYPE
x11

**Comment by peter-kehl** [comment] 2021-07-14 23:02
I confirm this issue on the newest Manjaro, x64, GNOME 40.2.0, X11.
However, my error stack trace (as shown in "Extensions" application) is slightly different:
```
Gtk.BuilderError: /home/pkehl/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/Settings.ui:13:35 Invalid property: GtkBox.margin_left

Stack trace:
  DashToDock_Settings@/home/pkehl/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:92:23
  buildPrefsWidget@/home/pkehl/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:869:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  ```

**Comment by Raj-Joshi-dev** [comment] 2021-07-15 07:05
Try this : https://forum.manjaro.org/t/dash-to-dock-fails-and-default-desktop-view-changed-after-the-update/73521/19

**Comment by Zappo-II** [comment] 2021-07-15 09:15
> Try this : https://forum.manjaro.org/t/dash-to-dock-fails-and-default-desktop-view-changed-after-the-update/73521/19

Fixed it for me...THXALOT...

**Comment by peter-kehl** [comment] 2021-07-19 23:01
Over the last few days I received two updates of this extensions, both over Manajaro package manager (and not through Chrome) - thank you. However, I still get the same/similar error as I've reported above.

**Comment by pathummd** [comment] 2021-08-20 14:18
> Try this : https://forum.manjaro.org/t/dash-to-dock-fails-and-default-desktop-view-changed-after-the-update/73521/19

this fixed my issue. Reboot the system after done this

**Comment by ewlsh** [comment] 2021-10-05 05:02
Duplicate of #1475

See https://github.com/micheleg/dash-to-dock/issues/1475#issuecomment-880138403

**Closed by ewlsh** 2021-10-05 05:02 UTC
