### ISSUE TITLE
panel mode - clock on right

### ISSUE THREAD

**Issue by wareczek** [micheleg/dash-to-dock#430] opened 2017-01-10 12:52 UTC
I have hidden top bar and only dash as panel on bottom of screen. What you think about putting clock in right side of panel?

![screenshot from 2017-01-10 13-48-21](https://cloud.githubusercontent.com/assets/1897839/21806764/8dae6428-d73b-11e6-91fd-fb92eea856af.png)

**Comment by fastrizwaan** [comment] 2017-01-10 14:56
You may try github.com/jderose9/dash-to-panel it makes the dash look and behave like windows 7/10

**Comment by micheleg** [comment] 2017-01-10 20:44
I recommend checking out the dash-to-panel extension, as it might fit your needs. Such functionality has been considered in the past. Closing as duplicate of #247.

**Closed by micheleg** 2017-01-10 20:44 UTC
Labels: duplicate
