### ISSUE TITLE
Launch using dedicated graphics not working on Pop-os 20.04

### ISSUE THREAD

**Issue by roboknight5** [micheleg/dash-to-dock#1219] opened 2020-05-12 23:28 UTC
Hello i have an issue with hybrid graphics in Pop-os 20.04 theError logs are`JS ERROR: Error: Expected type enum for Argument 'discrete_gpu' but got type 'booleanWindow manager warning: Invalid WM_TRANSIENT_FOR window 0x4600005 specified for 0x4600225.
JS ERROR: Error: Expected type enum for Argument 'discrete_gpu' but got type 'boolean'
_rebuildMenu/<@/home/mohamed/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIcons.js:828:42
activate@resource:///org/gnome/shell/ui/popupMenu.js:191:14
vfunc_button_release_event@resource:///org/gnome/shell/ui/popupMenu.js:138:14`
and thank you in advance

**Comment by roboknight5** [comment] 2020-05-13 00:01
i think i found a fix in appIcons.js line 828 this._source.app.launch(0, -1, true); change true to 1 this._source.app.launch(0, -1, 1); i am not sure if this a proper fix but it worked for me

**Comment by vanvugt** [comment] 2024-10-09 09:25
Duplicate of #1102

**Closed by vanvugt** 2024-10-09 09:25 UTC
