### ISSUE TITLE
Dock pops up if mouse is brought to the edge of the screen when in full screen and auto-hide enabled.

### ISSUE THREAD

**Issue by nose-gnome** [micheleg/dash-to-dock#2060] opened 2023-07-19 15:02 UTC
When you have auto-hide enabled and you're in a full screened application and you drag your mouse to the corner of the screen that the dock is set to, it will pop up, overlapping the full-screened content.

This is not so much a problem for watching videos/films but it happens while in full screened video games as well, which is annoying and stops also stops the game from receiving mouse directional input when the dock is up, and can make the user accidentally open an application mid game.

It seems to sometimes act differently depending on how the application is full screened: sometimes the dock only appears for a seconds and disappears before appearing again and repeating, other times it just appears and doesn't go away until you move your mouse up, which is distracting and makes it hard to look down in video games.

To remedy this, I think it would be a good idea to make it so that the dock does not show itself when in full screen at all.

**Comment by vanvugt** [comment] 2023-07-20 03:37
Duplicate of #1381

**Closed by vanvugt** 2023-07-20 03:37 UTC
