### ISSUE TITLE
Bug with the extension

### ISSUE THREAD

**Issue by vdsvinicius** [micheleg/dash-to-dock#1862] opened 2022-10-21 20:21 UTC
Hello

Just feedbacking some bug error

--

The settings of extension dash-to-dock@micxgx.gmail.com had an error:
```
GLib.FileError: Falha ao abrir arquivo “/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas/gschemas.compiled”: open() falhou: Arquivo ou diretório inexistente
```

Stack trace:
```
getSettings@resource:///org/gnome/Shell/Extensions/js/misc/extensionUtils.js:200:31
_init@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:191:45
DashToDock_Settings@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:185:4
buildPrefsWidget@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:1116:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:32:44
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
--

Thanks

**Comment by vanvugt** [comment] 2022-10-24 06:34
Duplicate of #1170

**Closed by vanvugt** 2022-10-24 06:34 UTC
