### ISSUE TITLE
Entire shell crashes after attempting to lock or switch user in shell overview

### ISSUE THREAD

**Issue by someone2639** [micheleg/dash-to-dock#2251] opened 2024-07-08 15:13 UTC
Narrowed down to this extension, reports as version 92, installed as AUR package `aur/gnome-shell-extension-dash-to-dock 1:92-1`. I can show my extension settings if it's possible to export those to a file.

Steps to reproduce:
- Open Overview menu with any method (I have tried Super key, touchpad gesture, top left overview button)
- Lock the system with any method (I have tried Meta+L, selecting Lock or Switch User from the top right panel)
- GNOME should crash and put you back on the login screen

dmesg output:
```
[176705.264462] gnome-shell[105469]: segfault at 30 ip 00007e90ad15a4f0 sp 00007ffed5ff5c40 error 4 in libst-14.so[7e90ad129000+6f000] likely on CPU 12 (core 6, socket 0)
[176705.264481] Code: ad 20 ff ff ff 0f 84 e5 06 00 00 48 8b 85 68 ff ff ff 48 8b b5 30 ff ff ff 48 8b 80 28 01 00 00 4a 8b 1c 28 48 8b 03 48 8b 00 <48> 8b 38 ff 15 7f 24 06 00 85 c0 75 c3 4c 8b 63 08 4d 85 e4 74 ba
```
(note that the likely CPU is not constant between invocations of the crash)

journalctl output:
[journal.txt](https://github.com/user-attachments/files/15875384/journal.txt)

**Comment by sergio-costas** [comment] 2024-07-08 15:17
This seems related to https://github.com/micheleg/dash-to-dock/issues/2179 There's a patch for upstream.

**Comment by vanvugt** [comment] 2024-07-09 01:47
Duplicate of #2179.

The proposed fix is https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3252

**Closed by vanvugt** 2024-07-09 01:47 UTC
