### ISSUE TITLE
Crashed after latest system updates

### ISSUE THREAD

**Issue by a-wakeel** [micheleg/dash-to-dock#1944] opened 2023-02-28 05:58 UTC
I am using **Manjaro Gnome** and after some latest system updates (probably gnome extensions related) the dash to dock crashed. I have the Gnome version **43.3**.

**Error that i get:** _this._launchMaxWaitIds is undefined_

**Comment by a-wakeel** [comment] 2023-02-28 06:26
Looks like this has been fixed in https://github.com/micheleg/dash-to-dock/commit/668f7ce557d9ada9bd06a3b783e56bfb9edae8b7 So Please close this (or i will do) when v78 is released to extensions.

**Comment by vanvugt** [comment] 2023-02-28 06:41
Duplicate of #1935.

**Closed by vanvugt** 2023-02-28 06:41 UTC
