### ISSUE TITLE
Blur effect on dock (effect added to Mutter recently)

### ISSUE THREAD

**Issue by patrykbajos** [micheleg/dash-to-dock#1146] opened 2020-03-30 08:21 UTC
Hi,

As said at https://blogs.gnome.org/shell-dev/2020/02/07/this-month-in-mutter-gnome-shell-december-2019-january-2020/ there are added effects to Mutter. Also blur effect on lock screen was added in GNOME 3.36. Recently the main obstacle to add this effect to dock was lack of support in Mutter (request in 2017) but now there is support. So is there a slightest chance to see this effect in future release of dash-to-dock?

**Comment by rmader** [comment] 2020-04-03 13:57
Unfortunately this blur effect can not be used for what you are asking. I talked to feaneron whether it would work for the top-bar, which I guess would be the same use case, and he said it can only be used to blur the *content* of an actor, not the *background*.

**Comment by patrykbajos** [comment] 2020-04-05 15:14
Hm... If blurring background of window is impossible what about directly setting content of dock as part of wallpaper (the part behind dock) and blurring it?

**Comment by sbsbs15** [comment] 2020-04-06 17:31
It seems that Blyr extension supports blurring for the top-bar with the new native shell effect, maybe his code could be useful https://github.com/yozoon/gnome-shell-extension-blyr/commit/6eb7aee909ef5bf683af7d2518825481776c1b2b

**Comment by rmader** [comment] 2020-04-06 18:34
> It seems that Blyr extension supports blurring for the top-bar with the new native shell effect, maybe his code could be useful [yozoon/gnome-shell-extension-blyr@6eb7aee](https://github.com/yozoon/gnome-shell-extension-blyr/commit/6eb7aee909ef5bf683af7d2518825481776c1b2b)

Apparently the has been talk about that before: https://github.com/yozoon/gnome-shell-extension-blyr/issues/8#issuecomment-391074728

**Comment by vanvugt** [comment] 2022-09-01 06:29
Duplicate of #224

**Closed by vanvugt** 2022-09-01 06:29 UTC
