### ISSUE TITLE
White Trash Icon Border when Trash is Full

### ISSUE THREAD

**Issue by tootbrute** [micheleg/dash-to-dock#1820] opened 2022-09-16 08:16 UTC
When trash is empty it looks like this. (all good)

When trash is full it looks like this (weird border)
![Screenshot from 2022-09-16 16-14-22](https://user-images.githubusercontent.com/47593393/190590648-9f4b39c5-86ef-4a74-b986-108e7f583638.png)

This happens with Dash to Dock and Cosmic Dash to Dock. This is on Fedora 36 with GNOME.
![Screenshot from 2022-09-16 16-14-34](https://user-images.githubusercontent.com/47593393/190590668-65376584-91ec-4e74-824b-6a27ff87fe43.png)

Anybody else having this problem? How can I troubleshoot it?

**Comment by vanvugt** [comment] 2022-09-19 07:38
Duplicate of #1772

**Closed by vanvugt** 2022-09-19 07:38 UTC
