### ISSUE TITLE
Dash to dock showing a ghost/empty firefox window

### ISSUE THREAD

**Issue by codevski** [micheleg/dash-to-dock#1652] opened 2022-01-23 00:28 UTC
It seems like dash to dock is showing a ghost / empty firefox window when you click on show all windows. Gnome top bar doesn't show it so I have a feeling it might be related to dash to dock?.

System info:
   OS: Arch Linux x86_64 
  Kernel: 5.16.2-arch1-1 
  DE: GNOME 41.3
  
Dash to dock:
![Screenshot from 2022-01-23 11-20-55](https://user-images.githubusercontent.com/1435321/150659879-19f9e2ae-a121-4dd0-bcb8-b68b5e25c0e6.png)

Gnome top bar:
![Screenshot from 2022-01-23 11-21-17](https://user-images.githubusercontent.com/1435321/150659882-c1e06f69-12b2-4d78-8de6-cd887c05b108.png)

**Comment by somepaulo** [comment] 2022-01-23 15:10
Same here, but not only Firefox, Files (Nautilus) as well. Haven't noticed it with other apps.

![Screenshot from 2022-01-23 18-00-13](https://user-images.githubusercontent.com/15643750/150684934-57abfc72-43bd-4a9f-87ab-59b9888cfa58.png)

![Screenshot from 2022-01-23 18-01-29](https://user-images.githubusercontent.com/15643750/150684989-b659852e-b922-43ce-b99c-87f3755071bf.png)


Closing the only actual window leaves the ghost windows hanging in the icon until you open the overview.

![Screenshot from 2022-01-23 18-03-43](https://user-images.githubusercontent.com/15643750/150685026-33161dcf-825c-40ad-82eb-079262e6f56e.png)


Also, it doesn't happen with the original Gnome dash.

![Screenshot from 2022-01-23 18-02-37](https://user-images.githubusercontent.com/15643750/150685034-e74a3d2d-5f05-4c39-876f-46fcfec15e95.png)

**Comment by noumanmhd** [comment] 2022-01-24 15:06
I have the same issue on Fedora 35 as @somepaulo  described...

**Comment by shinyvision** [comment] 2022-01-24 19:55
Same here with Nautilus. Tried switching to Pcmanfm GTK3, but the same problem occurs when using that program, so I'm assuming this is a problem with Dash to dock.

![nautilus](https://user-images.githubusercontent.com/12270626/150854717-9f84d088-cc9d-4050-b302-64b4fc3f5926.png)

**Comment by shinyvision** [comment] 2022-01-24 20:14
Update: this seems to have been fixed in the master branch. It should work if you build the extension from source.

@noumanmhd @somepaulo @codevski FYI

**Comment by hmlendea** [comment] 2022-01-25 18:23
Same on Arch Linux. Worked fine on GNOME 38 before updating it (yeah, I held off for a while).

**Comment by GeoffreyCoulaud** [comment] 2022-01-25 23:20
Yup, this was fixed by MR #1637 and this issue is a duplicate of #1629.
If this bug bothers you, please build the extension from source, or wait for the gnome extensions site / youyr distro's packages to be updated.

**Comment by 3v1n0** [comment] 2022-01-26 04:11
Dulicate of #1629

**Closed by 3v1n0** 2022-01-26 04:11 UTC
