### ISSUE TITLE
Feature Request: Add Desktop & Trash Icon

### ISSUE THREAD

**Issue by Saurav92** [micheleg/dash-to-dock#356] opened 2016-08-08 04:46 UTC
Please add a Desktop & Trash icon which can be enabled optionally. On clicking desktop icon the desktop will show, minimize all the open windows. Note this is not the Desktop **folder**. And user can enable them optionally.

**Comment by zapashcanon** [comment] 2016-08-08 07:12
Hi,

- "Trash icon" is a duplicate of #173...
- What do you mean by "Desktop icon" ?
- I'm not sure, but the show application icon is not set by the extension.

You also probably should open one issue for each feature request, it's easier to track.

**Comment by Saurav92** [comment] 2016-08-08 13:02
Hi I created separate issue. And explained what is desktop icon.

**Comment by zapashcanon** [comment] 2016-08-08 18:56
Thanks. :)

The Trash icon request is a duplicate as I already said. You maybe could remove this from this issue ?

For the desktop icon, there's some extensions doing it already (e.g. [show-desktop-button on GNOME website](https://extensions.gnome.org/extension/64/show-desktop-button/) and it's on [GitHub](https://github.com/l300lvl/Show-Desktop-Button) too.)

But maybe @micheleg will implement it in dash-to-dock too. :)

**Comment by micheleg** [comment] 2016-08-08 21:13
Show desktop is also a duplicate of #163. There's a possible workaround following https://github.com/micheleg/dash-to-dock/issues/158#issuecomment-109706606. You can create a desktop file for the show desktop shortcut and add it to your favorites. (also see http://askubuntu.com/a/29988).

Closing as duplicate.

**Closed by micheleg** 2016-08-08 21:13 UTC
