### ISSUE TITLE
shadow beside th dock

### ISSUE THREAD

**Issue by rudrab** [micheleg/dash-to-dock#1436] opened 2021-05-08 06:43 UTC
Hi,
there is a shadow around the dash, with straight corner. Kindly have a look at it. 
The screenshot is attached: 
https://drive.google.com/file/d/1wDtx4owknpqLI81WYC8lnvli_qWfkbFn/view?usp=sharing

**Comment by vanvugt** [comment] 2022-09-20 05:54
Since there's no useful screenshot here anymore...

Duplicate of #1623

**Closed by vanvugt** 2022-09-20 05:54 UTC
