### ISSUE TITLE
Customising the Applications icon

### ISSUE THREAD

**Issue by nlpsuge** [micheleg/dash-to-dock#997] opened 2019-09-24 11:43 UTC
Can you please add a feature of customising the Applications icon? 

I find the default icon of this one ![image](https://user-images.githubusercontent.com/2271720/65508637-38a8e700-df03-11e9-888a-dc485a4dc247.png) is boring. I hope to set up a new icon.

**Comment by mdragossh** [comment] 2019-10-02 18:17
you can set an icons over old one by editing gnome-shell.css 

.show-apps .show-apps-icon {
  color: white;
  background-image: url("new_icon_folder/my_new_icon.svg");
  background-size: contain;
}

**Comment by nlpsuge** [comment] 2019-10-03 02:40
@mdragossh 

Thanks, I'll try it.

But it should be overridden after the updating of gnome-shell.

**Comment by micheleg** [comment] 2019-11-02 22:30
duplicate of #472.

**Closed by micheleg** 2019-11-02 22:30 UTC
Labels: duplicate, question
