### ISSUE TITLE
Somthing's gone wrong (Kernel: 5.12.19-1-MANJARO, GNOME 40.4)

### ISSUE THREAD

**Issue by CRY-D** [micheleg/dash-to-dock#1525] opened 2021-09-28 13:52 UTC
- I don't know why i got this little Exclamation mark after updating manjaro?

![DeepinScreenshot_select-area_20210928144605](https://user-images.githubusercontent.com/16564491/135099844-2e1c435d-686d-4b36-a555-fd372e9e0077.png)

- and when i click the setting button this stack-trace appear.

![Screenshot-20210928144150-855x711](https://user-images.githubusercontent.com/16564491/135100344-d70bfa3d-0530-413d-aa58-29a4fa9f724e.png)

**Comment by henrik-wittenberg** [comment] 2021-09-29 17:03
I'm getting the same error message (Manjaro Gnome 40.4 with 5.14 Kernel) under "Technical Details" when I click on the settings:

![image](https://user-images.githubusercontent.com/56762401/135315346-a8f2851a-2dfa-4cb7-ade5-1699f98a80d6.png)

Only the symbol being displayed in the extension app is different for me:

![image](https://user-images.githubusercontent.com/56762401/135315631-b7a52959-dbf3-4377-8c65-98347ecdd3bc.png)

**Comment by kamikazestar** [comment] 2021-09-29 20:23
OS: Manjaro
OS type: 64-bit
Gnome version: 40.4.0
Windowing system: X11

Expected behavior: After the left mouse button click on 'Show Application'  and 'Dash to Dock Settings' I should be able to open the window with Dash to Dock settings.


Current behavior: Instead of the Dash to Dock settings window, there's information that something went wrong as on the attached screenshot.
![Screenshot from 2021-09-29 22-13-09](https://user-images.githubusercontent.com/8329080/135341873-fb8f43b1-c172-437b-85fe-eb55644ce01c.png)

Error message:
```
The settings of extension dash-to-dock@micxgx.gmail.com had an error:
Error: GSettings key preview-size-scale not found in schema org.gnome.shell.extensions.dash-to-dock

Stack trace:
_checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:563:23
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:515:30
_bindSettings@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:545:81
_init@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:219:14
buildPrefsWidget@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:1013:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
Extension state: Working, but unable to change any settings of the Dash to Dock.

**Comment by ewlsh** [comment] 2021-10-05 04:41
There are multiple errors here, I would report to Manjaro's packager first given these seem related to the installation of Dash to Dock's schema file.

**Comment by ewlsh** [comment] 2021-10-05 04:54
Possible Duplicate of #1475

See https://github.com/micheleg/dash-to-dock/issues/1475#issuecomment-880138403

**Closed** 2021-10-05 14:12 UTC
Labels: downstream

**Comment by kamikazestar** [comment] 2021-10-15 19:44
Update:

During my attempts to fix this issue, I'd realized that there's a missing directory called ```dash-to-dock@micxgx.gmail.com``` in path ```$HOME/.local/share/gnome-shell/extensions```. 

I decided to re-install dash-to-dock from the source using the official Dash to Dock installation [website](https://micheleg.github.io/dash-to-dock/download.html). After reinstallation problem was still appearing, but the directory was present in the path. I'd log out and log in, and after that, dash-to-dock was working as expected, and the error that id reported above dissipated.

I hope that this will help someone.

**Comment by philmmanjaro** [comment] 2021-12-11 00:32
We are now removed the pre-compiled file via: https://gitlab.manjaro.org/packages/community/gnome/gnome-shell-extension/-/commit/799a315711f1c81ee7929a202491f65981bb0025. We also had to remove the override of the schema: https://gitlab.manjaro.org/packages/community/gnome/gnome-settings/-/commit/1940be6f9e54e81f4aa1c398df00f706edb18f1b
