### ISSUE TITLE
Dash to Dock crashes GNOME when entering the lock screen from the overview

### ISSUE THREAD

**Issue by Aethersan** [micheleg/dash-to-dock#2234] opened 2024-06-20 10:17 UTC
Steps to reproduce:
1. Activate Dash to Dock
2. Enter the Overview
3. Press Control + L to enter the lock screen
- GNOME crashes and restarts

![Screenshot](https://github.com/micheleg/dash-to-dock/assets/155457202/8ae3231f-9686-4486-8277-05663a366f2c)

**Comment by vanvugt** [comment] 2024-06-21 05:07
Duplicate of #2179

**Closed by vanvugt** 2024-06-21 05:07 UTC
