### ISSUE TITLE
Extra non theme "Active foreground app dot" in dock

### ISSUE THREAD

**Issue by whnr** [micheleg/dash-to-dock#776] opened 2018-07-24 14:50 UTC
Gnome 3.28
Archlinux
Dash-to-dock 63

The active app has an extra highlight dot on the right for me. In an older version (with a 3.26 shell I think) It behaved correctly. You can also see, that the windowcounter is below the colored dots as well as a little white dot.

![bildschirmfoto von 2018-07-24 16-32-00](https://user-images.githubusercontent.com/8114817/43145745-529f4bb8-8f4f-11e8-91dd-ac2910018e35.png)

**Comment by micheleg** [comment] 2018-07-29 15:30
Hi, thats probably due to the theme you are using. Can you check with different themes? If the theme is the cause of the problem, your options are: 
1. disabling the extension provided dots
2. changing theme
3. contacting the theme author and ask/help providing explicit support for dash to dock.

**Comment by whnr** [comment] 2018-07-29 19:09
It seems to be the materia theme. Before I only tried changing the app-theme. But it was the shell theme that is causing the dot.
See: https://github.com/nana-4/materia-theme/issues/270

**Comment by micheleg** [comment] 2018-07-29 20:11
Closing then, as it's not an issue on our side.

**Closed by micheleg** 2018-07-29 20:11 UTC
