### ISSUE TITLE
Can't open DTD settings

### ISSUE THREAD

**Issue by handicraftsman** [micheleg/dash-to-dock#268] opened 2015-12-21 18:53 UTC

**Comment by micheleg** [comment] 2015-12-22 15:47
This is aknown issue caused by a bug in librsvg, Have a look at #262. Closing as duplicate.

**Closed by micheleg** 2015-12-22 15:47 UTC
Labels: duplicate

**Comment by handicraftsman** [comment] 2015-12-23 14:02
librsvg2-2 is already the newest version (2.40.12-1).
librsvg2-2 set to manually installed.

**Comment by micheleg** [comment] 2015-12-23 17:04
You can now update to the master branch and the bug should be solved. You will still have to wait for an updated library, but the extension should not be affected any more.

**Comment by handicraftsman** [comment] 2015-12-23 20:29
Thanks for fixing
