### ISSUE TITLE
Lock screen crashes the Dock. "DockManager.getDefault() is null. dockManager is null"

### ISSUE THREAD

**Issue by muhammetsafak** [micheleg/dash-to-dock#2300] opened 2024-09-28 04:21 UTC
Hi, the Dock crashes when I lock and unlock the screen. There are many error messages in the `journalctl` output.

```
JS ERROR: TypeError: dockManager is null
                                            getApps@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:1447:9
                                            getRunningApps@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:1460:12
                                            _ensureLocations/<@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/docking.js:1847:56
                                            _create/object[name]@file:///usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/utils.js:326:37
                                            _ensureLocations/<@file:///home/muhammet/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1851:60
                                            _create/object[name]@file:///home/muhammet/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/utils.js:358:37
                                            _syncRunningApplications@resource:///org/gnome/shell/misc/introspect.js:75:36
                                            IntrospectService/<@resource:///org/gnome/shell/misc/introspect.js:37:18
                                            @resource:///org/gnome/shell/ui/init.js:21:20
```

![Screenshot from 2024-09-28 07-20-08](https://github.com/user-attachments/assets/a66306d5-580b-48f9-8976-3b94090b08f4)

**Comment by Neo-29** [comment] 2024-09-28 11:17
This is confirmed on archlinux here too
It gets stuck for a while then goes back to lock screen

**Comment by vanvugt** [comment] 2024-10-01 01:56
Duplicate of #1992

**Closed by vanvugt** 2024-10-01 01:56 UTC
