### ISSUE TITLE
Intelligent hide - dock on primary monitor remains hidden even when no window is covering the dock

### ISSUE THREAD

**Issue by traek728** [micheleg/dash-to-dock#1847] opened 2022-10-07 22:50 UTC
I'm experiencing an issue with multiple monitors that seems to effect just about any configuration of intelligent hide I have tested.  When I have an application open, for example gnome terminal, on multiples monitors, if I select an open window preview by clicking on an open app with multiple windows on the dock, the dock hides on the primary monitor regardless of what window I select, or what monitor that window is on.  Once this happens, the dock on the primary monitor remains hidden until I grab a window (any window) on the primary monitor and cover/uncover the dock before it will come back.  I see this behavior any time I have multiple instances of an app across multiple monitors - the dock disappears from the primary monitor as soon as you select a window from the window preview list on the dock.

Difficult bug to describe, so I apologize if this is a confusing description.  I've seen similar issues reported for users with multiple monitors, but even with the intended function of intelligent hide, it seems it should not require this for the dock to reappear on the primary monitor.

Thank you for the awesome extension - I couldn't live without it!

**Comment by traek728** [comment] 2022-10-07 23:16
I should clarify that using the mouse show the dock when it is hidden in this situation will show the dock, but it will immediately hide again as soon as the mouse moves off of the dock.  As mentioned above, the only way to get the dock to remain on the primary display when no windows are covering it, is to drag any window over the dock to make it re-appear and it will remain on the primary monitor after uncovered by that window from that point forward, until, of course, you select something on a separate monitor from the dock on the primary monitor once again.

**Comment by 3v1n0** [comment] 2022-10-13 19:22
Duplicate of #1769

**Closed by 3v1n0** 2022-10-13 19:22 UTC
