### ISSUE TITLE
Not compatible with GNOME Shell 44, again

### ISSUE THREAD

**Issue by OlegKrikun** [micheleg/dash-to-dock#1948] opened 2023-02-28 11:34 UTC
After the last update of `gjs` this extension stopped working.

```
VFunc get_id returns a transfer-none string. This is not supported (https://gitlab.gnome.org/GNOME/gjs/-/issues/519)
```

Gnome 44.beta
gjs 1.75.2
Arch Linux

**Comment by vanvugt** [comment] 2023-03-01 01:50
Duplicate of #1919

**Closed by vanvugt** 2023-03-01 01:50 UTC
