### ISSUE TITLE
(Option) Show dock instantly when pushing your mouse into the site

### ISSUE THREAD

**Issue by rugk** [micheleg/dash-to-dock#369] opened 2016-09-02 19:11 UTC
There should at least be an option to make the dock behave similar to the "overview" top-left corner.
When you push your mouse into the corner it is always shown instantly without any timeout.
This dock does not honour this and still seems to apply the usual timeout until it is shown.

This option is e.g. present in workspaces-to-dock.

**Comment by micheleg** [comment] 2016-09-03 22:23
By timeout do you mean delay before the sart of the animation or actual animation duration? Either case, I don't see any of this delay. Can you please elaborate further?

**Comment by micheleg** [comment] 2016-09-03 22:31
I think this was actually fixed by https://github.com/micheleg/dash-to-dock/commit/42ee3eca48663d5ec858ce114d8a0eb267caf8d7

Unfortunately the fix is not in the released version yet. Can anybody try current master and confirm if the problem disappear?  I will try to make a release soon, as 3.22 is also approaching.

**Comment by franglais125** [comment] 2016-09-05 17:03
I tried to reproduce the issue and see if master fixes it, however I don't fully understand what the issue is: the dock is shown with no delay. The only delay is the "show" animation itself, but there is no timeout.
I tested:
- version 51 on Gnome 3.14
- version 53 on Gnome 3.20
- master on Gnome 3.20

In all 3 cases I saw no difference in behavior when triggering the overview.

@rugk : I installed workspaces-to-dock and again I see no difference to dash-to-dock's behavior. Would you mind posting a screenshot of the option you are using?

**Comment by rugk** [comment] 2016-09-05 20:42
It is quite subjective, but I see that there seems to be a timeout somehow.

But when you e.g. move your mouse a bit away and then speed it up "crashing" against the screen border I really feel as if there is a 0.5 sec delay or so. At least I do not notice it in other docks (e.g. "Docky").

Here is a screencast:
[Timeout.webm.zip](https://github.com/micheleg/dash-to-dock/files/455603/Timeout.webm.zip)

Maybe you can look at it picture by picture and you'll see that my mouse hovers a short time at the border and nothing happens.

**Closed** 2018-06-10 08:58 UTC
Labels: invalid
