### ISSUE TITLE
Option to switch between rounder and straight coners

### ISSUE THREAD

**Issue by gayanper** [micheleg/dash-to-dock#407] opened 2016-11-24 14:44 UTC
Its better to provide a option to switch between rounded and straight coners for dash. In some environments with themes the coner backgrounds are shown as black which looks ugly on a light wallpaper.

**Comment by zapashcanon** [comment] 2016-11-24 19:57
Hi,

Seems like a duplicate of #378.

**Closed** 2016-11-25 04:44 UTC
