### ISSUE TITLE
Dock persists on lock screen

### ISSUE THREAD

**Issue by ningacoding** [micheleg/dash-to-dock#762] opened 2018-06-27 20:09 UTC
Ussing: NOME Shell 3.28.1 (ubuntu-communitheme mode)
GTK+ 3.22.30

![image](https://user-images.githubusercontent.com/17342546/41996820-ae8acaae-7a1b-11e8-882e-f3157c4d9b30.png)

The configuration is "show at the bottom of screen" but showing also a dock in the left side of screen.

**Comment by scurrvy2020** [comment] 2018-06-29 12:52
Same issue here, only seems to happen after suspend for me.

**Comment by scurrvy2020** [comment] 2018-06-29 13:07
I think this is a duplicate of https://github.com/micheleg/dash-to-dock/issues/739

**Comment by ningacoding** [comment] 2018-06-29 14:58
Thank you @scurrvy2020 , after trying to replicate "happen after suspend for me", i noticed that dock persists in lock screen:

![image](https://user-images.githubusercontent.com/17342546/42099371-dbe77b38-7b82-11e8-8d6b-c075afaeec5d.png)

**Comment by betsegaw** [comment] 2018-07-01 23:35
Is there any progress on this issue?

**Comment by alex-q** [comment] 2018-07-10 15:05
Same issue.
Ubuntu 18.04 LTS, Gnome 3.28.1.
```
$ dconf dump /org/gnome/shell/extensions/dash-to-dock/
[/]
autohide-in-fullscreen=false
animate-show-apps=true
shift-click-action='minimize'
shift-middle-click-action='launch'
extend-height=false
dock-fixed=false
force-straight-corner=false
click-action='previews'
intellihide-mode='FOCUS_APPLICATION_WINDOWS'
show-apps-at-top=false
max-alpha=0.80000000000000004
multi-monitor=true
scroll-action='do-nothing'
show-show-apps-button=true
require-pressure-to-show=true
apply-custom-theme=false
dock-position='BOTTOM'
custom-theme-shrink=false
icon-size-fixed=false
running-indicator-style='DASHES'
dash-max-icon-size=64
middle-click-action='launch'
preferred-monitor=0
transparency-mode='ADAPTIVE'
```

**Comment by scurrvy2020** [comment] 2018-07-10 15:51
What i noticed is that i can disable dash to dock, but still use it to change settings of ubuntu dock. Then i do not have a problem where two docks are present.

**Comment by ultraUser76** [comment] 2018-07-13 01:13
Dock persists on lock screen just the same as the picture above (ningacoding post).

Ubuntu 18.04,  Gnome 3.38.2

**Comment by vsimitsis** [comment] 2018-07-19 18:57
This happens to me also..On lock screen the dock is visible and this happens even if i restart my computer and lock the screen (super + L)...

**Comment by ultraUser76** [comment] 2018-07-20 23:05
Dock no more persist on lock screen. Yayyyy :+1: 

Checking gnome version found that retrieves 2 versions... is that normal? How do I interpret this?

#command
$ apt-cache show gnome-shell | grep Version
#output
Version: 3.28.2-0ubuntu0.18.04.1
Version: 3.28.1-0ubuntu2

**Comment by mdagtek** [comment] 2018-07-22 08:53
I have the same or similar problem. Also, further, occasionally after I login the native dock merges wish the custom dock:
![screenshot from 2018-07-22 11-45-55](https://user-images.githubusercontent.com/17520803/43043969-d6b1c990-8da5-11e8-9abf-051e0c82ecac.png)

**Comment by ianrobrien** [comment] 2018-07-24 07:50
Looks like a duplicate of #649

**Comment by micheleg** [comment] 2018-07-29 15:33
I believe this is due to incompatibilities/version mismatch with ubuntu-dock. Can you try uninstalling/disabling it? Have a look at the discussion in #649.

**Comment by szemet1** [comment] 2018-08-02 01:48
Issue still exists after the workaround on #649 applied. Just that now icons are randomly and not always  showing up on Ubuntu 17.10 with the compatible dock installed.

Please, don't close this one, all the others are now closed and just looping back to each other. Thank you.

**Comment by Puthika** [comment] 2018-08-03 22:34
I have observe that if the dconf Editor is open, the persists Dock does not show up in the lock screen. I'm running ubuntu 18.04

**Comment by qingju32** [comment] 2018-08-11 13:31
I find the solution. "the two dock and dock in lock screen" is the conflict between ubuntu dock and dash to dock. What we need do is to close the dash to dock. What's more, the setting of dash to dock is still useful. But actually you need  to set once more to make the settings effective.

**Comment by micheleg** [comment] 2018-12-02 19:14
Closing as duplicate  of #641.

**Closed by micheleg** 2018-12-02 19:14 UTC
Labels: duplicate

**Comment by kamdoumloich** [comment] 2019-01-24 12:54
I done the following operations:

> sudo mv /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com /~
> sudo reboot

after restarting my computer I took back the file and restart it again. It's working since one week without any problem
