### ISSUE TITLE
Enabling dash-to-dock messes up search results navigation

### ISSUE THREAD

**Issue by yoursred** [micheleg/dash-to-dock#1612] opened 2021-12-07 06:06 UTC
GNOME: 41.1
dash-to-dock: 71
Kernel: 5.14.21-2-MANJAR

Description: With dash-to-dock enabled, side-to-side navigation with the arrow keys is nonfunctional, and trying to navigate takes the search bar out of focus.

**Comment by yoursred** [comment] 2021-12-07 06:12
Update: intelligent autohide seems to be cause

**Comment by yoursred** [comment] 2021-12-07 06:13
Update: enabling it, regardless of its settings, seems to be the cause

**Comment by 3v1n0** [comment] 2021-12-07 15:23
Please, explain exactly how to reproduce because it's not clear to me.

If it's about the fact that using arrow-keys while moving around the search text, moves the focus to the app icons, that's an upstream bug/feature as well.

**Comment by yoursred** [comment] 2021-12-07 17:45
I guess it's a combination of gnome and the extension
![ezgif-3-028a676f4f63](https://user-images.githubusercontent.com/86563891/145079984-6f6b9cdc-728e-47fb-bc83-3f40a82156a4.gif)
.

**Comment by JustCryen** [comment] 2021-12-10 17:51
I've been having the same issue for quite some time.
I just narrowed it down to Dash To Dock but nothing more.
For now I can confirm that either disabling the extension or Intelligent Autohide feature fixes it.
OS: archlinux
Gnome: gnome-shell 1:41.1-1

**Comment by yoursred** [comment] 2021-12-10 18:55
I want to add another thing, it only happens with intelligent autohide when the dock is not extended and is on the left side of the screen.

**Comment by JustCryen** [comment] 2021-12-10 20:13
You're right… sadly that's exactly how I use it.

**Comment by yoursred** [comment] 2021-12-10 20:15
I would recommend extending it until a fix is found

**Comment by JustCryen** [comment] 2021-12-10 20:18
Actually, under Appearance, disabling "Shrink the dash" makes it work again.
That's something I can tolerate, extending it is too distracting for me.

**Comment by yoursred** [comment] 2021-12-10 20:27
Quite the bizarre bug

**Comment by rollflick** [comment] 2021-12-20 09:35
The issue in Activities Overview only occurs for me after suspending, not after a reboot. Occurs whether using Wayland or Xorg (though maybe need to do reboot rather than just logging out, which I didn't do).

Turning off Ubuntu Dock in extensions seems to have sorted it for me. Never needed to do that before for this extension to work well.

**Comment by yoursred** [comment] 2021-12-20 09:44
I can confirm that it happens regardless of session type (Xorg or Wayland), but for me at least, it doesn't care about being woke up or a cold boot.

**Comment by JustCryen** [comment] 2021-12-20 09:50
Same as @yoursred.
For now I just have "Shrink the dash" disabled.
Ideally I would like to turn it back on.

**Comment by sirianni** [comment] 2022-01-06 21:58
Same issue here.  Note that strangely this only happens when the dock is placed on the left.  If I place the dock on bottom or right side of the screen then keyboard navigation works properly.

**Comment by muflone** [comment] 2022-03-13 13:08
Confirmed in GNOME 41.4 for Arch Linux

Disabling the dash reduce fixes the navigation

**Comment by S0llarCode** [comment] 2022-07-09 17:20
**_Additional bug report_**
GNOME 42.2 with Wayland, Manjaro 21.3.2 (Arch Linux)
Dash to dock 72

When "Intelligent autohide" is enabled and the maximum icon size is odd (like 37px), then the same bug occurs. If the maximum icon size is changed to an even size (like 38px) then the bug disappears.

**You can fix the bug by** `choosing a maximum icon size with a PAIR number`. Examples : 32px, 36px, 38px...

**Comment by vanvugt** [comment] 2022-09-12 11:03
Downstream Ubuntu bug: https://launchpad.net/bugs/1979096

**Comment by soumyatheman** [comment] 2022-09-13 18:15
> Please, explain exactly how to reproduce because it's not clear to me.
> 
> If it's about the fact that using arrow-keys while moving around the search text, moves the focus to the app icons, that's an upstream bug/feature as well.
To reproduce this, in ubuntu specifically, install the [gnome-4x-ui-improvements](https://extensions.gnome.org/extension/4158/gnome-40-ui-improvements/) extension. Then logout and login. The overviews cannot be seen anymore. Disable the hide search bar option in the above said extension, things will work again.

**Comment by 3v1n0** [comment] 2022-09-24 08:28
Wondering if commit 3431f5f91d9ddc3f7cf0a4b59d54f04e53572078 has anything to do with this...

**Comment by siddhpant** [comment] 2022-09-26 08:56
On Sat, 24 Sep 2022 at 13:58 +0530, @3v1n0 wrote:
> Wondering if commit [3431f5f](https://github.com/micheleg/dash-to-dock/commit/3431f5f91d9ddc3f7cf0a4b59d54f04e53572078) has anything to do with this...

I am still experiencing the bug after updating to v74, so the commit probably doesn't fully address the bug...

**Comment by jabossu** [comment] 2022-10-04 06:09
> **_Additional bug report_** GNOME 42.2 with Wayland, Manjaro 21.3.2 (Arch Linux) Dash to dock 72
> 
> When "Intelligent autohide" is enabled and the **maximum icon size number is odd** (like 37px), then the same bug occurs. If the maximum icon size is changed to an even size (like 38px) then the bug disappears.
> 
> **You can fix the bug by** `choosing a maximum icon size with a even number`. Examples : 32px, 36px, 38px...
> 
> Fix idea.. Settings.ui

I can confirm this solution worked for me.

- Manjaro (up to date)
- Dash-To-Dock v74
- Other extensions enabled : Caffeine, Emoji Selector, GSConnect

**Comment by 3v1n0** [comment] 2022-10-09 23:03
Please check if #1849 solves the issue.

**Comment by 3v1n0** [comment] 2023-05-31 00:30
This does not seem to have really fixed in all the cases, but the good news is that it looks like I got a solution at https://github.com/micheleg/dash-to-dock/pull/2020

**Closed** 2023-06-02 01:29 UTC
