### ISSUE TITLE
Switch window by dragging and holding drag item on dock item which have window opened

### ISSUE THREAD

**Issue by ghost** [micheleg/dash-to-dock#278] opened 2016-01-12 02:35 UTC
For example, drag file from Nautilus and holding it on Firefox icon for some time(Firefox window should be opened), will focus on last Firefox window opened. And where you will drop this file for some reason.

I have read the issue #49 and I know, this can not be implemented right now, because [this patch](https://bugzilla.gnome.org/show_bug.cgi?id=696321) is required. And it is some kind _ignored_ for years.

But if they suddenly change their mind, this can be a feature to implement.

**Comment by micheleg** [comment] 2016-01-12 21:56
The feature you are describing should in reality already be feasable. In fact, you can drag a file over the activity button, enter the overview and reach a window holding the dragged file on it. In principle I could implement something similar. The way I was considering is showing all windows of the applications in an overview restricted to that app only (regardless of the workspace), after implementing #216, to help the window selection. But I haven't had the time and motivation to look deeper into it yet.

**Comment by nexfwall** [comment] 2016-01-12 23:46
Thanks for the answer.

I will subscribe to #216, and wait for some movement. Because I don't
know GJS and can not help you.

Tue, 12/01/2016 13:56 -0800, @micheleg:
> The feature you are describing should in reality already be feasable.
> In fact, you can drag a file over the activity button, enter the
> overview and reach a window holding the dragged file on it. In
> principle I could implement something similar. The way I was
> considering is showing all windows of the applications in an overview
> restricted to that app only (regardless of the workspace), after
> implementing #216, to help the window selection. But I haven't had
> the time and motivation to look deeper into it yet.

**Comment by lordadamson** [comment] 2016-08-18 20:20
I want this. Ready to help coding but don't know how to start and would like some guidance.

**Comment by micheleg** [comment] 2016-08-18 21:15
I'd like this too :) I just uploades my old branch where I tried tinkering with it.

https://github.com/micheleg/dash-to-dock/tree/experimental_appwindowsview

As already sad, given the limitation of the drag and drop support (See #49), I was planning to consider showing all windows of that application in an additional overview view, and from there reach the window. If only one window is available direct switching could make sense too.

This was just an ugly test, but it might give you some ideas. 

I'm happy to provide further guidance.

**Comment by lordadamson** [comment] 2016-08-18 21:29
looking into it :+1:

**Comment by lordadamson** [comment] 2016-08-18 21:36
This look good but is really useless without #49 
Is there something we can do to get the gnome guys to accept the patch upstream?

**Comment by micheleg** [comment] 2016-08-18 21:42
It's not totally useless: the shell objects  can't accept darg and drop, or better  can't  get all the information out of it). But once you have reached the window, you can release the file there. The same way it works dragging and dropping a file into the overview. But I might be ignoring some additional issue. 

For the upstream code, you can try asking for updates and desire to add this functionality. Best would be to rebase the patch on current code and try to propose it again. Also, I have no idea if the transition to wayland is going to change things.

**Comment by micheleg** [comment] 2016-08-21 16:06
Also the branch https://github.com/micheleg/dash-to-dock/tree/experimental_xdnd contains some old experiments.

**Comment by corebots** [comment] 2017-01-11 15:00
Hello I'm really waiting for this to get implemented. has any progress been made recently in regards to the mentioned bug please? IMHO this would help new users greatly when stepping over to GNOME from OS X.

**Comment by micheleg** [comment] 2017-01-13 22:12
As far as I know unfortunately there haven't been change upstream, so this feature should still be not implementable on a not patched gnome shell.

**Comment by Valent-in** [comment] 2021-04-25 11:23
#882 - duplicate

**Comment by vanvugt** [comment] 2022-11-28 09:40
Duplicate of #49

**Closed by vanvugt** 2022-11-28 09:40 UTC
Labels: feature request
