### ISSUE TITLE
Wayland: dock empty at login when "show mounted drives" is toggled on

### ISSUE THREAD

**Issue by Magean0** [micheleg/dash-to-dock#1239] opened 2020-05-25 21:20 UTC
Hey,

First of all, thanks for your amazing work. Dash to Dock is one of the gems among GNOME Extensions.

Now, onto the bug report... On Wayland, when Dash to Dock is setup to show mounted drives and a drive is plugged in at login, then the dock is empty or shows only the application grid button, like [this](https://i.imgur.com/YlcMbY7.png).

More specifically, here's how I reproduce the bug:
-disable all extensions but Dash to Dock, so as not to misattribute the issue
-make sure "show mounted drives" is toggled on in the extension's settings
-plug a removable drive
-reboot (just logging out and back in may not be enough), and log in to a Wayland session. Xorg is unaffected.
-the dock is empty, as well as the application grid.

The bug goes away after a minute or so; in the meantime however, I need to search an application by name or run a command to do anything.

System information:
* Dash to Dock v68
* Gnome Shell v3.36.2
* Ubuntu 20.04, up-to-date. I'm on a vanilla GNOME session, not the default Ubuntu session, so Ubuntu extensions and in particular Ubuntu's fork of Dash to Dock are disabled.
* Single monitor
* Display protocol: Wayland
* Intel integrated graphics with default drivers

Extension settings:
```
[/]
apply-custom-theme=false
autohide=false
click-action='previews'
custom-theme-shrink=true
dock-fixed=false
dock-position='LEFT'
intellihide-mode='ALL_WINDOWS'
running-indicator-style='DOTS'
show-apps-at-top=true
show-mounts=false
show-show-apps-button=true
```

And here's the [output of `journalctl /usr/bin/gnome-shell | grep dash-to-dock`](https://pastebin.com/YuwVQBi3).

Thanks in advance for having a look!

**Comment by mike2307** [comment] 2020-06-09 07:24
Yet another issue likely caused by the same trigger:
Started and afterwards closed applications, which are not favourites, stay stuck in the dock.

**Comment by tinklern** [comment] 2020-06-23 13:06
I'm also seeing applications started and then closed remain in the dock.  Eventually they will clear, but it takes anywhere from 30 seconds to 5 minutes.  The dots to indicate window count are updated immediately and are correct.

In addition, newly started applications do not appear in the dock until I trigger a change in state in an application already in the dock (open/close a window, exit an app)

output of "journalctl /usr/bin/gnome-shell | grep 'dock'" is here:
https://pastebin.com/iC4uPUJG

**Comment by nazar2sfive** [comment] 2020-08-08 04:25
![image](https://user-images.githubusercontent.com/12841320/89702273-4f133200-d95f-11ea-94d7-df747f38b95c.png)

it remains empty for around 4-5 minutes in wayland and it appears later.

**Comment by n-nikol98** [comment] 2020-09-09 17:53
Have the same issue on my system (Fedora 32).

It seems that the delay occurs when the extension tries to verify that one of the icon names of the volume / mount is present in the default icon pack (code snippet from `location.js`):

```
_getWorkingIconName(icon) {
	if (icon instanceof Gio.EmblemedIcon) {
		icon = icon.get_icon();
	}
	if (icon instanceof Gio.ThemedIcon) {
		let iconTheme = Gtk.IconTheme.get_default();
		let names = icon.get_names();
		for (let i = 0; i < names.length; i++) {
			let iconName = names[i];
			if (iconTheme.has_icon(iconName)) {
				return iconName;
			}
		}
		return '';
	} else {
		return icon.to_string();
	}
}
```
Specifically:

```
if (iconTheme.has_icon(iconName)) {
	...
}
```
A potential temporary fix is to simply remove the check and return the first icon name of the volume / mount:
```
if (icon instanceof Gio.ThemedIcon) {
	let names = icon.get_names();
	
	return names[0];
}
```
Or...don't return anything:
```
_getWorkingIconName(icon) {
	if (icon instanceof Gio.EmblemedIcon) {
		icon = icon.get_icon();
	}
	if (icon instanceof Gio.ThemedIcon) {
		return '';
	} else {
		return icon.to_string();
	}
}
```

**Comment by vanvugt** [comment] 2021-02-25 05:07
Duplicate of #1217.

**Comment by vanvugt** [comment] 2021-02-25 05:12
Downstream Ubuntu bug: https://bugs.launchpad.net/bugs/1874578

Also, #1217 is curiously the opposite of this one. Or is that a typo?

**Comment by pablodz** [comment] 2021-10-17 20:05
![image](https://user-images.githubusercontent.com/28235457/137643157-1979a153-822f-4fb1-9d03-01359dedef17.png)
same here

**Closed** 2022-04-28 00:31 UTC
