### ISSUE TITLE
Show Apps button does nothing, unless activities is open

### ISSUE THREAD

**Issue by Nekture** [micheleg/dash-to-dock#2131] opened 2023-12-08 14:16 UTC
Gnome version 45.1
Dash to Dock version: 89
Enabled extensions:
```
apps-menu@gnome-shell-extensions.gcampax.github.com
dash-to-dock@micxgx.gmail.com
legacyschemeautoswitcher@joshimukul29.gmail.com
pamac-updates@manjaro.org
places-menu@gnome-shell-extensions.gcampax.github.com
user-theme@gnome-shell-extensions.gcampax.github.com
```

When opening the dock and clicking the "Show Apps" button, nothing happens.
When in the activities view it does work as intended.

Expected behaviour is that pressing "Show Apps" opens Activities and then the App List.

**Comment by Nekture** [comment] 2023-12-08 14:26
Addendum: 
I've fiddled with the settings for Dash to Dock.
Enabling "Animate Show Applications" fixes the issue and returns to expected behaviour.

**Comment by vanvugt** [comment] 2024-01-04 07:38
Duplicate of #2112

**Closed by vanvugt** 2024-01-04 07:38 UTC
