### ISSUE TITLE
Invalid GtkBox Property on Fedora 34, Gnome 40

### ISSUE THREAD

**Issue by joshuamil** [micheleg/dash-to-dock#1430] opened 2021-04-30 13:05 UTC
When starting with Fedora 34, Gnome 40, the user receives a Gtk.BuilderError from an invalid property in the Settings.ui file, for GtkBox.margin_left.

Gtk.BuilderError: /home/<user>/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/Settings.ui:13:35 Invalid property: GtkBox.margin_left

Stack trace:
  DashToDock_Settings@/home/<user>/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:92:23
  buildPrefsWidget@/home/<user>/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:869:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by Sidpatchy** [comment] 2021-04-30 13:17
Dash to Dock doesn't support Gnome 40 yet.

See #1358 and #1402.

**Comment by ewlsh** [comment] 2021-10-05 05:16
Duplicate of #1358

**Closed by ewlsh** 2021-10-05 05:16 UTC
