### ISSUE TITLE
Dock crashes after monitor wake

### ISSUE THREAD

**Issue by sekurilabs** [micheleg/dash-to-dock#1947] opened 2023-02-28 08:24 UTC
Dock seems to crash after monitor turns off. When turning the monitor on again dock is not shown again and I have to restart the shell.
Here are some errors I picked up, I don't know if they are relevant:

```
JS ERROR: Extension dash-to-dock@micxgx.gmail.com: TypeError: this._launchMaxWaitIds is undefined
JS ERROR: TypeError: Docking.State is undefined
```

**Comment by vanvugt** [comment] 2023-02-28 08:25
Duplicate of #1935

**Closed by vanvugt** 2023-02-28 08:25 UTC
