### ISSUE TITLE
Not compatible with GNOME 46

### ISSUE THREAD

**Issue by ActuallyFlamey** [micheleg/dash-to-dock#2171] opened 2024-03-24 09:42 UTC
The GNOME Shell Extensions website and GNOME Extensions app say that it's out of date.

**Comment by maxxcan** [comment] 2024-03-24 10:02
If you compile from source works perfectly in Gnome 46.

**Comment by Nooberieno** [comment] 2024-03-24 15:16
if you change your shell version from 45 to 46 in the metadata.json it should work for gnome 46

**Comment by assapir** [comment] 2024-03-24 19:53
When ignoring the shell version, using "disable version validation", the extension fails with 
`TypeError: this._dashContainer.add_actor is not a function`

**Comment by carneeki** [comment] 2024-03-24 23:49
> If you compile from source works perfectly in Gnome 46.

While master (current [554f7c5](https://github.com/micheleg/dash-to-dock/commit/554f7c5541bc4ff05d89a9419d2580d3780595e3) ) does compile for me and appears to work, it doesn't actually mean that @ActuallyFlamey's issue is fixed though - posting a tag/release to GNOME's extension page would resolve their issue, assuming the extension is ready for release.

**Comment by vanvugt** [comment] 2024-03-25 02:28
Duplicate of #2156

**Closed by vanvugt** 2024-03-25 02:28 UTC

**Comment by Aqua1ung** [comment] 2024-04-09 15:53
> I would be surprised if it was more than a couple of weeks from now. It should be sooner.

Are you surprised yet?😊

Joke aside, I am very grateful for the work you guys are doing. As someone said however, it looks like you guys have turned this extension into a panaceum, hence the issues you are coming across when it comes to reacting to GNOME changes. You guys should have kept it simpler, and let other extensions handle the multitude of features that you are currently striving to incorporate.
