### ISSUE TITLE
Dock collapses after screen blanking

### ISSUE THREAD

**Issue by brucej72** [micheleg/dash-to-dock#1959] opened 2023-03-06 16:15 UTC
Ubuntu 22:04 with v76 of dash to dock. 
My system is set to screen blank after 5 minutes inactivity. When this happens, the dock collapses to just the app selector icon, and I need to restart the window manager with ALT-F2 +r for it to reappear. 
In the logs, I see a collection of these messages (but not sure if relevant or not):

15:59:13 gnome-shell: Spurious clutter_actor_allocate called for actor 0x55c182b3e430/<dashtodockContainer>[<Gjs_ubuntu-dock_ubuntu_com_docking_DashToDock>:0x55c182b3e430] which isn't a descendent of the stage!

15:59:13 gnome-shell: st_widget_get_theme_node called on the widget [0x55c182b3e430 Gjs_ubuntu-dock_ubuntu_com_docking_DashToDock.bottom shrink running-dots fixed extended:insensitive "dashtodockContainer"] which is not in the stage.

**Comment by vanvugt** [comment] 2023-03-07 02:45
Duplicate of #1522

**Closed by vanvugt** 2023-03-07 02:45 UTC
