### ISSUE TITLE
Every app shows "running" indicators, although not running

### ISSUE THREAD

**Issue by markusmacher** [micheleg/dash-to-dock#1787] opened 2022-08-17 09:27 UTC
Every app shows "running" indicators, although they are not running. This happend since the last update on Fedora 36 (17-08-2022).

----------------------------------------------------------------------------------

OS: Fedora Linux 36 (Workstation Edition) x86_64 
Host: MS-7C02 3.0 
Kernel: 5.18.17-200.fc36.x86_64 
Uptime: 12 mins 
Packages: 2513 (rpm), 16 (flatpak) 
Shell: zsh 5.8.1 
Resolution: 3440x1440 
DE: GNOME 42.4 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz 
GPU: NVIDIA GeForce GTX 980 Ti 
Memory: 2812MiB / 15913MiB 

                        

                                         
                                                                 
![Bildschirmfoto vom 2022-08-17 11-25-52](https://user-images.githubusercontent.com/48573077/185084616-67814d5c-7dd3-4b29-a360-c71485ecf801.png)

**Comment by markusmacher** [comment] 2022-08-17 09:28
but maybe this is a gnome issue, dont know

**Comment by davorvr** [comment] 2022-08-17 21:29
I can confirm this, also on fully updated Fedora 36 Workstation.

**Comment by afinkel71** [comment] 2022-08-18 11:52
I can also confirm this.  Also on a fully updated Fedora 36 Workstation.
![image](https://user-images.githubusercontent.com/38784838/185388197-878dc5d4-30c4-4ae6-8105-9a46d81b081a.png)

**Comment by markusmacher** [comment] 2022-08-18 11:55
should be a dash-to-dock issue. disabling the extension returns everything to normal.
![Bildschirmfoto vom 2022-08-18 13-54-59](https://user-images.githubusercontent.com/48573077/185388653-cd3de1ba-dae7-430c-bd67-309eb0b2557f.png)

**Comment by afinkel71** [comment] 2022-08-18 22:05
I disabled and re-enabled the extension and I still see the indicators on all apps in the dock.

**Comment by maxborowsky** [comment] 2022-08-20 22:30
Temporary solution for Fedora 36 (how it seems to me):

```
sudo dnf remove gnome-shell-extension-dash-to-dock
find /usr/share/glib-2.0/schemas -type f -name org.gnome.shell.extensions.*
gsettings list-schemas
gsettings reset-recursively org.gnome.shell.extensions.dash-to-dock
wget -nc -P Downloads https://kojipkgs.fedoraproject.org//packages/gnome-shell-extension-dash-to-dock/72/1.fc36/noarch/gnome-shell-extension-dash-to-dock-72-1.fc36.noarch.rpm
sudo dnf install Downloads/gnome-shell-extension-dash-to-dock-72-1.fc36.noarch.rpm
```

A recent update to the gnome-shell-extension-dash-to-dock package for Fedora broke the extension.

**Comment by orestephen** [comment] 2022-08-29 03:42
has there been any progress on this?? i currently have this problem too.. would like very much to not have to downgrade back to an unmanaged rpm package.

**Comment by maxborowsky** [comment] 2022-08-29 22:16
@orestephen

There is certainly some progress. Look at the dates of the latest source code changes.

But DtD is developing more slowly than Dash to Panel (so far you can try using instead of Dash to Dock, by the way). We don't pay developers, right? They spend their own time.

This is an inevitable fee for non-proprietary software - to put up with flaws and bugs that will always be in software that is not funded by anyone :-(

**Comment by leandro-kemp** [comment] 2022-09-05 05:20
It works for me on Fedora 36 without issues. However I use the Gnome Extensions version, not the rpm one.
There might be some issue related to the rpm package.

**Comment by leandrokemp** [comment] 2022-09-05 05:22
It works for me on Fedora 36 without issues. However, I use the Gnome extensions version, not the rpm one.
There might be some issue with the rpm package.
Compiling from the source also works fine for me.

**Comment by afinkel71** [comment] 2022-09-06 12:11
Updated this morning and updated to gnome-shell-extension-dash-to-dock-73-1.fc36.noarch which has resolved the issue.  Thanks!!!

**Comment by sirweazel** [comment] 2022-09-06 12:57
Ran updates in Fedora 36 this morning, and issue is resolved in Fedora 36 from the repo.  When looking at the changlog on Fedora Build system, it mentions fixing the dot issue.

**Closed** 2022-09-21 14:34 UTC
