### ISSUE TITLE
Activities Not working when Dash to Dock 72 is enabled

### ISSUE THREAD

**Issue by afzl-wtu** [micheleg/dash-to-dock#1747] opened 2022-05-18 08:22 UTC
I have installed fresh Manjaro latest version and updated it to GNOME version 42.1. It has Dash to Dock version 72. But unfortunately when this extension is enabled Activities does not work. Does not matter if I click on Left Top Activities button or press the Super Key. As soon as I disable it. Everything works fine. Please fix the issue.

**Comment by jeetsrs** [comment] 2022-06-05 14:42
Same issue here. It took some time to isolate this - but Activities is 100% broken when running dash-to-dock 72 on Manjaro (latest updated Gnome 42.1 as of June 2022). 
[https://sodhi-polaris.synology.me:5001/drive/d/s/oyePOGxBVUvCDZfOohjxGo5kqjVxTEdr/K6Gei8pblCAN-qFBZFNb21dPSjljWMk3-r7Qgw7q3kwk](url)

**Comment by Jhackler** [comment] 2022-06-07 20:06
same on vanilla arch

**Comment by afzl-wtu** [comment] 2022-06-09 16:26
Update: It is now working again automatically. I do not why but it corrected itself.
But there is another trick when you see activities blank screen start typing any letters and it will start working again.

**Comment by Jhackler** [comment] 2022-06-09 17:03
well my issue is that in activities, when I search I can not click on the application or use arrow to switch so I have to keep typing till the one I want is highlighted and use enter key. This issue does not exist with dock disabled. https://youtu.be/CG3rknuToRk to demonstrate

**Comment by jeetsrs** [comment] 2022-06-10 14:02
I have noticed that sometimes it (dash to dock) starts working without causing the activities to crap out. But there is no consistent reason for why it breaks activities on Gnome. 

I have tried re-starting dash to dock. Rebooting the PC. Changing the layout on Manjaro (using their Layout app) to default GNOME (no dash to dock enabled), and then going back to the dash to dock extension.... nothing fixes the broken Activities on Gnome when running Dash to Dock. 

But the second I disable the Dash to dock extension, the Activities of Gnome start working flawlessly. 

For now I am giving up on using Dash to Dock entirely. Enjoying the default Gnome workflow. Will wait and see if this issue is fixed - else nix Dash to dock permanently.

**Comment by 3v1n0** [comment] 2022-07-08 04:19
Quite hard to debug this without journal gnome-shell logs

**Comment by siddhpant** [comment] 2022-07-16 11:14
You should see the following issue on launchpad:
https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/1979096
https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1971126

**Comment by freshgiammi** [comment] 2022-07-28 08:38
> Quite hard to debug this without journal gnome-shell logs

I can replicate this issue consistently. Here's a log:
https://www.toptal.com/developers/hastebin/oyubuvafib.yaml

I'm currently running [mutter-performance](https://aur.archlinux.org/packages/mutter-performance) instead of the classic version, but the issue persists in the same way using the regular version. I can only replicate this when auto-hide is active, and it looks like searching something in the activity search bar makes this bug 'go away'. 
I can provide logs with mutter, if you need.

System info:
```
OS: Arch Linux
Kernel: 5.18.14-arch1-1
DE: Gnome 42.3.1 (https://aur.archlinux.org/packages/gnome-shell-performance)
WM: Mutter 42.3 (https://aur.archlinux.org/packages/mutter-performance)
```

**Comment by freshgiammi** [comment] 2022-07-29 13:23
@Jhackler @siddhpant @jeetsrs are you guys using this extension by any chance? [Gnome 4x UI Improvements](https://extensions.gnome.org/extension/4158/gnome-40-ui-improvements)

It appears that I'm only able to replicate this bug when that extension is enabled, **and even then,** only when the 'hide-search' setting is turned on. 

This would also match reports on both gnome's extension website and the extension's repository.
(https://github.com/axxapy/gnome-ui-tune/issues/28 https://github.com/axxapy/gnome-ui-tune/issues/29), as well as the behaviour going back to normal once you try and search something in the activity page. 
This, however, does not happen when the search bar is hidden using [Just Perfection](https://extensions.gnome.org/extension/3843/just-perfection), so I'm inclined to point my finger towards the first extension, even if I haven't been deep-diving on the related code.

Hope this can help somehow @3v1n0

**Comment by Jhackler** [comment] 2022-08-15 11:16
> 

I am not though its possible the option is affected by another extension as well? I dont have any extenstions that have a hide search I am aware of though

**Comment by Jhackler** [comment] 2022-08-15 11:19
it also is still an issue for me on the activities and other pages lol I can click things that are setting but not apps. I have concluded that gnome is just gonna keep moving further from how I want to use it while more and more extensions that fix it get broken till I finally just take the time to make kde act more like unity lol

**Comment by vanvugt** [comment] 2022-09-12 11:01
The auto-hide issue is tracked in #1612

**Comment by jabossu** [comment] 2022-10-04 06:11
> The auto-hide issue is tracked in #1612

And a workaround was found there : https://github.com/micheleg/dash-to-dock/issues/1612#issuecomment-1243836251
The bug only happens when the icon size is odd. Making it even fixed the issue for me. Read the comment for more information.

**Comment by 3v1n0** [comment] 2022-10-09 19:48
Duplicate of #1612

**Closed by 3v1n0** 2022-10-09 19:48 UTC
