### ISSUE TITLE
show-mounts false causes icons to appear/disappear slowly

### ISSUE THREAD

**Issue by ndlarsen** [micheleg/dash-to-dock#1217] opened 2020-05-12 18:07 UTC
Related to
https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/1869572
https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/1874578

Setting `gsettings set org.gnome.shell.extensions.dash-to-dock show-mounts false` and restarting gnome causes icons on the dock to appear/disappear very slowly (as in after a delay). Setting it back to `true` and restarting gnome clears the issue.

Observerd on gnome 3.36.1 with 67ubuntu20.04.5
- Problem persisted after a dconf reset.
- Problem also oberserved on a fresh 20.04 with old profile.
- Problem also observed on fresh install in virtualbox with a fresh user profile.

All were minimal installs if that matters which I highly doubt. Reproducible as described above. Running X11.

It likely a duplicate of the multi monitor related ones eventhough I'm not actually using such a setup.

**Comment by vanvugt** [comment] 2021-02-25 05:10
Do you mean `true` instead of `false` ?

**Comment by 3v1n0** [comment] 2022-01-21 00:52
Duplicate of #1239

**Closed by 3v1n0** 2022-01-21 00:52 UTC
