### ISSUE TITLE
[ubuntu-dock] minimize/preview behavior

### ISSUE THREAD

**Issue by ghost** [micheleg/dash-to-dock#833] opened 2018-11-12 11:26 UTC
Hello,

I understand that ubuntu-dock doesn't have a lot of settings to keep it beginner-friendly, however it's kinda sad to see that when we click on an opened app it does absolutely nothing. It would be natural and useful if clicking on something would minimize and restore (show previews if several windows), like one of the default behaviors available in dash-to-dock.

**Comment by vanvugt** [comment] 2020-11-27 03:55
Duplicate of #594

**Comment by vanvugt** [comment] 2023-05-18 08:12
Duplicate of #365

**Closed by vanvugt** 2023-05-18 08:12 UTC
Labels: ubuntu-dock
