### ISSUE TITLE
dash to dock doesn't open on startup

### ISSUE THREAD

**Issue by shraykumar100** [micheleg/dash-to-dock#2031] opened 2023-06-03 19:03 UTC
Using fedora 37 and dash to dock does not run itself on startup. I have to disable and re-enable the extension to make it work.

**Comment by idanka** [comment] 2023-06-05 16:43
On Fedora 38, the application launch sometimes works, sometimes not:(

**Comment by persicsb** [comment] 2023-06-09 09:25
This is a duplicate of https://github.com/micheleg/dash-to-dock/issues/2029

**Comment by 3v1n0** [comment] 2023-06-13 00:04
Duplicate of #2029

**Closed by 3v1n0** 2023-06-13 00:04 UTC
