### ISSUE TITLE
all of the apps disapper when i turn on disks

### ISSUE THREAD

**Issue by rx10** [micheleg/dash-to-dock#1441] opened 2021-05-09 21:39 UTC
when i turn on the show mounted drives option, the applications disappear. i am running gnome 40 on fedora.
i have previously used this extension on the same configuration and it worked perfectly. i don't understand why this happened.

**Comment by linoshkm** [comment] 2021-05-29 06:06
Duplicate of #1239
Try this solution  #1239 (comment)

**Comment by 3v1n0** [comment] 2021-11-04 21:27
Duplicate of #1239

**Closed** 2022-01-21 00:50 UTC
