### ISSUE TITLE
intelligent autohide is not working

### ISSUE THREAD

**Issue by Coleej** [micheleg/dash-to-dock#411] opened 2016-11-29 16:28 UTC
Intelligent autohide is not working since I upgraded to Fedora 25. Its a great app, but without this feature its unusable. Hope to see it corrected in the future.

Please let me know if you need any info about my system and I will provide them. Not sure what would help you at this point.

**Comment by zapashcanon** [comment] 2016-11-29 17:56
What's your dash-to-dock version ?

Also, Fedora 25 set Wayland as default, could you try with X to see if it's also not working ?

**Comment by Mancooo** [comment] 2016-12-02 10:51
I have the same problem, Dash to Dock version 55 and running Fedora 25 with Xorg (or Wayland, that doesn't matter). Sometimes the intelligent authide does not work, even I keep pushing the mouse to the side, only by vertically moving the mouse towards the top of the display, the dock shows.

**Comment by micheleg** [comment] 2016-12-11 23:53
Sorry for the late reply. What the issue? Is the dock not hiding by the overlapping with windows or not showing by mouse hover on the screen edge?

**Comment by Mancooo** [comment] 2016-12-12 19:13
The dock is not showing when you hover on the screen edge. I keep pushing to the side of the screen and the dock does not show. Only when I move up (vertically) while pushing to the side, the dock shows.

**Comment by micheleg** [comment] 2016-12-12 20:22
Few questions:
Are you running in wayland? If so, coould you test it in X? 
Can you try disabling the push to show option? 
Can you confirm the bug occur without other extensions enabled?

**Comment by Mancooo** [comment] 2016-12-13 21:04
I am running X, I tried disabling push to show (it does not help) and I can confirm the bug exists with all other extensions disabled.

**Comment by micheleg** [comment] 2016-12-15 17:17
It's quite strange. Do you have multiple screens? Where is the dock positioned?

**Comment by Coleej** [comment] 2016-12-15 21:58
I'm not sure who you are referring to. 

When I have multiple screens my dock-to-dash's intelligent hide doesn't
work. I have it on the left of my screen. Its a laptop, so sometimes I
don't have two monitors and the plugin works fine.

**Comment by Mancooo** [comment] 2016-12-16 10:43
I do not have multiple screens, the dock is on the left side. I will try to make a screencast of it in a couple of days.

**Comment by franglais125** [comment] 2016-12-16 21:27
@Mancooo do you mind testing this branch?

https://github.com/franglais125/dash-to-dock/tree/fix_intellihide

**Comment by Mancooo** [comment] 2016-12-16 23:09
I downloaded it and I am going to test it, I will let you know when I know some more

**Comment by Mancooo** [comment] 2016-12-16 23:17
As soon as I started testing it, I immediately noticed the bug and managed to make a screencast of it, see [https://www.dropbox.com/s/3awevfed10sofjw/Screencast%20from%2012-17-2016%2012%3A11%3A14%20AM.webm?dl=0](url)

You will notice from the video that the dock does not show up, even if I try really hard to show it, it is only when move up vertically the dock shows.

**Comment by franglais125** [comment] 2016-12-16 23:22
From your screencast, I can see that the dock shows if you put the mouse on the edge of the screen just above the dock. I had this behavior too, but in my case that branch fixed the problem, don't know why it doesn't for you...

**Comment by Mancooo** [comment] 2016-12-16 23:26
Yes exactly, the dock only shows when you move towards the top of the screen, both builds (branches) exhibit the same behaviour in my case.

**Comment by micheleg** [comment] 2016-12-18 18:32
I think It's related to #399, even if @franglais125 fix doesn't work here.

@Mancooo, @Coleej : could you try with a freshly made user and session?

**Comment by teoulas** [comment] 2016-12-29 20:47
I also have this issue when running Wayland on Arch Linux. When running X11 it works fine. I use v55 of the extension.

**Comment by andrewfonseca** [comment] 2017-01-05 09:39
I'm having this issue as well. I just upgraded to fedora 25 and the dock is always visible no matter which window is active and on top. This only happens when I have another monitor connected.

**Comment by andrewfonseca** [comment] 2017-01-05 09:44
Well I just tried multiple options and it is now working. The problem is in selected monitor, for some reason in order for the intelligent hide to work i have to set the dock to the Secondary monitor 1. But, the dock remains on the primary monitor. Weird behavior.

**Comment by micheleg** [comment] 2017-01-05 13:05
@andrewfonseca: would you mind looking for some errors in the log when you try moving the dock to a different monitor.  Possible places to look for the relevant logs depend on the system log configuration:
* Runnning journalctl /usr/bin/gnome-session or journalctl /usr/bin/gnome-shell. This might require to be run as root/with sudo. You can add -f, for instance journalctl /usr/bin/gnome-shell -f, to follow the new messages.
 * In the file ~/.xsession-errors.
 * In the file ~/var/log/syslog .

**Comment by teoulas** [comment] 2017-01-05 14:14
I confirm @andrewfonseca 's finding. The dock auto-hides if you select the secondary monitor, but it still appears on the primary one. I checked for errors by running `journalctl /usr/bin/gnome-shell -f` but nothing appeared.

**Comment by andrewfonseca** [comment] 2017-01-05 14:15
I'm not getting anything on the logs. I have been trying multiple options again and after a while the intelligent autohide suddenly works as it supposed to but the dock wont move to the secondary monitor.

Here are some screenshots:
[Intelligent autohide not working on primary monitor](https://postimg.org/image/miy530abn/)
[Intelligent autohide working on primary monitor](https://postimg.org/image/l2mmkv7er/)
[Dock not working on secondary monitor](https://postimg.org/image/dldf5nhvn/)

**Comment by micheleg** [comment] 2017-01-10 21:56
Can you check if the working/not working of autohide has anything to do with having or not windows on the secondary monitor as suggested in https://github.com/micheleg/dash-to-dock/issues/255#issuecomment-271029691?

**Comment by teoulas** [comment] 2017-01-11 13:12
Hi @micheleg ,

I just confirmed it works correctly when there is a window on the secondary monitor. No windows, the dock is not hiding.

The window must have most of its area in the secondary monitor, to be specific. If most of it is in the primary monitor, the dock does not hide. I can what the threshold is, because my screens have different pixel density and the window manager scales it according to the monitor where the window belongs.

**Comment by micheleg** [comment] 2017-01-15 00:52
Please have a look at https://github.com/micheleg/dash-to-dock/tree/fix_intellihide_wayland and https://github.com/micheleg/dash-to-dock/tree/fix_intellihide_wayland_2 and see if they help

**Comment by teoulas** [comment] 2017-01-16 01:13
The `fix_intellihide_wayland` branch fixes the problem! The dock is shown in the selected monitor and it autohides correctly regardless of which monitor is selected.

:+1: 

Now, there's a different issue with DPI-awareness. My monitors have different pixel density, but the dock does not scale itself based on the monitor's DPI. I'll probably have to open a different issue.

**Comment by micheleg** [comment] 2017-01-16 21:47
Fix merged in master d553004e014cefb981.

@teoulas: please open a separate issue.

**Closed by micheleg** 2017-01-16 21:47 UTC
Labels: bug

**Comment by teoulas** [comment] 2017-01-16 23:54
DPI issue: #435
