### ISSUE TITLE
Space between dock icons

### ISSUE THREAD

**Issue by cesaraquino** [micheleg/dash-to-dock#2226] opened 2024-05-31 01:28 UTC
Good evening, is there a way to decrease the margin between the icons in the dock? I feel that they are too far apart from each other.

**Current:**
![dock 1](https://github.com/micheleg/dash-to-dock/assets/4138916/b8eb6370-af1d-4625-bd4c-870c23329ecb)

**Expected:**
![dock 2](https://github.com/micheleg/dash-to-dock/assets/4138916/de2b3fac-2dac-4aa6-9de1-581322573eea)

If you notice in the first image, there is a lot of distance between the dock icons. Maybe it is because the item that contains them has a padding or border that would be good to be able to control from the extension preferences panel. Thanks.

**Comment by vanvugt** [comment] 2024-06-04 05:34
Duplicate of #844

**Closed by vanvugt** 2024-06-04 05:34 UTC
