### ISSUE TITLE
dash to dock blinking with multi screen and auto-hide activated

### ISSUE THREAD

**Issue by JeromeBobe** [micheleg/dash-to-dock#1936] opened 2023-02-27 14:19 UTC
When i use dash to dock with auto-hide activated, under certains conditions my dock start blinking.

How to reproduce :
    - Activate auto-hide
    - use two screens minimum
    - open two window, one window per screen
    - on one screen, maximise the window, and minimise on the other

Now if you try to show the dock on the screen with the maximize window, the dock will blink in a very strange way.

I tried this on two different setup:
    * Manjaro + gnome 43.3 + wayland + Asus notebook
    * Fedora 37 + gnome 43.3 + wayland +  HP 250 G8 Notebook PC
 
PS : can't show you with a video, my screen recorder doesn't capture the blink of the dock.

**Comment by vanvugt** [comment] 2023-02-28 03:43
Duplicate of #1381

**Closed by vanvugt** 2023-02-28 03:43 UTC
