### ISSUE TITLE
dash-to-dock Intelligent autohide glitches while entering in firefox full screen

### ISSUE THREAD

**Issue by denilgabani** [micheleg/dash-to-dock#1813] opened 2022-09-06 17:38 UTC
While we go to the edge of screen in Firefox full screen When Intelligent auto hide is enabled it flickers continuously.
OS: Manjaro Linux
Gnome Version: 42.4

**Comment by denilgabani** [comment] 2022-09-16 05:14
It flickers only in GNOME Wayland note in Xorg.

**Comment by kevincianfarini** [comment] 2022-09-21 23:11
I also experience this issue.

**Comment by taoky** [comment] 2022-09-26 11:54
Maybe duplicate of https://github.com/micheleg/dash-to-dock/issues/1381.

Disable hardware acceleration of Firefox may workaround this bug. Could it be a bug of GNOME (when an app with hardware acceleration is in full screen)?

**Comment by kevincianfarini** [comment] 2022-09-26 12:14
Interesting that you mention that. Intelligent hiding of the top bar via an extension also expresses similar behavior.

**Comment by taoky** [comment] 2022-09-26 12:27
> > Interesting that you mention that. Intelligent hiding of the top bar via an extension also expresses similar behavior.
> 
> Well here I cannot trigger dock out when Firefox/Chromium is in fullscreen mode (F11) without attaching to external monitor. I find dock glitches when these conditions satisfy:
> 
>     * Firefox/Chromium is in maximum window in laptop screen
> 
>     * The "dock" is in laptop screen
> 
>     * The GNOME "top bar" is in external screen
> 
> 
> However if disabling hardware acceleration works in your case, I believe that it's the same bug as issue 1381.

For developers to reproduce this bug, this is how I position my displays:

![image](https://user-images.githubusercontent.com/2109893/192275690-ecc1bccc-4cbc-4686-b310-b60899e6629c.png)

**Comment by kevincianfarini** [comment] 2022-09-26 12:48
Disabling FF hardware acceleration works around the issue. Unlike others, this is problematic even on a single display for me.

**Comment by taoky** [comment] 2022-09-26 12:51
> Disabling FF hardware acceleration works around the issue. Unlike others, this is problematic even on a single display for me.

So this bug exists on display with dock and without top bar (by other extensions, or in multi-display environment)...

**Comment by Neubulae** [comment] 2022-10-28 16:46
suffering the same thing

**Comment by denilgabani** [comment] 2022-10-28 17:34
The best solution I found is to move to Xorg as it is working in XOrg perfectly😔.

**Comment by taoky** [comment] 2022-11-07 05:00
According to #1868 and <https://www.reddit.com/r/gnome/comments/ye9yzu/dash_to_dock_flickering/>, `Meta.disable_unredirect_for_display(global.display);` can workaround this problem, and it works on my laptop.

Disabling unredirection may hurt full-screen games performance, I guess that's why mutter enables that by default. However, I have tested supertuxkart and firefox (F11) and I find that the dock will NOT be triggered out when it is actually in fullscreen mode. As apps all use CSD in wayland, I guess that when an app gets maximized in a display without any gnome-shell decorations, mutter thinks that it should use undirection for that app, and this behavior of mutter brings out the bug of dash-to-dock.

Maybe people familiar with mutter could file an issue/merge request to that?

**Comment by Neubulae** [comment] 2022-11-12 19:01
this seems to be fixed for me for whatever reason

**Comment by chumariesco** [comment] 2022-11-15 23:22
I'm also suffering this problem. First I thought it was a problem with the 'Hide Top Bar' extension, but it was Dash to Dock with autohide enabled and fullscreen apps (ie. Ardour or Blender).

The trick from redit works temporarily:
Alt+F2, lg and then enter Meta.disable_unredirect_for_display(global.display)

**Comment by chumariesco** [comment] 2022-11-15 23:47
This extension is out there to automate the aforementioned workaround.
https://extensions.gnome.org/extension/1873/disable-unredirect-fullscreen-windows/

**Comment by cbeley** [comment] 2022-11-18 04:50
I'm also experiencing this, though not in fullscreen. If I simply have some windows maximized the glitching occurs. Using the disable unredirect fix completely fixes things on Ubuntu 22.10.

**Comment by mihalycsaba** [comment] 2022-11-18 16:58
Did you guys find any issues after disabling unredirection on wayland? Tried a few games, don't really see performance problems.

**Comment by vanvugt** [comment] 2023-02-28 03:42
Duplicate of #1381

**Closed by vanvugt** 2023-02-28 03:42 UTC

**Comment by martinprad0** [comment] 2023-12-03 22:48
> This extension is out there to automate the aforementioned workaround. https://extensions.gnome.org/extension/1873/disable-unredirect-fullscreen-windows/

Thank you, it worked
