### ISSUE TITLE
Appearance bug?

### ISSUE THREAD

**Issue by TheAifam5** [micheleg/dash-to-dock#388] opened 2016-10-21 21:13 UTC
The actually problem is when the "Shrink the dash" is enabled.
I'm using ArchLinux.
Git version of dash-to-dock (f6becc9c8fb7a10e9901aa249783919c75c0f5a5)
Theme: Adapta Nokto Eta
Problem is also on Adwaita theme.

![a](https://cloud.githubusercontent.com/assets/2192274/19611700/30461bf6-97e3-11e6-9edb-7057c5aa92d6.png)
(Look at the corners)

Appearance config:
![w](https://cloud.githubusercontent.com/assets/2192274/19611803/b20cb078-97e3-11e6-82a6-7d43a7b5c496.png)

**Comment by micheleg** [comment] 2016-10-21 21:27
Mmmm,

I see and I can reproduce the bug with the Adapta theme. Those settings are mainly meant to work with the default Adwaita theme, as they are overwriting the default theme settings.  You say you are experiencing the bug with the default theme too. Can you confirm?

**Comment by TheAifam5** [comment] 2016-10-21 21:36
So,
Default theme doesn't have that bug.
I will report that problem to Adapta author. :)

**Comment by micheleg** [comment] 2016-10-21 21:39
Ok. It's an incompatibility but they might understand better then me what they are doing.  They should be able to tailor their them for this extension following https://micheleg.github.io/dash-to-dock/theming.html. Closing this issue.

**Closed by micheleg** 2016-10-21 21:39 UTC

**Comment by TheAifam5** [comment] 2016-10-22 16:46
@micheleg look at the issue: https://github.com/adapta-project/adapta-gtk-theme/issues/256

**Comment by MS7WN7D-V3N0M** [comment] 2016-12-07 20:21
I'm using Gnome 3.22.2 and I love this extension, as I love the Adapta theme...
Hope you fix it @micheleg .

**Comment by micheleg** [comment] 2016-12-11 18:49
I just installed the Adapta theme and it seems I can't reproduce the problem any mode? Can you confirm?
