### ISSUE TITLE
Feature Request: Add more customization option

### ISSUE THREAD

**Issue by Saurav92** [micheleg/dash-to-dock#358] opened 2016-08-08 13:01 UTC
Please add option to change the look and feel of the dock, like color, custom theme etc. And if we could change the show applications icon (the 9 dots) it would be great.

**Comment by zapashcanon** [comment] 2016-08-08 18:50
Seems like a duplicate of #333, please look at it, and if that's what you want, you can close this issue. :)

**Closed** 2016-08-09 05:25 UTC
Labels: duplicate
