### ISSUE TITLE
Option to hide Dash in Activites Overview

### ISSUE THREAD

**Issue by vjcagay** [micheleg/dash-to-dock#294] opened 2016-03-19 19:07 UTC
Adding this option can make the open windows/activities appear larger when viewing them on Activities Overview mode by freeing up the space that is taken up by the dash. This could be an additional intellihide option. Usability-wise, it makes sense to hide the dash when Activities Overview is open since the focus of the user is on the activities/open windows not on the dock.

**Comment by micheleg** [comment] 2016-03-21 00:18
Closing as duplicate of #25.  However, I just uploaded an experimental branch with an attempt to enable this feature: https://github.com/micheleg/dash-to-dock/tree/experimental_autohide_in_overview

It's based on 3.14, but can be easily rebased on new releases. What version are you running? I'd like to get some feedback.

**Closed by micheleg** 2016-03-21 00:18 UTC

**Comment by vjcagay** [comment] 2016-03-21 03:00
I'm currently running Arch, so I'm currently running on Gnome 3.18. Since this is still an experimental feature I'm still not seeing this in my machine, but at least I can look forward having this feature in the near future. :+1:

**Comment by micheleg** [comment] 2016-03-21 13:46
I've uploaded a 3.18 branch too:  ```experimental_autohide_in_overview_3.18``` . Please have a look at it, I've already noticed some bugs, but I'm also interested on what could be the best implementation: what should the dock do in overview when intellihide is disabled? Should the windows view shrink similar to when the workspaces are slided in, or should the dock just cover the the view? ...

**Comment by micheleg** [comment] 2016-03-23 10:55
@vjcagay, did you have the chance to try the branch?

**Comment by RitwickVerma** [comment] 2018-01-16 10:58
hey @micheleg I am using ubuntu 17.10 with gnome shell 3.26.2. I tried out the branch `experimental_autohide_in_overview`
My shell stopped working completely and had blank screen after login. So I removed the extension manually and tried out the branch `experimental_autohide_in_overview_3.18.`
That one doesn't create issues with the shell and works. I was wondering if you could rebase it for the latest shell with the new features. I'd really like to have an option to hide dock in overview regardless of intellihide.

**Comment by micheleg** [comment] 2018-01-17 00:59
I have rebased the branch on master. Still not sure if and when this could be merged. Anyhow, having a rebased branch will simplify considering it.  This should solve the problem stated in "edit 2". Refardin "edit 1", it could be made an option too.

**Comment by RitwickVerma** [comment] 2018-01-17 07:28
Thanks a ton! it's working perfectly as expected. Regarding that option, do you think you can make it happen anytime? I'd love to see it as a feature and I believe many others would too.
Thanks again for taking out the time :+1:
