### ISSUE TITLE
Support per-display DPI scale factor

### ISSUE THREAD

**Issue by Rambden** [micheleg/dash-to-dock#1363] opened 2020-12-22 10:33 UTC
Currently dash-to-dock uses global scaling factor obtained from primary display, which leads to inadequate scaling factor on secondary displays.

GTK and Gnome shell already support per-display DPI under Wayland, so it would be nice to have it.

**Comment by vanvugt** [comment] 2022-11-29 08:13
Duplicate of #435

**Closed by vanvugt** 2022-11-29 08:13 UTC
