### ISSUE TITLE
Ubuntu Dock won't follow directions in Turkish

### ISSUE THREAD

**Issue by libreajans** [micheleg/dash-to-dock#1725] opened 2022-04-28 13:37 UTC
Hi, 

When I try to change Dock's position via "Position on screen" in Turkish, it won't follow my choice and do nothing. 

On the video, you can see I'm changing dock's position from center to left.

In Turkish Alt -> Bottom, Sol -> Left.

https://user-images.githubusercontent.com/6218679/165764202-66f43412-3315-4432-8872-b8e23f729c20.mp4

**Comment by 3v1n0** [comment] 2022-04-28 16:08
Duplicate of #1687

**Closed by 3v1n0** 2022-04-28 16:08 UTC
