### ISSUE TITLE
Hold Super to change Window

### ISSUE THREAD

**Issue by otavioschwanck** [micheleg/dash-to-dock#229] opened 2015-10-03 00:02 UTC
Hi,

I'm a big fan of dash to dock but i miss a extraordinary feature:

Hold super to change window, like Windows 7 or Unity.

This is a picture of the feature:

http://i2.wp.com/complete-concrete-concise.com/wp-content/uploads/2012/04/ubuntu-12.04-basic-unity-tutorial-dash-4-big.jpg

Hold the super button and press the window number to change.  Its extremely productive and this is only found in unity desktop and Cinnamon Icon Only Applet.

Is possible to implement this feature ?

**Comment by micheleg** [comment] 2015-10-03 12:15
Hi, this is duplicate of #6 and #46. It's still in my todo list, but I haven't managed to find the time to implement it yet. In case you don't know, this extension does what you ask https://extensions.gnome.org/extension/413/dash-hotkeys/, but I'm not sure if it is fully compatible with dash-to-dock.

**Comment by micheleg** [comment] 2015-10-03 12:16
Closing as duplicate.

**Closed** 2015-10-03 12:15 UTC
Labels: duplicate, Feauture request
