### ISSUE TITLE
[Feature request] Add dock to each monitor

### ISSUE THREAD

**Issue by samlehman617** [micheleg/dash-to-dock#297] opened 2016-03-22 16:54 UTC
Currently, the dock can only be used on one monitor, but it would be really convenient to have a dock on each monitor, not just one

**Comment by micheleg** [comment] 2016-03-23 10:54
Hi,

This has been asked for a long time, but I haven't managed to dedicate time to it, partially because it doesn't fit my workflow. I'm closing this as it is a duplicate of #37. Please follow this issue for future updates.

**Closed by micheleg** 2016-03-23 10:54 UTC
Labels: duplicate
