### ISSUE TITLE
Allow icons size > 64

### ISSUE THREAD

**Issue by samuelhumeau** [micheleg/dash-to-dock#150] opened 2015-03-27 06:00 UTC
Hi!

On my 3200x1800px screen, the icons are quite tiny, even with the size of "64".
I see on the xml schema that the range of the "dash-max-icon-size" is between 16 and 64. Is there a way to make it bigger?

Sam
![screenshot from 2015-03-26 22 49 46](https://cloud.githubusercontent.com/assets/4238961/6863284/de23487c-d40b-11e4-989d-dc9acc403984.png)

**Comment by region51** [comment] 2015-03-27 18:50
# Sorry For My Bad English
@micheleg, think would not hurt to increase the size to 96
![2015-03-27 21 19 22](https://cloud.githubusercontent.com/assets/10940138/6874622/c6af028a-d4c9-11e4-856e-cb48df0efb2d.png)

**Comment by micheleg** [comment] 2015-03-27 22:39
I've never thought to the problem of having too small icons, I wish I have such a screen... Just to clarify: are the icons smaller than the one in the standard dash (extension off). Also, I'm wondering if you are using the hidpi settings and if the problem is related to that, I mean if the there's some kind of doubling in size which is not applied.

**Comment by samuelhumeau** [comment] 2015-03-28 19:05
When the extension is off, the icons have the same size as the one of the favorite bar (when I go to the activity screen). I am using the hidpi scaling for gnome ("gsettings set org.gnome.desktop.interface scaling-factor 2"). 
This scaling let invariant dash to dock as well as the default favorite bar.

**Comment by micheleg** [comment] 2015-03-29 23:12
There's a 128pxmaxicon branch now, with the 128 and 96px options added. 

I'm not sure how it looks like, in particular on hidpi displays, as I'm not sure if all icons provide sizes higher than 64px.

**Comment by micheleg** [comment] 2015-04-02 23:14
This has been merged into master (03fc047f18ca28ced397d30136873af151481d61 and 975d2d5a914e62cdf595d63675755dcffcababd4 ) and in the gnome-3.14 branch.

**Closed by micheleg** 2015-04-02 23:14 UTC
