### ISSUE TITLE
Gnome 40.2 right click on running app icon in dock

### ISSUE THREAD

**Issue by Zappo-II** [micheleg/dash-to-dock#1478] opened 2021-07-14 09:28 UTC
The Pop Up displays in upper left corner on primary monitor instead of above the icon...
The Menu Items inside the popup are not interactive / operateable / clickable ...
The Pop Up won't close unless `alt-f2 r` ...

```
Jul 14 11:26:21 un-tuxedo gnome-shell[1770]: JS ERROR: Error: GSettings key preview-size-scale not found in schema org.gnome.shell.extensions.dash-to-dock
                                             _checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:563:23
                                             createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:515:30
                                             getPreviewScale@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/utils.js:337:41
                                             _getWindowPreviewSize@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/windowPreview.js:381:19
                                             _init@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/windowPreview.js:323:57
                                             _populateAllWindowMenu@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIcons.js:1149:32
                                             update@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIcons.js:1108:20
                                             _rebuildMenu@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIcons.js:1076:14
                                             popup@resource:///org/gnome/shell/ui/appDisplay.js:3565:14
                                             popupMenu@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIcons.js:419:20
                                             vfunc_button_press_event@resource:///org/gnome/shell/ui/appDisplay.js:3216:18
```

**Comment by qs5779** [comment] 2021-07-14 11:44
Same error occurs when clicking on settings from Extensions app.

**Comment by Zappo-II** [comment] 2021-07-14 11:59
Might be same issue as in #1475 ...

**Comment by mx-psi** [comment] 2021-08-14 17:13
https://github.com/micheleg/dash-to-dock/issues/1475#issuecomment-880138403 solved it for me

**Comment by ewlsh** [comment] 2021-10-05 05:00
Duplicate of #1475

See https://github.com/micheleg/dash-to-dock/issues/1475#issuecomment-880138403

**Closed by ewlsh** 2021-10-05 05:00 UTC
