### ISSUE TITLE
Opaque class is not applied to any real class

### ISSUE THREAD

**Issue by clobrano** [micheleg/dash-to-dock#752] opened 2018-06-08 12:27 UTC
Opaque class is used only to retrieve predefined opacity levels

This way, it is not possible to apply any change to other properties through css in opaque state.

**Comment by clobrano** [comment] 2018-06-18 07:04
@micheleg if there's anything I can do to speed the adoption of the patch we tested, don't esitate to tell me :)

**Comment by micheleg** [comment] 2018-06-23 14:36
Hi @clobrano. Have a look at the updated https://github.com/micheleg/dash-to-dock/tree/fix/opacity-class.
I have split the classes into an `.opaque` class that is to be used as a normal general-purpose class, and a  `.dummy-opaque` class from which only the alphas are taken (and the transparent classes respectively).

You mention in an email that there was some change in behaviour with the previous implementation. Can you confirm if this is still the case? I'm trying to avoid introducing unexpected regressions.

**Comment by clobrano** [comment] 2018-06-23 15:19
Hi @micheleg, yes I can still see some difference (opaque value is 0.1 less opaque than with the official version), however my test environment might not be the best for your purpose. Installing locally dash-to-dock, everything seems fine, while the difference that I saw was applying the changed files to the ubuntu's version of dash-to-dock, which is probably a little behind.

**Comment by micheleg** [comment] 2018-06-23 18:14
Ok, I have the feeling that's due to the theme or settings in Ubunut. I have committed the change to master [05436df4fbb].

**Closed by micheleg** 2018-06-23 18:14 UTC
