### ISSUE TITLE
dash-to-dock can't be used again

### ISSUE THREAD

**Issue by hehellooedas** [micheleg/dash-to-dock#1930] opened 2023-02-25 23:29 UTC
![image](https://user-images.githubusercontent.com/96963528/221384184-274a0881-21ce-425d-985a-453ec9520ddb.png)

After updating some days ago,dash-to-dock could be used on GNOME44.
However,when I update some rpm packages about gnome,it prompts the error again

**Comment by psgreco** [comment] 2023-02-26 12:37
I've seen the same regression, in Fedora it happens when you update from gjs-1.7.1-6 to 1.7.2-1. Downgrading back to gjs-1.7.1-6 makes dash-to-dock v76 works as expected

**Comment by psgreco** [comment] 2023-02-26 13:59
@hehellooedas the new failure seems to be related to the introduction of https://gitlab.gnome.org/GNOME/gjs/-/commit/a77a3b990e3a59b0e993f86836a92cc3ff9bc8ff in gjs 1.75.2, reverting that patch in gjs makes dash-to-dock work again. Although seems like the real solution is being handled in https://gitlab.gnome.org/GNOME/gjs/-/merge_requests/823. Added that patch locally and dash-to-dock works again too. So either way, seems like this will be solved soon.

**Comment by vanvugt** [comment] 2023-02-27 03:42
Duplicate of #1919

**Closed by vanvugt** 2023-02-27 03:42 UTC
