### ISSUE TITLE
Dashtodock conflicts with icons on Gnome desktop

### ISSUE THREAD

**Issue by danielcra** [micheleg/dash-to-dock#644] opened 2017-11-14 11:57 UTC
When I configure Gnome to show icons on the desktop, and dashtodock to extend on the left hand side of the screen, no auto hiding, then the dock overlays desktop icons after logging in. Once I click on any of the dock icons to start the first app, the desktop icons are magically moved to the right. The latter should happen right from the beginning. This is probably a matter of proper interaction between Gnome and dashtodock. See attached screenshots before and after clicking an app icon in the dock. I used a custom theme for the screenshots but the problem also occurs with the default theme (Adwaita). The problem also occurs regardless of whether I select RMB->keep aligned on the Gnome desktop.

Debian 9, Gnome 3.22, dashtodock 61

![virtualbox_2017-11-14_12-49-02](https://user-images.githubusercontent.com/10501139/32778729-4ce8724c-c93b-11e7-8212-b810f3ea0da8.png)
![virtualbox_2017-11-14_12-49-27](https://user-images.githubusercontent.com/10501139/32778730-4d10c648-c93b-11e7-9d5f-d796c8be2733.png)

test@debian:~$ dconf dump /org/gnome/shell/extensions/dash-to-dock/
opaque-background=true
custom-theme-running-dots-border-color='#ffffff'
shift-click-action='minimize'
shift-middle-click-action='launch'
extend-height=true
dock-fixed=true
custom-theme-running-dots-color='#ffffff'
click-action='minimize'
force-straight-corner=false
show-apps-at-top=true
preferred-monitor=0
multi-monitor=true
custom-background-color=true
custom-theme-customize-running-dots=true
show-favorites=true
apply-custom-theme=false
custom-theme-running-dots=true
unity-backlit-items=false
dock-position='LEFT'
custom-theme-shrink=true
background-opacity=0.80000000000000004
icon-size-fixed=true
background-color='#000000'
middle-click-action='launch'

**Comment by micheleg** [comment] 2017-11-15 22:36
As the desktop is drawn by nautilus, unfortunately there's no way we can control it from the extension. Closing as duplicate of #17.

**Closed by micheleg** 2017-11-15 22:36 UTC
Labels: duplicate

**Comment by danielcra** [comment] 2017-11-16 12:52
OK. For the record (people finding this later): there is a simple workaround. in Gnome Tweaktool, create an autostart entry for "Files" i.e. Nautilus, or any other application that you don't mind starting after login, and you will never see the problem again.
