### ISSUE TITLE
It Should have zoom in/out when hovering on an aap

### ISSUE THREAD

**Issue by omi10859** [micheleg/dash-to-dock#562] opened 2017-08-12 17:44 UTC
There should be a option to customize zoom in/out feature when hovering over an app in dock.

**Comment by micheleg** [comment] 2017-08-14 09:58
Can you please elaborate? I don't understand what's the behaviour you are describing.

**Comment by skoruppa** [comment] 2017-08-19 20:04
I think he is talking about something that is available in Plank/Docky or MacOS's dock. A simple zoomin animation when you hover over dock elements 

![dock_zoom](https://user-images.githubusercontent.com/899429/29489837-44389f46-852a-11e7-9432-05819da9f442.png)

I don't know if that is possible with your extension but this is one of things that I'm also missing :)

**Comment by micheleg** [comment] 2017-08-20 15:16
This is a duplicate of #357.

**Closed by micheleg** 2017-08-20 15:16 UTC
Labels: duplicate
