### ISSUE TITLE
too big gap between dock and workspace

### ISSUE THREAD

**Issue by stigman9393** [micheleg/dash-to-dock#2204] opened 2024-04-20 20:47 UTC
hello, i cant see any option to decrease gap on overview. for now its too big if i can compare it to default gnome dock. how to addjust?

![Zrzut ekranu z 2024-04-20 22-46-19](https://github.com/micheleg/dash-to-dock/assets/147590841/862ef4b0-3c9b-4c92-9d50-e68b34465dba)
default

![Zrzut ekranu z 2024-04-20 22-43-21](https://github.com/micheleg/dash-to-dock/assets/147590841/a0811a19-2692-4761-bb87-d5dd28245223)
dash to dock

**Comment by vanvugt** [comment] 2024-04-22 06:11
Do you mean dash-to-dock is too small now, or did the gap and the workspace shrink instead?

**Comment by pchmykh** [comment] 2024-04-23 19:44
Nope, I have the same. Whole activity overview desktop size is different with dash-to-dock enabled, attaching two whole desktop screenshots, one with dash-to-dock enabled and other disabled. It is not about size of the dock, it is about whole desktop overview size. Also, dash-to-dock dock is placed slightly differently unlike default dash, less gap between dash and bottom of the screen.
So I think bug report should be renamed to something like 'desktop overview size in activity menu differs with default one with dash-to-dock extension enabled'
![Screenshot from 2024-04-23 22-37-20](https://github.com/micheleg/dash-to-dock/assets/125208381/83f78c97-cfff-48bf-affd-e73f841001e5)
![Screenshot from 2024-04-23 22-37-04](https://github.com/micheleg/dash-to-dock/assets/125208381/8894290e-f7e3-4b91-b940-bde5bb5db453)

**Comment by masterdokuro** [comment] 2024-04-24 11:43
I've just upgraded to fedora 40 with gnome 46 & dash-to-doc v91 and I see the same problem.  Its very obvious when you have a white background behind the dash-to-dock (see screenshot below):

![Screenshot from 2024-04-24 12-39-59](https://github.com/micheleg/dash-to-dock/assets/148326796/15c613b2-0972-4ac9-9a55-54c3f991daf2)

Its almost like the icons are bottom aligned in the dash bar itself.  BTW... if you look at the application icons (bar right in the screenshot) its positioned correctly.

Prior to upgrade (fedora 39, gnome 45 & dash-to-doc v91) I did not have this problem.

**Comment by masterdokuro** [comment] 2024-04-24 13:39
> No icon issues for me. Maybe another issue?

Never mind.  I removed the extension and added it again which has fixed the icon problem I was having.  Sorry for wasting time, I should have tried this first.

**Comment by pchmykh** [comment] 2024-04-24 15:52
> > No icon issues for me. Maybe another issue?
> 
> Never mind. I removed the extension and added it again which has fixed the icon problem I was having. Sorry for wasting your time, I should have tried this first.

just delete ur comments

**Comment by 3v1n0** [comment] 2024-04-24 18:11
So, IIRC the reason why this space has been added was to make the application labels to be visible (and centered) when hovering a window.

I see that it's different in default dash, but complexity of options that we have lead to have a different behavior of the windows.

**Comment by stigman9393** [comment] 2024-04-27 18:17
> So, IIRC the reason why this space has been added was to make the application labels to be visible (and centered) when hovering a window.
> 
> I see that it's different in default dash, but complexity of options that we have lead to have a different behavior of the windows.

but can i change it ? which line of css is to change this property?

**Comment by pchmykh** [comment] 2024-04-27 18:25
I think default size looks more clean also.

**Comment by stigman9393** [comment] 2024-04-27 18:32
> So, IIRC the reason why this space has been added was to make the application labels to be visible (and centered) when hovering a window.
> 
> I see that it's different in default dash, but complexity of options that we have lead to have a different behavior of the windows.

but can i change it ? which line of css is to change this property?


> I think default size looks more clean also.

yes, me too. dash to dock gap looks little bit weird if all elements have a different gap like for example search bar have rly small gap and dash to dock completly different like 50px

**Comment by vanvugt** [comment] 2024-06-04 05:35
Duplicate of #1815

**Closed by vanvugt** 2024-06-04 05:35 UTC
