### ISSUE TITLE
Minimize or Raise window on Left click on app icon

### ISSUE THREAD

**Issue by danfmaia** [micheleg/dash-to-dock#2011] opened 2023-05-17 02:22 UTC
Is it possible to set the action of "Minimize or Raise window(s)" on Left click on app icon?

That is, if one or more windows of an are open, the click will minimize them all.

And if no window is open, the click will raise only the previously open windows. This click won't maximize all the app windows, as it does when the current "Behavior > Click action" setting is set to "Minimize".

**Comment by vanvugt** [comment] 2023-05-18 08:15
Duplicate of #365

**Closed by vanvugt** 2023-05-18 08:15 UTC
