### ISSUE TITLE
Show minimised windows in the dock

### ISSUE THREAD

**Issue by kprinssu** [micheleg/dash-to-dock#551] opened 2017-07-18 16:33 UTC
In my opinion a good macOS dock feature is the displaying minimised windows in the dock. 
An example of the feature I am requesting is shown in this screenshot:  https://i.stack.imgur.com/vyTSu.jpg

In the above screenshot, you can see a preview of the minimised "Safari" window in the dock. 

Is this possible to do in dash-to-dock? If not, can this feature be added to dash-to-dock?

**Comment by Cookie74** [comment] 2017-07-18 20:03
It would be nice.

**Comment by micheleg** [comment] 2017-07-21 21:27
I have mixed feeling about this feature. Anyhow, this is a duplicate of #201.

**Closed by micheleg** 2017-07-21 21:27 UTC
Labels: duplicate
