### ISSUE TITLE
option: activity overview button

### ISSUE THREAD

**Issue by naldir** [micheleg/dash-to-dock#212] opened 2015-08-28 18:42 UTC
Option to add an activity overview button under the appMenu button in the dash

**Comment by micheleg** [comment] 2015-09-05 13:18
Could you explain what the button would do and where you would place it?

**Comment by naldir** [comment] 2015-09-09 17:39
The first icon on the dock is a shortcut to show applications.
I would like an optional activities overview shortcut to be the 2nd element
of the dock. It would lead to the activities overview that is already
accessible via the super keyboard shortcut.
Because on default gnome-shell the dash is only accessible in the
activities overview, it is not useful in default gnome-shell but the dock
instead is always showed and it could be useful (at least for me but also
for many others i think) to add a shortcut to the activities overview just
beside the show applications shortcut.
I would place it just below the show applications shortcut when the dock is
in vertical mode and just on the right of the show applications shortcut
when the dock is in horizontal mode

**Comment by micheleg** [comment] 2015-09-11 18:30
I think this is duplicate of #158, thus closing.

**Closed by micheleg** 2015-09-11 18:30 UTC
Labels: duplicate, Feauture request
