### ISSUE TITLE
Incompatible for Ubuntu 22.04

### ISSUE THREAD

**Issue by ashukumar2021** [micheleg/dash-to-dock#1698] opened 2022-04-05 07:48 UTC
![image](https://user-images.githubusercontent.com/86044488/161704953-614998d1-af0c-48e7-a78a-93151c97ffd0.png)

**Comment by pled** [comment] 2022-04-05 09:50
Yes, same here with Debian testing. Just ran apt update, got Gnome 42, et voilà ! ;)
Any expected date for Gnome 42 support ? or anyway to get dash-to-dock running ?
Thanks !

**Comment by carneeki** [comment] 2022-04-05 11:46
@pled I just noticed there's a PR mentioned in issue #1679 and it might help. As for an expected date, I imagine the author(s) are still testing stuff - #1692 is asking for a tag so it can be packaged, so I'm hoping soon!

**Comment by pled** [comment] 2022-04-05 13:46
@carneeki Thank you, I installed [#1692](https://github.com/micheleg/dash-to-dock/issues/1692) and it looks good so far...

**Comment by yashrathi-git** [comment] 2022-04-07 03:58
Hey @carneeki 
I tried installing it. I am having sticky icon indicator labels. @pled do you have the same issue?

**Comment by pled** [comment] 2022-04-07 09:13
@[yashrathi-git](https://github.com/yashrathi-git) : no, I only had to change the "Customize windows counter indicators" under Appreance to Dots instead of Default, as described [here](https://github.com/micheleg/dash-to-dock/issues/1679).

**Comment by yashrathi-git** [comment] 2022-04-07 09:54
it was probably an issue with gnome. Recent mutter update on arch seems to have fixed this issue.

**Comment by 3v1n0** [comment] 2022-04-11 13:42
Duplicate of #1692

**Closed by 3v1n0** 2022-04-11 13:42 UTC

**Comment by mukash** [comment] 2022-08-24 08:45
GNOME 42 compatible alternative

https://extensions.gnome.org/extension/4703/dock-from-dash/
