### ISSUE TITLE
Middle click to close does not function properly

### ISSUE THREAD

**Issue by dfkamm** [micheleg/dash-to-dock#517] opened 2017-06-09 19:27 UTC
Since updating to v59, I can no longer middle click to close applications. I have middle click action set to close, but when I middle click, instead of closing, the window will minimize, or if I have more than one instance of the program open, bring up the Gnome overview.

This is on Ubuntu Gnome 16.04.2 with Gnome Shell version 3.18.5

**Comment by franglais125** [comment] 2017-06-09 19:36
I can confirm this. This is due to the introduction of the "minimize or overview" feature.
The reason is this option was not included in the advanced click options.

A fix for this was already included in the click-preview PR: https://github.com/micheleg/dash-to-dock/pull/504

**Comment by micheleg** [comment] 2017-06-09 20:21
Thanks you for the bug report and for the fix! I've merged it into master [877cbd9].

**Closed** 2017-06-09 20:20 UTC
