### ISSUE TITLE
Intelli auto-hide overlaps legacy status tray

### ISSUE THREAD

**Issue by alex285** [micheleg/dash-to-dock#219] opened 2015-09-06 04:10 UTC
GNOME 3.17.91 and dash-to-dock 3.17 branch.

**Comment by micheleg** [comment] 2015-09-06 20:24
Hi, thanks for testing the extension with the development branch. I need more info: what's wrong exactly? Is is a bug specific to GNOME 3.17.91 ?

**Comment by alex285** [comment] 2015-09-07 20:35
It only happens when Intelli-hide is enabled. 
The arrow to close the tray is hidden behind Dash-to-Dock sidebar.  

![overlap](https://cloud.githubusercontent.com/assets/11244308/9722612/f5f1cb2a-55b8-11e5-9a9c-7446e5834be9.png)

**Comment by micheleg** [comment] 2015-09-11 17:59
Same problem in 3.16. Unfortunately I don't know what to do with the legacyTray. Given the limited amount of time, I honestly don't want to put effort on something which is being deprecated and might sooner or later disappear. The tray is moved with the autohide disabled though. With other settings, I recommend the topicon extensions [https://extensions.gnome.org/extension/495/topicons/]

I close this as it is somehow a duplicate of #168, and not related to the upcoming upstream release.

**Closed by micheleg** 2015-09-11 17:59 UTC
