### ISSUE TITLE
Can't adjust padding between dock icons no matter by what method I try

### ISSUE THREAD

**Issue by calindan2013** [micheleg/dash-to-dock#1982] opened 2023-03-29 11:00 UTC
Is there any way to adjust this waste of screen real estate between the icons ? That's excessive spacing between dash icons. I'm using default Adwaita and GNOME 3.38

**Comment by 3v1n0** [comment] 2023-04-12 17:43
mh, what is the css you have used?

That's the only way dash-to-dock is themed.

**Comment by joaocandre** [comment] 2023-07-02 16:10
I'm also curious about this, default theme has excessive padding.
There was a [workaround](https://github.com/micheleg/dash-to-dock/issues/844) some years back, but it doesn't work anymore.  Considering `stylesheet.css` has 1000+ lines of code, some input by the developers would be helpful.

**Comment by joaocandre** [comment] 2023-07-03 14:27
As a current workaround, some themes like [WhiteSur](https://github.com/vinceliuice/WhiteSur-gtk-theme) override the default theming done in `stylesheet.css` and achieve a much more compact look; looking through their config (check `gnome-shell.css`, there are some `dashtodockContainer` settings there with 0 padding) and with the help of some tool like [Gradience](https://github.com/GradienceTeam/Gradience), @calindan2013 you may be able to reverse engineer the required configs.

As a suggestion to the developers, along with the existing option to shrink the dash, one could also have an additional parameter of how much % to shrink it.

**Comment by vanvugt** [comment] 2024-03-28 01:41
Duplicate of #844.

**Closed by vanvugt** 2024-03-28 01:41 UTC
