### ISSUE TITLE
Most maximized applications are resized after unlock

### ISSUE THREAD

**Issue by gyeben** [micheleg/dash-to-dock#454] opened 2017-03-20 22:38 UTC
After locking and unlocking my computer, most maximized applications are resized.

It also happens with no other extensions enabled.
I am using Fedora 25, Gnome 3.22 with Wayland and the latest version of dash-to-dock.

![kepernyokep errol 2017-03-20 23-32-49](https://cloud.githubusercontent.com/assets/2202350/24124926/3dfe09d0-0dc6-11e7-9161-a5c044cef516.png)
![kepernyokep errol 2017-03-20 23-32-57](https://cloud.githubusercontent.com/assets/2202350/24124925/3dfcb706-0dc6-11e7-9e02-46ee4fc6130b.png)

**Comment by franglais125** [comment] 2017-03-20 23:08
I think this is a duplicate of https://github.com/micheleg/dash-to-dock/issues/423

Also, I can confirm this problem after unlocking. Debian Stretch, Wayland, Gnome 3.22.

**Comment by micheleg** [comment] 2017-03-21 00:20
Even in current master? Only under Wayland?

**Comment by franglais125** [comment] 2017-03-21 01:53
Yes, I'm always running master :). Let me give it a try on X as well, as I haven't used it in a while (Wayland is quite pleasant!).

As a side note, let me add that this is not 100% reproducible. It just seems to happen sometimes after a screen unlock (maybe 1/10 times). I'll try to pay more attention and see if I can get a pattern... I wasn't too bothered by this.

**Comment by gyeben** [comment] 2017-03-21 12:10
It only happens under Wayland.

**Comment by franglais125** [comment] 2017-03-21 21:26
In my case too it seems to happen only under Wayland. And now that I'm paying attention, it happens much more often than I thought: roughly 50% of the times many of the maximized windows will get resized (but not necessarily all).

Also, the problem only occurs with native Wayland applications. Is this the case for you too, @gyeben ? For example, I never see this happen with Firefox, Thunderbird or VLC.

**Comment by franglais125** [comment] 2017-03-21 21:35
Another way of triggering something similar, is by successively disabling/enabling dash-to-dock from the Tweak tool (with all other extensions turned off). It's not even necessary to do it quickly, just doing it a few times will sometimes yield the wrong window size for native Wayland applications (if maximized).

i guess this is due to the dash spacer that is introduced when enabling the extension.

**Comment by gyeben** [comment] 2017-03-22 00:19
@franglais125: yeah, it seems like only the native Wayland applications are affected.

**Comment by franglais125** [comment] 2017-09-27 07:12
I have a proposed fixed here: https://github.com/franglais125/dash-to-dock/tree/fix_maximize_unlock

Could somebody give it a try to confirm this, and make sure there are no regressions?

Commit: https://github.com/franglais125/dash-to-dock/commit/0ab02b068d901fd0f94da8ff02e425b02d376be1

**Comment by tjaalton** [comment] 2017-09-30 06:34
seems to fix it for me, thanks!

**Comment by franglais125** [comment] 2017-10-01 13:37
@tjaalton Thanks for the feedback! I just updated the branch after Michele's comments. It is working on my system, but if you can re-confirm this it would be great.

**Comment by micheleg** [comment] 2017-10-01 14:02
The fix is now in master [fd81051ee0ae8320e], please check if it works for you.

**Comment by didrocks** [comment] 2017-10-03 12:00
I just cherry-pick and tested this in ubuntu. I confirm it's working well. Thanks @franglais125 & @micheleg :)

**Closed** 2017-10-04 21:53 UTC
Labels: bug
