### ISSUE TITLE
Non-pinned apps sometimes have very low resolution highlights

### ISSUE THREAD

**Issue by stuarthayhurst** [micheleg/dash-to-dock#2002] opened 2023-04-29 16:57 UTC
Sorry if this is a duplicate, I feel like I've seen this mentioned before, but I couldn't find any issues related to it.

Opening an app that I don't have pinned to the dash will cause the highlight / border to be very low resolution. This resolution isn't consistent either, sometimes it's VERY low res, and other times it's *almost* the right resolution. In any of these cases, hovering over the dash causes the correct resolution to be selected. I've tested this with different icon themes including Yaru and Adwaita, with no improvement.

I'm currently running X11 on GNOME 44 (Debian Experimental), but this definitely happened on GNOME 43. I can't remember if this was present on Wayland (I can test if this is important), and it's been present for quite a while, I only just got round to reporting it.

Example:
![image](https://user-images.githubusercontent.com/33733427/235314433-f1c87b41-82f0-4988-a371-b2e81d7f9de0.png)

**Comment by vanvugt** [comment] 2023-05-15 08:05
Duplicate of #1817

**Closed by vanvugt** 2023-05-15 08:05 UTC
