### ISSUE TITLE
Recycle Bin dialog box promt shows in random places

### ISSUE THREAD

**Issue by sergiotca** [micheleg/dash-to-dock#1880] opened 2022-11-21 18:58 UTC
![Captura desde 2022-11-21 13-04-56](https://user-images.githubusercontent.com/41351896/203138456-ae3326b7-160e-4be0-b2f8-422c9f755979.png)

Since I updated to gnome 43 the recycle bin dialog (the prompt that asks you to confirm if you want to empty the bin) shows in line of all other open windows, which forces it to appear on whatever available space it can find on the desktop:
[Example of the issue](https://user-images.githubusercontent.com/41351896/203136873-71759322-b280-40de-b63e-d0e9d9ad78b2.webm)

Previously this dialogue box used to appear on top of everything else, always centered in the middle of the screen. 
For me this was the more sensible behavior since it was a consistent UI design. 
Is this something we can return to?

Using:
-Manjaro
-Gnome v43.1 & X11
-Dash to Dock Extension: v75

**Comment by lfom** [comment] 2022-11-27 14:42
This is a Gnome thing, by default Gnome places new windows using the "empty" space, as close as possible to the currently active window... You can use Gnome Tweaks to enable "Center New Windows" for a more sane behavior.

**Comment by sergiotca** [comment] 2022-11-28 18:41
@lfom Thank you buddy, I ended up using tweaks to force the new windows to launch centered. It feels more logical for my workflow.

**Comment by lfom** [comment] 2022-11-29 10:34
@sergiotca Great. Probably it's a good idea to close the issue then, since it's not a problem caused by Dash to Dock. Thanks.

**Closed** 2022-11-29 22:52 UTC
