### ISSUE TITLE
Add window ungrouping + label feature like Windows 10?

### ISSUE THREAD

**Issue by mattrbonnette** [micheleg/dash-to-dock#688] opened 2018-02-11 01:09 UTC
Would it be possible for you to add an option for ungrouping windows of multiple instances of windows.
Could you also add labels to the icons like how Windows 10 does it.

I know I'm asking a lot, but this is something I cannot do on my own.

![image](https://user-images.githubusercontent.com/22666756/36068218-224b070e-0e9e-11e8-83e9-0e24f243a89b.png)

The first thing, not the second.

**Comment by micheleg** [comment] 2018-03-04 00:43
Closing as duplicate of #108. To be honest I don't think this is the kind of multi-instance behaviour I'm interested to implement, but thanks for the suggestion. Please refer to #108 for further discussions.

**Closed by micheleg** 2018-03-04 00:43 UTC
Labels: duplicate
