### ISSUE TITLE
[Bug] Maximized windows periodically become hidden behind dock

### ISSUE THREAD

**Issue by venteto** [micheleg/dash-to-dock#1396] opened 2021-03-12 18:40 UTC
I haven't noticed any pattern to triggering this bug, like how long a window has been open, after screen blanking, etc. It seems very random.

The only way I can fix the affected window is to unmaximize it, then maximize it again.

I'm using GNOME 3.38.3 on on Wayland on Manjaro Linux, and Intelligent autohide is disabled in my Dash To Dock settings (the dock is always visible).

The screenshot with the arrow shows the bug, the other screenshot shows the window in a normal state (its left edge not hidden behind the dock):
![dash-to-dock-problem](https://user-images.githubusercontent.com/7062385/110983588-ef876580-8337-11eb-9cfe-8cdcc0396d6d.png)

![dash-to-dock-problem-normal](https://user-images.githubusercontent.com/7062385/110983613-f7dfa080-8337-11eb-817e-28163152ab0c.png)

Any ideas how I could stop this? Thanks!

**Comment by crosscodr** [comment] 2021-03-17 10:29
Hi!
I can confirm this bug. On my side it is fully reproducible: When I use additional screens with my notebook, this error occurs every time when I lock the screens (e.g. <Super> + L) and unlock it later. After unlocking, maximized windows are placed behind the dock.
However, this happens only to windows placed on secondary screens.

I'm on Fedora 33 with Gnome 3.38.4 on Wayland.

**Comment by derrgill** [comment] 2021-03-17 12:55
For what it's worth, I am not using any secondary screens, just the laptop screen (Lenovo ThinkPad T15).

**Comment by vanvugt** [comment] 2021-03-18 08:17
Duplicate of #1370, which is a duplicate of https://gitlab.gnome.org/GNOME/mutter/-/issues/1627

**Comment by LuccoJ** [comment] 2022-10-24 14:47
Except that GitLab issue focuses on applications hiding under the standard panel, which apparently now only happens to Ubuntu users, and I'm on Fedora but this has been a continuing issue now for years. I don't know how to tell my parents, who aren't that great with computers, that this will likely stay because the extension blames GNOME and GNOME blames the extension...

**Comment by vanvugt** [comment] 2022-10-31 09:59
Duplicate of #1370

**Closed by vanvugt** 2022-10-31 09:59 UTC
