### ISSUE TITLE
Autohide not working properly on maximized Mozilla applications on external display

### ISSUE THREAD

**Issue by joaocandre** [micheleg/dash-to-dock#2178] opened 2024-03-27 01:18 UTC
I've noticed that the "Intelligent autohide" feature doesn't seem to work properly when Firefox and Thunderbird  are *maximized* on a second/external display.
As as the animation finishes, the dock disappears, and afterwards is only shown for a brief instant *only* on mouse movement, leading to an annoying "blinking" effect.

Tested on Archlinux, Firefox 124 and Thunderbird 115, and it happens in Gnome 45 and 46 as far as I'm aware.
 I'll try to add a screencast reproducing this issue as I'm able to.

**Comment by vanvugt** [comment] 2024-03-27 05:01
Duplicate of #1381

**Closed by vanvugt** 2024-03-27 05:01 UTC
