### ISSUE TITLE
Apps Launcher does react strangely on Touch Screens

### ISSUE THREAD

**Issue by Wotanhaecker** [micheleg/dash-to-dock#408] opened 2016-11-27 06:30 UTC
I am using Antergos, GNOME and obviously Dash to Dock on a XPS13, which has a Touch Display. When i open the application launcher with the mouse, everything works fine. But often (not always) when i touch it with the touch display, it starts the animation but the icons got hide immediatelly. this behaviour also correlates strangely to the application launcher on the top menue bar.

It's nearly impossible to explain, so i made a video and uploaded it on youtube, see here:
https://youtu.be/A-PRok7eiMw

**Comment by micheleg** [comment] 2016-11-29 22:36
It looks like a duplicate of #196. Also see #128. It's very difficult for me to debug, I don't have a touchscreen.

**Closed** 2017-02-04 01:21 UTC
Labels: duplicate
