### ISSUE TITLE
Manual gnome session lock hides icons in dock and freezes activities menu

### ISSUE THREAD

**Issue by jbravo94** [micheleg/dash-to-dock#1663] opened 2022-01-29 10:19 UTC
Dear Maintainers,

i experience following issue:

When i manually lock the Gnome Session and log back in all icons disappear in the dock except applications icon.
When i afterwards go to activities top left, the Gnome Session freezes - only system menu is possible where i need to log out and login again to reset the dock.

Looks like this issue only appears when no application window is open.

Default Dock:
![Screenshot from 2022-01-29 10-33-19](https://user-images.githubusercontent.com/26746017/151656873-5c588032-dde5-4cb8-9d5e-0c59bc43316e.png)

After Locking the Session (top right menu) and logging in again:
![Screenshot from 2022-01-29 10-32-49](https://user-images.githubusercontent.com/26746017/151656871-52eb2177-c705-4214-841b-a5445df2406d.png)

After opening Activities it cannot be exited and stays like this:
![Screenshot from 2022-01-29 10-33-00](https://user-images.githubusercontent.com/26746017/151656872-4e966a2c-334f-4c50-b9de-867c6f1f431a.png)

System Information:

- Ubuntu 21.10
- Gnome 40.4.0
- Dash to Dock v70 installed via Browser Extension https://extensions.gnome.org/extension/307/dash-to-dock/

Configuration:
- Default

I think solving this issue would improve the Desktop experience for normal users.

BR,
Johannes

**Comment by linuxbastler** [comment] 2022-02-03 19:56
I have the same configuration (Ubuntu 21.10 ...) and the same issue here.
Activities cant be exited. 
The only way to get out of this hang is to restart the session with Alt-F2 + r

**Comment by ethan-halsall** [comment] 2022-02-08 16:28
Same on fedora 35

**Comment by sher1** [comment] 2022-02-08 23:26
I also have this issue
Ubuntu 21.10
Gnome 40.5-1
Kernel: 5.13.0-28-generic

I remember having this problem before with a previous version of Gnome also

**Comment by Demon-tk** [comment] 2022-10-19 15:41
I have the same issue.
Ubuntu 22.04
Gnome 42
Kernel 5.15.0-50-generic

When clicking "show applications" the screen will hang on a grey page with no loaded activities or programs. I have to log out and log in to interact with the computer again (I can see the time moving and I can move my mouse).

**Comment by simone-romiti** [comment] 2023-03-12 18:38
I had the same issue on Ubuntu 22.04.02. I solved deactivating the `ubuntu dock` extension. 
I think that the `dash-to-dock` should at least give a warning if detects that `ubuntu dock` is installed.

**Comment by vanvugt** [comment] 2023-03-13 01:18
Duplicate of #1522

**Closed by vanvugt** 2023-03-13 01:18 UTC
