### ISSUE TITLE
Strange behaviour on application menu animation & scrolling

### ISSUE THREAD

**Issue by Lukypie** [micheleg/dash-to-dock#309] opened 2016-05-01 17:37 UTC
It's a bit hard to explain this bug, but I'm getting this odd behaviour clicking on the application menu.
It happens with no specific reason randomly. With the animation disabled, sometimes, I'm unable to scroll with dragging the mouse or using the mouse wheel, unless I click on the activity or i press the super button, and as you can see then there is the menu animation, where it shouldn't be. 
Yes I have disabled the animation because is too laggy, but it is also enabled when I click it from the activities menu. (That can be another problem)

[2016-05-01 19-29-55.flv.zip](https://github.com/micheleg/dash-to-dock/files/244243/2016-05-01.19-29-55.flv.zip)

**Comment by Lukypie** [comment] 2016-05-01 17:43
I'm running GNOME 3.20 on ArchLinux

**Comment by micheleg** [comment] 2016-05-08 22:41
Hi, sorry for the late reply.

What do you exactly means with "animation disabled"? Are you referring the the extension option or to a global settings?

> Yes I have disabled the animation because is too laggy, but it is also enabled when I click it from the activities menu. (That can be another problem)

Are you saying that the extension ignore such global disable animation settings?

**Comment by Lukypie** [comment] 2016-05-09 04:31
Yes, the one from the extension

**Comment by micheleg** [comment] 2016-05-11 23:15
I can't reproduce the bug on my system. Do you have other extension installed or some strange configuration. If so, could you test it in a  more "clean" system?

**Comment by Lukypie** [comment] 2016-05-15 15:59
Nope, but I'll try on a fresh user maybe also recording.

**Comment by Lukypie** [comment] 2016-05-17 18:26
Sei italiano suppongo quindi scrivo in ita, è abbastanza difficile da spiegare dal momento che accadono diverse cose strane. Innanzitutto ho creato un nuovo utente e fin qui tutto ok, messo l'estensione e disabilitato le animazioni come faccio di solito dal menu di dashtodock, il problema non si presenta, 
dopo non so quale motivo però le animazioni tornano a funzionare SOLO se sono nel in attività e clicco sul menu, e oltre a questo casualmente appare il problema di cui ho allegato il video nel thread principale.

**Comment by Lukypie** [comment] 2016-05-17 18:27
Cerco di spiegarmi meglio, giorni fa ho creato un nuovo utente e oggi il problema si è ripresentato

**Comment by micheleg** [comment] 2016-05-19 22:19
Yes, I understand. Not deterministically reproducible bugs are the most difficult to solve.... Are you running Wayland by any chance? 
You could help by looking for some relevant errors in the logs (some instructions here: https://micheleg.github.io/dash-to-dock/development.html#bugreporting)

**Comment by Lukypie** [comment] 2016-05-27 10:22
No, never used wayland. This problem is halso appening in Ubuntu like in Arch Linux. like I said

dconf dump /org/gnome/shell/extensions/dash-to-dock/

apply-custom-theme=false
preferred-monitor=0
custom-theme-shrink=false
animate-show-apps=false
click-action='minimize'
dock-position='BOTTOM'
show-apps-at-top=false

No errors in lg, the problem seems not to be resolved by resetting the dconf of the extension. I didn't find any on .xsession-errors or with journalctl

**Comment by Lukypie** [comment] 2016-05-27 10:32
Another couple of videos, as you can see, the problem seems to be related to this strange animation behaviour on my user, and with another user I created, that's the fourth time I re-create my user but the problem seems to come after some days. Basically, if the animation is still enabled on the activity when I click on the menu from there, the problem that I showed you in the first video of the thread is still happening.
[filmati.zip](https://github.com/micheleg/dash-to-dock/files/286278/filmati.zip)

**Comment by micheleg** [comment] 2016-05-27 23:19
First, the fact that the animation still happen from inside the overview even with the settings off is the expected behaviour (https://github.com/micheleg/dash-to-dock/issues/200#issuecomment-143371597); this is the behaviour of video 1. Instead on video 2 the behaviour seems reversed.

When you say it happens after few days, does it means after few days of use or after few days of not restarting the shell. In other words, does restarting the shell solve the problem temporary?

**Comment by Lukypie** [comment] 2016-05-28 06:27
After few days of daily use, that means multiple computer restarts. That animation seems to come from nowhere together with this "problem"

**Comment by Lukypie** [comment] 2016-05-28 19:42
In detail, the problem is that animation where it shouldn't be, and the other "behaviour" which I showed you in the first video on the first post.

**Comment by jderose9** [comment] 2017-03-19 21:31
I haven't tried to resolve it yet, but this was reported on my fork with steps to reproduce: https://github.com/jderose9/dash-to-panel/issues/40

> - go with the mouse to the top left corner or press the Windows key
> - search for some application and launch it
> - open applications menu with the "Show Applications" button that dash to panel provides
> - applications are not scrollable

**Comment by franglais125** [comment] 2017-03-19 21:51
@jderose9 I managed to consistently reproduce this with the steps you described, on dash-to-dock.
In my case, it only happens when I disable the animation on the "Show Applications" button.

Debian Stretch, Gnome Shell 3.22.

**Comment by jderose9** [comment] 2017-03-19 21:55
I think I fixed it.. I'm not sure the exact issue but it just seems like the active page was getting out of sync so I followed the same logic as when animation was enabled.

https://github.com/jderose9/dash-to-panel/commit/afb92f9c1382a76e9f8c200df84c56d6f9a51cf6

**Comment by franglais125** [comment] 2017-03-19 22:15
Thanks @jderose9 ! I prepared a patch for this for dash-to-dock. In my testing at least, the problem is fixed.

https://github.com/franglais125/dash-to-dock/tree/fix_icon_grid

**Comment by jderose9** [comment] 2017-03-19 23:31
Awesome​, thanks @franglais125!

**Comment by micheleg** [comment] 2017-03-21 00:49
Wonderful! 
I've merged it into master [51b709cb32fa7b]. Thank you @jderose9 @franglais125 !

**Closed by micheleg** 2017-03-21 00:49 UTC
