### ISSUE TITLE
isolate workspaces

### ISSUE THREAD

**Issue by vendforce** [micheleg/dash-to-dock#403] opened 2016-11-13 09:51 UTC
When you enabled it , when scrolling through workspaces that dont have any applications open the workspaces gives pop out animation .. what is the reason for this , is it to tell the user that there is no open applications on that workspace I dont think it is of any use .. and only a distraction it would be better to have the workspaces to stay static when scolling through them whether they have applications open or not

for example if I have appliactions open on workspace 1,2,4,6 when scrolling through 2,4,6 it gives a pop out animation on workspace 3 & 5 , I see of no use this has,only of distraction could you please remove this

dash to dock is a great extension keep up the great work

**Comment by micheleg** [comment] 2016-11-13 19:51
Hi, 

I don't understand what you are referring to when you say "workspace gives pop out animation". Can you explain it further?

**Comment by vendforce** [comment] 2016-11-16 08:13
If you press the windows key or click activities corner you see the workspaces on the right,  now go and open some applications on desktop 4 and 5 and then start from one and scroll down you will see as your scrolling from 1,2,3 nothing happens but when you get to 4 the workspaces pops out

**Comment by franglais125** [comment] 2016-11-17 00:14
@vendforce It seems that that's the default Gnome-Shell behaviour, unless I'm misunderstanding.

If you disable dash-to-dock, you still get the same "issue" (although it seems to be like that by design). At least in my testing, "isolate workspaces" didn't change anything, and disabling the extension altogether again presented the same behaviour.

**Comment by micheleg** [comment] 2017-01-17 23:49
I'm closing this as it seems the default behaviour, not a bug.

**Closed by micheleg** 2017-01-17 23:49 UTC
Labels: invalid
