### ISSUE TITLE
Dock show when a context menu is shown (and prevent using it)

### ISSUE THREAD

**Issue by noirbizarre** [micheleg/dash-to-dock#2037] opened 2023-06-09 16:39 UTC
Hey 👋🏼 

First, great extension 👏🏼 

I have an issue which is highly counter-productive:

When "Show dock for urgent notifications" is enabled in intellihide settings, whenever you open a context menu, Dash to dock doesn't consider the current window focused and show. This is problematic for any chat application where the entry field is at the bottom of the window because when you right-click to fix a typo for example, dock show and prevent seeing and clicking the menu

Here's an example with Telegram when trying to pick a suggested typo fix:
![image](https://github.com/micheleg/dash-to-dock/assets/15725/39f5f3b1-3ed0-45db-a933-2f0f8f337245)

Unchecking "Show dock for urgent notifications" fix this behavior

**Comment by vanvugt** [comment] 2023-06-13 06:13
This should have been fixed in extension version 82, duplicate of issue #1887?

**Comment by vanvugt** [comment] 2023-06-19 09:16
Duplicate of #1887

**Closed by vanvugt** 2023-06-19 09:16 UTC
