### ISSUE TITLE
JS ERROR: TypeError: DockManager.getDefault() is null

### ISSUE THREAD

**Issue by theogjlaw** [micheleg/dash-to-dock#2155] opened 2024-03-02 09:51 UTC
Having an issue with dock-to-dash errors that seem to be the same as what was described at https://github.com/micheleg/dash-to-dock/issues/1444

Here is what the log shows. I'm on gnome 45 on Clear Linux.  Was there a fix for this that I can refer to. Sorry if there is an answer out there - couldn't find one.

JS ERROR: TypeError: DockManager.getDefault() is null
get settings@file:///home/theogjlaw/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1723:28
updateNotificationBadgeStyle@file:///home/theogjlaw/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIconIndicators.js:745:33
_unloadExtensionStylesheet@resource:///org/gnome/shell/ui/extensionSystem.js:150:15
_callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:207:14
_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:619:24
async*_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:799:20
ExtensionManager/<@resource:///org/gnome/shell/ui/extensionSystem.js:44:18
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_sync@resource:///org/gnome/shell/ui/sessionMode.js:212:14
pushMode@resource:///org/gnome/shell/ui/sessionMode.js:170:14
activate@resource:///org/gnome/shell/ui/screenShield.js:617:34
_onLongLightbox@resource:///org/gnome/shell/ui/screenShield.js:340:18
onComplete@resource:///org/gnome/shell/ui/lightbox.js:202:18
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:86:13
_easeActor@resource:///org/gnome/shell/ui/environment.js:175:17
Clutter.Actor.prototype.ease@resource:///org/gnome/shell/ui/environment.js:297:15
lightOn@resource:///org/gnome/shell/ui/lightbox.js:214:18
_activateFade@resource:///org/gnome/shell/ui/screenShield.js:306:18
_onStatusChanged@resource:///org/gnome/shell/ui/screenShield.js:301:14
ScreenShield/<@resource:///org/gnome/shell/ui/screenShield.js:89:18
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_convertToNativeSignal@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:152:19
@resource:///org/gnome/shell/ui/init.js:21:20

**Comment by vanvugt** [comment] 2024-03-05 06:50
Duplicate of #1444

**Closed by vanvugt** 2024-03-05 06:50 UTC
